using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Hu = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — régi mappa biztonságos tisztítása",
            "TabWork", "Összehasonlítás és tisztítás",
            "TabHelp", "Útmutató és biztonság",
            "LanguageButton", "Nyelv…",
            "Intro", "A RÉGI mappa balra, a JELENLEGI jobbra van. A LegacySift csak azokat a fájlokat távolítja el a RÉGI mappából, amelyeknek már van teljesen azonos másolata a JELENLEGI mappában.",
            "OldTitle", "1. RÉGI MAPPA",
            "OldBadge", "EZ TISZTÍTHATÓ",
            "OldDescription", "A régi számítógépről, lemezről vagy mentésből visszaállított mappa. A tisztítás csak ezt az oldalt módosíthatja.",
            "CurrentTitle", "2. JELENLEGI MAPPA",
            "CurrentBadge", "VÉDETT • CSAK OLVASHATÓ",
            "CurrentDescription", "A ma használt mappa. A LegacySift csak összehasonlítás céljából olvassa, és soha nem tisztítja.",
            "Browse", "Tallózás…",
            "Direction", "Összehasonlítás: RÉGI mappa → védett JELENLEGI mappa. Az ellenőrzés csak olvas; semmit nem módosít.",
            "Analyze", "3. ELLENŐRIZZE, MI VAN MÁR MEG — semmit nem módosít",
            "Cancel", "Mégse",
            "OpenReport", "Utolsó jelentés megnyitása",
            "NoAnalysis", "Válassza ki a RÉGI és a védett JELENLEGI mappát, majd indítsa el az ellenőrzést.",
            "PathsChanged", "Megváltozott egy mappaválasztás. Tisztítás előtt futtassa újra az ellenőrzést.",
            "TabRecover", "NINCS A JELENLEGI MAPPÁBAN",
            "TabVersions", "LEHETSÉGES ELTÉRŐ VERZIÓK",
            "TabDuplicates", "TELJESEN AZONOS MÁSOLATOK",
            "TabProblems", "NEM ELLENŐRZÖTT FÁJLOK",
            "GridOld", "Fájl a RÉGI mappában",
            "GridSize", "Méret",
            "GridCurrent", "Megfelelő fájl a JELENLEGI mappában",
            "GridNote", "A LegacySift eredménye",
            "CleanupGroup", "4. A RÉGI MAPPA TISZTÍTÁSA",
            "Quarantine", "Biztonsági mappa (ajánlott) — az azonos másolatokat kiveszi a RÉGI mappából, és visszaállíthatóvá teszi őket",
            "Recycle", "Windows Lomtár — a RÉGI mappa azonos másolatait a Lomtárba küldi",
            "OtherOptions", "További beállítások",
            "HideOptions", "Beállítások elrejtése",
            "RemoveEmpty", "A RÉGI mappában teljesen üresen maradt mappák eltávolítása",
            "Confirm", "Megértettem: CSAK a RÉGI mappa módosul. A JELENLEGI mappa változatlan marad.",
            "Cleanup", "AZONOS MÁSOLATOK ELTÁVOLÍTÁSA A RÉGI MAPPÁBÓL",
            "Restore", "Félretett fájlok visszaállítása…",
            "ProtectedReminder", "A JELENLEGI mappa védett marad",
            "Ready", "Kész.",
            "ChooseOldDialog", "Válassza ki az ellenőrizendő és tisztítandó RÉGI mappát",
            "ChooseCurrentDialog", "Válassza ki a JELENLEGI / VÉDETT mappát",
            "AnalyzeDone", "Az ellenőrzés kész. Egyetlen fájl sem módosult.",
            "AnalyzeCanceled", "Az ellenőrzés megszakadt. Egyetlen fájl sem módosult.",
            "AnalyzeErrorTitle", "Hiba az ellenőrzés közben",
            "AnalyzeErrorStatus", "Az ellenőrzés hiba miatt leállt. Tisztítás nem történt.",
            "PathCheckTitle", "LegacySift — mappaválasztás ellenőrzése",
            "CleanupConfirmTitle", "A RÉGI mappa tisztításának megerősítése",
            "CleanupConfirm", "Most CSAK a RÉGI mappa tisztítása következik:\n\n{0}\n\nA JELENLEGI mappa védett, és nem módosul:\n\n{1}\n\nEltávolítás a RÉGI mappából: {2} azonos másolat.\nA RÉGI mappában marad: {3}, amely nincs a JELENLEGIBEN; {4} lehetséges eltérő verzió; {5} nem ellenőrzött.\n\nMódszer: {6}\n\nFolytatja?",
            "ModeSafety", "BIZTONSÁGI MAPPA (visszaállítható)",
            "ModeRecycle", "WINDOWS LOMTÁR",
            "CleanupDoneStatus", "Kész: {0} azonos másolat eltávolítva a RÉGI mappából; {1} elem biztonsági okból érintetlen maradt.",
            "CleanupDoneTitle", "LegacySift — kész",
            "CleanupDone", "A tisztítás befejeződött.\n\nEltávolítva a RÉGI mappából: {0} azonos másolat\nBiztonsági okból helyben maradt: {1}{2}\n\nA JELENLEGIBEN nem található fájlok és a lehetséges eltérő verziók nem módosultak. Futtassa újra az ellenőrzést a pontos maradék megtekintéséhez.",
            "CleanupSafetyLocation", "\n\nBiztonsági mappa:\n{0}\n\nNe törölje, amíg nem ellenőrizte a régi mappában maradt fájlokat.",
            "CleanupCanceled", "A tisztítás leállt. A már áthelyezett fájlok a biztonsági mappában / Lomtárban maradnak; a többi fájl nem módosult.",
            "CleanupErrorTitle", "Hiba a tisztítás közben",
            "CleanupErrorStatus", "A tisztítás hiba miatt leállt. Ellenőrizze a biztonsági mappát, és új próbálkozás előtt végezzen új összehasonlítást.",
            "RestoreLast", "Visszaállítja a legutóbb létrehozott biztonsági mappát?\n\n{0}",
            "RestoreTitle", "Fájlok visszaállítása",
            "RestoreChoose", "Válasszon egy __LegacySift_Safety_... mappát",
            "RestoreConfirm", "A LegacySift megpróbálja visszatenni a fájlokat eredeti helyükre a RÉGI mappában.\nA már létező fájlokat NEM írja felül.\n\nFolytatja?",
            "RestoreConfirmTitle", "Visszaállítás megerősítése",
            "RestoreDoneStatus", "Visszaállítás kész: {0} fájl visszaállítva; {1} ütközés nem lett felülírva.",
            "RestoreDone", "Visszaállítva: {0}\nNEM felülírt ütközések: {1}\nHibák: {2}",
            "RestoreCanceled", "A visszaállítás leállt.",
            "RestoreErrorTitle", "Hiba a visszaállítás közben",
            "Summary", "ELLENŐRZÉS KÉSZ — egyetlen fájl sem módosult.\n{0} nincs a JELENLEGIBEN   |   {1} lehetséges eltérő verzió   |   {2} azonos másolat ({3})   |   {4} nem ellenőrzött",
            "CleanupCount", "{0} AZONOS MÁSOLAT ELTÁVOLÍTÁSA A RÉGI MAPPÁBÓL",
            "PhaseOldScan", "RÉGI mappa olvasása",
            "PhaseCurrentScan", "Védett JELENLEGI mappa olvasása",
            "PhaseCompare", "Fájltartalmak összehasonlítása",
            "PhaseSafety", "Fájlok áthelyezése a biztonsági mappába",
            "PhaseRecycle", "Fájlok áthelyezése a Lomtárba",
            "PhaseRestoreRead", "Biztonsági mappa olvasása",
            "PhaseRestore", "Fájlok visszaállítása",
            "OldRequired", "Először válassza ki a RÉGI mappát.",
            "CurrentRequired", "Válassza ki a JELENLEGI / VÉDETT mappát.",
            "InvalidPath", "Érvénytelen elérési út: {0}",
            "OldMissing", "A RÉGI mappa nem létezik.",
            "CurrentMissing", "A JELENLEGI / VÉDETT mappa nem létezik.",
            "SameFolder", "A két választás ugyanarra a mappára mutat. A művelet letiltva.",
            "OldRootBlocked", "Biztonsági okból teljes meghajtógyökér nem használható RÉGI mappaként.",
            "CurrentRootBlocked", "Biztonsági okból teljes meghajtógyökér nem használható JELENLEGI mappaként.",
            "NestedBlocked", "Az egyik kiválasztott mappa a másikon belül van. Válasszon két külön mappát.",
            "SystemFolderBlocked", "Biztonsági okból a LegacySift nem tisztít közvetlenül fő Windows rendszermappát.",
            "OutsideOld", "A biztonsági ellenőrzés sikertelen: a fájl nem a RÉGI mappában található.",
            "ReparseDir", "Csatolt mappa / reparse point biztonsági okból kihagyva.",
            "ReparseFile", "Csatolt fájl / reparse point biztonsági okból kihagyva.",
            "ExactNote", "A JELENLEGI mappában van azonos másolat. Ez a RÉGI mappabeli másolat biztonságosan eltávolítható.",
            "VersionNoteOne", "A jelenlegi mappában van azonos nevű, de eltérő tartalmú fájl. Ez a fájl NEM lesz eltávolítva.",
            "VersionNoteMany", "{0} azonos nevű fájl található, de egyik sem teljesen azonos. Ez a fájl NEM lesz eltávolítva.",
            "UniqueNote", "Nem található azonos másolat a JELENLEGI mappában. Ez a fájl a RÉGI mappában marad.",
            "LanguageRestart", "A LegacySift újraindul az új nyelv alkalmazásához. A jelenlegi ellenőrzés eredményei törlődnek.",
            "LanguageRestartTitle", "Nyelvváltás",
            "SafetyParentMissing", "A LegacySift nem tudja meghatározni, hol hozza létre a biztonsági mappát.",
            "OldFileMissingNow", "A régi mappában lévő fájl már nem létezik.",
            "CurrentCopyMissingNow", "A jelenlegi mappában lévő megfelelő fájl már nem létezik.",
            "ChangedSize", "A fájl mérete az összehasonlítás után megváltozott. A fájl érintetlen maradt.",
            "ChangedHash", "A két fájl már nem azonos. A régi fájl érintetlen maradt.",
            "SafetyDestinationExists", "A biztonsági mappában már létezik fájl ugyanezen az útvonalon.",
            "SafetyVerificationFailed", "A biztonsági mappába helyezés utáni ellenőrzés sikertelen. A LegacySift megpróbálta automatikusan visszaállítani az eredeti fájlt.",
            "MovedSafety", "Áthelyezve a biztonsági mappába és ellenőrizve.",
            "MovedRecycle", "Áthelyezve a Windows Lomtárba.",
            "SafetyFolderMissing", "A biztonsági mappa nem található.",
            "RestoreNoOverwrite", "NEM lett felülírva: {0}",
            "SessionMissing", "A LegacySift.session hiányzik, ezért az automatikus visszaállítás nem lehetséges.",
            "SessionInvalid", "A biztonsági mappa munkamenete érvénytelen: hiányzik a régi mappa eredeti útvonala.",
            "TabRecoverHelp", "Nem található azonos másolat a JELENLEGIBEN. Ezek a fájlok a RÉGI mappában maradnak.",
            "TabVersionsHelp", "A JELENLEGIBEN van azonos név, de eltér a tartalom. Ezek a fájlok a RÉGI mappában maradnak.",
            "TabDuplicatesHelp", "A JELENLEGIBEN már van azonos másolat. Tisztítással csak ezek a RÉGI mappabeli fájlok távolíthatók el.",
            "TabProblemsHelp", "A LegacySift nem tudta biztonságosan ellenőrizni ezeket a fájlokat. A RÉGI mappában maradnak.",
            "CheckingNow", "A két mappa ellenőrzése folyamatban… egyetlen fájl sem módosul.",
            "CleanupBeforeAnalysis", "Először futtassa az ellenőrzést. A LegacySift ezután pontosan megmutatja, mi távolítható el a RÉGI mappából, és mi marad ott.",
            "CleanupWaitForAnalysis", "Várja meg az ellenőrzés végét. A tisztítás le van tiltva, amíg a LegacySift olvassa a mappákat.",
            "CleanupExplanation", "Tisztítás után a RÉGI mappában marad {0} fájl, amely nincs a JELENLEGIBEN, {1} lehetséges eltérő verzió és {2} nem ellenőrzött fájl. Csak a {3} azonos másolat kerül ki a RÉGI mappából.",
            "AfterCleanupSummary", "A tisztítás kész: {0} azonos másolat eltávolítva a RÉGI mappából; {1} elem biztonsági okból érintetlen maradt. Futtassa újra az ellenőrzést a pontos maradék megtekintéséhez.",
            "CleanupNeedsNewCheck", "A tisztítás befejeződött. Futtassa újra az ellenőrzést, hogy csak a RÉGI mappában maradt fájlokat lássa.",
            "HelpText", "LEGACYSIFT — GYORS ÚTMUTATÓ\n\nMIRE VALÓ\nA LegacySift számítógép-költöztetéshez, régi lemezekhez és helyreállított mentésekhez készült. Válassza ki a RÉGI mappát és a ma használt JELENLEGI mappát. Megmutatja, mi hiányzik a JELENLEGIBŐL, és mely pontos másolatok vannak már meg.\n\nAZ IRÁNY SOHA NEM VÁLTOZIK\nRÉGI MAPPA = tisztítható.\nJELENLEGI MAPPA = védett, csak összehasonlításra szolgál. A LegacySift soha nem tisztítja.\n\nHASZNÁLAT\n1. Válassza ki a RÉGI MAPPÁT.\n2. Válassza ki a JELENLEGI MAPPÁT.\n3. Kattintson az ELLENŐRIZZE, MI VAN MÁR MEG gombra. Ez nem módosít semmit.\n4. Olvassa el az eredményeket.\n5. Ha rendben vannak, csak az azonos másolatokat távolítsa el a RÉGI mappából.\n\nAZ EREDMÉNYEK JELENTÉSE\n• NINCS A JELENLEGIBEN: nincs azonos másolat. A fájlok a RÉGI mappában maradnak.\n• LEHETSÉGES ELTÉRŐ VERZIÓK: a név azonos, de a tartalom eltér. A fájlok a RÉGI mappában maradnak.\n• AZONOS MÁSOLATOK A JELENLEGIBEN: van pontos másolat. Csak ezek távolíthatók el a RÉGI mappából.\n• NEM ELLENŐRZÖTT FÁJLOK: a LegacySift nem tudta biztonságosan ellenőrizni őket. A RÉGI mappában maradnak.\n\nTISZTÍTÁS UTÁN\nA RÉGI mappában maradnak a JELENLEGIBEN nem található fájlok, a lehetséges eltérő verziók és minden, amit nem sikerült biztonságosan ellenőrizni. Csak a pontos másolatok kerülnek ki.\n\nLEGBIZTONSÁGOSABB MÓDSZER\nHasználja a biztonsági mappát. A pontos másolatok végleges törlés helyett egy külön, visszaállítható mappába kerülnek a RÉGI mellett.\n\nMŰSZAKI BIZTONSÁG\nA pontos tartalmat SHA-256-tal hasonlítja össze, majd tisztítás előtt újra ellenőrzi. A csatolt mappákat és reparse pointokat kihagyja. Az egymásba ágyazott mappaválasztást letiltja. A LegacySift nem kér rendszergazdai jogot, és teljesen helyben működik.\n\nEGYSZERŰ SZABÁLY\nHa bizonytalan, álljon meg az ellenőrzés után. Semmi nem változik, amíg kifejezetten el nem indítja a tisztítást."
        );
    }
}
