using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Lt = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — saugus seno aplanko valymas",
            "TabWork", "Palyginti ir išvalyti",
            "TabHelp", "Instrukcijos ir saugumas",
            "LanguageButton", "Kalba...",
            "Intro", "Senas aplankas – kairėje. Dabartinis aplankas – dešinėje.„LegacySift“ iš SENO aplanko pašalina tik tuos failus, kurie yra identiški failams DABARTINIAME aplanke.",
            "OldTitle", "1. SENAS APLANKAS",
            "OldBadge", "ŠĮ APLANKĄ GALIMA VALYTI",
            "OldDescription", "Aplankas, atkurtas iš seno kompiuterio, disko ar atsarginės kopijos. Valymo metu keičiama tik ši pusė.",
            "CurrentTitle", "2. DABARTINIS APLANKAS",
            "CurrentBadge", "APSAUGOTAS • TIK SKAITYMUI",
            "CurrentDescription", "Aplankas, kurį naudojate šiuo metu.„LegacySift“ jį skaito tik palyginimo tikslais ir niekada jo nevalo.",
            "Browse", "Naršyti...",
            "Direction", "Palyginti SENĄ aplanką su DABARTINIU apsaugotu aplanku. Tikrinant failai tik skaitomi;niekas nekeičiama.",
            "Analyze", "3. PATIKRINTI, KĄ JAU TURITE — niekas nekeičiama",
            "Cancel", "Atšaukti",
            "OpenReport", "Atidaryti paskutinę ataskaitą",
            "NoAnalysis", "Pasirinkite SENĄ aplanką ir DABARTINĮ apsaugotą aplanką, tada paleiskite patikrą.",
            "PathsChanged", "Pasikeitė aplankų pasirinkimas. Prieš ką nors valydami, vėl paleiskite patikrą.",
            "TabRecover", "NĖRA DABARTINIAME APLANKE",
            "TabVersions", "GALI BŪTI SKIRTINGOS VERSIJOS",
            "TabDuplicates", "IDENTIŠKOS KOPIJOS",
            "TabProblems", "NEPATIKRINTI FAILAI",
            "GridOld", "Failas SENAME aplanke",
            "GridSize", "Dydis",
            "GridCurrent", "Atitinkamas failas DABARTINIAME aplanke",
            "GridNote", "Ką rado „LegacySift“",
            "CleanupGroup", "4. IŠVALYTI SENĄ APLANKĄ",
            "Quarantine", "Apsauginis aplankas (rekomenduojama) — perkelti identiškas kopijas iš SENO aplanko, kad jas būtų galima atkurti",
            "Recycle", "„Windows“ šiukšlinė — perkelti identiškas SENO aplanko kopijas į šiukšlinę",
            "OtherOptions", "Rodyti kitas parinktis",
            "HideOptions", "Slėpti kitas parinktis",
            "RemoveEmpty", "Pašalinti aplankus, kurie SENAME aplanke liko visiškai tušti",
            "Confirm", "Suprantu: bus keičiamas TIK SENAS aplankas. DABARTINIS aplankas liks nepakeistas.",
            "Cleanup", "PAŠALINTI IDENTIŠKAS KOPIJAS IŠ SENO APLANKO",
            "Restore", "Atkurti atidėtus failus...",
            "ProtectedReminder", "CURRENT (dabartinis) aplankas lieka apsaugotas",
            "Ready", "Parengta.",
            "ChooseOldDialog", "Pasirinkite OLD (senąjį) aplanką patikrai ir valymui",
            "ChooseCurrentDialog", "Pasirinkite CURRENT / PROTECTED (dabartinį / apsaugotą) aplanką",
            "AnalyzeDone", "Patikra baigta. Jokie failai nebuvo pakeisti.",
            "AnalyzeCanceled", "Patikra atšaukta. Jokie failai nebuvo pakeisti.",
            "AnalyzeErrorTitle", "Problema patikros metu",
            "AnalyzeErrorStatus", "Patikra sustabdyta dėl problemos. Valymas nebuvo atliktas.",
            "PathCheckTitle", "„LegacySift“ – aplankų pasirinkimas patikrai",
            "CleanupConfirmTitle", "Patvirtinkite OLD (senojo) aplanko valymą",
            "CleanupConfirm", "Ruošiatės valyti TIK OLD (senąjį) aplanką:\\n\\n{0}\\n\\nCURRENT (dabartinis) aplankas yra apsaugotas ir nebus keičiamas:\\n\\n{1}\\n\\nIš OLD pašalinta: {2} identiškų kopijų.\\nOLD aplanke liko: {3} nerastų CURRENT aplanke, {4} galimai skirtingų versijų, {5} netikrintų.\\n\\nMetodas: {6}\\n\\nTęsti?",
            "ModeSafety", "SAUGOS APLANKAS (galima atkurti)",
            "ModeRecycle", "„WINDOWS“ ŠIUKŠLIADĖŽĖ",
            "CleanupDoneStatus", "Atlikta: iš OLD aplanko pašalinta {0} identiškų kopijų;{1} kandidatų palikta nepaliestų saugumo sumetimais.",
            "CleanupDoneTitle", "„LegacySift“ – baigta",
            "CleanupDone", "Valymas baigtas.\\n\\nIš OLD aplanko pašalinta: {0} identiškų kopijų\\nSaugumo sumetimais palikta: {1}{2}\\n\\nFailai, nerasti CURRENT aplanke, bei galimai skirtingos versijos nebuvo paliesti. Paleiskite patikrą dar kartą, kad tiksliai pamatytumėte, kas liko.",
            "CleanupSafetyLocation", "\n\nSaugos aplankas:\n{0}\n\nNeištrinkite jo, kol nepatikrinote senajame aplanke likusių failų.",
            "CleanupCanceled", "Valymas sustabdytas. Jau perkelti failai lieka atsarginiame aplanke / šiukšlinėje;likę failai nebuvo paliesti.",
            "CleanupErrorTitle", "Problema valymo metu",
            "CleanupErrorStatus", "Valymas sustabdytas dėl problemos. Prieš bandydami dar kartą, patikrinkite atsarginį aplanką ir atlikite naują palyginimą.",
            "RestoreLast", "Atkurti paskutinį sukurtą saugos aplanką?\n\n{0}",
            "RestoreTitle", "Atkurti failus",
            "RestoreChoose", "Pasirinkite „__LegacySift_Safety_...“ aplanką",
            "RestoreConfirm", "„LegacySift“ bandys grąžinti failus į jų pradines vietas senajame aplanke. Ten jau esantys failai NEBUS perrašyti. Tęsti?",
            "RestoreConfirmTitle", "Patvirtinti atkūrimą",
            "RestoreDoneStatus", "Atkūrimas baigtas: atkurta failų – {0};konfliktuojančių failų ({1}) perrašyti nepavyko.",
            "RestoreDone", "Atkurta: {0} |Konfliktuojantys failai (neperrašyti): {1} | Klaidos: {2}",
            "RestoreCanceled", "Atkūrimas sustabdytas.",
            "RestoreErrorTitle", "Problema atkūrimo metu",
            "Summary", "PATIKRA BAIGTA — joks failas nepakeistas.\\n{0} nerasta aplanke CURRENT   |{1} galimos skirtingos versijos   |{2} identiškos kopijos ({3})   |{4} netikrinta",
            "CleanupCount", "PAŠALINKITE {0} IDENTIŠKAS KOPIJAS IŠ SENOJO APLANKO",
            "PhaseOldScan", "Skaitomas SENASIS aplankas",
            "PhaseCurrentScan", "Skaitomas DABARTINIS apsaugotas aplankas",
            "PhaseCompare", "Lyginamas failų turinys",
            "PhaseSafety", "Failai perkeliami į saugos aplanką",
            "PhaseRecycle", "Failai perkeliami į šiukšlinę",
            "PhaseRestoreRead", "Skaitomas saugos aplankas",
            "PhaseRestore", "Atkuriami failai",
            "OldRequired", "Pirmiausia pasirinkite SENĄJĮ aplanką.",
            "CurrentRequired", "Pasirinkite DABARTINĮ / APSAUGOTĄ aplanką.",
            "InvalidPath", "Netinkamas kelias: {0}",
            "OldMissing", "SENASIS aplankas neegzistuoja.",
            "CurrentMissing", "DABARTINIS / APSAUGOTAS aplankas neegzistuoja.",
            "SameFolder", "Abu pasirinkimai nurodo tą patį aplanką. Veiksmas užblokuotas.",
            "OldRootBlocked", "Saugumo sumetimais viso disko šakninis aplankas negali būti naudojamas kaip SENASIS aplankas.",
            "CurrentRootBlocked", "Saugumo sumetimais viso disko šakninis aplankas negali būti naudojamas kaip DABARTINIS aplankas.",
            "NestedBlocked", "Vienas pasirinktas aplankas yra kito aplanko viduje. Pasirinkite du atskirus aplankus.",
            "SystemFolderBlocked", "Saugumo sumetimais „LegacySift“ nevalys pagrindinio „Windows“ sistemos aplanko.",
            "OutsideOld", "Saugumo patikra nepavyko: šis failas nėra SENAJAME aplanke.",
            "ReparseDir", "Susietas aplankas / peradresavimo taškas praleistas saugumo sumetimais.",
            "ReparseFile", "Susietas failas / peradresavimo taškas praleistas saugumo sumetimais.",
            "ExactNote", "DABARTINIAME aplanke yra identiška kopija. Šią SENOJO aplanko kopiją galima saugiai pašalinti.",
            "VersionNoteOne", "DABARTINIAME aplanke yra failas tokiu pačiu pavadinimu, tačiau jo turinys skiriasi. Šis failas NEBUS pašalintas.",
            "VersionNoteMany", "Rasti {0} failai tokiu pačiu pavadinimu, tačiau nė vienas nėra identiškas. Šis failas NEBUS pašalintas.",
            "UniqueNote", "DABARTINIAME aplanke identiškos kopijos nerasta. Šis failas lieka aplanke OLD.",
            "LanguageRestart", "„LegacySift“ bus paleista iš naujo, kad būtų pritaikyta nauja kalba. Visi esami palyginimo rezultatai bus ištrinti.",
            "LanguageRestartTitle", "Keisti kalbą",
            "SafetyParentMissing", "„LegacySift“ negali nustatyti, kur sukurti atsarginį aplanką.",
            "OldFileMissingNow", "Failo senajame aplanke nebėra.",
            "CurrentCopyMissingNow", "Atitinkamo failo dabartiniame aplanke nebėra.",
            "ChangedSize", "Po palyginimo pasikeitė failo dydis. Failas paliktas nepakeistas.",
            "ChangedHash", "Šie du failai nebėra identiški. Senasis failas paliktas nepakeistas.",
            "SafetyDestinationExists", "Atsarginiame aplanke jau yra failas tuo pačiu keliu.",
            "SafetyVerificationFailed", "Po perkėlimo nepavyko patikrinti atsarginio aplanko.„LegacySift“ bandė automatiškai atkurti pradinį failą.",
            "MovedSafety", "Perkelta į atsarginį aplanką ir patikrinta.",
            "MovedRecycle", "Perkelta į „Windows“ šiukšlinę.",
            "SafetyFolderMissing", "Atsarginis aplankas nerastas.",
            "RestoreNoOverwrite", "NEPERRAŠYTA: {0}",
            "SessionMissing", "Trūksta „LegacySift.session“ failo, todėl automatinis atkūrimas negalimas.",
            "SessionInvalid", "Atsarginio aplanko sesija netinkama: trūksta pradinio kelio į senąjį aplanką.",
            "TabRecoverHelp", "Aplanke CURRENT nerasta identiškos kopijos. Šie failai lieka aplanke OLD.",
            "TabVersionsHelp", "Aplanke CURRENT yra failas tokiu pačiu pavadinimu, tačiau jų turinys skiriasi. Šie failai lieka aplanke OLD.",
            "TabDuplicatesHelp", "Aplanke CURRENT jau yra identiška kopija. Valymo metu galima pašalinti tik šiuos aplanko OLD failus.",
            "TabProblemsHelp", "„LegacySift“ negalėjo saugiai patikrinti šių failų. Jie lieka aplanke OLD.",
            "CheckingNow", "Tikrinami du aplankai... joks failas nekeičiamas.",
            "CleanupBeforeAnalysis", "Pirmiausia atlikite patikrą. Tada „LegacySift“ parodys, ką tiksliai galima pašalinti iš aplanko OLD ir kas jame liks.",
            "CleanupWaitForAnalysis", "Palaukite, kol patikra bus baigta. Kol „LegacySift“ skaito aplankus, valymo funkcija išjungta.",
            "CleanupExplanation", "Po valymo aplanke OLD liks failai {0} (kurių nėra aplanke CURRENT), galimos skirtingos versijos {1} ir netikrinti failai {2}. Iš „OLD“ bus pašalintos tik identiškos „{3}“ kopijos.",
            "AfterCleanupSummary", "Valymas baigtas: iš „OLD“ pašalintos identiškos „{0}“ kopijos;„{1}“ kandidatai palikti nepaliesti saugumo sumetimais. Dar kartą atlikite patikrą, kad pamatytumėte, kas tiksliai liko.",
            "CleanupNeedsNewCheck", "Valymas baigtas. Dar kartą atlikite patikrą, kad pamatytumėte, kas liko „OLD“ aplanke.",
            "HelpText", "LEGACYSIFT — Trumpas vadovas\\n\\nPaskirtis\\n„LegacySift“ skirta duomenų perkėlimui į naują kompiuterį, senų diskų tvarkymui ir atkurtų atsarginių kopijų analizei. Pasirinkite SENĄ (OLD) aplanką ir DABARTINĮ (CURRENT) aplanką, kurį naudojate šiuo metu.„LegacySift“ parodo, ko trūksta DABARTINIAME aplanke ir kokias tikslias kopijas jau turite.\\n\\nVeikimo kryptis nesikeičia\\nSENAS APLANKAS = gali būti išvalytas.\\nDABARTINIS APLANKAS = apsaugotas, naudojamas tik palyginimui.„LegacySift“ jo niekada nevalo.\\n\\nKaip naudotis\\n1. Pasirinkite SENĄ APLANKĄ.\\n2. Pasirinkite DABARTINĮ APLANKĄ.\\n3. Spustelėkite „CHECK WHAT YOU ALREADY HAVE“ (patikrinti, ką jau turite). Šis veiksmas nieko nekeičia.\\n4. Peržiūrėkite rezultatus.\\n5. Jei rezultatai atrodo tinkami, pašalinkite iš SENO aplanko tik identiškas kopijas.\\n\\nRezultatų reikšmė\\n• NOT FOUND IN CURRENT (nerasta DABARTINIAME): DABARTINIAME aplanke nėra identiškos kopijos. Šie failai lieka SENAME aplanke.\\n• POSSIBLE DIFFERENT VERSIONS (galimos skirtingos versijos): failai tuo pačiu pavadinimu egzistuoja, bet jų turinys skiriasi. Šie failai lieka SENAME aplanke.\\n• IDENTICAL COPIES ALREADY IN CURRENT (identiškos kopijos jau yra DABARTINIAME): DABARTINIAME aplanke yra tiksli kopija. Tik šiuos failus iš SENO aplanko galima pašalinti.\\n• FILES NOT CHECKED (failai netikrinti): „LegacySift“ negalėjo jų saugiai patikrinti. Jie lieka SENAME aplanke.\\n\\nPo valymo\\nSENAME aplanke lieka failai, kurių nebuvo DABARTINIAME aplanke, galimos skirtingos versijos ir failai, kurių „LegacySift“ negalėjo saugiai patikrinti. Iš SENO aplanko pašalinamos tik tikslios kopijos.\\n\\nSaugiausias būdas\\nNaudokite „Safety“ (apsaugos) aplanką. Tikslios kopijos perkeliamos į atskirą, atkuriamą aplanką šalia SENO aplanko, o ne visam laikui ištrinamos.\\n\\nTECHNINĖ SAUGA\\nTikslus turinys tikrinamas naudojant SHA-256 algoritmą; pakartotinis patikrinimas atliekamas prieš pradedant valymą. Susietieji aplankai ir pakartotinės analizės taškai (angl. *reparse points*) praleidžiami. Įdėtųjų aplankų pasirinkimas blokuojamas.„LegacySift“ nereikalauja administratoriaus teisių ir veikia tik vietoje (lokaliai).\\n\\nPAPRASTA TAISYKLĖ\\nJei abejojate, sustokite po patikrinimo. Jokie pakeitimai neatliekami, kol aiškiai nepradedate valymo proceso."
        );
    }
}
