using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Ms = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — bersihkan folder lama dengan selamat",
            "TabWork", "Banding dan bersihkan",
            "TabHelp", "Panduan dan keselamatan",
            "LanguageButton", "Bahasa…",
            "Intro", "Folder lama di sebelah kiri. Folder semasa di sebelah kanan. LegacySift hanya membuang fail daripada folder LAMA yang sudah pun sama dengan fail dalam folder SEMASA.",
            "OldTitle", "1. FOLDER LAMA",
            "OldBadge", "INI BOLEH DIBERSIHKAN",
            "OldDescription", "Folder yang diperoleh semula daripada komputer lama, cakera atau sandaran. Hanya bahagian ini yang boleh diubah melalui proses pembersihan.",
            "CurrentTitle", "2. FOLDER SEMASA",
            "CurrentBadge", "DILINDUNGI • BACA SAHAJA",
            "CurrentDescription", "Folder yang anda gunakan hari ini. LegacySift membacanya hanya untuk tujuan perbandingan dan tidak akan membersihkannya.",
            "Browse", "Semak imbas…",
            "Direction", "Bandingkan folder LAMA → folder SEMASA yang dilindungi. Proses semakan hanya membaca fail;ia tidak mengubah apa-apa.",
            "Analyze", "3. SEMAK APA YANG ANDA MILIKI — tidak mengubah apa-apa",
            "Cancel", "Batal",
            "OpenReport", "Buka laporan terakhir",
            "NoAnalysis", "Pilih folder LAMA dan folder SEMASA yang dilindungi, kemudian jalankan semakan.",
            "PathsChanged", "Pilihan folder telah berubah. Jalankan semula semakan sebelum melakukan sebarang pembersihan.",
            "TabRecover", "TIADA DALAM FOLDER SEMASA",
            "TabVersions", "KEMUNGKINAN VERSI BERBEZA",
            "TabDuplicates", "SALINAN SAMA",
            "TabProblems", "FAIL TIDAK DISEMAK",
            "GridOld", "Fail dalam folder LAMA",
            "GridSize", "Saiz",
            "GridCurrent", "Fail sepadan dalam folder SEMASA",
            "GridNote", "Hasil dapatan LegacySift",
            "CleanupGroup", "4. BERSIHKAN FOLDER LAMA",
            "Quarantine", "Folder keselamatan (disyorkan) — alihkan salinan yang sama keluar daripada folder LAMA supaya ia boleh dipulihkan",
            "Recycle", "Tong Kitar Semula Windows — hantar salinan folder LAMA yang sama ke Tong Kitar Semula",
            "OtherOptions", "Paparkan pilihan lain",
            "HideOptions", "Sembunyikan pilihan lain",
            "RemoveEmpty", "Buang folder yang menjadi kosong sepenuhnya di dalam folder LAMA",
            "Confirm", "Saya faham: HANYA folder LAMA yang akan diubah. Folder SEMASA tidak akan berubah.",
            "Cleanup", "BUANG SALINAN YANG SAMA DARIPADA FOLDER LAMA",
            "Restore", "Pulihkan fail yang diketepikan…",
            "ProtectedReminder", "CURRENT kekal dilindungi",
            "Ready", "Sedia.",
            "ChooseOldDialog", "Pilih folder OLD untuk diperiksa dan dibersihkan",
            "ChooseCurrentDialog", "Pilih folder CURRENT / PROTECTED",
            "AnalyzeDone", "Pemeriksaan selesai. Tiada fail diubah.",
            "AnalyzeCanceled", "Pemeriksaan dibatalkan. Tiada fail diubah.",
            "AnalyzeErrorTitle", "Masalah semasa pemeriksaan",
            "AnalyzeErrorStatus", "Pemeriksaan terhenti akibat masalah. Tiada pembersihan dilakukan.",
            "PathCheckTitle", "LegacySift — semak pemilihan folder",
            "CleanupConfirmTitle", "Sahkan pembersihan folder OLD",
            "CleanupConfirm", "Anda akan membersihkan folder OLD SAHAJA:\\n\\n{0}\\n\\nFolder CURRENT dilindungi dan tidak akan diubah:\\n\\n{1}\\n\\nDibuang daripada OLD: {2} salinan serupa.\\nDibiarkan dalam OLD: {3} tidak ditemui dalam CURRENT, {4} kemungkinan versi berbeza, {5} tidak diperiksa.\\n\\nKaedah: {6}\\n\\nTeruskan?",
            "ModeSafety", "FOLDER KESELAMATAN (boleh dipulihkan)",
            "ModeRecycle", "TONG KITAR SEMULA WINDOWS",
            "CleanupDoneStatus", "Selesai: {0} salinan serupa telah dibuang daripada folder OLD;{1} calon dibiarkan tanpa usik demi keselamatan.",
            "CleanupDoneTitle", "LegacySift — selesai",
            "CleanupDone", "Pembersihan selesai.\\n\\nDibuang daripada folder OLD: {0} salinan serupa\\nDibiarkan di tempat asal demi keselamatan: {1}{2}\\n\\nFail yang tidak ditemui dalam CURRENT dan kemungkinan versi berbeza tidak diusik. Jalankan pemeriksaan semula untuk melihat dengan tepat apa yang tinggal.",
            "CleanupSafetyLocation", "\n\nFolder keselamatan:\n{0}\n\nJangan padamkannya sehingga anda menyemak fail yang masih berada dalam folder lama.",
            "CleanupCanceled", "Pembersihan dihentikan. Fail yang telah dipindahkan kekal dalam folder keselamatan / Tong Kitar Semula;fail yang selebihnya tidak disentuh.",
            "CleanupErrorTitle", "Masalah semasa pembersihan",
            "CleanupErrorStatus", "Pembersihan dihentikan akibat masalah. Semak folder keselamatan dan jalankan perbandingan baharu sebelum mencuba semula.",
            "RestoreLast", "Pulihkan folder keselamatan terakhir yang dicipta?\n\n{0}",
            "RestoreTitle", "Pulihkan fail",
            "RestoreChoose", "Pilih folder __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift akan cuba meletakkan semula fail ke lokasi folder asal (OLD-folder). Fail yang sedia ada di sana TIDAK akan ditindih. Teruskan?",
            "RestoreConfirmTitle", "Sahkan pemulihan",
            "RestoreDoneStatus", "Pemulihan selesai: {0} fail dipulihkan;{1} konflik tidak ditindih.",
            "RestoreDone", "Dipulihkan: {0} Konflik TIDAK ditindih: {1} Ralat: {2}",
            "RestoreCanceled", "Pemulihan dihentikan.",
            "RestoreErrorTitle", "Masalah semasa pemulihan",
            "Summary", "SEMAKAN SELESAI — tiada fail diubah.\\n{0} tidak ditemui dalam CURRENT   |{1} kemungkinan versi berbeza   |{2} salinan serupa ({3})   |{4} tidak disemak",
            "CleanupCount", "BUANG SALINAN SERUPA {0} DARIPADA FOLDER LAMA",
            "PhaseOldScan", "Membaca folder LAMA",
            "PhaseCurrentScan", "Membaca folder CURRENT yang dilindungi",
            "PhaseCompare", "Membandingkan kandungan fail",
            "PhaseSafety", "Memindahkan fail ke folder keselamatan",
            "PhaseRecycle", "Memindahkan fail ke Tong Kitar Semula (Recycle Bin)",
            "PhaseRestoreRead", "Membaca folder keselamatan",
            "PhaseRestore", "Memulihkan fail",
            "OldRequired", "Pilih folder LAMA dahulu.",
            "CurrentRequired", "Pilih folder CURRENT / DILINDUNGI.",
            "InvalidPath", "Laluan tidak sah: {0}",
            "OldMissing", "Folder LAMA tidak wujud.",
            "CurrentMissing", "Folder CURRENT / DILINDUNGI tidak wujud.",
            "SameFolder", "Kedua-dua pilihan merujuk kepada folder yang sama. Operasi disekat.",
            "OldRootBlocked", "Demi keselamatan, akar pemacu (root) keseluruhan tidak boleh digunakan sebagai folder LAMA.",
            "CurrentRootBlocked", "Demi keselamatan, akar pemacu (root) keseluruhan tidak boleh digunakan sebagai folder CURRENT.",
            "NestedBlocked", "Satu folder yang dipilih berada di dalam folder yang satu lagi. Pilih dua folder yang berasingan.",
            "SystemFolderBlocked", "Demi keselamatan, LegacySift tidak akan membersihkan folder sistem utama Windows.",
            "OutsideOld", "Semakan keselamatan gagal: fail ini tidak berada di dalam folder LAMA.",
            "ReparseDir", "Folder terpaut / titik *reparse* dilangkau demi keselamatan.",
            "ReparseFile", "Fail terpaut / titik *reparse* dilangkau demi keselamatan.",
            "ExactNote", "Salinan serupa wujud dalam folder CURRENT. Salinan folder LAMA ini boleh dibuang dengan selamat.",
            "VersionNoteOne", "Fail dengan nama yang sama wujud dalam folder semasa, tetapi kandungannya berbeza. Fail ini TIDAK akan dibuang.",
            "VersionNoteMany", "Fail {0} dengan nama yang sama ditemui, tetapi tiada yang serupa. Fail ini TIDAK akan dibuang.",
            "UniqueNote", "Tiada salinan serupa ditemui dalam folder CURRENT. Fail ini kekal dalam folder OLD.",
            "LanguageRestart", "LegacySift akan dimulakan semula untuk menggunakan bahasa baharu. Sebarang hasil perbandingan semasa akan dipadamkan.",
            "LanguageRestartTitle", "Tukar bahasa",
            "SafetyParentMissing", "LegacySift tidak dapat menentukan lokasi untuk mencipta folder keselamatan.",
            "OldFileMissingNow", "Fail dalam folder lama tidak lagi wujud.",
            "CurrentCopyMissingNow", "Fail yang sepadan dalam folder semasa tidak lagi wujud.",
            "ChangedSize", "Saiz fail berubah selepas perbandingan. Fail tersebut dibiarkan tanpa perubahan.",
            "ChangedHash", "Kedua-dua fail tidak lagi serupa. Fail lama dibiarkan tanpa perubahan.",
            "SafetyDestinationExists", "Fail dengan laluan yang sama sudah wujud dalam folder keselamatan.",
            "SafetyVerificationFailed", "Pengesahan folder keselamatan gagal selepas pemindahan. LegacySift cuba memulihkan fail asal secara automatik.",
            "MovedSafety", "Dipindahkan ke folder keselamatan dan disahkan.",
            "MovedRecycle", "Dipindahkan ke Tong Kitar Semula (Recycle Bin) Windows.",
            "SafetyFolderMissing", "Folder keselamatan tidak ditemui.",
            "RestoreNoOverwrite", "TIDAK ditindih: {0}",
            "SessionMissing", "LegacySift.session tiada, jadi pemulihan automatik tidak dapat dilakukan.",
            "SessionInvalid", "Sesi folder keselamatan tidak sah: laluan asal folder lama tiada.",
            "TabRecoverHelp", "Tiada salinan serupa ditemui dalam CURRENT. Fail-fail ini kekal dalam folder OLD.",
            "TabVersionsHelp", "Fail dengan nama yang sama wujud dalam CURRENT, tetapi kandungannya berbeza. Fail-fail ini kekal dalam folder OLD.",
            "TabDuplicatesHelp", "Salinan serupa sudah wujud dalam CURRENT. Hanya fail folder OLD ini yang boleh dibuang melalui proses pembersihan.",
            "TabProblemsHelp", "LegacySift tidak dapat mengesahkan fail-fail ini dengan selamat. Ia kekal dalam folder OLD.",
            "CheckingNow", "Memeriksa kedua-dua folder… tiada fail yang diubah.",
            "CleanupBeforeAnalysis", "Jalankan pemeriksaan dahulu. Kemudian, LegacySift akan menunjukkan dengan tepat apa yang boleh dibuang daripada folder OLD dan apa yang akan kekal di situ.",
            "CleanupWaitForAnalysis", "Tunggu sehingga pemeriksaan selesai. Pembersihan dilumpuhkan semasa LegacySift sedang membaca folder-folder tersebut.",
            "CleanupExplanation", "Selepas pembersihan, OLD akan menyimpan fail {0} yang tidak ditemui dalam CURRENT, fail {1} yang mungkin merupakan versi berbeza, dan fail {2} yang tidak diperiksa. Hanya salinan serupa {3} yang akan dialih keluar daripada OLD.",
            "AfterCleanupSummary", "Pembersihan selesai: Salinan serupa {0} dialih keluar daripada OLD;calon {1} dibiarkan tanpa usik demi keselamatan. Jalankan semula pemeriksaan untuk melihat dengan tepat apa yang tinggal.",
            "CleanupNeedsNewCheck", "Pembersihan telah selesai. Jalankan semula pemeriksaan untuk melihat apa yang tinggal dalam folder OLD sahaja.",
            "HelpText", "LEGACYSIFT — PANDUAN RINGKAS\\n\\nFUNGSI\\nLegacySift direka untuk migrasi komputer, cakera lama dan sandaran yang dipulihkan. Pilih folder LAMA dan folder SEMASA yang anda gunakan sekarang. LegacySift menunjukkan perkara yang tiada dalam folder SEMASA serta salinan tepat yang sudah anda miliki.\\n\\nARAH PROSES TIDAK BERUBAH\\nFOLDER LAMA = boleh dibersihkan.\\nFOLDER SEMASA = dilindungi, untuk perbandingan sahaja. LegacySift tidak akan membersihkannya.\\n\\nCARA PENGGUNAAN\\n1. Pilih FOLDER LAMA.\\n2. Pilih FOLDER SEMASA.\\n3. Klik \"CHECK WHAT YOU ALREADY HAVE\" (Semak apa yang sudah anda miliki). Langkah ini tidak mengubah apa-apa.\\n4. Baca hasilnya.\\n5. Jika hasilnya munasabah, buang hanya salinan yang serupa (identikal) daripada folder LAMA.\\n\\nMAKSUD HASIL\\n• NOT FOUND IN CURRENT (Tiada dalam SEMASA): tiada salinan serupa dalam folder SEMASA. Fail-fail ini kekal dalam folder LAMA.\\n• POSSIBLE DIFFERENT VERSIONS (Kemungkinan versi berbeza): nama fail sama, tetapi kandungannya berbeza. Fail-fail ini kekal dalam folder LAMA.\\n• IDENTICAL COPIES ALREADY IN CURRENT (Salinan serupa sudah ada dalam SEMASA): terdapat salinan tepat dalam folder SEMASA. Hanya fail-fail LAMA ini boleh dibuang.\\n• FILES NOT CHECKED (Fail tidak disemak): LegacySift tidak dapat mengesahkannya dengan selamat. Fail-fail ini kekal dalam folder LAMA.\\n\\nSELEPAS PEMBERSIHAN\\nFolder LAMA akan mengandungi fail yang tidak ditemui dalam folder SEMASA, kemungkinan versi berbeza, dan apa-apa yang tidak dapat disahkan dengan selamat oleh LegacySift. Hanya salinan tepat yang dibuang daripada folder LAMA.\\n\\nKAEDAH PALING SELAMAT\\nGunakan folder \"Safety\" (Keselamatan). Salinan tepat dipindahkan ke folder berasingan yang boleh dipulihkan di sebelah folder LAMA dan bukannya dipadam secara kekal.\\n\\nKESELAMATAN TEKNIKAL\\nKandungan sebenar disemak menggunakan SHA-256 dan disemak semula sebelum proses pembersihan. Folder terpaut/titik penguraian semula (reparse points) tidak diproses. Pemilihan folder bersarang disekat. LegacySift tidak memerlukan keistimewaan pentadbir dan beroperasi sepenuhnya secara setempat.\\n\\nPERATURAN MUDAH\\nJika anda tidak pasti, hentikan proses selepas langkah semakan. Tiada perubahan akan berlaku sehingga anda memulakan proses pembersihan secara khusus."
        );
    }
}
