using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Sk = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — bezpečné vyčistenie starého priečinka",
            "TabWork", "Porovnanie a čistenie",
            "TabHelp", "Sprievodca a bezpečnosť",
            "LanguageButton", "Jazyk…",
            "Intro", "Starý priečinok vľavo. Aktuálny priečinok vpravo. LegacySift zo STARÉHO priečinka odstráni len tie súbory, ktoré sú už identické v AKTUÁLNOM priečinku.",
            "OldTitle", "1. STARÝ PRIEČINOK",
            "OldBadge", "TENTO PRIEČINOK MOŽNO VYČISTIŤ",
            "OldDescription", "Priečinok obnovený zo starého počítača, disku alebo zálohy. Čistenie môže zmeniť iba túto stranu.",
            "CurrentTitle", "2. AKTUÁLNY PRIEČINOK",
            "CurrentBadge", "CHRÁNENÝ • IBA NA ČÍTANIE",
            "CurrentDescription", "Priečinok, ktorý používate v súčasnosti. LegacySift ho číta len na účely porovnania a nikdy ho nečistí.",
            "Browse", "Prehľadávať…",
            "Direction", "Porovnať STARÝ priečinok → AKTUÁLNY chránený priečinok. Kontrola súbory len číta;nič nemení.",
            "Analyze", "3. SKONTROLUJTE, ČO UŽ MÁTE — nič sa nemení",
            "Cancel", "Zrušiť",
            "OpenReport", "Otvoriť poslednú správu",
            "NoAnalysis", "Vyberte STARÝ priečinok a AKTUÁLNY chránený priečinok, potom spustite kontrolu.",
            "PathsChanged", "Výber priečinkov sa zmenil. Pred čistením znova spustite kontrolu.",
            "TabRecover", "NENÁJDENÉ V AKTUÁLNOM",
            "TabVersions", "MOŽNÉ ROZLIŠNÉ VERZIE",
            "TabDuplicates", "IDENTICKÉ KÓPIE",
            "TabProblems", "NESKONTROLOVANÉ SÚBORY",
            "GridOld", "Súbor v STAROM priečinku",
            "GridSize", "Veľkosť",
            "GridCurrent", "Zodpovedajúci súbor v AKTUÁLNOM priečinku",
            "GridNote", "Čo našiel program LegacySift",
            "CleanupGroup", "4. VYČISTIŤ STARÝ PRIEČINOK",
            "Quarantine", "Bezpečnostný priečinok (odporúčané) — presunúť identické kópie zo STARÉHO priečinka, aby sa dali obnoviť",
            "Recycle", "Kôš systému Windows — odoslať identické kópie zo STARÉHO priečinka do Koša",
            "OtherOptions", "Zobraziť ďalšie možnosti",
            "HideOptions", "Skryť ďalšie možnosti",
            "RemoveEmpty", "Odstrániť priečinky, ktoré zostali v rámci STARÉHO priečinka úplne prázdne",
            "Confirm", "Rozumiem: Zmení sa IBA STARÝ priečinok. AKTUÁLNY priečinok zostane nezmenený.",
            "Cleanup", "ODSTRÁNIŤ IDENTICKÉ KÓPIE ZO STARÉHO PRIEČINKA",
            "Restore", "Obnoviť odložené súbory…",
            "ProtectedReminder", "Priečinok CURRENT zostáva chránený",
            "Ready", "Pripravené.",
            "ChooseOldDialog", "Vyberte priečinok OLD na kontrolu a vyčistenie",
            "ChooseCurrentDialog", "Vyberte priečinok CURRENT / PROTECTED",
            "AnalyzeDone", "Kontrola dokončená. Žiadny súbor nebol zmenený.",
            "AnalyzeCanceled", "Kontrola zrušená. Žiadny súbor nebol zmenený.",
            "AnalyzeErrorTitle", "Problém počas kontroly",
            "AnalyzeErrorStatus", "Kontrola sa zastavila kvôli problému. Nevykonalo sa žiadne čistenie.",
            "PathCheckTitle", "LegacySift — výber priečinkov na kontrolu",
            "CleanupConfirmTitle", "Potvrdiť vyčistenie priečinka OLD",
            "CleanupConfirm", "Chystáte sa vyčistiť IBA priečinok OLD:\\n\\n{0}\\n\\nPriečinok CURRENT je chránený a nebude sa meniť:\\n\\n{1}\\n\\nOdstránené z OLD: {2} identických kópií.\\nPonechané v OLD: {3} nenájdené v CURRENT, {4} možné odlišné verzie, {5} neskontrolované.\\n\\nMetóda: {6}\\n\\nPokračovať?",
            "ModeSafety", "BEZPEČNOSTNÝ PRIEČINOK (možno obnoviť)",
            "ModeRecycle", "KÔŠ SYSTÉMU WINDOWS",
            "CleanupDoneStatus", "Hotovo: Z priečinka OLD bolo odstránených {0} identických kópií;{1} kandidátov zostalo z bezpečnostných dôvodov nedotknutých.",
            "CleanupDoneTitle", "LegacySift — dokončené",
            "CleanupDone", "Čistenie dokončené.\\n\\nOdstránené z priečinka OLD: {0} identických kópií\\nPonechané na mieste z bezpečnostných dôvodov: {1}{2}\\n\\nSúbory nenájdené v CURRENT a možné odlišné verzie zostali nedotknuté. Spustite kontrolu znova, aby ste videli, čo presne zostalo.",
            "CleanupSafetyLocation", "\n\nBezpečnostný priečinok:\n{0}\n\nNeodstraňujte ho, kým neskontrolujete súbory, ktoré zostali v starom priečinku.",
            "CleanupCanceled", "Čistenie zastavené. Súbory, ktoré už boli presunuté, zostávajú v bezpečnostnom priečinku / Koši;so zvyšnými súbormi sa nemanipulovalo.",
            "CleanupErrorTitle", "Problém počas čistenia",
            "CleanupErrorStatus", "Čistenie bolo zastavené kvôli problému. Skontrolujte bezpečnostný priečinok a pred ďalším pokusom spustite nové porovnanie.",
            "RestoreLast", "Obnoviť naposledy vytvorený bezpečnostný priečinok?\n\n{0}",
            "RestoreTitle", "Obnoviť súbory",
            "RestoreChoose", "Vyberte priečinok __LegacySift_Safety_...",
            "RestoreConfirm", "Program LegacySift sa pokúsi vrátiť súbory na ich pôvodné umiestnenia v priečinku OLD. Súbory, ktoré tam už existujú, NEBUDÚ prepísané. Pokračovať?",
            "RestoreConfirmTitle", "Potvrdiť obnovenie",
            "RestoreDoneStatus", "Obnovenie dokončené: obnovených bolo {0} súborov;konflikty ({1}) neboli prepísané.",
            "RestoreDone", "Obnovené: {0}  Konflikty NEPREPÍSANÉ: {1}  Chyby: {2}",
            "RestoreCanceled", "Obnovenie zastavené.",
            "RestoreErrorTitle", "Problém počas obnovy",
            "Summary", "KONTROLA DOKONČENÁ — žiadny súbor nebol zmenený.\\n{0} nenájdené v CURRENT   |{1} možné odlišné verzie   |{2} identické kópie ({3})   |{4} nekontrolované",
            "CleanupCount", "ODSTRÁŇTE IDENTICKÉ KÓPIE {0} ZO STARÉHO PRIEČINKA",
            "PhaseOldScan", "Čítanie STARÉHO priečinka",
            "PhaseCurrentScan", "Čítanie aktuálneho (CURRENT) chráneného priečinka",
            "PhaseCompare", "Porovnávanie obsahu súborov",
            "PhaseSafety", "Presúvanie súborov do bezpečnostného priečinka",
            "PhaseRecycle", "Presúvanie súborov do Koša",
            "PhaseRestoreRead", "Čítanie bezpečnostného priečinka",
            "PhaseRestore", "Obnova súborov",
            "OldRequired", "Najprv vyberte STARÝ priečinok.",
            "CurrentRequired", "Vyberte aktuálny (CURRENT) / CHRÁNENÝ priečinok.",
            "InvalidPath", "Neplatná cesta: {0}",
            "OldMissing", "STARÝ priečinok neexistuje.",
            "CurrentMissing", "Aktuálny (CURRENT) / CHRÁNENÝ priečinok neexistuje.",
            "SameFolder", "Oba výbery smerujú do toho istého priečinka. Operácia zablokovaná.",
            "OldRootBlocked", "Z bezpečnostných dôvodov nemožno ako STARÝ priečinok použiť koreňový adresár disku.",
            "CurrentRootBlocked", "Z bezpečnostných dôvodov nemožno ako aktuálny (CURRENT) priečinok použiť koreňový adresár disku.",
            "NestedBlocked", "Jeden z vybraných priečinkov sa nachádza v druhom. Vyberte dva samostatné priečinky.",
            "SystemFolderBlocked", "Z bezpečnostných dôvodov program LegacySift nevyčistí hlavný systémový priečinok Windows.",
            "OutsideOld", "Bezpečnostná kontrola zlyhala: tento súbor sa nenachádza v STAROM priečinku.",
            "ReparseDir", "Prepojený priečinok / bod opätovného spracovania (reparse point) vynechaný z bezpečnostných dôvodov.",
            "ReparseFile", "Prepojený súbor / bod opätovného spracovania (reparse point) vynechaný z bezpečnostných dôvodov.",
            "ExactNote", "V aktuálnom (CURRENT) priečinku existuje identická kópia. Túto kópiu zo STARÉHO priečinka možno bezpečne odstrániť.",
            "VersionNoteOne", "V aktuálnom priečinku existuje súbor s rovnakým názvom, ale jeho obsah je odlišný. Tento súbor NEBUDE odstránený.",
            "VersionNoteMany", "Našli sa súbory {0} s rovnakým názvom, ale žiadny z nich nie je identický. Tento súbor NEBUDE odstránený.",
            "UniqueNote", "V aktuálnom (CURRENT) priečinku sa nenašla žiadna identická kópia. Tento súbor zostáva v priečinku OLD.",
            "LanguageRestart", "Program LegacySift sa reštartuje, aby sa uplatnil nový jazyk. Všetky aktuálne výsledky porovnania sa vymažú.",
            "LanguageRestartTitle", "Zmeniť jazyk",
            "SafetyParentMissing", "Program LegacySift nedokáže určiť, kde vytvoriť bezpečnostný priečinok.",
            "OldFileMissingNow", "Súbor v starom priečinku už neexistuje.",
            "CurrentCopyMissingNow", "Zodpovedajúci súbor v aktuálnom priečinku už neexistuje.",
            "ChangedSize", "Veľkosť súboru sa po porovnaní zmenila. Súbor zostal nezmenený.",
            "ChangedHash", "Tieto dva súbory už nie sú totožné. Starý súbor zostal nezmenený.",
            "SafetyDestinationExists", "Súbor s rovnakou cestou už v bezpečnostnom priečinku existuje.",
            "SafetyVerificationFailed", "Overenie bezpečnostného priečinka po presune zlyhalo. Program LegacySift sa pokúsil automaticky obnoviť pôvodný súbor.",
            "MovedSafety", "Presunuté do bezpečnostného priečinka a overené.",
            "MovedRecycle", "Presunuté do Koša systému Windows.",
            "SafetyFolderMissing", "Bezpečnostný priečinok sa nenašiel.",
            "RestoreNoOverwrite", "Neprepísané: {0}",
            "SessionMissing", "Chýba súbor LegacySift.session, takže automatická obnova nie je možná.",
            "SessionInvalid", "Relácia bezpečnostného priečinka je neplatná: chýba pôvodná cesta k starému priečinku.",
            "TabRecoverHelp", "V priečinku CURRENT sa nenašla žiadna totožná kópia. Tieto súbory zostávajú v priečinku OLD.",
            "TabVersionsHelp", "V priečinku CURRENT existuje súbor s rovnakým názvom, ale obsah sa líši. Tieto súbory zostávajú v priečinku OLD.",
            "TabDuplicatesHelp", "V priečinku CURRENT už existuje totožná kópia. Počas čistenia možno odstrániť len tieto súbory z priečinka OLD.",
            "TabProblemsHelp", "Program LegacySift nedokázal tieto súbory bezpečne overiť. Zostávajú v priečinku OLD.",
            "CheckingNow", "Kontrola dvoch priečinkov... žiadny súbor sa nemení.",
            "CleanupBeforeAnalysis", "Najprv spustite kontrolu. Program LegacySift následne presne ukáže, čo možno z priečinka OLD odstrániť a čo tam zostane.",
            "CleanupWaitForAnalysis", "Počkajte na dokončenie kontroly. Počas čítania priečinkov programom LegacySift je čistenie zakázané.",
            "CleanupExplanation", "Po čistení zostanú v priečinku OLD súbory {0} (nenájdené v CURRENT), {1} (možné odlišné verzie) a {2} (neskontrolované súbory). Z priečinka OLD sa odstránia iba identické kópie {3}.",
            "AfterCleanupSummary", "Čistenie dokončené: identické kópie {0} boli odstránené z priečinka OLD;kandidáti {1} zostali z bezpečnostných dôvodov nedotknutí. Spustite kontrolu znova, aby ste videli, čo presne zostalo.",
            "CleanupNeedsNewCheck", "Čistenie sa skončilo. Spustite kontrolu znova, aby ste videli, čo zostalo v priečinku OLD.",
            "HelpText", "LEGACYSIFT — RÝCHLY NÁVOD\\n\\nNA ČO SLÚŽI\\nLegacySift je určený na migráciu dát, prácu so starými diskmi a obnovenými zálohami. Vyberte priečinok OLD (starý) a priečinok CURRENT (aktuálny), ktorý používate v súčasnosti. LegacySift ukáže, čo v priečinku CURRENT chýba a aké presné kópie už máte k dispozícii.\\n\\nSMER SA NEMENÍ\\nPriečinok OLD = môže byť vyčistený.\\nPriečinok CURRENT = chránený, slúži len na porovnanie. LegacySift ho nikdy nečistí.\\n\\nAKO HO POUŽÍVAŤ\\n1. Vyberte priečinok OLD.\\n2. Vyberte priečinok CURRENT.\\n3. Kliknite na „CHECK WHAT YOU ALREADY HAVE“ (Skontrolovať, čo už máte). Tento krok nič nemení.\\n4. Prečítajte si výsledky.\\n5. Ak dávajú zmysel, odstráňte z priečinka OLD len identické kópie.\\n\\nVÝZNAM VÝSLEDKOV\\n• NOT FOUND IN CURRENT (Nenájdené v CURRENT): v priečinku CURRENT neexistuje žiadna identická kópia. Tieto súbory zostávajú v priečinku OLD.\\n• POSSIBLE DIFFERENT VERSIONS (Možné odlišné verzie): existuje súbor s rovnakým názvom, ale obsah sa líši. Tieto súbory zostávajú v priečinku OLD.\\n• IDENTICAL COPIES ALREADY IN CURRENT (Identické kópie už v CURRENT): v priečinku CURRENT existuje presná kópia. Z priečinka OLD možno odstrániť len tieto súbory.\\n• FILES NOT CHECKED (Neskontrolované súbory): LegacySift ich nedokázal bezpečne overiť. Zostávajú v priečinku OLD.\\n\\nPO VYČISTENÍ\\nV priečinku OLD zostanú súbory, ktoré sa nenašli v priečinku CURRENT, prípadné odlišné verzie a všetko, čo LegacySift nedokázal bezpečne overiť. Z priečinka OLD sa odstraňujú iba presné kópie.\\n\\nNAJBEZPEČNEJŠIA METÓDA\\nPoužite priečinok Safety (bezpečnostný priečinok). Presné kópie sa namiesto trvalého odstránenia presunú do samostatného priečinka vedľa priečinka OLD, z ktorého ich možno obnoviť.\\n\\nTECHNICKÁ BEZPEČNOSŤ\\nPresný obsah sa overuje pomocou algoritmu SHA-256 a opätovne kontroluje pred samotným čistením. Prepojené priečinky (tzv. reparse points) sa vynechávajú. Výber vnorených priečinkov je blokovaný. Nástroj LegacySift nevyžaduje oprávnenia správcu a funguje výlučne lokálne.\\n\\nJEDNODUCHÉ PRAVIDLO\\nAk si nie ste istí, po kontrole proces ukončite. K žiadnym zmenám nedôjde, kým výslovne nespustíte čistenie."
        );
    }
}
