using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Pl = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — bezpiecznie wyczyść stary folder",
            "TabWork", "Porównaj i wyczyść",
            "TabHelp", "Instrukcja i bezpieczeństwo",
            "LanguageButton", "Język…",
            "Intro", "Stary folder po lewej, bieżący folder po prawej. LegacySift usuwa ze STAREGO folderu tylko pliki, których identyczna kopia już istnieje w BIEŻĄCYM folderze.",
            "OldTitle", "1. STARY FOLDER",
            "OldBadge", "TEN MOŻE BYĆ CZYSZCZONY",
            "OldDescription", "Folder odzyskany ze starego komputera, dysku lub kopii zapasowej. Tylko ta strona może zostać zmieniona podczas czyszczenia.",
            "CurrentTitle", "2. BIEŻĄCY FOLDER",
            "CurrentBadge", "CHRONIONY • TYLKO DO ODCZYTU",
            "CurrentDescription", "Folder, którego używasz teraz. LegacySift tylko go odczytuje do porównania i nigdy go nie czyści.",
            "Browse", "Przeglądaj…",
            "Direction", "Porównanie: STARY folder → chroniony BIEŻĄCY folder. Sprawdzanie tylko odczytuje pliki i niczego nie zmienia.",
            "Analyze", "3. SPRAWDŹ, CO JUŻ MASZ — niczego nie zmienia",
            "Cancel", "Anuluj",
            "OpenReport", "Otwórz ostatni raport",
            "NoAnalysis", "Wybierz STARY folder i chroniony BIEŻĄCY folder, a następnie uruchom sprawdzanie.",
            "PathsChanged", "Zmieniono wybór folderu. Uruchom sprawdzanie ponownie przed czyszczeniem.",
            "TabRecover", "BRAK W BIEŻĄCYM FOLDERZE",
            "TabVersions", "MOŻLIWE INNE WERSJE",
            "TabDuplicates", "IDENTYCZNE KOPIE",
            "TabProblems", "PLIKI NIESPRAWDZONE",
            "GridOld", "Plik w STARYM folderze",
            "GridSize", "Rozmiar",
            "GridCurrent", "Pasujący plik w BIEŻĄCYM folderze",
            "GridNote", "Co znalazł LegacySift",
            "CleanupGroup", "4. WYCZYŚĆ STARY FOLDER",
            "Quarantine", "Folder bezpieczeństwa (zalecane) — przenosi identyczne kopie poza STARY folder i pozwala je przywrócić",
            "Recycle", "Kosz systemu Windows — wysyła identyczne kopie ze STAREGO folderu do Kosza",
            "OtherOptions", "Pokaż inne opcje",
            "HideOptions", "Ukryj inne opcje",
            "RemoveEmpty", "Usuń foldery, które po czyszczeniu są całkowicie puste w STARYM folderze",
            "Confirm", "Rozumiem: zmieniony zostanie TYLKO STARY folder. BIEŻĄCY folder pozostanie bez zmian.",
            "Cleanup", "USUŃ IDENTYCZNE KOPIE ZE STAREGO FOLDERU",
            "Restore", "Przywróć odłożone pliki…",
            "ProtectedReminder", "BIEŻĄCY pozostaje chroniony",
            "Ready", "Gotowe.",
            "ChooseOldDialog", "Wybierz STARY folder do sprawdzenia i wyczyszczenia",
            "ChooseCurrentDialog", "Wybierz BIEŻĄCY / CHRONIONY folder",
            "AnalyzeDone", "Sprawdzanie zakończone. Żaden plik nie został zmieniony.",
            "AnalyzeCanceled", "Sprawdzanie anulowane. Żaden plik nie został zmieniony.",
            "AnalyzeErrorTitle", "Problem podczas sprawdzania",
            "AnalyzeErrorStatus", "Sprawdzanie zatrzymało się z powodu problemu. Nie wykonano czyszczenia.",
            "PathCheckTitle", "LegacySift — sprawdź wybór folderów",
            "CleanupConfirmTitle", "Potwierdź czyszczenie STAREGO folderu",
            "CleanupConfirm", "Za chwilę wyczyścisz TYLKO STARY folder:\n\n{0}\n\nBIEŻĄCY folder jest chroniony i nie zostanie zmieniony:\n\n{1}\n\nUsunięte ze STAREGO: {2} identycznych kopii.\nPozostaną w STARYM: {3} brakujących w BIEŻĄCYM, {4} możliwych innych wersji, {5} niesprawdzonych.\n\nMetoda: {6}\n\nKontynuować?",
            "ModeSafety", "FOLDER BEZPIECZEŃSTWA (można przywrócić)",
            "ModeRecycle", "KOSZ SYSTEMU WINDOWS",
            "CleanupDoneStatus", "Gotowe: ze STAREGO folderu usunięto {0} identycznych kopii; {1} pozycji pozostawiono bez zmian dla bezpieczeństwa.",
            "CleanupDoneTitle", "LegacySift — zakończono",
            "CleanupDone", "Czyszczenie zakończone.\n\nUsunięto ze STAREGO folderu: {0} identycznych kopii\nPozostawiono dla bezpieczeństwa: {1}{2}\n\nPliki nieobecne w BIEŻĄCYM folderze i możliwe inne wersje nie zostały zmienione. Uruchom sprawdzanie ponownie, aby zobaczyć dokładnie, co zostało.",
            "CleanupSafetyLocation", "\n\nFolder bezpieczeństwa:\n{0}\n\nNie usuwaj go, dopóki nie sprawdzisz plików pozostałych w starym folderze.",
            "CleanupCanceled", "Czyszczenie zatrzymane. Pliki już przeniesione pozostają w folderze bezpieczeństwa / Koszu; pozostałych plików nie zmieniono.",
            "CleanupErrorTitle", "Problem podczas czyszczenia",
            "CleanupErrorStatus", "Czyszczenie zatrzymało się z powodu problemu. Sprawdź folder bezpieczeństwa i wykonaj nowe porównanie przed ponowną próbą.",
            "RestoreLast", "Przywrócić ostatnio utworzony folder bezpieczeństwa?\n\n{0}",
            "RestoreTitle", "Przywróć pliki",
            "RestoreChoose", "Wybierz folder __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift spróbuje przywrócić pliki do ich pierwotnych miejsc w STARYM folderze.\nPliki, które już tam istnieją, NIE zostaną nadpisane.\n\nKontynuować?",
            "RestoreConfirmTitle", "Potwierdź przywracanie",
            "RestoreDoneStatus", "Przywracanie zakończone: przywrócono {0} plików; {1} konfliktów nie nadpisano.",
            "RestoreDone", "Przywrócono: {0}\nKonflikty NIE nadpisane: {1}\nBłędy: {2}",
            "RestoreCanceled", "Przywracanie zatrzymane.",
            "RestoreErrorTitle", "Problem podczas przywracania",
            "Summary", "SPRAWDZANIE ZAKOŃCZONE — żaden plik nie został zmieniony.\n{0} brak w BIEŻĄCYM   |   {1} możliwe inne wersje   |   {2} identyczne kopie ({3})   |   {4} niesprawdzone",
            "CleanupCount", "USUŃ {0} IDENTYCZNYCH KOPII ZE STAREGO FOLDERU",
            "PhaseOldScan", "Odczytywanie STAREGO folderu",
            "PhaseCurrentScan", "Odczytywanie chronionego BIEŻĄCEGO folderu",
            "PhaseCompare", "Porównywanie zawartości plików",
            "PhaseSafety", "Przenoszenie plików do folderu bezpieczeństwa",
            "PhaseRecycle", "Przenoszenie plików do Kosza",
            "PhaseRestoreRead", "Odczytywanie folderu bezpieczeństwa",
            "PhaseRestore", "Przywracanie plików",
            "OldRequired", "Najpierw wybierz STARY folder.",
            "CurrentRequired", "Wybierz BIEŻĄCY / CHRONIONY folder.",
            "InvalidPath", "Nieprawidłowa ścieżka: {0}",
            "OldMissing", "STARY folder nie istnieje.",
            "CurrentMissing", "BIEŻĄCY / CHRONIONY folder nie istnieje.",
            "SameFolder", "Oba wybory wskazują ten sam folder. Operacja zablokowana.",
            "OldRootBlocked", "Dla bezpieczeństwa nie można użyć całego katalogu głównego dysku jako STAREGO folderu.",
            "CurrentRootBlocked", "Dla bezpieczeństwa nie można użyć całego katalogu głównego dysku jako BIEŻĄCEGO folderu.",
            "NestedBlocked", "Jeden wybrany folder znajduje się wewnątrz drugiego. Wybierz dwa oddzielne foldery.",
            "SystemFolderBlocked", "Dla bezpieczeństwa LegacySift nie czyści bezpośrednio głównego folderu systemowego Windows.",
            "OutsideOld", "Kontrola bezpieczeństwa nie powiodła się: ten plik nie znajduje się w STARYM folderze.",
            "ReparseDir", "Połączony folder / punkt ponownej analizy pominięty dla bezpieczeństwa.",
            "ReparseFile", "Połączony plik / punkt ponownej analizy pominięty dla bezpieczeństwa.",
            "ExactNote", "W BIEŻĄCYM folderze istnieje identyczna kopia. Tę kopię w STARYM folderze można bezpiecznie usunąć.",
            "VersionNoteOne", "W bieżącym folderze istnieje plik o tej samej nazwie, ale jego zawartość jest inna. Ten plik NIE zostanie usunięty.",
            "VersionNoteMany", "Znaleziono {0} plików o tej samej nazwie, ale żaden nie jest identyczny. Ten plik NIE zostanie usunięty.",
            "UniqueNote", "W BIEŻĄCYM folderze nie znaleziono identycznej kopii. Ten plik pozostaje w STARYM folderze.",
            "LanguageRestart", "LegacySift uruchomi się ponownie, aby zastosować nowy język. Bieżące wyniki sprawdzania zostaną wyczyszczone.",
            "LanguageRestartTitle", "Zmień język",
            "SafetyParentMissing", "LegacySift nie może określić, gdzie utworzyć folder bezpieczeństwa.",
            "OldFileMissingNow", "Plik w starym folderze już nie istnieje.",
            "CurrentCopyMissingNow", "Pasujący plik w bieżącym folderze już nie istnieje.",
            "ChangedSize", "Rozmiar pliku zmienił się po porównaniu. Plik pozostawiono bez zmian.",
            "ChangedHash", "Pliki nie są już identyczne. Stary plik pozostawiono bez zmian.",
            "SafetyDestinationExists", "W folderze bezpieczeństwa istnieje już plik o tej samej ścieżce.",
            "SafetyVerificationFailed", "Weryfikacja po przeniesieniu do folderu bezpieczeństwa nie powiodła się. LegacySift próbował automatycznie przywrócić oryginalny plik.",
            "MovedSafety", "Przeniesiono do folderu bezpieczeństwa i zweryfikowano.",
            "MovedRecycle", "Przeniesiono do Kosza systemu Windows.",
            "SafetyFolderMissing", "Nie znaleziono folderu bezpieczeństwa.",
            "RestoreNoOverwrite", "NIE nadpisano: {0}",
            "SessionMissing", "Brakuje LegacySift.session, więc automatyczne przywrócenie nie jest możliwe.",
            "SessionInvalid", "Sesja folderu bezpieczeństwa jest nieprawidłowa: brakuje pierwotnej ścieżki starego folderu.",
            "TabRecoverHelp", "W BIEŻĄCYM folderze nie znaleziono identycznej kopii. Te pliki pozostaną w STARYM folderze.",
            "TabVersionsHelp", "W BIEŻĄCYM folderze istnieje ta sama nazwa, ale zawartość jest inna. Te pliki pozostaną w STARYM folderze.",
            "TabDuplicatesHelp", "W BIEŻĄCYM folderze istnieje już identyczna kopia. Tylko te pliki ze STAREGO folderu mogą zostać usunięte podczas czyszczenia.",
            "TabProblemsHelp", "LegacySift nie mógł bezpiecznie zweryfikować tych plików. Pozostaną w STARYM folderze.",
            "CheckingNow", "Sprawdzanie obu folderów… żaden plik nie jest zmieniany.",
            "CleanupBeforeAnalysis", "Najpierw uruchom sprawdzanie. Potem LegacySift pokaże dokładnie, co można usunąć ze STAREGO folderu i co w nim pozostanie.",
            "CleanupWaitForAnalysis", "Poczekaj na zakończenie sprawdzania. Czyszczenie jest wyłączone, gdy LegacySift odczytuje foldery.",
            "CleanupExplanation", "Po czyszczeniu w STARYM folderze pozostanie {0} plików nieobecnych w BIEŻĄCYM, {1} możliwych innych wersji i {2} plików niesprawdzonych. Tylko {3} identycznych kopii zostanie usuniętych ze STAREGO.",
            "AfterCleanupSummary", "Czyszczenie zakończone: {0} identycznych kopii usunięto ze STAREGO; {1} elementów pozostawiono bez zmian dla bezpieczeństwa. Uruchom sprawdzanie ponownie, aby dokładnie zobaczyć, co zostało.",
            "CleanupNeedsNewCheck", "Czyszczenie zakończone. Uruchom sprawdzanie ponownie, aby zobaczyć tylko to, co pozostało w STARYM folderze.",
            "HelpText", "LEGACYSIFT — SZYBKA INSTRUKCJA\n\nDO CZEGO SŁUŻY\nLegacySift jest przeznaczony do migracji komputerów, starych dysków i odzyskanych kopii zapasowych. Wybierz STARY folder i BIEŻĄCY folder, którego używasz dziś. LegacySift pokaże, czego brakuje w BIEŻĄCYM i które dokładne kopie już masz.\n\nKIERUNEK NIGDY SIĘ NIE ZMIENIA\nSTARY FOLDER = może być czyszczony.\nBIEŻĄCY FOLDER = chroniony, tylko do porównania. LegacySift nigdy go nie czyści.\n\nJAK UŻYWAĆ\n1. Wybierz STARY FOLDER.\n2. Wybierz BIEŻĄCY FOLDER.\n3. Kliknij SPRAWDŹ, CO JUŻ MASZ. Ten krok niczego nie zmienia.\n4. Przeczytaj wyniki.\n5. Jeśli wszystko się zgadza, usuń ze STAREGO tylko identyczne kopie.\n\nCO OZNACZAJĄ WYNIKI\n• BRAK W BIEŻĄCYM FOLDERZE: w BIEŻĄCYM nie ma identycznej kopii. Te pliki pozostają w STARYM.\n• MOŻLIWE INNE WERSJE: istnieje ta sama nazwa, ale zawartość jest inna. Te pliki pozostają w STARYM.\n• IDENTYCZNE KOPIE: w BIEŻĄCYM istnieje dokładna kopia. Tylko te pliki można usunąć ze STAREGO.\n• PLIKI NIESPRAWDZONE: LegacySift nie mógł ich bezpiecznie zweryfikować. Pozostają w STARYM.\n\nPO CZYSZCZENIU\nW STARYM folderze pozostają pliki nieznalezione w BIEŻĄCYM, możliwe inne wersje i wszystko, czego LegacySift nie mógł bezpiecznie zweryfikować. Usuwane są tylko identyczne kopie.\n\nNAJBEZPIECZNIEJSZA METODA\nUżyj FOLDERU BEZPIECZEŃSTWA. Identyczne kopie są przenoszone do osobnego, możliwego do przywrócenia folderu obok STAREGO zamiast trwałego usuwania.\n\nBEZPIECZEŃSTWO TECHNICZNE\nDokładna zawartość jest porównywana za pomocą SHA-256 i ponownie sprawdzana przed czyszczeniem. Łącza i punkty ponownej analizy są pomijane. Zagnieżdżone foldery są blokowane. LegacySift nie wymaga uprawnień administratora i działa całkowicie lokalnie.\n\nPROSTA ZASADA\nJeśli masz wątpliwości, zatrzymaj się po sprawdzeniu. Nic się nie zmienia, dopóki wyraźnie nie uruchomisz czyszczenia."
        );

        private static readonly Dictionary<string, string> Nl = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — ruim een oude map veilig op",
            "TabWork", "Vergelijken en opruimen",
            "TabHelp", "Handleiding en veiligheid",
            "LanguageButton", "Taal…",
            "Intro", "Oude map links, huidige map rechts. LegacySift verwijdert uit de OUDE map alleen bestanden waarvan al een identieke kopie in de HUIDIGE map bestaat.",
            "OldTitle", "1. OUDE MAP",
            "OldBadge", "DEZE MAG WORDEN OPGESCHOOND",
            "OldDescription", "De teruggehaalde map van de oude computer, schijf of back-up. Alleen deze kant mag door de opruiming worden gewijzigd.",
            "CurrentTitle", "2. HUIDIGE MAP",
            "CurrentBadge", "BESCHERMD • ALLEEN-LEZEN",
            "CurrentDescription", "De map die je nu gebruikt. LegacySift leest deze alleen voor vergelijking en ruimt hem nooit op.",
            "Browse", "Bladeren…",
            "Direction", "Vergelijking: OUDE map → beschermde HUIDIGE map. De controle leest alleen bestanden en wijzigt niets.",
            "Analyze", "3. CONTROLEER WAT JE AL HEBT — wijzigt niets",
            "Cancel", "Annuleren",
            "OpenReport", "Laatste rapport openen",
            "NoAnalysis", "Kies de OUDE map en de beschermde HUIDIGE map en start daarna de controle.",
            "PathsChanged", "Een mapselectie is gewijzigd. Voer de controle opnieuw uit voordat je opruimt.",
            "TabRecover", "NIET IN DE HUIDIGE MAP",
            "TabVersions", "MOGELIJK ANDERE VERSIES",
            "TabDuplicates", "IDENTIEKE KOPIEËN",
            "TabProblems", "NIET GECONTROLEERDE BESTANDEN",
            "GridOld", "Bestand in OUDE map",
            "GridSize", "Grootte",
            "GridCurrent", "Overeenkomstig bestand in HUIDIGE map",
            "GridNote", "Wat LegacySift heeft gevonden",
            "CleanupGroup", "4. RUIM DE OUDE MAP OP",
            "Quarantine", "Veiligheidsmap (aanbevolen) — verplaats identieke kopieën uit OUDE zodat ze kunnen worden hersteld",
            "Recycle", "Windows Prullenbak — stuur identieke kopieën uit de OUDE map naar de Prullenbak",
            "OtherOptions", "Meer opties tonen",
            "HideOptions", "Meer opties verbergen",
            "RemoveEmpty", "Mappen verwijderen die volledig leeg zijn geworden in de OUDE map",
            "Confirm", "Ik begrijp het: ALLEEN de OUDE map wordt gewijzigd. De HUIDIGE map blijft ongewijzigd.",
            "Cleanup", "IDENTIEKE KOPIEËN UIT DE OUDE MAP VERWIJDEREN",
            "Restore", "Apart gezette bestanden herstellen…",
            "ProtectedReminder", "HUIDIGE blijft beschermd",
            "Ready", "Gereed.",
            "ChooseOldDialog", "Kies de OUDE map om te controleren en op te ruimen",
            "ChooseCurrentDialog", "Kies de HUIDIGE / BESCHERMDE map",
            "AnalyzeDone", "Controle voltooid. Geen enkel bestand is gewijzigd.",
            "AnalyzeCanceled", "Controle geannuleerd. Geen enkel bestand is gewijzigd.",
            "AnalyzeErrorTitle", "Probleem tijdens de controle",
            "AnalyzeErrorStatus", "De controle is gestopt door een probleem. Er is niets opgeruimd.",
            "PathCheckTitle", "LegacySift — mapselectie controleren",
            "CleanupConfirmTitle", "Opruimen van de OUDE map bevestigen",
            "CleanupConfirm", "Je staat op het punt ALLEEN de OUDE map op te ruimen:\n\n{0}\n\nDe HUIDIGE map is beschermd en wordt niet gewijzigd:\n\n{1}\n\nUit OUDE verwijderd: {2} identieke kopieën.\nBlijven in OUDE: {3} niet gevonden in HUIDIGE, {4} mogelijk andere versies, {5} niet gecontroleerd.\n\nMethode: {6}\n\nDoorgaan?",
            "ModeSafety", "VEILIGHEIDSMAP (herstelbaar)",
            "ModeRecycle", "WINDOWS PRULLENBAK",
            "CleanupDoneStatus", "Klaar: {0} identieke kopieën zijn uit de OUDE map verwijderd; {1} items zijn voor de veiligheid ongemoeid gelaten.",
            "CleanupDoneTitle", "LegacySift — voltooid",
            "CleanupDone", "Opruiming voltooid.\n\nUit de OUDE map verwijderd: {0} identieke kopieën\nVoor de veiligheid ongemoeid gelaten: {1}{2}\n\nBestanden die niet in de HUIDIGE map stonden en mogelijke andere versies zijn niet gewijzigd. Voer de controle opnieuw uit om precies te zien wat er over is.",
            "CleanupSafetyLocation", "\n\nVeiligheidsmap:\n{0}\n\nVerwijder deze niet voordat je de bestanden hebt gecontroleerd die in de oude map zijn achtergebleven.",
            "CleanupCanceled", "Opruiming gestopt. Reeds verplaatste bestanden blijven in de veiligheidsmap / Prullenbak; de overige bestanden zijn niet gewijzigd.",
            "CleanupErrorTitle", "Probleem tijdens het opruimen",
            "CleanupErrorStatus", "De opruiming is gestopt door een probleem. Controleer de veiligheidsmap en voer een nieuwe vergelijking uit voordat je opnieuw probeert.",
            "RestoreLast", "De laatst gemaakte veiligheidsmap herstellen?\n\n{0}",
            "RestoreTitle", "Bestanden herstellen",
            "RestoreChoose", "Kies een __LegacySift_Safety_... map",
            "RestoreConfirm", "LegacySift probeert de bestanden terug te zetten op hun oorspronkelijke plaatsen in de OUDE map.\nBestanden die daar al bestaan worden NIET overschreven.\n\nDoorgaan?",
            "RestoreConfirmTitle", "Herstel bevestigen",
            "RestoreDoneStatus", "Herstel voltooid: {0} bestanden hersteld; {1} conflicten niet overschreven.",
            "RestoreDone", "Hersteld: {0}\nConflicten NIET overschreven: {1}\nFouten: {2}",
            "RestoreCanceled", "Herstel gestopt.",
            "RestoreErrorTitle", "Probleem tijdens herstel",
            "Summary", "CONTROLE VOLTOOID — geen enkel bestand is gewijzigd.\n{0} niet in HUIDIGE   |   {1} mogelijk andere versies   |   {2} identieke kopieën ({3})   |   {4} niet gecontroleerd",
            "CleanupCount", "{0} IDENTIEKE KOPIEËN UIT DE OUDE MAP VERWIJDEREN",
            "PhaseOldScan", "OUDE map lezen",
            "PhaseCurrentScan", "Beschermde HUIDIGE map lezen",
            "PhaseCompare", "Bestandsinhoud vergelijken",
            "PhaseSafety", "Bestanden naar veiligheidsmap verplaatsen",
            "PhaseRecycle", "Bestanden naar Prullenbak verplaatsen",
            "PhaseRestoreRead", "Veiligheidsmap lezen",
            "PhaseRestore", "Bestanden herstellen",
            "OldRequired", "Kies eerst de OUDE map.",
            "CurrentRequired", "Kies de HUIDIGE / BESCHERMDE map.",
            "InvalidPath", "Ongeldig pad: {0}",
            "OldMissing", "De OUDE map bestaat niet.",
            "CurrentMissing", "De HUIDIGE / BESCHERMDE map bestaat niet.",
            "SameFolder", "Beide selecties wijzen naar dezelfde map. Bewerking geblokkeerd.",
            "OldRootBlocked", "Voor de veiligheid kan de hoofdmap van een volledig station niet als OUDE map worden gebruikt.",
            "CurrentRootBlocked", "Voor de veiligheid kan de hoofdmap van een volledig station niet als HUIDIGE map worden gebruikt.",
            "NestedBlocked", "Een geselecteerde map bevindt zich in de andere. Kies twee aparte mappen.",
            "SystemFolderBlocked", "Voor de veiligheid ruimt LegacySift geen belangrijke Windows-systeemmap rechtstreeks op.",
            "OutsideOld", "Veiligheidscontrole mislukt: dit bestand bevindt zich niet in de OUDE map.",
            "ReparseDir", "Gekoppelde map / reparse point overgeslagen voor de veiligheid.",
            "ReparseFile", "Gekoppeld bestand / reparse point overgeslagen voor de veiligheid.",
            "ExactNote", "In de HUIDIGE map bestaat een identieke kopie. Deze kopie in de OUDE map kan veilig worden verwijderd.",
            "VersionNoteOne", "In de huidige map bestaat een bestand met dezelfde naam maar met andere inhoud. Dit bestand wordt NIET verwijderd.",
            "VersionNoteMany", "Er zijn {0} bestanden met dezelfde naam gevonden, maar geen daarvan is identiek. Dit bestand wordt NIET verwijderd.",
            "UniqueNote", "In de HUIDIGE map is geen identieke kopie gevonden. Dit bestand blijft in de OUDE map.",
            "LanguageRestart", "LegacySift wordt opnieuw gestart om de nieuwe taal toe te passen. De huidige controleresultaten worden gewist.",
            "LanguageRestartTitle", "Taal wijzigen",
            "SafetyParentMissing", "LegacySift kan niet bepalen waar de veiligheidsmap moet worden gemaakt.",
            "OldFileMissingNow", "Het bestand in de oude map bestaat niet meer.",
            "CurrentCopyMissingNow", "Het overeenkomende bestand in de huidige map bestaat niet meer.",
            "ChangedSize", "De bestandsgrootte is gewijzigd na de vergelijking. Het bestand is ongemoeid gelaten.",
            "ChangedHash", "De twee bestanden zijn niet langer identiek. Het oude bestand is ongemoeid gelaten.",
            "SafetyDestinationExists", "Er bestaat al een bestand met hetzelfde pad in de veiligheidsmap.",
            "SafetyVerificationFailed", "Controle na het verplaatsen naar de veiligheidsmap is mislukt. LegacySift heeft geprobeerd het oorspronkelijke bestand automatisch te herstellen.",
            "MovedSafety", "Naar de veiligheidsmap verplaatst en gecontroleerd.",
            "MovedRecycle", "Naar de Windows Prullenbak verplaatst.",
            "SafetyFolderMissing", "Veiligheidsmap niet gevonden.",
            "RestoreNoOverwrite", "NIET overschreven: {0}",
            "SessionMissing", "LegacySift.session ontbreekt, dus automatisch herstel is niet mogelijk.",
            "SessionInvalid", "De sessie van de veiligheidsmap is ongeldig: het oorspronkelijke pad van de oude map ontbreekt.",
            "TabRecoverHelp", "In HUIDIGE is geen identieke kopie gevonden. Deze bestanden blijven in de OUDE map.",
            "TabVersionsHelp", "In HUIDIGE bestaat dezelfde naam, maar de inhoud is anders. Deze bestanden blijven in de OUDE map.",
            "TabDuplicatesHelp", "In HUIDIGE bestaat al een identieke kopie. Alleen deze bestanden uit de OUDE map kunnen door opruiming worden verwijderd.",
            "TabProblemsHelp", "LegacySift kon deze bestanden niet veilig controleren. Ze blijven in de OUDE map.",
            "CheckingNow", "De twee mappen worden gecontroleerd… geen enkel bestand wordt gewijzigd.",
            "CleanupBeforeAnalysis", "Voer eerst de controle uit. Daarna laat LegacySift precies zien wat uit de OUDE map kan worden verwijderd en wat daar blijft.",
            "CleanupWaitForAnalysis", "Wacht tot de controle klaar is. Opruimen is uitgeschakeld terwijl LegacySift de mappen leest.",
            "CleanupExplanation", "Na het opruimen houdt de OUDE map {0} bestanden die niet in HUIDIGE zijn gevonden, {1} mogelijk andere versies en {2} niet gecontroleerde bestanden. Alleen de {3} identieke kopieën worden uit OUDE verwijderd.",
            "AfterCleanupSummary", "Opruiming voltooid: {0} identieke kopieën uit OUDE verwijderd; {1} items voor de veiligheid ongemoeid gelaten. Voer de controle opnieuw uit om precies te zien wat er over is.",
            "CleanupNeedsNewCheck", "De opruiming is klaar. Voer de controle opnieuw uit om alleen te zien wat in de OUDE map is overgebleven.",
            "HelpText", "LEGACYSIFT — SNELLE HANDLEIDING\n\nWAARVOOR HET DIENT\nLegacySift is bedoeld voor computerverhuizingen, oude schijven en teruggehaalde back-ups. Kies de OUDE map en de HUIDIGE map die je nu gebruikt. LegacySift toont wat in HUIDIGE ontbreekt en welke exacte kopieën je al hebt.\n\nDE RICHTING VERANDERT NOOIT\nOUDE MAP = mag worden opgeschoond.\nHUIDIGE MAP = beschermd, alleen voor vergelijking. LegacySift ruimt deze nooit op.\n\nHOE TE GEBRUIKEN\n1. Kies de OUDE MAP.\n2. Kies de HUIDIGE MAP.\n3. Klik op CONTROLEER WAT JE AL HEBT. Deze stap wijzigt niets.\n4. Lees de resultaten.\n5. Als alles klopt, verwijder dan alleen de identieke kopieën uit OUDE.\n\nWAT DE RESULTATEN BETEKENEN\n• NIET IN DE HUIDIGE MAP: er is geen identieke kopie in HUIDIGE. Deze bestanden blijven in OUDE.\n• MOGELIJK ANDERE VERSIES: dezelfde naam bestaat, maar de inhoud is anders. Deze bestanden blijven in OUDE.\n• IDENTIEKE KOPIEËN: in HUIDIGE bestaat een exacte kopie. Alleen deze bestanden kunnen uit OUDE worden verwijderd.\n• NIET GECONTROLEERDE BESTANDEN: LegacySift kon ze niet veilig controleren. Ze blijven in OUDE.\n\nNA HET OPRUIMEN\nDe OUDE map houdt de bestanden die niet in HUIDIGE zijn gevonden, mogelijk andere versies en alles wat LegacySift niet veilig kon controleren. Alleen identieke kopieën worden verwijderd.\n\nVEILIGSTE METHODE\nGebruik de VEILIGHEIDSMAP. Identieke kopieën worden verplaatst naar een aparte, herstelbare map naast OUDE in plaats van permanent verwijderd.\n\nTECHNISCHE VEILIGHEID\nExacte inhoud wordt met SHA-256 vergeleken en vóór het opruimen opnieuw gecontroleerd. Koppelingen en reparse points worden overgeslagen. Geneste mappen worden geblokkeerd. LegacySift vraagt geen administratorrechten en werkt volledig lokaal.\n\nEENVOUDIGE REGEL\nAls je twijfelt, stop dan na de controle. Er verandert niets totdat je het opruimen expliciet start."
        );

        private static readonly Dictionary<string, string> Tr = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — eski bir klasörü güvenle temizle",
            "TabWork", "Karşılaştır ve temizle",
            "TabHelp", "Kılavuz ve güvenlik",
            "LanguageButton", "Dil…",
            "Intro", "Eski klasör solda, güncel klasör sağda. LegacySift ESKİ klasörden yalnızca GÜNCEL klasörde birebir aynı kopyası bulunan dosyaları kaldırır.",
            "OldTitle", "1. ESKİ KLASÖR",
            "OldBadge", "BU TEMİZLENEBİLİR",
            "OldDescription", "Eski bilgisayar, disk veya yedekten kurtarılan klasör. Temizleme sırasında yalnızca bu taraf değiştirilebilir.",
            "CurrentTitle", "2. GÜNCEL KLASÖR",
            "CurrentBadge", "KORUMALI • SALT OKUNUR",
            "CurrentDescription", "Bugün kullandığınız klasör. LegacySift bunu yalnızca karşılaştırma için okur ve asla temizlemez.",
            "Browse", "Gözat…",
            "Direction", "Karşılaştırma: ESKİ klasör → korumalı GÜNCEL klasör. Kontrol yalnızca dosyaları okur; hiçbir şeyi değiştirmez.",
            "Analyze", "3. ZATEN NELERE SAHİP OLDUĞUNU KONTROL ET — hiçbir şeyi değiştirmez",
            "Cancel", "İptal",
            "OpenReport", "Son raporu aç",
            "NoAnalysis", "ESKİ klasörü ve korumalı GÜNCEL klasörü seçin, ardından kontrolü başlatın.",
            "PathsChanged", "Klasör seçimi değişti. Herhangi bir temizlik yapmadan önce kontrolü yeniden çalıştırın.",
            "TabRecover", "GÜNCEL KLASÖRDE YOK",
            "TabVersions", "OLASI FARKLI SÜRÜMLER",
            "TabDuplicates", "BİREBİR AYNI KOPYALAR",
            "TabProblems", "KONTROL EDİLEMEYEN DOSYALAR",
            "GridOld", "ESKİ klasördeki dosya",
            "GridSize", "Boyut",
            "GridCurrent", "GÜNCEL klasörde eşleşen dosya",
            "GridNote", "LegacySift'in bulduğu",
            "CleanupGroup", "4. ESKİ KLASÖRÜ TEMİZLE",
            "Quarantine", "Güvenlik klasörü (önerilen) — aynı kopyaları ESKİ klasörün dışına taşır ve geri yüklenmelerine izin verir",
            "Recycle", "Windows Geri Dönüşüm Kutusu — ESKİ klasördeki aynı kopyaları Geri Dönüşüm Kutusu'na gönderir",
            "OtherOptions", "Diğer seçenekleri göster",
            "HideOptions", "Diğer seçenekleri gizle",
            "RemoveEmpty", "ESKİ klasörde tamamen boş kalan klasörleri kaldır",
            "Confirm", "Anlıyorum: YALNIZCA ESKİ klasör değiştirilecek. GÜNCEL klasör değişmeden kalacak.",
            "Cleanup", "AYNI KOPYALARI ESKİ KLASÖRDEN KALDIR",
            "Restore", "Kenara alınan dosyaları geri yükle…",
            "ProtectedReminder", "GÜNCEL korumalı kalır",
            "Ready", "Hazır.",
            "ChooseOldDialog", "Kontrol edip temizlemek için ESKİ klasörü seçin",
            "ChooseCurrentDialog", "GÜNCEL / KORUMALI klasörü seçin",
            "AnalyzeDone", "Kontrol tamamlandı. Hiçbir dosya değiştirilmedi.",
            "AnalyzeCanceled", "Kontrol iptal edildi. Hiçbir dosya değiştirilmedi.",
            "AnalyzeErrorTitle", "Kontrol sırasında sorun",
            "AnalyzeErrorStatus", "Kontrol bir sorun nedeniyle durdu. Temizlik yapılmadı.",
            "PathCheckTitle", "LegacySift — klasör seçimini kontrol et",
            "CleanupConfirmTitle", "ESKİ klasör temizliğini onayla",
            "CleanupConfirm", "YALNIZCA ESKİ klasörü temizlemek üzeresiniz:\n\n{0}\n\nGÜNCEL klasör korumalıdır ve değiştirilmeyecektir:\n\n{1}\n\nESKİ klasörden kaldırılacak: {2} birebir aynı kopya.\nESKİ klasörde kalacak: GÜNCEL'de bulunmayan {3}, olası farklı sürüm {4}, kontrol edilmeyen {5}.\n\nYöntem: {6}\n\nDevam edilsin mi?",
            "ModeSafety", "GÜVENLİK KLASÖRÜ (geri yüklenebilir)",
            "ModeRecycle", "WINDOWS GERİ DÖNÜŞÜM KUTUSU",
            "CleanupDoneStatus", "Tamam: ESKİ klasörden {0} birebir aynı kopya kaldırıldı; {1} öğeye güvenlik için dokunulmadı.",
            "CleanupDoneTitle", "LegacySift — tamamlandı",
            "CleanupDone", "Temizlik tamamlandı.\n\nESKİ klasörden kaldırıldı: {0} birebir aynı kopya\nGüvenlik için yerinde bırakıldı: {1}{2}\n\nGÜNCEL klasörde bulunmayan dosyalara ve olası farklı sürümlere dokunulmadı. Tam olarak ne kaldığını görmek için kontrolü yeniden çalıştırın.",
            "CleanupSafetyLocation", "\n\nGüvenlik klasörü:\n{0}\n\nEski klasörde kalan dosyaları kontrol edene kadar bunu silmeyin.",
            "CleanupCanceled", "Temizlik durduruldu. Daha önce taşınan dosyalar güvenlik klasöründe / Geri Dönüşüm Kutusu'nda kalır; diğer dosyalara dokunulmadı.",
            "CleanupErrorTitle", "Temizlik sırasında sorun",
            "CleanupErrorStatus", "Temizlik bir sorun nedeniyle durdu. Güvenlik klasörünü kontrol edin ve yeniden denemeden önce yeni bir karşılaştırma yapın.",
            "RestoreLast", "Son oluşturulan güvenlik klasörü geri yüklensin mi?\n\n{0}",
            "RestoreTitle", "Dosyaları geri yükle",
            "RestoreChoose", "Bir __LegacySift_Safety_... klasörü seçin",
            "RestoreConfirm", "LegacySift dosyaları ESKİ klasördeki özgün konumlarına geri koymayı deneyecek.\nOrada zaten bulunan dosyaların üzerine YAZILMAYACAK.\n\nDevam edilsin mi?",
            "RestoreConfirmTitle", "Geri yüklemeyi onayla",
            "RestoreDoneStatus", "Geri yükleme tamamlandı: {0} dosya geri yüklendi; {1} çakışmanın üzerine yazılmadı.",
            "RestoreDone", "Geri yüklendi: {0}\nÜzerine YAZILMAYAN çakışmalar: {1}\nHatalar: {2}",
            "RestoreCanceled", "Geri yükleme durduruldu.",
            "RestoreErrorTitle", "Geri yükleme sırasında sorun",
            "Summary", "KONTROL TAMAMLANDI — hiçbir dosya değiştirilmedi.\nGÜNCEL'de yok: {0}   |   olası farklı sürüm: {1}   |   birebir aynı kopya: {2} ({3})   |   kontrol edilmedi: {4}",
            "CleanupCount", "{0} AYNI KOPYAYI ESKİ KLASÖRDEN KALDIR",
            "PhaseOldScan", "ESKİ klasör okunuyor",
            "PhaseCurrentScan", "Korumalı GÜNCEL klasör okunuyor",
            "PhaseCompare", "Dosya içerikleri karşılaştırılıyor",
            "PhaseSafety", "Dosyalar güvenlik klasörüne taşınıyor",
            "PhaseRecycle", "Dosyalar Geri Dönüşüm Kutusu'na taşınıyor",
            "PhaseRestoreRead", "Güvenlik klasörü okunuyor",
            "PhaseRestore", "Dosyalar geri yükleniyor",
            "OldRequired", "Önce ESKİ klasörü seçin.",
            "CurrentRequired", "GÜNCEL / KORUMALI klasörü seçin.",
            "InvalidPath", "Geçersiz yol: {0}",
            "OldMissing", "ESKİ klasör mevcut değil.",
            "CurrentMissing", "GÜNCEL / KORUMALI klasör mevcut değil.",
            "SameFolder", "İki seçim aynı klasörü gösteriyor. İşlem engellendi.",
            "OldRootBlocked", "Güvenlik için tüm sürücü kökü ESKİ klasör olarak kullanılamaz.",
            "CurrentRootBlocked", "Güvenlik için tüm sürücü kökü GÜNCEL klasör olarak kullanılamaz.",
            "NestedBlocked", "Seçilen klasörlerden biri diğerinin içinde. İki ayrı klasör seçin.",
            "SystemFolderBlocked", "Güvenlik için LegacySift ana Windows sistem klasörlerini doğrudan temizlemez.",
            "OutsideOld", "Güvenlik kontrolü başarısız: bu dosya ESKİ klasörün içinde değil.",
            "ReparseDir", "Bağlantılı klasör / reparse point güvenlik için atlandı.",
            "ReparseFile", "Bağlantılı dosya / reparse point güvenlik için atlandı.",
            "ExactNote", "GÜNCEL klasörde birebir aynı bir kopya var. ESKİ klasördeki bu kopya güvenle kaldırılabilir.",
            "VersionNoteOne", "Güncel klasörde aynı adda bir dosya var ancak içeriği farklı. Bu dosya KALDIRILMAYACAK.",
            "VersionNoteMany", "Aynı ada sahip {0} dosya bulundu ancak hiçbiri birebir aynı değil. Bu dosya KALDIRILMAYACAK.",
            "UniqueNote", "GÜNCEL klasörde birebir aynı bir kopya bulunamadı. Bu dosya ESKİ klasörde kalır.",
            "LanguageRestart", "Yeni dili uygulamak için LegacySift yeniden başlatılacak. Mevcut kontrol sonuçları temizlenecek.",
            "LanguageRestartTitle", "Dili değiştir",
            "SafetyParentMissing", "LegacySift güvenlik klasörünün nerede oluşturulacağını belirleyemiyor.",
            "OldFileMissingNow", "Eski klasördeki dosya artık mevcut değil.",
            "CurrentCopyMissingNow", "Güncel klasördeki eşleşen dosya artık mevcut değil.",
            "ChangedSize", "Dosya boyutu karşılaştırmadan sonra değişti. Dosyaya dokunulmadı.",
            "ChangedHash", "İki dosya artık birebir aynı değil. Eski dosyaya dokunulmadı.",
            "SafetyDestinationExists", "Güvenlik klasöründe aynı yola sahip bir dosya zaten var.",
            "SafetyVerificationFailed", "Güvenlik klasörüne taşıma sonrası doğrulama başarısız oldu. LegacySift özgün dosyayı otomatik olarak geri yüklemeyi denedi.",
            "MovedSafety", "Güvenlik klasörüne taşındı ve doğrulandı.",
            "MovedRecycle", "Windows Geri Dönüşüm Kutusu'na taşındı.",
            "SafetyFolderMissing", "Güvenlik klasörü bulunamadı.",
            "RestoreNoOverwrite", "Üzerine YAZILMADI: {0}",
            "SessionMissing", "LegacySift.session eksik; otomatik geri yükleme mümkün değil.",
            "SessionInvalid", "Güvenlik klasörü oturumu geçersiz: eski klasörün özgün yolu eksik.",
            "TabRecoverHelp", "GÜNCEL klasörde birebir aynı kopya bulunamadı. Bu dosyalar ESKİ klasörde kalır.",
            "TabVersionsHelp", "GÜNCEL klasörde aynı ad var ancak içerik farklı. Bu dosyalar ESKİ klasörde kalır.",
            "TabDuplicatesHelp", "GÜNCEL klasörde birebir aynı kopya zaten var. Temizleme ile yalnızca ESKİ klasördeki bu dosyalar kaldırılabilir.",
            "TabProblemsHelp", "LegacySift bu dosyaları güvenli biçimde doğrulayamadı. ESKİ klasörde kalırlar.",
            "CheckingNow", "İki klasör kontrol ediliyor… hiçbir dosya değiştirilmiyor.",
            "CleanupBeforeAnalysis", "Önce kontrolü çalıştırın. Sonra LegacySift ESKİ klasörden tam olarak nelerin kaldırılabileceğini ve nelerin kalacağını gösterecek.",
            "CleanupWaitForAnalysis", "Kontrolün bitmesini bekleyin. LegacySift klasörleri okurken temizlik devre dışıdır.",
            "CleanupExplanation", "Temizlikten sonra ESKİ klasörde GÜNCEL'de bulunmayan {0} dosya, {1} olası farklı sürüm ve {2} kontrol edilemeyen dosya kalacak. Yalnızca {3} birebir aynı kopya ESKİ'den kaldırılacak.",
            "AfterCleanupSummary", "Temizlik tamamlandı: ESKİ'den {0} birebir aynı kopya kaldırıldı; {1} öğeye güvenlik için dokunulmadı. Tam olarak ne kaldığını görmek için kontrolü yeniden çalıştırın.",
            "CleanupNeedsNewCheck", "Temizlik bitti. ESKİ klasörde yalnızca ne kaldığını görmek için kontrolü yeniden çalıştırın.",
            "HelpText", "LEGACYSIFT — HIZLI KILAVUZ\n\nNE İŞE YARAR\nLegacySift bilgisayar taşıma, eski diskler ve kurtarılan yedekler için tasarlanmıştır. ESKİ klasörü ve bugün kullandığınız GÜNCEL klasörü seçin. LegacySift GÜNCEL'de nelerin eksik olduğunu ve hangi birebir aynı kopyalara zaten sahip olduğunuzu gösterir.\n\nYÖN HİÇ DEĞİŞMEZ\nESKİ KLASÖR = temizlenebilir.\nGÜNCEL KLASÖR = korumalıdır, yalnızca karşılaştırma için kullanılır. LegacySift onu asla temizlemez.\n\nNASIL KULLANILIR\n1. ESKİ KLASÖRÜ seçin.\n2. GÜNCEL KLASÖRÜ seçin.\n3. ZATEN NELERE SAHİP OLDUĞUNU KONTROL ET düğmesine basın. Bu adım hiçbir şeyi değiştirmez.\n4. Sonuçları okuyun.\n5. Sonuçlar doğruysa ESKİ'den yalnızca birebir aynı kopyaları kaldırın.\n\nSONUÇLAR NE ANLAMA GELİR\n• GÜNCEL KLASÖRDE YOK: GÜNCEL'de birebir aynı kopya yoktur. Bu dosyalar ESKİ'de kalır.\n• OLASI FARKLI SÜRÜMLER: aynı ad vardır ancak içerik farklıdır. Bu dosyalar ESKİ'de kalır.\n• BİREBİR AYNI KOPYALAR: GÜNCEL'de tam kopya vardır. ESKİ'den yalnızca bunlar kaldırılabilir.\n• KONTROL EDİLEMEYEN DOSYALAR: LegacySift bunları güvenli biçimde doğrulayamadı. ESKİ'de kalırlar.\n\nTEMİZLİKTEN SONRA\nESKİ klasörde GÜNCEL'de bulunmayan dosyalar, olası farklı sürümler ve LegacySift'in güvenli biçimde doğrulayamadığı her şey kalır. Yalnızca birebir aynı kopyalar kaldırılır.\n\nEN GÜVENLİ YÖNTEM\nGÜVENLİK KLASÖRÜNÜ kullanın. Birebir aynı kopyalar kalıcı olarak silinmek yerine ESKİ'nin yanındaki ayrı ve geri yüklenebilir bir klasöre taşınır.\n\nTEKNİK GÜVENLİK\nBirebir içerik SHA-256 ile karşılaştırılır ve temizlikten önce yeniden doğrulanır. Bağlantılar ve reparse point'ler atlanır. İç içe klasör seçimleri engellenir. LegacySift yönetici izni istemez ve tamamen yerel çalışır.\n\nBASİT KURAL\nEmin değilseniz kontrolden sonra durun. Temizliği açıkça başlatana kadar hiçbir şey değişmez."
        );

        private static readonly Dictionary<string, string> Ru = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — безопасная очистка старой папки",
            "TabWork", "Сравнить и очистить",
            "TabHelp", "Инструкция и безопасность",
            "LanguageButton", "Язык…",
            "Intro", "Старая папка слева, текущая справа. LegacySift удаляет из СТАРОЙ папки только те файлы, идентичная копия которых уже есть в ТЕКУЩЕЙ папке.",
            "OldTitle", "1. СТАРАЯ ПАПКА",
            "OldBadge", "ЕЁ МОЖНО ОЧИЩАТЬ",
            "OldDescription", "Папка, восстановленная со старого компьютера, диска или резервной копии. Только эта сторона может изменяться при очистке.",
            "CurrentTitle", "2. ТЕКУЩАЯ ПАПКА",
            "CurrentBadge", "ЗАЩИЩЕНА • ТОЛЬКО ЧТЕНИЕ",
            "CurrentDescription", "Папка, которой вы пользуетесь сейчас. LegacySift только читает её для сравнения и никогда не очищает.",
            "Browse", "Обзор…",
            "Direction", "Сравнение: СТАРАЯ папка → защищённая ТЕКУЩАЯ папка. Проверка только читает файлы и ничего не изменяет.",
            "Analyze", "3. ПРОВЕРИТЬ, ЧТО УЖЕ ЕСТЬ — ничего не изменяет",
            "Cancel", "Отмена",
            "OpenReport", "Открыть последний отчёт",
            "NoAnalysis", "Выберите СТАРУЮ папку и защищённую ТЕКУЩУЮ папку, затем запустите проверку.",
            "PathsChanged", "Выбор папки изменён. Перед очисткой запустите проверку снова.",
            "TabRecover", "НЕТ В ТЕКУЩЕЙ ПАПКЕ",
            "TabVersions", "ВОЗМОЖНО ДРУГИЕ ВЕРСИИ",
            "TabDuplicates", "ИДЕНТИЧНЫЕ КОПИИ",
            "TabProblems", "НЕПРОВЕРЕННЫЕ ФАЙЛЫ",
            "GridOld", "Файл в СТАРОЙ папке",
            "GridSize", "Размер",
            "GridCurrent", "Соответствующий файл в ТЕКУЩЕЙ папке",
            "GridNote", "Что нашёл LegacySift",
            "CleanupGroup", "4. ОЧИСТИТЬ СТАРУЮ ПАПКУ",
            "Quarantine", "Папка безопасности (рекомендуется) — перемещает идентичные копии из СТАРОЙ папки и позволяет их восстановить",
            "Recycle", "Корзина Windows — отправляет идентичные копии из СТАРОЙ папки в Корзину",
            "OtherOptions", "Показать другие параметры",
            "HideOptions", "Скрыть другие параметры",
            "RemoveEmpty", "Удалить полностью пустые папки внутри СТАРОЙ папки",
            "Confirm", "Я понимаю: будет изменена ТОЛЬКО СТАРАЯ папка. ТЕКУЩАЯ папка останется без изменений.",
            "Cleanup", "УБРАТЬ ИДЕНТИЧНЫЕ КОПИИ ИЗ СТАРОЙ ПАПКИ",
            "Restore", "Восстановить отложенные файлы…",
            "ProtectedReminder", "ТЕКУЩАЯ остаётся защищённой",
            "Ready", "Готово.",
            "ChooseOldDialog", "Выберите СТАРУЮ папку для проверки и очистки",
            "ChooseCurrentDialog", "Выберите ТЕКУЩУЮ / ЗАЩИЩЁННУЮ папку",
            "AnalyzeDone", "Проверка завершена. Ни один файл не изменён.",
            "AnalyzeCanceled", "Проверка отменена. Ни один файл не изменён.",
            "AnalyzeErrorTitle", "Проблема во время проверки",
            "AnalyzeErrorStatus", "Проверка остановлена из-за проблемы. Очистка не выполнялась.",
            "PathCheckTitle", "LegacySift — проверка выбора папок",
            "CleanupConfirmTitle", "Подтвердить очистку СТАРОЙ папки",
            "CleanupConfirm", "Вы собираетесь очистить ТОЛЬКО СТАРУЮ папку:\n\n{0}\n\nТЕКУЩАЯ папка защищена и не будет изменена:\n\n{1}\n\nБудет убрано из СТАРОЙ: {2} идентичных копий.\nОстанется в СТАРОЙ: {3} отсутствующих в ТЕКУЩЕЙ, {4} возможных других версий, {5} непроверенных.\n\nМетод: {6}\n\nПродолжить?",
            "ModeSafety", "ПАПКА БЕЗОПАСНОСТИ (можно восстановить)",
            "ModeRecycle", "КОРЗИНА WINDOWS",
            "CleanupDoneStatus", "Готово: из СТАРОЙ папки убрано {0} идентичных копий; {1} элементов оставлены без изменений ради безопасности.",
            "CleanupDoneTitle", "LegacySift — завершено",
            "CleanupDone", "Очистка завершена.\n\nУбрано из СТАРОЙ папки: {0} идентичных копий\nОставлено без изменений ради безопасности: {1}{2}\n\nФайлы, которых нет в ТЕКУЩЕЙ папке, и возможные другие версии не изменялись. Запустите проверку снова, чтобы точно увидеть, что осталось.",
            "CleanupSafetyLocation", "\n\nПапка безопасности:\n{0}\n\nНе удаляйте её, пока не проверите файлы, оставшиеся в старой папке.",
            "CleanupCanceled", "Очистка остановлена. Уже перемещённые файлы остаются в папке безопасности / Корзине; остальные файлы не изменены.",
            "CleanupErrorTitle", "Проблема во время очистки",
            "CleanupErrorStatus", "Очистка остановлена из-за проблемы. Проверьте папку безопасности и выполните новое сравнение перед повторной попыткой.",
            "RestoreLast", "Восстановить последнюю созданную папку безопасности?\n\n{0}",
            "RestoreTitle", "Восстановить файлы",
            "RestoreChoose", "Выберите папку __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift попытается вернуть файлы в их исходные места в СТАРОЙ папке.\nФайлы, которые уже там существуют, НЕ будут перезаписаны.\n\nПродолжить?",
            "RestoreConfirmTitle", "Подтвердить восстановление",
            "RestoreDoneStatus", "Восстановление завершено: восстановлено {0} файлов; {1} конфликтов не перезаписаны.",
            "RestoreDone", "Восстановлено: {0}\nКонфликты НЕ перезаписаны: {1}\nОшибки: {2}",
            "RestoreCanceled", "Восстановление остановлено.",
            "RestoreErrorTitle", "Проблема во время восстановления",
            "Summary", "ПРОВЕРКА ЗАВЕРШЕНА — ни один файл не изменён.\nНет в ТЕКУЩЕЙ: {0}   |   возможные другие версии: {1}   |   идентичные копии: {2} ({3})   |   не проверено: {4}",
            "CleanupCount", "УБРАТЬ {0} ИДЕНТИЧНЫХ КОПИЙ ИЗ СТАРОЙ ПАПКИ",
            "PhaseOldScan", "Чтение СТАРОЙ папки",
            "PhaseCurrentScan", "Чтение защищённой ТЕКУЩЕЙ папки",
            "PhaseCompare", "Сравнение содержимого файлов",
            "PhaseSafety", "Перемещение файлов в папку безопасности",
            "PhaseRecycle", "Перемещение файлов в Корзину",
            "PhaseRestoreRead", "Чтение папки безопасности",
            "PhaseRestore", "Восстановление файлов",
            "OldRequired", "Сначала выберите СТАРУЮ папку.",
            "CurrentRequired", "Выберите ТЕКУЩУЮ / ЗАЩИЩЁННУЮ папку.",
            "InvalidPath", "Недопустимый путь: {0}",
            "OldMissing", "СТАРАЯ папка не существует.",
            "CurrentMissing", "ТЕКУЩАЯ / ЗАЩИЩЁННАЯ папка не существует.",
            "SameFolder", "Оба выбора указывают на одну и ту же папку. Операция заблокирована.",
            "OldRootBlocked", "Для безопасности нельзя использовать корень всего диска как СТАРУЮ папку.",
            "CurrentRootBlocked", "Для безопасности нельзя использовать корень всего диска как ТЕКУЩУЮ папку.",
            "NestedBlocked", "Одна выбранная папка находится внутри другой. Выберите две отдельные папки.",
            "SystemFolderBlocked", "Для безопасности LegacySift не очищает напрямую основные системные папки Windows.",
            "OutsideOld", "Проверка безопасности не пройдена: этот файл находится не в СТАРОЙ папке.",
            "ReparseDir", "Связанная папка / reparse point пропущена ради безопасности.",
            "ReparseFile", "Связанный файл / reparse point пропущен ради безопасности.",
            "ExactNote", "В ТЕКУЩЕЙ папке есть идентичная копия. Эту копию в СТАРОЙ папке можно безопасно убрать.",
            "VersionNoteOne", "В текущей папке есть файл с тем же именем, но другим содержимым. Этот файл НЕ будет удалён.",
            "VersionNoteMany", "Найдено {0} файлов с тем же именем, но ни один не идентичен. Этот файл НЕ будет удалён.",
            "UniqueNote", "В ТЕКУЩЕЙ папке не найдена идентичная копия. Этот файл остаётся в СТАРОЙ папке.",
            "LanguageRestart", "LegacySift перезапустится, чтобы применить новый язык. Текущие результаты проверки будут очищены.",
            "LanguageRestartTitle", "Изменить язык",
            "SafetyParentMissing", "LegacySift не может определить, где создать папку безопасности.",
            "OldFileMissingNow", "Файл в старой папке больше не существует.",
            "CurrentCopyMissingNow", "Соответствующий файл в текущей папке больше не существует.",
            "ChangedSize", "Размер файла изменился после сравнения. Файл оставлен без изменений.",
            "ChangedHash", "Файлы больше не идентичны. Старый файл оставлен без изменений.",
            "SafetyDestinationExists", "В папке безопасности уже есть файл с таким же путём.",
            "SafetyVerificationFailed", "Проверка после перемещения в папку безопасности не удалась. LegacySift попытался автоматически восстановить исходный файл.",
            "MovedSafety", "Перемещено в папку безопасности и проверено.",
            "MovedRecycle", "Перемещено в Корзину Windows.",
            "SafetyFolderMissing", "Папка безопасности не найдена.",
            "RestoreNoOverwrite", "НЕ перезаписано: {0}",
            "SessionMissing", "Файл LegacySift.session отсутствует, автоматическое восстановление невозможно.",
            "SessionInvalid", "Сеанс папки безопасности недействителен: отсутствует исходный путь старой папки.",
            "TabRecoverHelp", "В ТЕКУЩЕЙ папке не найдена идентичная копия. Эти файлы остаются в СТАРОЙ папке.",
            "TabVersionsHelp", "В ТЕКУЩЕЙ папке есть такое же имя, но содержимое отличается. Эти файлы остаются в СТАРОЙ папке.",
            "TabDuplicatesHelp", "В ТЕКУЩЕЙ папке уже есть идентичная копия. Только эти файлы из СТАРОЙ папки могут быть убраны при очистке.",
            "TabProblemsHelp", "LegacySift не смог безопасно проверить эти файлы. Они остаются в СТАРОЙ папке.",
            "CheckingNow", "Проверка двух папок… ни один файл не изменяется.",
            "CleanupBeforeAnalysis", "Сначала запустите проверку. Затем LegacySift точно покажет, что можно убрать из СТАРОЙ папки и что там останется.",
            "CleanupWaitForAnalysis", "Дождитесь завершения проверки. Очистка отключена, пока LegacySift читает папки.",
            "CleanupExplanation", "После очистки в СТАРОЙ папке останется {0} файлов, не найденных в ТЕКУЩЕЙ, {1} возможных других версий и {2} непроверенных файлов. Только {3} идентичных копий будут убраны из СТАРОЙ.",
            "AfterCleanupSummary", "Очистка завершена: из СТАРОЙ убрано {0} идентичных копий; {1} элементов оставлены без изменений ради безопасности. Запустите проверку снова, чтобы точно увидеть, что осталось.",
            "CleanupNeedsNewCheck", "Очистка завершена. Запустите проверку снова, чтобы увидеть только то, что осталось в СТАРОЙ папке.",
            "HelpText", "LEGACYSIFT — КРАТКОЕ РУКОВОДСТВО\n\nДЛЯ ЧЕГО НУЖЕН\nLegacySift предназначен для переноса компьютеров, старых дисков и восстановленных резервных копий. Выберите СТАРУЮ папку и ТЕКУЩУЮ папку, которой пользуетесь сегодня. LegacySift показывает, чего нет в ТЕКУЩЕЙ папке и какие точные копии у вас уже есть.\n\nНАПРАВЛЕНИЕ НИКОГДА НЕ МЕНЯЕТСЯ\nСТАРАЯ ПАПКА = может быть очищена.\nТЕКУЩАЯ ПАПКА = защищена, используется только для сравнения. LegacySift никогда её не очищает.\n\nКАК ПОЛЬЗОВАТЬСЯ\n1. Выберите СТАРУЮ ПАПКУ.\n2. Выберите ТЕКУЩУЮ ПАПКУ.\n3. Нажмите ПРОВЕРИТЬ, ЧТО УЖЕ ЕСТЬ. Этот шаг ничего не изменяет.\n4. Просмотрите результаты.\n5. Если всё верно, уберите из СТАРОЙ только идентичные копии.\n\nЧТО ОЗНАЧАЮТ РЕЗУЛЬТАТЫ\n• НЕТ В ТЕКУЩЕЙ ПАПКЕ: идентичной копии в ТЕКУЩЕЙ нет. Эти файлы остаются в СТАРОЙ.\n• ВОЗМОЖНО ДРУГИЕ ВЕРСИИ: имя то же, но содержимое отличается. Эти файлы остаются в СТАРОЙ.\n• ИДЕНТИЧНЫЕ КОПИИ: точная копия уже есть в ТЕКУЩЕЙ. Только эти файлы можно убрать из СТАРОЙ.\n• НЕПРОВЕРЕННЫЕ ФАЙЛЫ: LegacySift не смог безопасно их проверить. Они остаются в СТАРОЙ.\n\nПОСЛЕ ОЧИСТКИ\nВ СТАРОЙ папке остаются файлы, не найденные в ТЕКУЩЕЙ, возможные другие версии и всё, что LegacySift не смог безопасно проверить. Убираются только идентичные копии.\n\nСАМЫЙ БЕЗОПАСНЫЙ СПОСОБ\nИспользуйте ПАПКУ БЕЗОПАСНОСТИ. Идентичные копии перемещаются в отдельную восстанавливаемую папку рядом со СТАРОЙ вместо безвозвратного удаления.\n\nТЕХНИЧЕСКАЯ БЕЗОПАСНОСТЬ\nТочное содержимое сравнивается с помощью SHA-256 и повторно проверяется перед очисткой. Ссылки и reparse point пропускаются. Вложенные папки блокируются. LegacySift не требует прав администратора и работает полностью локально.\n\nПРОСТОЕ ПРАВИЛО\nЕсли сомневаетесь, остановитесь после проверки. Ничего не меняется, пока вы явно не запустите очистку."
        );

        private static readonly Dictionary<string, string> Uk = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — безпечно очистіть стару папку",
            "TabWork", "Порівняти й очистити",
            "TabHelp", "Інструкція та безпека",
            "LanguageButton", "Мова…",
            "Intro", "Стара папка ліворуч, поточна праворуч. LegacySift вилучає зі СТАРОЇ папки лише ті файли, ідентична копія яких уже є в ПОТОЧНІЙ папці.",
            "OldTitle", "1. СТАРА ПАПКА",
            "OldBadge", "ЇЇ МОЖНА ОЧИЩАТИ",
            "OldDescription", "Папка, відновлена зі старого комп’ютера, диска або резервної копії. Лише ця сторона може змінюватися під час очищення.",
            "CurrentTitle", "2. ПОТОЧНА ПАПКА",
            "CurrentBadge", "ЗАХИЩЕНА • ЛИШЕ ЧИТАННЯ",
            "CurrentDescription", "Папка, якою ви користуєтеся зараз. LegacySift лише читає її для порівняння й ніколи не очищає.",
            "Browse", "Огляд…",
            "Direction", "Порівняння: СТАРА папка → захищена ПОТОЧНА папка. Перевірка лише читає файли й нічого не змінює.",
            "Analyze", "3. ПЕРЕВІРИТИ, ЩО ВЖЕ Є — нічого не змінює",
            "Cancel", "Скасувати",
            "OpenReport", "Відкрити останній звіт",
            "NoAnalysis", "Виберіть СТАРУ папку та захищену ПОТОЧНУ папку, потім запустіть перевірку.",
            "PathsChanged", "Вибір папки змінено. Перед очищенням запустіть перевірку знову.",
            "TabRecover", "НЕМАЄ В ПОТОЧНІЙ ПАПЦІ",
            "TabVersions", "МОЖЛИВО ІНШІ ВЕРСІЇ",
            "TabDuplicates", "ІДЕНТИЧНІ КОПІЇ",
            "TabProblems", "НЕПЕРЕВІРЕНІ ФАЙЛИ",
            "GridOld", "Файл у СТАРІЙ папці",
            "GridSize", "Розмір",
            "GridCurrent", "Відповідний файл у ПОТОЧНІЙ папці",
            "GridNote", "Що знайшов LegacySift",
            "CleanupGroup", "4. ОЧИСТИТИ СТАРУ ПАПКУ",
            "Quarantine", "Папка безпеки (рекомендовано) — переміщує ідентичні копії зі СТАРОЇ папки й дає змогу їх відновити",
            "Recycle", "Кошик Windows — надсилає ідентичні копії зі СТАРОЇ папки до Кошика",
            "OtherOptions", "Показати інші параметри",
            "HideOptions", "Сховати інші параметри",
            "RemoveEmpty", "Видалити папки, що стали повністю порожніми всередині СТАРОЇ папки",
            "Confirm", "Я розумію: буде змінено ЛИШЕ СТАРУ папку. ПОТОЧНА папка залишиться без змін.",
            "Cleanup", "ПРИБРАТИ ІДЕНТИЧНІ КОПІЇ ЗІ СТАРОЇ ПАПКИ",
            "Restore", "Відновити відкладені файли…",
            "ProtectedReminder", "ПОТОЧНА залишається захищеною",
            "Ready", "Готово.",
            "ChooseOldDialog", "Виберіть СТАРУ папку для перевірки й очищення",
            "ChooseCurrentDialog", "Виберіть ПОТОЧНУ / ЗАХИЩЕНУ папку",
            "AnalyzeDone", "Перевірку завершено. Жоден файл не змінено.",
            "AnalyzeCanceled", "Перевірку скасовано. Жоден файл не змінено.",
            "AnalyzeErrorTitle", "Проблема під час перевірки",
            "AnalyzeErrorStatus", "Перевірку зупинено через проблему. Очищення не виконувалося.",
            "PathCheckTitle", "LegacySift — перевірка вибору папок",
            "CleanupConfirmTitle", "Підтвердити очищення СТАРОЇ папки",
            "CleanupConfirm", "Ви збираєтеся очистити ЛИШЕ СТАРУ папку:\n\n{0}\n\nПОТОЧНА папка захищена й не буде змінена:\n\n{1}\n\nЗі СТАРОЇ буде прибрано: {2} ідентичних копій.\nУ СТАРІЙ залишиться: {3} відсутніх у ПОТОЧНІЙ, {4} можливих інших версій, {5} неперевірених.\n\nМетод: {6}\n\nПродовжити?",
            "ModeSafety", "ПАПКА БЕЗПЕКИ (можна відновити)",
            "ModeRecycle", "КОШИК WINDOWS",
            "CleanupDoneStatus", "Готово: зі СТАРОЇ папки прибрано {0} ідентичних копій; {1} елементів залишено без змін задля безпеки.",
            "CleanupDoneTitle", "LegacySift — завершено",
            "CleanupDone", "Очищення завершено.\n\nПрибрано зі СТАРОЇ папки: {0} ідентичних копій\nЗалишено без змін задля безпеки: {1}{2}\n\nФайли, яких немає в ПОТОЧНІЙ папці, та можливі інші версії не змінювалися. Запустіть перевірку знову, щоб точно побачити, що залишилося.",
            "CleanupSafetyLocation", "\n\nПапка безпеки:\n{0}\n\nНе видаляйте її, доки не перевірите файли, що залишилися в старій папці.",
            "CleanupCanceled", "Очищення зупинено. Уже переміщені файли залишаються в папці безпеки / Кошику; решту файлів не змінено.",
            "CleanupErrorTitle", "Проблема під час очищення",
            "CleanupErrorStatus", "Очищення зупинено через проблему. Перевірте папку безпеки й виконайте нове порівняння перед повторною спробою.",
            "RestoreLast", "Відновити останню створену папку безпеки?\n\n{0}",
            "RestoreTitle", "Відновити файли",
            "RestoreChoose", "Виберіть папку __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift спробує повернути файли до їхніх початкових місць у СТАРІЙ папці.\nФайли, які вже там існують, НЕ буде перезаписано.\n\nПродовжити?",
            "RestoreConfirmTitle", "Підтвердити відновлення",
            "RestoreDoneStatus", "Відновлення завершено: відновлено {0} файлів; {1} конфліктів не перезаписано.",
            "RestoreDone", "Відновлено: {0}\nКонфлікти НЕ перезаписано: {1}\nПомилки: {2}",
            "RestoreCanceled", "Відновлення зупинено.",
            "RestoreErrorTitle", "Проблема під час відновлення",
            "Summary", "ПЕРЕВІРКУ ЗАВЕРШЕНО — жоден файл не змінено.\nНемає в ПОТОЧНІЙ: {0}   |   можливі інші версії: {1}   |   ідентичні копії: {2} ({3})   |   не перевірено: {4}",
            "CleanupCount", "ПРИБРАТИ {0} ІДЕНТИЧНИХ КОПІЙ ЗІ СТАРОЇ ПАПКИ",
            "PhaseOldScan", "Читання СТАРОЇ папки",
            "PhaseCurrentScan", "Читання захищеної ПОТОЧНОЇ папки",
            "PhaseCompare", "Порівняння вмісту файлів",
            "PhaseSafety", "Переміщення файлів до папки безпеки",
            "PhaseRecycle", "Переміщення файлів до Кошика",
            "PhaseRestoreRead", "Читання папки безпеки",
            "PhaseRestore", "Відновлення файлів",
            "OldRequired", "Спочатку виберіть СТАРУ папку.",
            "CurrentRequired", "Виберіть ПОТОЧНУ / ЗАХИЩЕНУ папку.",
            "InvalidPath", "Недійсний шлях: {0}",
            "OldMissing", "СТАРА папка не існує.",
            "CurrentMissing", "ПОТОЧНА / ЗАХИЩЕНА папка не існує.",
            "SameFolder", "Обидва вибори вказують на ту саму папку. Операцію заблоковано.",
            "OldRootBlocked", "Задля безпеки не можна використовувати корінь усього диска як СТАРУ папку.",
            "CurrentRootBlocked", "Задля безпеки не можна використовувати корінь усього диска як ПОТОЧНУ папку.",
            "NestedBlocked", "Одна вибрана папка міститься всередині іншої. Виберіть дві окремі папки.",
            "SystemFolderBlocked", "Задля безпеки LegacySift не очищає безпосередньо основні системні папки Windows.",
            "OutsideOld", "Перевірку безпеки не пройдено: цей файл не міститься в СТАРІЙ папці.",
            "ReparseDir", "Пов’язану папку / reparse point пропущено задля безпеки.",
            "ReparseFile", "Пов’язаний файл / reparse point пропущено задля безпеки.",
            "ExactNote", "У ПОТОЧНІЙ папці є ідентична копія. Цю копію в СТАРІЙ папці можна безпечно прибрати.",
            "VersionNoteOne", "У поточній папці є файл із такою самою назвою, але іншим вмістом. Цей файл НЕ буде видалено.",
            "VersionNoteMany", "Знайдено {0} файлів із такою самою назвою, але жоден не є ідентичним. Цей файл НЕ буде видалено.",
            "UniqueNote", "У ПОТОЧНІЙ папці не знайдено ідентичної копії. Цей файл залишається в СТАРІЙ папці.",
            "LanguageRestart", "LegacySift перезапуститься, щоб застосувати нову мову. Поточні результати перевірки буде очищено.",
            "LanguageRestartTitle", "Змінити мову",
            "SafetyParentMissing", "LegacySift не може визначити, де створити папку безпеки.",
            "OldFileMissingNow", "Файл у старій папці більше не існує.",
            "CurrentCopyMissingNow", "Відповідний файл у поточній папці більше не існує.",
            "ChangedSize", "Розмір файлу змінився після порівняння. Файл залишено без змін.",
            "ChangedHash", "Файли більше не ідентичні. Старий файл залишено без змін.",
            "SafetyDestinationExists", "У папці безпеки вже є файл із таким самим шляхом.",
            "SafetyVerificationFailed", "Перевірка після переміщення до папки безпеки не вдалася. LegacySift спробував автоматично відновити початковий файл.",
            "MovedSafety", "Переміщено до папки безпеки й перевірено.",
            "MovedRecycle", "Переміщено до Кошика Windows.",
            "SafetyFolderMissing", "Папку безпеки не знайдено.",
            "RestoreNoOverwrite", "НЕ перезаписано: {0}",
            "SessionMissing", "Файл LegacySift.session відсутній, тому автоматичне відновлення неможливе.",
            "SessionInvalid", "Сеанс папки безпеки недійсний: відсутній початковий шлях старої папки.",
            "TabRecoverHelp", "У ПОТОЧНІЙ папці не знайдено ідентичної копії. Ці файли залишаться в СТАРІЙ папці.",
            "TabVersionsHelp", "У ПОТОЧНІЙ папці є така сама назва, але вміст відрізняється. Ці файли залишаться в СТАРІЙ папці.",
            "TabDuplicatesHelp", "У ПОТОЧНІЙ папці вже є ідентична копія. Лише ці файли зі СТАРОЇ папки можна прибрати під час очищення.",
            "TabProblemsHelp", "LegacySift не зміг безпечно перевірити ці файли. Вони залишаться в СТАРІЙ папці.",
            "CheckingNow", "Перевірка двох папок… жоден файл не змінюється.",
            "CleanupBeforeAnalysis", "Спочатку запустіть перевірку. Потім LegacySift точно покаже, що можна прибрати зі СТАРОЇ папки і що там залишиться.",
            "CleanupWaitForAnalysis", "Дочекайтеся завершення перевірки. Очищення вимкнено, поки LegacySift читає папки.",
            "CleanupExplanation", "Після очищення в СТАРІЙ папці залишиться {0} файлів, яких немає в ПОТОЧНІЙ, {1} можливих інших версій і {2} неперевірених файлів. Лише {3} ідентичних копій буде прибрано зі СТАРОЇ.",
            "AfterCleanupSummary", "Очищення завершено: зі СТАРОЇ прибрано {0} ідентичних копій; {1} елементів залишено без змін задля безпеки. Запустіть перевірку знову, щоб точно побачити, що залишилося.",
            "CleanupNeedsNewCheck", "Очищення завершено. Запустіть перевірку знову, щоб побачити лише те, що залишилося в СТАРІЙ папці.",
            "HelpText", "LEGACYSIFT — КОРОТКА ІНСТРУКЦІЯ\n\nДЛЯ ЧОГО ВІН ПОТРІБЕН\nLegacySift призначений для перенесення комп’ютерів, старих дисків і відновлених резервних копій. Виберіть СТАРУ папку та ПОТОЧНУ папку, якою користуєтеся сьогодні. LegacySift покаже, чого немає в ПОТОЧНІЙ папці та які точні копії ви вже маєте.\n\nНАПРЯМОК НІКОЛИ НЕ ЗМІНЮЄТЬСЯ\nСТАРА ПАПКА = може бути очищена.\nПОТОЧНА ПАПКА = захищена, лише для порівняння. LegacySift ніколи її не очищає.\n\nЯК КОРИСТУВАТИСЯ\n1. Виберіть СТАРУ ПАПКУ.\n2. Виберіть ПОТОЧНУ ПАПКУ.\n3. Натисніть ПЕРЕВІРИТИ, ЩО ВЖЕ Є. Цей крок нічого не змінює.\n4. Перегляньте результати.\n5. Якщо все правильно, приберіть зі СТАРОЇ лише ідентичні копії.\n\nЩО ОЗНАЧАЮТЬ РЕЗУЛЬТАТИ\n• НЕМАЄ В ПОТОЧНІЙ ПАПЦІ: у ПОТОЧНІЙ немає ідентичної копії. Ці файли залишаються в СТАРІЙ.\n• МОЖЛИВО ІНШІ ВЕРСІЇ: назва така сама, але вміст відрізняється. Ці файли залишаються в СТАРІЙ.\n• ІДЕНТИЧНІ КОПІЇ: точна копія вже є в ПОТОЧНІЙ. Лише ці файли можна прибрати зі СТАРОЇ.\n• НЕПЕРЕВІРЕНІ ФАЙЛИ: LegacySift не зміг безпечно їх перевірити. Вони залишаються в СТАРІЙ.\n\nПІСЛЯ ОЧИЩЕННЯ\nУ СТАРІЙ папці залишаються файли, яких немає в ПОТОЧНІЙ, можливі інші версії та все, що LegacySift не зміг безпечно перевірити. Прибираються лише ідентичні копії.\n\nНАЙБЕЗПЕЧНІШИЙ СПОСІБ\nВикористовуйте ПАПКУ БЕЗПЕКИ. Ідентичні копії переміщуються в окрему відновлювану папку поруч зі СТАРОЮ замість безповоротного видалення.\n\nТЕХНІЧНА БЕЗПЕКА\nТочний вміст порівнюється за допомогою SHA-256 і повторно перевіряється перед очищенням. Посилання та reparse point пропускаються. Вкладені папки блокуються. LegacySift не потребує прав адміністратора й працює повністю локально.\n\nПРОСТЕ ПРАВИЛО\nЯкщо сумніваєтеся, зупиніться після перевірки. Нічого не змінюється, доки ви явно не запустите очищення."
        );
    }
}
