using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Hr = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — sigurno čišćenje stare mape",
            "TabWork", "Usporedba i čišćenje",
            "TabHelp", "Upute i sigurnost",
            "LanguageButton", "Jezik…",
            "Intro", "Stara mapa s lijeve strane. Trenutačna mapa s desne strane. LegacySift iz STARE mape uklanja samo one datoteke koje su već identične onima u TRENUTAČNOJ mapi.",
            "OldTitle", "1. STARA MAPA",
            "OldBadge", "OVO SE MOŽE OČISTITI",
            "OldDescription", "Mapa preuzeta sa starog računala, diska ili sigurnosne kopije. Samo se ova strana može mijenjati postupkom čišćenja.",
            "CurrentTitle", "2. TRENUTAČNA MAPA",
            "CurrentBadge", "ZAŠTIĆENO • SAMO ZA ČITANJE",
            "CurrentDescription", "Mapa koju trenutačno koristite. LegacySift je čita samo radi usporedbe i nikada je ne čisti.",
            "Browse", "Pregledaj…",
            "Direction", "Usporedi STARU mapu → TRENUTAČNU zaštićenu mapu. Provjera samo čita datoteke;ništa se ne mijenja.",
            "Analyze", "3. PROVJERITE ŠTO VEĆ IMATE — ništa se ne mijenja",
            "Cancel", "Odustani",
            "OpenReport", "Otvori zadnje izvješće",
            "NoAnalysis", "Odaberite STARU mapu i TRENUTAČNU zaštićenu mapu, a zatim pokrenite provjeru.",
            "PathsChanged", "Odabir mapa je promijenjen. Ponovno pokrenite provjeru prije bilo kakvog čišćenja.",
            "TabRecover", "NIJE PRONAĐENO U TRENUTAČNOJ",
            "TabVersions", "MOGUĆE RAZLIČITE VERZIJE",
            "TabDuplicates", "IDENTIČNE KOPIJE",
            "TabProblems", "DATOTEKE NISU PROVJERENE",
            "GridOld", "Datoteka u STAROJ mapi",
            "GridSize", "Veličina",
            "GridCurrent", "Odgovarajuća datoteka u TRENUTAČNOJ mapi",
            "GridNote", "Što je LegacySift pronašao",
            "CleanupGroup", "4. OČISTI STARU MAPU",
            "Quarantine", "Sigurnosna mapa (preporučeno) — premjesti identične kopije iz STARE mape kako bi se mogle vratiti",
            "Recycle", "Windows koš za smeće — pošalji identične kopije iz STARE mape u koš za smeće",
            "OtherOptions", "Prikaži ostale opcije",
            "HideOptions", "Sakrij ostale opcije",
            "RemoveEmpty", "Ukloni mape koje su ostale potpuno prazne unutar STARE mape",
            "Confirm", "Razumijem: mijenjat će se SAMO STARA mapa. TRENUTAČNA mapa ostat će nepromijenjena.",
            "Cleanup", "UKLONI IDENTIČNE KOPIJE IZ STARE MAPE",
            "Restore", "Vrati izdvojene datoteke…",
            "ProtectedReminder", "CURRENT ostaje zaštićen",
            "Ready", "Spreman.",
            "ChooseOldDialog", "Odaberite mapu OLD za provjeru i čišćenje",
            "ChooseCurrentDialog", "Odaberite mapu CURRENT / PROTECTED",
            "AnalyzeDone", "Provjera dovršena. Nijedna datoteka nije promijenjena.",
            "AnalyzeCanceled", "Provjera otkazana. Nijedna datoteka nije promijenjena.",
            "AnalyzeErrorTitle", "Problem tijekom provjere",
            "AnalyzeErrorStatus", "Provjera je zaustavljena zbog problema. Čišćenje nije provedeno.",
            "PathCheckTitle", "LegacySift — provjera odabira mapa",
            "CleanupConfirmTitle", "Potvrdite čišćenje mape OLD",
            "CleanupConfirm", "Čistite SAMO mapu OLD:\\n\\n{0}\\n\\nMapa CURRENT je zaštićena i neće se mijenjati:\\n\\n{1}\\n\\nUklonjeno iz OLD: {2} identičnih kopija.\\nOstalo u OLD: {3} nije pronađeno u CURRENT, {4} moguće različite verzije, {5} nije provjereno.\\n\\nMetoda: {6}\\n\\nNastaviti?",
            "ModeSafety", "SIGURNOSNA MAPA (moguće vraćanje)",
            "ModeRecycle", "WINDOWS KOŠ ZA SMEĆE",
            "CleanupDoneStatus", "Gotovo: {0} identičnih kopija uklonjeno je iz mape OLD;{1} kandidata ostavljeno je netaknuto radi sigurnosti.",
            "CleanupDoneTitle", "LegacySift — dovršeno",
            "CleanupDone", "Čišćenje dovršeno.\\n\\nUklonjeno iz mape OLD: {0} identičnih kopija\\nOstavljeno na mjestu radi sigurnosti: {1}{2}\\n\\nDatoteke koje nisu pronađene u CURRENT i moguće različite verzije nisu dirane. Ponovno pokrenite provjeru kako biste vidjeli što točno preostaje.",
            "CleanupSafetyLocation", "\\n\\nSigurnosna mapa:\\n{0}\\n\\nNemojte je brisati dok ne provjerite datoteke preostale u staroj mapi.",
            "CleanupCanceled", "Čišćenje zaustavljeno. Datoteke koje su već premještene ostaju u sigurnosnoj mapi / košu za smeće;preostale datoteke nisu dirane.",
            "CleanupErrorTitle", "Problem tijekom čišćenja",
            "CleanupErrorStatus", "Čišćenje zaustavljeno zbog problema. Provjerite sigurnosnu mapu i pokrenite novu usporedbu prije ponovnog pokušaja.",
            "RestoreLast", "Vratiti posljednju stvorenu sigurnosnu mapu?\\n\\n{0}",
            "RestoreTitle", "Vraćanje datoteka",
            "RestoreChoose", "Odaberite mapu __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift će pokušati vratiti datoteke na njihove izvorne lokacije u staroj mapi.\\nDatoteke koje tamo već postoje NEĆE biti prebrisane.\\n\\nNastaviti?",
            "RestoreConfirmTitle", "Potvrdi vraćanje",
            "RestoreDoneStatus", "Vraćanje dovršeno: vraćeno {0} datoteka;{1} sukoba nije prebrisano.",
            "RestoreDone", "Vraćeno: {0}\\nSukobi NISU prebrisani: {1}\\nPogreške: {2}",
            "RestoreCanceled", "Vraćanje zaustavljeno.",
            "RestoreErrorTitle", "Problem tijekom vraćanja podataka",
            "Summary", "PROVJERA ZAVRŠENA — nijedna datoteka nije promijenjena.\\n{0} nije pronađen u TRENUTNOJ mapi   |{1} moguće različite verzije   |{2} identične kopije ({3})   |{4} nije provjereno",
            "CleanupCount", "UKLONITE IDENTIČNE KOPIJE {0} IZ STARE MAPE",
            "PhaseOldScan", "Čitanje STARE mape",
            "PhaseCurrentScan", "Čitanje TRENUTNE zaštićene mape",
            "PhaseCompare", "Uspoređivanje sadržaja datoteka",
            "PhaseSafety", "Premještanje datoteka u sigurnosnu mapu",
            "PhaseRecycle", "Premještanje datoteka u Koš za smeće",
            "PhaseRestoreRead", "Čitanje sigurnosne mape",
            "PhaseRestore", "Vraćanje datoteka",
            "OldRequired", "Prvo odaberite STARU mapu.",
            "CurrentRequired", "Odaberite TRENUTNU / ZAŠTIĆENU mapu.",
            "InvalidPath", "Neispravna putanja: {0}",
            "OldMissing", "STARA mapa ne postoji.",
            "CurrentMissing", "TRENUTNA / ZAŠTIĆENA mapa ne postoji.",
            "SameFolder", "Oba odabira upućuju na istu mapu. Operacija blokirana.",
            "OldRootBlocked", "Radi sigurnosti, korijenska mapa cijelog pogona ne može se koristiti kao STARA mapa.",
            "CurrentRootBlocked", "Radi sigurnosti, korijenska mapa cijelog pogona ne može se koristiti kao TRENUTNA mapa.",
            "NestedBlocked", "Jedna odabrana mapa nalazi se unutar druge. Odaberite dvije zasebne mape.",
            "SystemFolderBlocked", "Radi sigurnosti, LegacySift neće čistiti glavnu sistemsku mapu sustava Windows.",
            "OutsideOld", "Sigurnosna provjera nije uspjela: ova se datoteka ne nalazi unutar STARE mape.",
            "ReparseDir", "Povezana mapa / točka ponovnog raščlanjivanja (reparse point) preskočena radi sigurnosti.",
            "ReparseFile", "Povezana datoteka / točka ponovnog raščlanjivanja (reparse point) preskočena radi sigurnosti.",
            "ExactNote", "Identična kopija postoji u TRENUTNOJ mapi. Ova se kopija iz STARE mape može sigurno ukloniti.",
            "VersionNoteOne", "Datoteka s istim nazivom postoji u trenutnoj mapi, ali joj je sadržaj drukčiji. Ova se datoteka NEĆE ukloniti.",
            "VersionNoteMany", "Pronađene su datoteke {0} s istim nazivom, ali nijedna nije identična. Ova se datoteka NEĆE ukloniti.",
            "UniqueNote", "U TRENUTNOJ mapi nije pronađena identična kopija. Ova datoteka ostaje u mapi OLD.",
            "LanguageRestart", "LegacySift će se ponovno pokrenuti kako bi primijenio novi jezik. Svi trenutni rezultati usporedbe bit će izbrisani.",
            "LanguageRestartTitle", "Promijeni jezik",
            "SafetyParentMissing", "LegacySift ne može odrediti gdje treba stvoriti sigurnosnu mapu.",
            "OldFileMissingNow", "Datoteka u staroj mapi više ne postoji.",
            "CurrentCopyMissingNow", "Odgovarajuća datoteka u trenutnoj mapi više ne postoji.",
            "ChangedSize", "Veličina datoteke promijenila se nakon usporedbe. Datoteka je ostavljena nepromijenjena.",
            "ChangedHash", "Dvije datoteke više nisu identične. Stara datoteka ostavljena je nepromijenjena.",
            "SafetyDestinationExists", "Datoteka s istom putanjom već postoji u sigurnosnoj mapi.",
            "SafetyVerificationFailed", "Provjera sigurnosne mape nakon premještanja nije uspjela. LegacySift je pokušao automatski vratiti izvornu datoteku.",
            "MovedSafety", "Premješteno u sigurnosnu mapu i provjereno.",
            "MovedRecycle", "Premješteno u Windows koš za smeće.",
            "SafetyFolderMissing", "Sigurnosna mapa nije pronađena.",
            "RestoreNoOverwrite", "NIJE prepisano: {0}",
            "SessionMissing", "Datoteka LegacySift.session nedostaje, stoga automatsko vraćanje nije moguće.",
            "SessionInvalid", "Sesija sigurnosne mape nije valjana: nedostaje izvorna putanja stare mape.",
            "TabRecoverHelp", "Nije pronađena identična kopija u mapi CURRENT. Ove datoteke ostaju u mapi OLD.",
            "TabVersionsHelp", "Datoteka s istim imenom postoji u mapi CURRENT, ali se sadržaj razlikuje. Ove datoteke ostaju u mapi OLD.",
            "TabDuplicatesHelp", "Identična kopija već postoji u mapi CURRENT. Samo se te datoteke iz mape OLD mogu ukloniti postupkom čišćenja.",
            "TabProblemsHelp", "LegacySift nije mogao sigurno provjeriti ove datoteke. One ostaju u mapi OLD.",
            "CheckingNow", "Provjera dviju mapa... nijedna se datoteka ne mijenja.",
            "CleanupBeforeAnalysis", "Prvo pokrenite provjeru. LegacySift će zatim prikazati što se točno može ukloniti iz mape OLD, a što će tamo ostati.",
            "CleanupWaitForAnalysis", "Pričekajte završetak provjere. Čišćenje je onemogućeno dok LegacySift čita mape.",
            "CleanupExplanation", "Nakon čišćenja, mapa OLD zadržat će datoteke {0} koje nisu pronađene u mapi CURRENT, moguće različite verzije {1} te neprovjerene datoteke {2}. Iz mape OLD uklonit će se samo identične kopije {3}.",
            "AfterCleanupSummary", "Čišćenje dovršeno: identične kopije {0} uklonjene su iz mape OLD;kandidati {1} ostavljeni su netaknuti radi sigurnosti. Ponovno pokrenite provjeru kako biste vidjeli što točno preostaje.",
            "CleanupNeedsNewCheck", "Čišćenje je završeno. Ponovno pokrenite provjeru kako biste vidjeli što je preostalo u mapi OLD.",
            "HelpText", "LEGACYSIFT — KRATKI VODIČ\\n\\nŠTO RADI\\nLegacySift je namijenjen migracijama računala, starim diskovima i vraćenim sigurnosnim kopijama. Odaberite mapu OLD (stara) i mapu CURRENT (trenutna) koju danas koristite. LegacySift prikazuje što nedostaje u mapi CURRENT i koje točne kopije već imate.\\n\\nSMJER SE NIKADA NE MIJENJA\\nMAPA OLD = može se očistiti.\\nMAPA CURRENT = zaštićena, služi samo za usporedbu. LegacySift je nikada ne čisti.\\n\\nKAKO GA KORISTITI\\n1. Odaberite mapu OLD.\\n2. Odaberite mapu CURRENT.\\n3. Kliknite na „CHECK WHAT YOU ALREADY HAVE” (Provjeri što već imaš). Ovaj korak ništa ne mijenja.\\n4. Pročitajte rezultate.\\n5. Ako imaju smisla, uklonite samo identične kopije iz mape OLD.\\n\\nŠTO ZNAČE REZULTATI\\n• NOT FOUND IN CURRENT (Nije pronađeno u CURRENT): ne postoji identična kopija u mapi CURRENT. Te datoteke ostaju u mapi OLD.\\n• POSSIBLE DIFFERENT VERSIONS (Moguće različite verzije): postoji isti naziv, ali se sadržaj razlikuje. Te datoteke ostaju u mapi OLD.\\n• IDENTICAL COPIES ALREADY IN CURRENT (Identične kopije već postoje u CURRENT): točna kopija postoji u mapi CURRENT. Samo se te datoteke iz mape OLD mogu ukloniti.\\n• FILES NOT CHECKED (Datoteke nisu provjerene): LegacySift ih nije mogao sigurno provjeriti. Ostaju u mapi OLD.\\n\\nNAKON ČIŠĆENJA\\nU mapi OLD ostaju datoteke koje nisu pronađene u mapi CURRENT, moguće različite verzije te sve ono što LegacySift nije mogao sigurno provjeriti. Iz mape OLD uklanjaju se samo točne kopije.\\n\\nNAJSIGURNIJA METODA\\nKoristite mapu Safety (sigurnosna mapa). Točne kopije premještaju se u zasebnu mapu (iz koje se mogu vratiti) pokraj mape OLD, umjesto da se trajno brišu.\\n\\nTEHNIČKA SIGURNOST\\nTočnost sadržaja provjerava se pomoću SHA-256 algoritma, a provjera se ponavlja i prije postupka čišćenja. Povezane mape (tzv. *reparse points*) se preskaču. Odabir ugniježđenih mapa nije moguć. LegacySift ne zahtijeva administratorske ovlasti i radi u potpunosti lokalno.\\n\\nJEDNOSTAVNO PRAVILO\\nAko niste sigurni, zaustavite se nakon provjere. Ništa se ne mijenja sve dok izričito ne pokrenete čišćenje."
        );
    }
}
