using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Id = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — bersihkan folder lama dengan aman",
            "TabWork", "Bandingkan dan bersihkan",
            "TabHelp", "Panduan dan keamanan",
            "LanguageButton", "Bahasa…",
            "Intro", "Folder LAMA ada di kiri dan folder SAAT INI di kanan. LegacySift hanya menghapus dari folder LAMA file yang salinan identiknya sudah ada di folder SAAT INI.",
            "OldTitle", "1. FOLDER LAMA",
            "OldBadge", "INI BOLEH DIBERSIHKAN",
            "OldDescription", "Folder yang dipulihkan dari komputer, disk, atau cadangan lama. Hanya sisi ini yang dapat diubah oleh pembersihan.",
            "CurrentTitle", "2. FOLDER SAAT INI",
            "CurrentBadge", "DILINDUNGI • HANYA BACA",
            "CurrentDescription", "Folder yang Anda gunakan sekarang. LegacySift hanya membacanya untuk perbandingan dan tidak pernah membersihkannya.",
            "Browse", "Telusuri…",
            "Direction", "Perbandingan: folder LAMA → folder SAAT INI yang dilindungi. Pemeriksaan hanya membaca file; tidak mengubah apa pun.",
            "Analyze", "3. PERIKSA YANG SUDAH ANDA MILIKI — tidak mengubah apa pun",
            "Cancel", "Batal",
            "OpenReport", "Buka laporan terakhir",
            "NoAnalysis", "Pilih folder LAMA dan folder SAAT INI yang dilindungi, lalu mulai pemeriksaan.",
            "PathsChanged", "Pilihan folder berubah. Jalankan pemeriksaan lagi sebelum membersihkan apa pun.",
            "TabRecover", "TIDAK ADA DI FOLDER SAAT INI",
            "TabVersions", "MUNGKIN VERSI BERBEDA",
            "TabDuplicates", "SALINAN IDENTIK",
            "TabProblems", "FILE YANG TIDAK DIPERIKSA",
            "GridOld", "File di folder LAMA",
            "GridSize", "Ukuran",
            "GridCurrent", "File yang cocok di folder SAAT INI",
            "GridNote", "Yang ditemukan LegacySift",
            "CleanupGroup", "4. BERSIHKAN FOLDER LAMA",
            "Quarantine", "Folder keamanan (disarankan) — pindahkan salinan identik dari LAMA agar dapat dipulihkan",
            "Recycle", "Keranjang Sampah Windows — kirim salinan identik dari folder LAMA ke Keranjang Sampah",
            "OtherOptions", "Tampilkan opsi lain",
            "HideOptions", "Sembunyikan opsi lain",
            "RemoveEmpty", "Hapus folder yang benar-benar kosong di dalam folder LAMA",
            "Confirm", "Saya mengerti: HANYA folder LAMA yang akan diubah. Folder SAAT INI tetap tidak berubah.",
            "Cleanup", "HAPUS SALINAN IDENTIK DARI FOLDER LAMA",
            "Restore", "Pulihkan file yang disisihkan…",
            "ProtectedReminder", "Folder SAAT INI tetap dilindungi",
            "Ready", "Siap.",
            "ChooseOldDialog", "Pilih folder LAMA untuk diperiksa dan dibersihkan",
            "ChooseCurrentDialog", "Pilih folder SAAT INI / DILINDUNGI",
            "AnalyzeDone", "Pemeriksaan selesai. Tidak ada file yang diubah.",
            "AnalyzeCanceled", "Pemeriksaan dibatalkan. Tidak ada file yang diubah.",
            "AnalyzeErrorTitle", "Masalah saat pemeriksaan",
            "AnalyzeErrorStatus", "Pemeriksaan berhenti karena masalah. Tidak ada pembersihan yang dilakukan.",
            "PathCheckTitle", "LegacySift — periksa pilihan folder",
            "CleanupConfirmTitle", "Konfirmasi pembersihan folder LAMA",
            "CleanupConfirm", "Anda akan membersihkan HANYA folder LAMA:\n\n{0}\n\nFolder SAAT INI dilindungi dan tidak akan diubah:\n\n{1}\n\nDihapus dari LAMA: {2} salinan identik.\nTetap di LAMA: {3} tidak ada di SAAT INI, {4} kemungkinan versi berbeda, {5} tidak diperiksa.\n\nMetode: {6}\n\nLanjutkan?",
            "ModeSafety", "FOLDER KEAMANAN (dapat dipulihkan)",
            "ModeRecycle", "KERANJANG SAMPAH WINDOWS",
            "CleanupDoneStatus", "Selesai: {0} salinan identik dihapus dari folder LAMA; {1} item dibiarkan tanpa perubahan demi keamanan.",
            "CleanupDoneTitle", "LegacySift — selesai",
            "CleanupDone", "Pembersihan selesai.\n\nDihapus dari folder LAMA: {0} salinan identik\nDibiarkan demi keamanan: {1}{2}\n\nFile yang tidak ada di SAAT INI dan kemungkinan versi berbeda tidak disentuh. Jalankan pemeriksaan lagi untuk melihat tepatnya yang tersisa.",
            "CleanupSafetyLocation", "\n\nFolder keamanan:\n{0}\n\nJangan hapus sebelum Anda memeriksa file yang tersisa di folder lama.",
            "CleanupCanceled", "Pembersihan dihentikan. File yang sudah dipindahkan tetap di folder keamanan / Keranjang Sampah; file lain tidak disentuh.",
            "CleanupErrorTitle", "Masalah saat pembersihan",
            "CleanupErrorStatus", "Pembersihan berhenti karena masalah. Periksa folder keamanan dan lakukan perbandingan baru sebelum mencoba lagi.",
            "RestoreLast", "Pulihkan folder keamanan terakhir yang dibuat?\n\n{0}",
            "RestoreTitle", "Pulihkan file",
            "RestoreChoose", "Pilih folder __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift akan mencoba mengembalikan file ke lokasi awalnya di folder LAMA.\nFile yang sudah ada di sana TIDAK akan ditimpa.\n\nLanjutkan?",
            "RestoreConfirmTitle", "Konfirmasi pemulihan",
            "RestoreDoneStatus", "Pemulihan selesai: {0} file dipulihkan; {1} konflik tidak ditimpa.",
            "RestoreDone", "Dipulihkan: {0}\nKonflik TIDAK ditimpa: {1}\nKesalahan: {2}",
            "RestoreCanceled", "Pemulihan dihentikan.",
            "RestoreErrorTitle", "Masalah saat pemulihan",
            "Summary", "PEMERIKSAAN SELESAI — tidak ada file yang diubah.\n{0} tidak ada di SAAT INI   |   {1} kemungkinan versi berbeda   |   {2} salinan identik ({3})   |   {4} tidak diperiksa",
            "CleanupCount", "HAPUS {0} SALINAN IDENTIK DARI FOLDER LAMA",
            "PhaseOldScan", "Membaca folder LAMA",
            "PhaseCurrentScan", "Membaca folder SAAT INI yang dilindungi",
            "PhaseCompare", "Membandingkan isi file",
            "PhaseSafety", "Memindahkan file ke folder keamanan",
            "PhaseRecycle", "Memindahkan file ke Keranjang Sampah",
            "PhaseRestoreRead", "Membaca folder keamanan",
            "PhaseRestore", "Memulihkan file",
            "OldRequired", "Pilih folder LAMA terlebih dahulu.",
            "CurrentRequired", "Pilih folder SAAT INI / DILINDUNGI.",
            "InvalidPath", "Jalur tidak valid: {0}",
            "OldMissing", "Folder LAMA tidak ada.",
            "CurrentMissing", "Folder SAAT INI / DILINDUNGI tidak ada.",
            "SameFolder", "Kedua pilihan mengarah ke folder yang sama. Operasi diblokir.",
            "OldRootBlocked", "Demi keamanan, akar seluruh drive tidak dapat dipakai sebagai folder LAMA.",
            "CurrentRootBlocked", "Demi keamanan, akar seluruh drive tidak dapat dipakai sebagai folder SAAT INI.",
            "NestedBlocked", "Satu folder yang dipilih berada di dalam folder lainnya. Pilih dua folder terpisah.",
            "SystemFolderBlocked", "Demi keamanan, LegacySift tidak langsung membersihkan folder sistem utama Windows.",
            "OutsideOld", "Pemeriksaan keamanan gagal: file ini tidak berada di folder LAMA.",
            "ReparseDir", "Folder tertaut / reparse point dilewati demi keamanan.",
            "ReparseFile", "File tertaut / reparse point dilewati demi keamanan.",
            "ExactNote", "Salinan identik ada di folder SAAT INI. Salinan di folder LAMA ini dapat dihapus dengan aman.",
            "VersionNoteOne", "File dengan nama yang sama ada di folder saat ini, tetapi isinya berbeda. File ini TIDAK akan dihapus.",
            "VersionNoteMany", "Ditemukan {0} file dengan nama yang sama, tetapi tidak ada yang identik. File ini TIDAK akan dihapus.",
            "UniqueNote", "Tidak ditemukan salinan identik di folder SAAT INI. File ini tetap berada di folder LAMA.",
            "LanguageRestart", "LegacySift akan dimulai ulang untuk menerapkan bahasa baru. Hasil pemeriksaan saat ini akan dihapus.",
            "LanguageRestartTitle", "Ganti bahasa",
            "SafetyParentMissing", "LegacySift tidak dapat menentukan tempat membuat folder keamanan.",
            "OldFileMissingNow", "File di folder lama sudah tidak ada.",
            "CurrentCopyMissingNow", "File yang cocok di folder saat ini sudah tidak ada.",
            "ChangedSize", "Ukuran file berubah setelah perbandingan. File dibiarkan tanpa perubahan.",
            "ChangedHash", "Kedua file tidak lagi identik. File lama dibiarkan tanpa perubahan.",
            "SafetyDestinationExists", "File dengan jalur yang sama sudah ada di folder keamanan.",
            "SafetyVerificationFailed", "Verifikasi setelah pemindahan ke folder keamanan gagal. LegacySift mencoba memulihkan file asli secara otomatis.",
            "MovedSafety", "Dipindahkan ke folder keamanan dan diverifikasi.",
            "MovedRecycle", "Dipindahkan ke Keranjang Sampah Windows.",
            "SafetyFolderMissing", "Folder keamanan tidak ditemukan.",
            "RestoreNoOverwrite", "TIDAK ditimpa: {0}",
            "SessionMissing", "LegacySift.session tidak ada, sehingga pemulihan otomatis tidak dapat dilakukan.",
            "SessionInvalid", "Sesi folder keamanan tidak valid: jalur asli folder lama tidak ada.",
            "TabRecoverHelp", "Tidak ditemukan salinan identik di SAAT INI. File ini tetap berada di folder LAMA.",
            "TabVersionsHelp", "Nama yang sama ada di SAAT INI, tetapi isinya berbeda. File ini tetap berada di folder LAMA.",
            "TabDuplicatesHelp", "Salinan identik sudah ada di SAAT INI. Hanya file ini dari folder LAMA yang dapat dihapus.",
            "TabProblemsHelp", "LegacySift tidak dapat memverifikasi file ini dengan aman. File tetap berada di folder LAMA.",
            "CheckingNow", "Memeriksa kedua folder… tidak ada file yang diubah.",
            "CleanupBeforeAnalysis", "Jalankan pemeriksaan terlebih dahulu. Setelah itu LegacySift menunjukkan tepatnya apa yang dapat dihapus dari LAMA dan apa yang tetap di sana.",
            "CleanupWaitForAnalysis", "Tunggu pemeriksaan selesai. Pembersihan dinonaktifkan saat LegacySift membaca folder.",
            "CleanupExplanation", "Setelah pembersihan, LAMA menyimpan {0} file yang tidak ada di SAAT INI, {1} kemungkinan versi berbeda, dan {2} file yang tidak diperiksa. Hanya {3} salinan identik yang dihapus dari LAMA.",
            "AfterCleanupSummary", "Pembersihan selesai: {0} salinan identik dihapus dari LAMA; {1} item dibiarkan demi keamanan. Jalankan pemeriksaan lagi untuk melihat tepatnya yang tersisa.",
            "CleanupNeedsNewCheck", "Pembersihan selesai. Jalankan pemeriksaan lagi untuk hanya melihat yang tersisa di folder LAMA.",
            "HelpText", "LEGACYSIFT — PANDUAN CEPAT\n\nKEGUNAAN\nLegacySift dibuat untuk pemindahan komputer, disk lama, dan cadangan yang dipulihkan. Pilih folder LAMA dan folder SAAT INI yang Anda gunakan sekarang. LegacySift menunjukkan apa yang tidak ada di SAAT INI dan salinan persis mana yang sudah Anda miliki.\n\nARAH TIDAK PERNAH BERUBAH\nFOLDER LAMA = boleh dibersihkan.\nFOLDER SAAT INI = dilindungi, hanya untuk perbandingan. LegacySift tidak pernah membersihkannya.\n\nCARA MENGGUNAKAN\n1. Pilih FOLDER LAMA.\n2. Pilih FOLDER SAAT INI.\n3. Klik PERIKSA YANG SUDAH ANDA MILIKI. Langkah ini tidak mengubah apa pun.\n4. Baca hasilnya.\n5. Jika sudah benar, hapus hanya salinan identik dari LAMA.\n\nARTI HASIL\n• TIDAK ADA DI SAAT INI: tidak ada salinan identik. File tetap di LAMA.\n• MUNGKIN VERSI BERBEDA: namanya sama, tetapi isinya berbeda. File tetap di LAMA.\n• SALINAN IDENTIK SUDAH ADA DI SAAT INI: ada salinan persis. Hanya file ini yang dapat dihapus dari LAMA.\n• FILE YANG TIDAK DIPERIKSA: LegacySift tidak dapat memverifikasinya dengan aman. File tetap di LAMA.\n\nSETELAH PEMBERSIHAN\nFolder LAMA tetap berisi file yang tidak ada di SAAT INI, kemungkinan versi berbeda, dan semua yang tidak dapat diverifikasi dengan aman. Hanya salinan persis yang dihapus dari LAMA.\n\nMETODE PALING AMAN\nGunakan folder keamanan. Salinan persis dipindahkan ke folder terpisah yang dapat dipulihkan di samping LAMA, bukan dihapus permanen.\n\nKEAMANAN TEKNIS\nIsi persis dibandingkan dengan SHA-256 dan diperiksa lagi sebelum pembersihan. Folder tertaut dan reparse point dilewati. Pilihan folder bersarang diblokir. LegacySift tidak meminta hak administrator dan bekerja sepenuhnya secara lokal.\n\nATURAN SEDERHANA\nJika ragu, berhenti setelah pemeriksaan. Tidak ada yang berubah sampai Anda memulai pembersihan secara langsung."
        );
    }
}
