using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Ro = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — curăță în siguranță un folder vechi",
            "TabWork", "Compară și curăță",
            "TabHelp", "Ghid și siguranță",
            "LanguageButton", "Limbă…",
            "Intro", "Folderul VECHI este în stânga, iar folderul CURENT în dreapta. LegacySift elimină din folderul VECHI numai fișierele care au deja o copie identică în folderul CURENT.",
            "OldTitle", "1. FOLDER VECHI",
            "OldBadge", "ACESTA POATE FI CURĂȚAT",
            "OldDescription", "Folderul recuperat de pe vechiul computer, disc sau backup. Numai această parte poate fi modificată prin curățare.",
            "CurrentTitle", "2. FOLDER CURENT",
            "CurrentBadge", "PROTEJAT • NUMAI CITIRE",
            "CurrentDescription", "Folderul pe care îl folosești astăzi. LegacySift îl citește doar pentru comparație și nu îl curăță niciodată.",
            "Browse", "Răsfoiește…",
            "Direction", "Comparație: folder VECHI → folder CURENT protejat. Verificarea doar citește fișierele; nu modifică nimic.",
            "Analyze", "3. VERIFICĂ CE AI DEJA — nu modifică nimic",
            "Cancel", "Anulează",
            "OpenReport", "Deschide ultimul raport",
            "NoAnalysis", "Alege folderul VECHI și folderul CURENT protejat, apoi pornește verificarea.",
            "PathsChanged", "Ai schimbat un folder. Rulează din nou verificarea înainte de a curăța ceva.",
            "TabRecover", "NU EXISTĂ ÎN FOLDERUL CURENT",
            "TabVersions", "POSIBILE VERSIUNI DIFERITE",
            "TabDuplicates", "COPII IDENTICE",
            "TabProblems", "FIȘIERE NEVERIFICATE",
            "GridOld", "Fișier în folderul VECHI",
            "GridSize", "Dimensiune",
            "GridCurrent", "Fișier corespunzător în folderul CURENT",
            "GridNote", "Ce a găsit LegacySift",
            "CleanupGroup", "4. CURĂȚĂ FOLDERUL VECHI",
            "Quarantine", "Folder de siguranță (recomandat) — mută copiile identice din VECHI și permite restaurarea lor",
            "Recycle", "Coș de reciclare Windows — trimite acolo copiile identice din folderul VECHI",
            "OtherOptions", "Arată alte opțiuni",
            "HideOptions", "Ascunde alte opțiuni",
            "RemoveEmpty", "Elimină folderele rămase complet goale în folderul VECHI",
            "Confirm", "Am înțeles: va fi modificat NUMAI folderul VECHI. Folderul CURENT va rămâne neschimbat.",
            "Cleanup", "ELIMINĂ COPIILE IDENTICE DIN FOLDERUL VECHI",
            "Restore", "Restaurează fișierele puse deoparte…",
            "ProtectedReminder", "Folderul CURENT rămâne protejat",
            "Ready", "Gata.",
            "ChooseOldDialog", "Alege folderul VECHI de verificat și curățat",
            "ChooseCurrentDialog", "Alege folderul CURENT / PROTEJAT",
            "AnalyzeDone", "Verificare finalizată. Niciun fișier nu a fost modificat.",
            "AnalyzeCanceled", "Verificare anulată. Niciun fișier nu a fost modificat.",
            "AnalyzeErrorTitle", "Problemă în timpul verificării",
            "AnalyzeErrorStatus", "Verificarea s-a oprit din cauza unei probleme. Nu s-a efectuat nicio curățare.",
            "PathCheckTitle", "LegacySift — verifică folderele selectate",
            "CleanupConfirmTitle", "Confirmă curățarea folderului VECHI",
            "CleanupConfirm", "Ești pe cale să cureți NUMAI folderul VECHI:\n\n{0}\n\nFolderul CURENT este protejat și nu va fi modificat:\n\n{1}\n\nEliminate din VECHI: {2} copii identice.\nRămân în VECHI: {3} inexistente în CURENT, {4} posibile versiuni diferite, {5} neverificate.\n\nMetodă: {6}\n\nContinui?",
            "ModeSafety", "FOLDER DE SIGURANȚĂ (restaurabil)",
            "ModeRecycle", "COȘ DE RECICLARE WINDOWS",
            "CleanupDoneStatus", "Gata: {0} copii identice au fost eliminate din folderul VECHI; {1} elemente au rămas neatinse pentru siguranță.",
            "CleanupDoneTitle", "LegacySift — finalizat",
            "CleanupDone", "Curățare finalizată.\n\nEliminate din folderul VECHI: {0} copii identice\nLăsate pe loc pentru siguranță: {1}{2}\n\nFișierele inexistente în CURENT și posibilele versiuni diferite nu au fost atinse. Rulează din nou verificarea pentru a vedea exact ce a rămas.",
            "CleanupSafetyLocation", "\n\nFolder de siguranță:\n{0}\n\nNu îl șterge până nu verifici fișierele rămase în folderul vechi.",
            "CleanupCanceled", "Curățarea s-a oprit. Fișierele deja mutate rămân în folderul de siguranță / Coș; celelalte nu au fost atinse.",
            "CleanupErrorTitle", "Problemă în timpul curățării",
            "CleanupErrorStatus", "Curățarea s-a oprit din cauza unei probleme. Verifică folderul de siguranță și compară din nou înainte de a reîncerca.",
            "RestoreLast", "Restaurezi ultimul folder de siguranță creat?\n\n{0}",
            "RestoreTitle", "Restaurează fișiere",
            "RestoreChoose", "Alege un folder __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift va încerca să pună fișierele înapoi în locurile lor inițiale din folderul VECHI.\nFișierele care există deja acolo NU vor fi suprascrise.\n\nContinui?",
            "RestoreConfirmTitle", "Confirmă restaurarea",
            "RestoreDoneStatus", "Restaurare finalizată: {0} fișiere restaurate; {1} conflicte nu au fost suprascrise.",
            "RestoreDone", "Restaurate: {0}\nConflicte NESUPRASCRISE: {1}\nErori: {2}",
            "RestoreCanceled", "Restaurare oprită.",
            "RestoreErrorTitle", "Problemă în timpul restaurării",
            "Summary", "VERIFICARE FINALIZATĂ — niciun fișier nu a fost modificat.\n{0} inexistente în CURENT   |   {1} posibile versiuni diferite   |   {2} copii identice ({3})   |   {4} neverificate",
            "CleanupCount", "ELIMINĂ {0} COPII IDENTICE DIN FOLDERUL VECHI",
            "PhaseOldScan", "Se citește folderul VECHI",
            "PhaseCurrentScan", "Se citește folderul CURENT protejat",
            "PhaseCompare", "Se compară conținutul fișierelor",
            "PhaseSafety", "Se mută fișierele în folderul de siguranță",
            "PhaseRecycle", "Se mută fișierele în Coșul de reciclare",
            "PhaseRestoreRead", "Se citește folderul de siguranță",
            "PhaseRestore", "Se restaurează fișierele",
            "OldRequired", "Alege mai întâi folderul VECHI.",
            "CurrentRequired", "Alege folderul CURENT / PROTEJAT.",
            "InvalidPath", "Cale nevalidă: {0}",
            "OldMissing", "Folderul VECHI nu există.",
            "CurrentMissing", "Folderul CURENT / PROTEJAT nu există.",
            "SameFolder", "Cele două selecții indică același folder. Operațiune blocată.",
            "OldRootBlocked", "Pentru siguranță, rădăcina întreagă a unui disc nu poate fi folderul VECHI.",
            "CurrentRootBlocked", "Pentru siguranță, rădăcina întreagă a unui disc nu poate fi folderul CURENT.",
            "NestedBlocked", "Un folder selectat se află în celălalt. Alege două foldere separate.",
            "SystemFolderBlocked", "Pentru siguranță, LegacySift nu curăță direct un folder principal de sistem Windows.",
            "OutsideOld", "Verificare de siguranță eșuată: fișierul nu se află în folderul VECHI.",
            "ReparseDir", "Folder legat / punct de reparse omis pentru siguranță.",
            "ReparseFile", "Fișier legat / punct de reparse omis pentru siguranță.",
            "ExactNote", "În folderul CURENT există o copie identică. Această copie din VECHI poate fi eliminată în siguranță.",
            "VersionNoteOne", "În folderul curent există un fișier cu același nume, dar cu alt conținut. Acest fișier NU va fi eliminat.",
            "VersionNoteMany", "Au fost găsite {0} fișiere cu același nume, dar niciunul nu este identic. Acest fișier NU va fi eliminat.",
            "UniqueNote", "Nu s-a găsit nicio copie identică în folderul CURENT. Fișierul rămâne în folderul VECHI.",
            "LanguageRestart", "LegacySift va reporni pentru a aplica noua limbă. Rezultatele verificării curente vor fi șterse.",
            "LanguageRestartTitle", "Schimbă limba",
            "SafetyParentMissing", "LegacySift nu poate stabili unde să creeze folderul de siguranță.",
            "OldFileMissingNow", "Fișierul din folderul vechi nu mai există.",
            "CurrentCopyMissingNow", "Fișierul corespunzător din folderul curent nu mai există.",
            "ChangedSize", "Dimensiunea fișierului s-a schimbat după comparație. Fișierul a rămas neatins.",
            "ChangedHash", "Cele două fișiere nu mai sunt identice. Fișierul vechi a rămas neatins.",
            "SafetyDestinationExists", "În folderul de siguranță există deja un fișier cu aceeași cale.",
            "SafetyVerificationFailed", "Verificarea după mutarea în folderul de siguranță a eșuat. LegacySift a încercat să restaureze automat fișierul original.",
            "MovedSafety", "Mutat în folderul de siguranță și verificat.",
            "MovedRecycle", "Mutat în Coșul de reciclare Windows.",
            "SafetyFolderMissing", "Folderul de siguranță nu a fost găsit.",
            "RestoreNoOverwrite", "NESUPRASCRIS: {0}",
            "SessionMissing", "Lipsește LegacySift.session, deci restaurarea automată nu este posibilă.",
            "SessionInvalid", "Sesiunea folderului de siguranță nu este validă: lipsește calea inițială a folderului vechi.",
            "TabRecoverHelp", "Nu s-a găsit o copie identică în CURENT. Aceste fișiere rămân în folderul VECHI.",
            "TabVersionsHelp", "În CURENT există același nume, dar conținutul diferă. Aceste fișiere rămân în folderul VECHI.",
            "TabDuplicatesHelp", "În CURENT există deja o copie identică. Numai aceste fișiere din VECHI pot fi eliminate prin curățare.",
            "TabProblemsHelp", "LegacySift nu a putut verifica în siguranță aceste fișiere. Ele rămân în folderul VECHI.",
            "CheckingNow", "Se verifică cele două foldere… niciun fișier nu este modificat.",
            "CleanupBeforeAnalysis", "Rulează mai întâi verificarea. Apoi LegacySift va arăta exact ce poate fi eliminat din VECHI și ce va rămâne acolo.",
            "CleanupWaitForAnalysis", "Așteaptă finalizarea verificării. Curățarea este dezactivată cât timp LegacySift citește folderele.",
            "CleanupExplanation", "După curățare, în VECHI vor rămâne {0} fișiere inexistente în CURENT, {1} posibile versiuni diferite și {2} fișiere neverificate. Numai cele {3} copii identice vor fi eliminate din VECHI.",
            "AfterCleanupSummary", "Curățare finalizată: {0} copii identice eliminate din VECHI; {1} elemente lăsate neatinse pentru siguranță. Rulează din nou verificarea pentru a vedea exact ce a rămas.",
            "CleanupNeedsNewCheck", "Curățarea s-a încheiat. Rulează din nou verificarea pentru a vedea numai ce a rămas în folderul VECHI.",
            "HelpText", "LEGACYSIFT — GHID RAPID\n\nLA CE FOLOSEȘTE\nLegacySift este destinat migrării computerelor, discurilor vechi și backupurilor recuperate. Alege folderul VECHI și folderul CURENT folosit astăzi. LegacySift arată ce lipsește din CURENT și ce copii exacte ai deja.\n\nDIRECȚIA NU SE SCHIMBĂ NICIODATĂ\nFOLDER VECHI = poate fi curățat.\nFOLDER CURENT = protejat, folosit numai pentru comparație. LegacySift nu îl curăță niciodată.\n\nCUM SE FOLOSEȘTE\n1. Alege FOLDERUL VECHI.\n2. Alege FOLDERUL CURENT.\n3. Apasă VERIFICĂ CE AI DEJA. Acest pas nu modifică nimic.\n4. Citește rezultatele.\n5. Dacă sunt corecte, elimină din VECHI numai copiile identice.\n\nCE ÎNSEAMNĂ REZULTATELE\n• NU EXISTĂ ÎN CURENT: nu există o copie identică în CURENT. Fișierele rămân în VECHI.\n• POSIBILE VERSIUNI DIFERITE: există același nume, dar conținutul diferă. Fișierele rămân în VECHI.\n• COPII IDENTICE DEJA ÎN CURENT: în CURENT există o copie exactă. Numai aceste fișiere din VECHI pot fi eliminate.\n• FIȘIERE NEVERIFICATE: LegacySift nu le-a putut verifica în siguranță. Ele rămân în VECHI.\n\nDUPĂ CURĂȚARE\nÎn folderul VECHI rămân fișierele inexistente în CURENT, posibilele versiuni diferite și tot ce LegacySift nu a putut verifica în siguranță. Numai copiile exacte sunt eliminate din VECHI.\n\nCEA MAI SIGURĂ METODĂ\nFolosește folderul de siguranță. Copiile exacte sunt mutate într-un folder separat și restaurabil, lângă VECHI, în loc să fie șterse definitiv.\n\nSIGURANȚĂ TEHNICĂ\nConținutul exact este comparat cu SHA-256 și verificat din nou înainte de curățare. Folderele legate și punctele de reparse sunt omise. Selecțiile de foldere imbricate sunt blocate. LegacySift nu cere drepturi de administrator și funcționează complet local.\n\nREGULĂ SIMPLĂ\nDacă ai dubii, oprește-te după verificare. Nimic nu se schimbă până când nu pornești explicit curățarea."
        );
    }
}
