using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Lv = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — droša vecās mapes tīrīšana",
            "TabWork", "Salīdzināt un tīrīt",
            "TabHelp", "Norādījumi un drošība",
            "LanguageButton", "Valoda…",
            "Intro", "Vecā mape — kreisajā pusē. Pašreizējā mape — labajā pusē. LegacySift no VECĀS mapes dzēš tikai tos failus, kas jau ir identiski PAŠREIZĒJĀ mapē.",
            "OldTitle", "1. VECĀ MAPE",
            "OldBadge", "ŠO MAPI VAR TĪRĪT",
            "OldDescription", "Mape, kas atgūta no vecā datora, diska vai rezerves kopijas. Tīrīšanas procesā tiek mainīta tikai šī puse.",
            "CurrentTitle", "2. PAŠREIZĒJĀ MAPE",
            "CurrentBadge", "AIZSARGĀTA • TIKAI LASĪŠANAI",
            "CurrentDescription", "Mape, ko izmantojat pašlaik. LegacySift to nolasa tikai salīdzināšanai un nekad netīra.",
            "Browse", "Pārlūkot…",
            "Direction", "Salīdzināt VECO mapi → PAŠREIZĒJO aizsargāto mapi. Pārbaudes laikā faili tiek tikai nolasīti;nekas netiek mainīts.",
            "Analyze", "3. PĀRBAUDĪT, KAS JAU IR — nekas netiek mainīts",
            "Cancel", "Atcelt",
            "OpenReport", "Atvērt pēdējo pārskatu",
            "NoAnalysis", "Izvēlieties VECO mapi un PAŠREIZĒJO aizsargāto mapi, pēc tam veiciet pārbaudi.",
            "PathsChanged", "Ir mainīta mapes izvēle. Pirms tīrīšanas veiciet pārbaudi atkārtoti.",
            "TabRecover", "NAV ATRASTS PAŠREIZĒJĀ MAPĒ",
            "TabVersions", "IESPĒJAMAS ATŠĶIRĪGAS VERSIJAS",
            "TabDuplicates", "IDENTISKAS KOPIJAS",
            "TabProblems", "FAILI NAV PĀRBAUDĪTI",
            "GridOld", "Fails VECAJĀ mapē",
            "GridSize", "Izmērs",
            "GridCurrent", "Atbilstošs fails PAŠREIZĒJĀ mapē",
            "GridNote", "LegacySift atradumi",
            "CleanupGroup", "4. TĪRĪT VECO MAPI",
            "Quarantine", "Drošības mape (ieteicams) — pārvietot identiskās kopijas prom no VECĀS mapes, lai tās varētu atjaunot",
            "Recycle", "Windows atkritne — nosūtīt identiskās VECĀS mapes kopijas uz atkritni",
            "OtherOptions", "Rādīt citas opcijas",
            "HideOptions", "Slēpt citas opcijas",
            "RemoveEmpty", "Dzēst mapes, kas VECĀS mapes iekšienē palikušas pilnīgi tukšas",
            "Confirm", "Es saprotu: tiks mainīta TIKAI VECĀ mape. PAŠREIZĒJĀ mape paliks nemainīga.",
            "Cleanup", "DZĒST IDENTISKĀS KOPIJAS NO VECĀS MAPES",
            "Restore", "Atjaunot atliktās datnes…",
            "ProtectedReminder", "CURRENT (pašreizējā) mape paliek aizsargāta",
            "Ready", "Gatavs.",
            "ChooseOldDialog", "Izvēlieties OLD (veco) mapi pārbaudei un tīrīšanai",
            "ChooseCurrentDialog", "Izvēlieties CURRENT (pašreizējo) / PROTECTED (aizsargāto) mapi",
            "AnalyzeDone", "Pārbaude pabeigta. Neviena datne netika mainīta.",
            "AnalyzeCanceled", "Pārbaude atcelta. Neviena datne netika mainīta.",
            "AnalyzeErrorTitle", "Problēma pārbaudes laikā",
            "AnalyzeErrorStatus", "Pārbaude tika pārtraukta problēmas dēļ. Tīrīšana netika veikta.",
            "PathCheckTitle", "LegacySift — mapes izvēle pārbaudei",
            "CleanupConfirmTitle", "Apstiprināt OLD (vecās) mapes tīrīšanu",
            "CleanupConfirm", "Jūs gatavojaties tīrīt TIKAI OLD (veco) mapi:\\n\\n{0}\\n\\nCURRENT (pašreizējā) mape ir aizsargāta un netiks mainīta:\\n\\n{1}\\n\\nNo OLD (vecās) mapes noņemtas: {2} identiskas kopijas.\\nOLD (vecajā) mapē atstātas: {3} nav atrastas CURRENT (pašreizējā) mapē, {4} iespējamas atšķirīgas versijas, {5} nav pārbaudītas.\\n\\nMetode: {6}\\n\\nVai turpināt?",
            "ModeSafety", "DROŠĪBAS MAPE (atjaunojama)",
            "ModeRecycle", "WINDOWS ATKRITUMGROZS",
            "CleanupDoneStatus", "Pabeigts: no OLD (vecās) mapes tika noņemtas {0} identiskas kopijas;{1} kandidāti drošības nolūkos tika atstāti neskarti.",
            "CleanupDoneTitle", "LegacySift — pabeigts",
            "CleanupDone", "Tīrīšana pabeigta.\\n\\nNo OLD (vecās) mapes noņemtas: {0} identiskas kopijas\\nDrošības nolūkos atstātas: {1}{2}\\n\\nDatnes, kas nav atrastas CURRENT (pašreizējā) mapē, un iespējamās atšķirīgās versijas netika aiztiktas. Palaidiet pārbaudi vēlreiz, lai redzētu, kas tieši ir palicis.",
            "CleanupSafetyLocation", "\n\nDrošības mape:\n{0}\n\nNeizdzēsiet to, kamēr neesat pārbaudījis vecajā mapē palikušos failus.",
            "CleanupCanceled", "Tīrīšana pārtraukta. Jau pārvietotie faili paliek drošības mapē / atkritumu tvertnē;pārējie faili netika aiztikti.",
            "CleanupErrorTitle", "Problēma tīrīšanas laikā",
            "CleanupErrorStatus", "Tīrīšana pārtraukta problēmas dēļ. Pirms atkārtotas mēģināšanas pārbaudiet drošības mapi un veiciet jaunu salīdzināšanu.",
            "RestoreLast", "Vai atjaunot pēdējo izveidoto drošības mapi?\n\n{0}",
            "RestoreTitle", "Atjaunot failus",
            "RestoreChoose", "Izvēlieties __LegacySift_Safety_... mapi",
            "RestoreConfirm", "LegacySift mēģinās atgriezt failus to sākotnējās atrašanās vietās vecajā mapē. Faili, kas tur jau atrodas, netiks pārrakstīti. Vai turpināt?",
            "RestoreConfirmTitle", "Apstiprināt atjaunošanu",
            "RestoreDoneStatus", "Atjaunošana pabeigta: atjaunoti {0} faili;{1} konflikti netika pārrakstīti.",
            "RestoreDone", "Atjaunoti: {0}  Konflikti NAV pārrakstīti: {1}  Kļūdas: {2}",
            "RestoreCanceled", "Atjaunošana pārtraukta.",
            "RestoreErrorTitle", "Problēma atjaunošanas laikā",
            "Summary", "Pārbaude pabeigta — neviens fails netika mainīts.\\n{0} nav atrasts mapē CURRENT   |{1} iespējamas dažādas versijas   |{2} identiskas kopijas ({3})   |   {4} nav pārbaudīts",
            "CleanupCount", "Noņemt {0} identiskās kopijas no vecās mapes (OLD folder)",
            "PhaseOldScan", "Tiek lasīta vecā mape (OLD folder)",
            "PhaseCurrentScan", "Tiek lasīta pašreizējā aizsargātā mape (CURRENT folder)",
            "PhaseCompare", "Tiek salīdzināts failu saturs",
            "PhaseSafety", "Faili tiek pārvietoti uz drošības mapi",
            "PhaseRecycle", "Faili tiek pārvietoti uz atkritni",
            "PhaseRestoreRead", "Tiek lasīta drošības mape",
            "PhaseRestore", "Faili tiek atjaunoti",
            "OldRequired", "Vispirms izvēlieties veco mapi (OLD folder).",
            "CurrentRequired", "Izvēlieties pašreizējo / ​​aizsargāto mapi (CURRENT / PROTECTED folder).",
            "InvalidPath", "Nederīgs ceļš: {0}",
            "OldMissing", "Vecā mape (OLD folder) neeksistē.",
            "CurrentMissing", "Pašreizējā / aizsargātā mape (CURRENT / PROTECTED folder) neeksistē.",
            "SameFolder", "Abas izvēlētās opcijas norāda uz vienu un to pašu mapi. Darbība bloķēta.",
            "OldRootBlocked", "Drošības apsvērumu dēļ kā veco mapi (OLD folder) nevar izmantot diska saknes mapi.",
            "CurrentRootBlocked", "Drošības apsvērumu dēļ kā pašreizējo mapi (CURRENT folder) nevar izmantot diska saknes mapi.",
            "NestedBlocked", "Viena no izvēlētajām mapēm atrodas otrā mapē. Izvēlieties divas atsevišķas mapes.",
            "SystemFolderBlocked", "Drošības apsvērumu dēļ LegacySift netīrīs galveno Windows sistēmas mapi.",
            "OutsideOld", "Drošības pārbaude neizdevās: šis fails neatrodas vecajā mapē (OLD folder).",
            "ReparseDir", "Saistītā mape / atkārtotas parsēšanas punkts (reparse point) izlaists drošības apsvērumu dēļ.",
            "ReparseFile", "Saistītais fails / atkārtotas parsēšanas punkts (reparse point) izlaists drošības apsvērumu dēļ.",
            "ExactNote", "Pašreizējā mapē (CURRENT folder) pastāv identiska kopija. Šo kopiju no vecās mapes (OLD folder) var droši noņemt.",
            "VersionNoteOne", "Pašreizējā mapē pastāv fails ar tādu pašu nosaukumu, taču tā saturs ir atšķirīgs. Šis fails netiks noņemts.",
            "VersionNoteMany", "Tika atrasti faili ar nosaukumu {0}, taču neviens no tiem nav identisks. Šis fails netiks noņemts.",
            "UniqueNote", "Pašreizējā mapē (CURRENT folder) netika atrasta identiska kopija. Šis fails paliek mapē OLD.",
            "LanguageRestart", "LegacySift restartēsies, lai lietotu jauno valodu. Visi pašreizējie salīdzināšanas rezultāti tiks dzēsti.",
            "LanguageRestartTitle", "Mainīt valodu",
            "SafetyParentMissing", "LegacySift nevar noteikt, kur izveidot drošības mapi.",
            "OldFileMissingNow", "Fails vecajā mapē vairs nepastāv.",
            "CurrentCopyMissingNow", "Atbilstošais fails pašreizējā mapē vairs nepastāv.",
            "ChangedSize", "Faila izmērs pēc salīdzināšanas ir mainījies. Fails netika aiztikts.",
            "ChangedHash", "Abi faili vairs nav identiski. Vecais fails netika aiztikts.",
            "SafetyDestinationExists", "Drošības mapē jau pastāv fails ar tādu pašu ceļu.",
            "SafetyVerificationFailed", "Pēc pārvietošanas neizdevās verificēt drošības mapi. LegacySift mēģināja automātiski atjaunot sākotnējo failu.",
            "MovedSafety", "Pārvietots uz drošības mapi un verificēts.",
            "MovedRecycle", "Pārvietots uz Windows atkritni.",
            "SafetyFolderMissing", "Drošības mape nav atrasta.",
            "RestoreNoOverwrite", "NAV pārrakstīts: {0}",
            "SessionMissing", "Trūkst LegacySift.session, tāpēc automātiska atjaunošana nav iespējama.",
            "SessionInvalid", "Drošības mapes sesija nav derīga: trūkst sākotnējā ceļa uz veco mapi.",
            "TabRecoverHelp", "Mapē CURRENT netika atrasta identiska kopija. Šie faili paliek mapē OLD.",
            "TabVersionsHelp", "Mapē CURRENT pastāv fails ar tādu pašu nosaukumu, bet to saturs atšķiras. Šie faili paliek mapē OLD.",
            "TabDuplicatesHelp", "Mapē CURRENT jau pastāv identiska kopija. Tīrīšanas procesā var noņemt tikai šos failus no mapes OLD.",
            "TabProblemsHelp", "LegacySift nevarēja droši verificēt šos failus. Tie paliek mapē OLD.",
            "CheckingNow", "Tiek pārbaudītas abas mapes... neviens fails netiek mainīts.",
            "CleanupBeforeAnalysis", "Vispirms veiciet pārbaudi. Pēc tam LegacySift parādīs, ko tieši var noņemt no mapes OLD un kas tajā paliks.",
            "CleanupWaitForAnalysis", "Uzgaidiet, līdz pārbaude beidzas. Tīrīšana ir atspējota, kamēr LegacySift nolasa mapes.",
            "CleanupExplanation", "Pēc tīrīšanas mapē OLD paliks {0} faili, kas nav atrasti mapē CURRENT, {1} iespējamās atšķirīgās versijas un {2} nepārbaudītie faili. No OLD tiks izdzēstas tikai {3} identiskās kopijas.",
            "AfterCleanupSummary", "Tīrīšana pabeigta: no OLD izdzēstas {0} identiskās kopijas;{1} kandidāti drošības nolūkos atstāti neskarti. Palaidiet pārbaudi vēlreiz, lai redzētu, kas tieši ir palicis.",
            "CleanupNeedsNewCheck", "Tīrīšana ir pabeigta. Palaidiet pārbaudi vēlreiz, lai redzētu, kas palicis OLD mapē.",
            "HelpText", "LEGACYSIFT — ĪSA PAMĀCĪBA\\n\\nFUNKCIJAS\\nLegacySift ir paredzēts datu migrācijai starp datoriem, kā arī darbam ar veciem diskiem un atgūtiem rezerves kopiju failiem. Izvēlieties mapi \"OLD\" (vecā mape) un mapi \"CURRENT\" (pašreizējā mape, ko izmantojat šobrīd). LegacySift parāda, kādu failu trūkst mapē \"CURRENT\" un kādas precīzas kopijas jums jau ir.\\n\\nDARBĪBAS VIRZIENS NEMAINĀS\\nMape \"OLD\" = var tikt tīrīta.\\nMape \"CURRENT\" = aizsargāta, tiek izmantota tikai salīdzināšanai. LegacySift to nekad netīra.\\n\\nLIETOŠANA\\n1. Izvēlieties mapi \"OLD\".\\n2. Izvēlieties mapi \"CURRENT\".\\n3. Noklikšķiniet uz \"CHECK WHAT YOU ALREADY HAVE\" (pārbaudīt, kas jau ir). Šis solis neko nemaina.\\n4. Iepazīstieties ar rezultātiem.\\n5. Ja rezultāti šķiet pareizi, no mapes \"OLD\" dzēsiet tikai identiskās kopijas.\\n\\nREZULTĀTU SKAIDROJUMS\\n• NOT FOUND IN CURRENT (nav atrasts mapē \"CURRENT\"): mapē \"CURRENT\" nav identiskas kopijas. Šie faili paliek mapē \"OLD\".\\n• POSSIBLE DIFFERENT VERSIONS (iespējami atšķirīgas versijas): pastāv fails ar tādu pašu nosaukumu, bet saturs atšķiras. Šie faili paliek mapē \"OLD\".\\n• IDENTICAL COPIES ALREADY IN CURRENT (identiskas kopijas jau ir mapē \"CURRENT\"): mapē \"CURRENT\" ir precīza kopija. No mapes \"OLD\" var dzēst tikai šos failus.\\n• FILES NOT CHECKED (faili nav pārbaudīti): LegacySift nevarēja tos droši pārbaudīt. Tie paliek mapē \"OLD\".\\n\\nPĒC TĪRĪŠANAS\\nMapē \"OLD\" paliek faili, kas netika atrasti mapē \"CURRENT\", iespējamās atšķirīgās versijas un faili, kurus LegacySift nevarēja droši pārbaudīt. No mapes \"OLD\" tiek dzēstas tikai precīzās kopijas.\\n\\nDROŠĀKĀ METODE\\nIzmantojiet drošības mapi (Safety folder). Precīzās kopijas tiek pārvietotas uz atsevišķu, atjaunojamu mapi blakus mapei \"OLD\", nevis neatgriezeniski izdzēstas.\\n\\nTEHNISKĀ DROŠĪBA\\nPrecīzs saturs tiek pārbaudīts, izmantojot SHA-256, un atkārtoti pārbaudīts pirms tīrīšanas. Saistītās mapes / atkārtotas apstrādes punkti (reparse points) tiek izlaisti. Iegulto mapju atlase ir bloķēta. LegacySift nepieprasa administratora tiesības un darbojas pilnībā lokāli.\\n\\nVIENKĀRŠS NOTEIKUMS\\nJa neesat pārliecināts, pārtrauciet darbību pēc pārbaudes. Nekas netiek mainīts, līdz jūs nepārprotami uzsākat tīrīšanu."
        );
    }
}
