using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> De = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — alten Ordner sicher bereinigen",
            "TabWork", "Vergleichen und bereinigen",
            "TabHelp", "Anleitung und Sicherheit",
            "LanguageButton", "Sprache…",
            "Intro", "Alter Ordner links, aktueller Ordner rechts. LegacySift entfernt aus dem ALTEN Ordner nur Dateien, von denen im AKTUELLEN Ordner bereits eine identische Kopie vorhanden ist.",
            "OldTitle", "1. ALTER ORDNER",
            "OldBadge", "DIESER DARF BEREINIGT WERDEN",
            "OldDescription", "Der wiederhergestellte Ordner vom alten Computer, Datenträger oder Backup. Nur diese Seite darf durch die Bereinigung verändert werden.",
            "CurrentTitle", "2. AKTUELLER ORDNER",
            "CurrentBadge", "GESCHÜTZT • NUR LESEN",
            "CurrentDescription", "Der Ordner, den du heute verwendest. LegacySift liest ihn nur zum Vergleichen und bereinigt ihn niemals.",
            "Browse", "Durchsuchen…",
            "Direction", "Vergleich: ALTER Ordner → geschützter AKTUELLER Ordner. Die Prüfung liest Dateien nur und verändert nichts.",
            "Analyze", "3. PRÜFEN, WAS DU SCHON HAST — ändert nichts",
            "Cancel", "Abbrechen",
            "OpenReport", "Letzten Bericht öffnen",
            "NoAnalysis", "Wähle den ALTEN Ordner und den geschützten AKTUELLEN Ordner und starte dann die Prüfung.",
            "PathsChanged", "Eine Ordnerauswahl wurde geändert. Führe die Prüfung erneut aus, bevor etwas bereinigt wird.",
            "TabRecover", "NICHT IM AKTUELLEN ORDNER",
            "TabVersions", "MÖGLICHE ANDERE VERSIONEN",
            "TabDuplicates", "IDENTISCHE KOPIEN",
            "TabProblems", "NICHT GEPRÜFTE DATEIEN",
            "GridOld", "Datei im ALTEN Ordner",
            "GridSize", "Größe",
            "GridCurrent", "Passende Datei im AKTUELLEN Ordner",
            "GridNote", "Was LegacySift gefunden hat",
            "CleanupGroup", "4. ALTEN ORDNER BEREINIGEN",
            "Quarantine", "Sicherheitsordner (empfohlen) — identische Kopien aus dem ALTEN Ordner verschieben und Wiederherstellung ermöglichen",
            "Recycle", "Windows-Papierkorb — identische Kopien aus dem ALTEN Ordner in den Papierkorb verschieben",
            "OtherOptions", "Weitere Optionen anzeigen",
            "HideOptions", "Weitere Optionen ausblenden",
            "RemoveEmpty", "Vollständig leere Ordner im ALTEN Ordner entfernen",
            "Confirm", "Ich verstehe: NUR der ALTE Ordner wird verändert. Der AKTUELLE Ordner bleibt unverändert.",
            "Cleanup", "IDENTISCHE KOPIEN AUS DEM ALTEN ORDNER ENTFERNEN",
            "Restore", "Zur Seite gelegte Dateien wiederherstellen…",
            "ProtectedReminder", "AKTUELL bleibt geschützt",
            "Ready", "Bereit.",
            "ChooseOldDialog", "ALTEN Ordner zum Prüfen und Bereinigen auswählen",
            "ChooseCurrentDialog", "AKTUELLEN / GESCHÜTZTEN Ordner auswählen",
            "AnalyzeDone", "Prüfung abgeschlossen. Keine Datei wurde verändert.",
            "AnalyzeCanceled", "Prüfung abgebrochen. Keine Datei wurde verändert.",
            "AnalyzeErrorTitle", "Problem bei der Prüfung",
            "AnalyzeErrorStatus", "Die Prüfung wurde wegen eines Problems beendet. Es wurde nichts bereinigt.",
            "PathCheckTitle", "LegacySift — Ordnerauswahl prüfen",
            "CleanupConfirmTitle", "Bereinigung des ALTEN Ordners bestätigen",
            "CleanupConfirm", "Du bist dabei, NUR den ALTEN Ordner zu bereinigen:\n\n{0}\n\nDer AKTUELLE Ordner ist geschützt und wird nicht verändert:\n\n{1}\n\nAus ALT entfernt: {2} identische Kopien.\nIn ALT verbleiben: {3} nicht in AKTUELL gefunden, {4} mögliche andere Versionen, {5} nicht geprüft.\n\nMethode: {6}\n\nFortfahren?",
            "ModeSafety", "SICHERHEITSORDNER (wiederherstellbar)",
            "ModeRecycle", "WINDOWS-PAPIERKORB",
            "CleanupDoneStatus", "Fertig: {0} identische Kopien wurden aus dem ALTEN Ordner entfernt; {1} Kandidaten blieben aus Sicherheitsgründen unverändert.",
            "CleanupDoneTitle", "LegacySift — abgeschlossen",
            "CleanupDone", "Bereinigung abgeschlossen.\n\nAus dem ALTEN Ordner entfernt: {0} identische Kopien\nAus Sicherheitsgründen belassen: {1}{2}\n\nNicht im AKTUELLEN Ordner gefundene Dateien und mögliche andere Versionen wurden nicht verändert. Führe die Prüfung erneut aus, um genau zu sehen, was übrig bleibt.",
            "CleanupSafetyLocation", "\n\nSicherheitsordner:\n{0}\n\nLösche ihn nicht, bevor du die im alten Ordner verbliebenen Dateien geprüft hast.",
            "CleanupCanceled", "Bereinigung gestoppt. Bereits verschobene Dateien bleiben im Sicherheitsordner / Papierkorb; die übrigen Dateien wurden nicht verändert.",
            "CleanupErrorTitle", "Problem bei der Bereinigung",
            "CleanupErrorStatus", "Die Bereinigung wurde wegen eines Problems beendet. Prüfe den Sicherheitsordner und führe vor einem neuen Versuch einen neuen Vergleich aus.",
            "RestoreLast", "Den zuletzt erstellten Sicherheitsordner wiederherstellen?\n\n{0}",
            "RestoreTitle", "Dateien wiederherstellen",
            "RestoreChoose", "Einen __LegacySift_Safety_... Ordner auswählen",
            "RestoreConfirm", "LegacySift versucht, die Dateien an ihre ursprünglichen Positionen im ALTEN Ordner zurückzulegen.\nBereits vorhandene Dateien werden NICHT überschrieben.\n\nFortfahren?",
            "RestoreConfirmTitle", "Wiederherstellung bestätigen",
            "RestoreDoneStatus", "Wiederherstellung abgeschlossen: {0} Dateien wiederhergestellt; {1} Konflikte wurden nicht überschrieben.",
            "RestoreDone", "Wiederhergestellt: {0}\nKonflikte NICHT überschrieben: {1}\nFehler: {2}",
            "RestoreCanceled", "Wiederherstellung gestoppt.",
            "RestoreErrorTitle", "Problem bei der Wiederherstellung",
            "Summary", "PRÜFUNG ABGESCHLOSSEN — keine Datei wurde verändert.\n{0} nicht in AKTUELL gefunden   |   {1} mögliche andere Versionen   |   {2} identische Kopien ({3})   |   {4} nicht geprüft",
            "CleanupCount", "{0} IDENTISCHE KOPIEN AUS DEM ALTEN ORDNER ENTFERNEN",
            "PhaseOldScan", "ALTEN Ordner lesen",
            "PhaseCurrentScan", "Geschützten AKTUELLEN Ordner lesen",
            "PhaseCompare", "Dateiinhalte vergleichen",
            "PhaseSafety", "Dateien in den Sicherheitsordner verschieben",
            "PhaseRecycle", "Dateien in den Papierkorb verschieben",
            "PhaseRestoreRead", "Sicherheitsordner lesen",
            "PhaseRestore", "Dateien wiederherstellen",
            "OldRequired", "Wähle zuerst den ALTEN Ordner.",
            "CurrentRequired", "Wähle den AKTUELLEN / GESCHÜTZTEN Ordner.",
            "InvalidPath", "Ungültiger Pfad: {0}",
            "OldMissing", "Der ALTE Ordner existiert nicht.",
            "CurrentMissing", "Der AKTUELLE / GESCHÜTZTE Ordner existiert nicht.",
            "SameFolder", "Beide Auswahlen zeigen auf denselben Ordner. Vorgang blockiert.",
            "OldRootBlocked", "Aus Sicherheitsgründen kann ein komplettes Laufwerksstammverzeichnis nicht als ALTER Ordner verwendet werden.",
            "CurrentRootBlocked", "Aus Sicherheitsgründen kann ein komplettes Laufwerksstammverzeichnis nicht als AKTUELLER Ordner verwendet werden.",
            "NestedBlocked", "Ein ausgewählter Ordner liegt im anderen. Wähle zwei getrennte Ordner.",
            "SystemFolderBlocked", "Aus Sicherheitsgründen bereinigt LegacySift keinen wichtigen Windows-Systemordner direkt.",
            "OutsideOld", "Sicherheitsprüfung fehlgeschlagen: Diese Datei liegt nicht im ALTEN Ordner.",
            "ReparseDir", "Verknüpfter Ordner / Reparse Point wurde aus Sicherheitsgründen übersprungen.",
            "ReparseFile", "Verknüpfte Datei / Reparse Point wurde aus Sicherheitsgründen übersprungen.",
            "ExactNote", "Im AKTUELLEN Ordner existiert eine identische Kopie. Diese Kopie im ALTEN Ordner kann sicher entfernt werden.",
            "VersionNoteOne", "Im aktuellen Ordner existiert eine Datei mit demselben Namen, aber anderem Inhalt. Diese Datei wird NICHT entfernt.",
            "VersionNoteMany", "Es wurden {0} Dateien mit demselben Namen gefunden, aber keine ist identisch. Diese Datei wird NICHT entfernt.",
            "UniqueNote", "Im AKTUELLEN Ordner wurde keine identische Kopie gefunden. Diese Datei bleibt im ALTEN Ordner.",
            "LanguageRestart", "LegacySift wird neu gestartet, um die neue Sprache anzuwenden. Aktuelle Prüfergebnisse werden gelöscht.",
            "LanguageRestartTitle", "Sprache ändern",
            "SafetyParentMissing", "LegacySift kann nicht bestimmen, wo der Sicherheitsordner erstellt werden soll.",
            "OldFileMissingNow", "Die Datei im alten Ordner existiert nicht mehr.",
            "CurrentCopyMissingNow", "Die passende Datei im aktuellen Ordner existiert nicht mehr.",
            "ChangedSize", "Die Dateigröße hat sich nach dem Vergleich geändert. Die Datei blieb unverändert.",
            "ChangedHash", "Die beiden Dateien sind nicht mehr identisch. Die alte Datei blieb unverändert.",
            "SafetyDestinationExists", "Im Sicherheitsordner existiert bereits eine Datei mit demselben Pfad.",
            "SafetyVerificationFailed", "Die Prüfung nach dem Verschieben in den Sicherheitsordner ist fehlgeschlagen. LegacySift hat versucht, die Originaldatei automatisch wiederherzustellen.",
            "MovedSafety", "In den Sicherheitsordner verschoben und geprüft.",
            "MovedRecycle", "In den Windows-Papierkorb verschoben.",
            "SafetyFolderMissing", "Sicherheitsordner nicht gefunden.",
            "RestoreNoOverwrite", "NICHT überschrieben: {0}",
            "SessionMissing", "LegacySift.session fehlt; eine automatische Wiederherstellung ist nicht möglich.",
            "SessionInvalid", "Die Sitzung des Sicherheitsordners ist ungültig: Der ursprüngliche Pfad des alten Ordners fehlt.",
            "TabRecoverHelp", "Im AKTUELLEN Ordner wurde keine identische Kopie gefunden. Diese Dateien bleiben im ALTEN Ordner.",
            "TabVersionsHelp", "Im AKTUELLEN Ordner existiert derselbe Name, aber der Inhalt ist anders. Diese Dateien bleiben im ALTEN Ordner.",
            "TabDuplicatesHelp", "Im AKTUELLEN Ordner existiert bereits eine identische Kopie. Nur diese Dateien aus dem ALTEN Ordner können durch die Bereinigung entfernt werden.",
            "TabProblemsHelp", "LegacySift konnte diese Dateien nicht sicher prüfen. Sie bleiben im ALTEN Ordner.",
            "CheckingNow", "Die beiden Ordner werden geprüft… keine Datei wird verändert.",
            "CleanupBeforeAnalysis", "Führe zuerst die Prüfung aus. Danach zeigt LegacySift genau, was aus dem ALTEN Ordner entfernt werden kann und was dort bleibt.",
            "CleanupWaitForAnalysis", "Warte, bis die Prüfung abgeschlossen ist. Die Bereinigung ist deaktiviert, solange LegacySift die Ordner liest.",
            "CleanupExplanation", "Nach der Bereinigung bleiben im ALTEN Ordner {0} nicht in AKTUELL gefundene Dateien, {1} mögliche andere Versionen und {2} nicht geprüfte Dateien. Nur die {3} identischen Kopien werden aus ALT entfernt.",
            "AfterCleanupSummary", "Bereinigung abgeschlossen: {0} identische Kopien aus ALT entfernt; {1} Kandidaten aus Sicherheitsgründen unverändert. Führe die Prüfung erneut aus, um genau zu sehen, was übrig bleibt.",
            "CleanupNeedsNewCheck", "Die Bereinigung ist abgeschlossen. Führe die Prüfung erneut aus, um nur das zu sehen, was im ALTEN Ordner übrig ist.",
            "HelpText", "LEGACYSIFT — KURZANLEITUNG\n\nWOFÜR ES DA IST\nLegacySift ist für Computerumzüge, alte Datenträger und wiederhergestellte Backups gedacht. Wähle den ALTEN Ordner und den AKTUELLEN Ordner, den du heute verwendest. LegacySift zeigt, was in AKTUELL fehlt und welche exakten Kopien du bereits besitzt.\n\nDIE RICHTUNG ÄNDERT SICH NIE\nALTER ORDNER = darf bereinigt werden.\nAKTUELLER ORDNER = geschützt, nur zum Vergleichen. LegacySift bereinigt ihn niemals.\n\nSO GEHT'S\n1. Wähle den ALTEN ORDNER.\n2. Wähle den AKTUELLEN ORDNER.\n3. Klicke auf PRÜFEN, WAS DU SCHON HAST. Dieser Schritt ändert nichts.\n4. Lies die Ergebnisse.\n5. Wenn alles stimmt, entferne aus ALT nur die identischen Kopien.\n\nBEDEUTUNG DER ERGEBNISSE\n• NICHT IM AKTUELLEN ORDNER: In AKTUELL existiert keine identische Kopie. Diese Dateien bleiben in ALT.\n• MÖGLICHE ANDERE VERSIONEN: Derselbe Name existiert, aber der Inhalt ist anders. Diese Dateien bleiben in ALT.\n• IDENTISCHE KOPIEN: In AKTUELL existiert eine exakte Kopie. Nur diese Dateien dürfen aus ALT entfernt werden.\n• NICHT GEPRÜFTE DATEIEN: LegacySift konnte sie nicht sicher prüfen. Sie bleiben in ALT.\n\nNACH DER BEREINIGUNG\nIm ALTEN Ordner bleiben Dateien, die in AKTUELL nicht gefunden wurden, mögliche andere Versionen und alles, was LegacySift nicht sicher prüfen konnte. Nur identische Kopien werden aus ALT entfernt.\n\nSICHERSTE METHODE\nVerwende den SICHERHEITSORDNER. Identische Kopien werden in einen separaten, wiederherstellbaren Ordner neben ALT verschoben, statt dauerhaft gelöscht zu werden.\n\nTECHNISCHE SICHERHEIT\nExakte Inhalte werden mit SHA-256 verglichen und vor der Bereinigung erneut geprüft. Verknüpfte Ordner/Reparse Points werden übersprungen. Verschachtelte Ordnerauswahlen werden blockiert. LegacySift benötigt keine Administratorrechte und arbeitet vollständig lokal.\n\nEINFACHE REGEL\nWenn du unsicher bist, stoppe nach der Prüfung. Nichts ändert sich, bis du die Bereinigung ausdrücklich startest."
        );

        private static readonly Dictionary<string, string> Fr = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — nettoyer un ancien dossier en toute sécurité",
            "TabWork", "Comparer et nettoyer",
            "TabHelp", "Guide et sécurité",
            "LanguageButton", "Langue…",
            "Intro", "Ancien dossier à gauche, dossier actuel à droite. LegacySift retire de l’ANCIEN dossier uniquement les fichiers dont une copie identique existe déjà dans le dossier ACTUEL.",
            "OldTitle", "1. ANCIEN DOSSIER",
            "OldBadge", "CELUI-CI PEUT ÊTRE NETTOYÉ",
            "OldDescription", "Le dossier récupéré depuis l’ancien ordinateur, disque ou sauvegarde. Seul ce côté peut être modifié par le nettoyage.",
            "CurrentTitle", "2. DOSSIER ACTUEL",
            "CurrentBadge", "PROTÉGÉ • LECTURE SEULE",
            "CurrentDescription", "Le dossier que vous utilisez aujourd’hui. LegacySift le lit uniquement pour comparer et ne le nettoie jamais.",
            "Browse", "Parcourir…",
            "Direction", "Comparaison : ANCIEN dossier → dossier ACTUEL protégé. Le contrôle lit seulement les fichiers et ne modifie rien.",
            "Analyze", "3. VÉRIFIER CE QUE VOUS AVEZ DÉJÀ — ne modifie rien",
            "Cancel", "Annuler",
            "OpenReport", "Ouvrir le dernier rapport",
            "NoAnalysis", "Choisissez l’ANCIEN dossier et le dossier ACTUEL protégé, puis lancez le contrôle.",
            "PathsChanged", "La sélection d’un dossier a changé. Relancez le contrôle avant tout nettoyage.",
            "TabRecover", "ABSENTS DU DOSSIER ACTUEL",
            "TabVersions", "AUTRES VERSIONS POSSIBLES",
            "TabDuplicates", "COPIES IDENTIQUES",
            "TabProblems", "FICHIERS NON CONTRÔLÉS",
            "GridOld", "Fichier dans l’ANCIEN dossier",
            "GridSize", "Taille",
            "GridCurrent", "Fichier correspondant dans le dossier ACTUEL",
            "GridNote", "Ce que LegacySift a trouvé",
            "CleanupGroup", "4. NETTOYER L’ANCIEN DOSSIER",
            "Quarantine", "Dossier de sécurité (recommandé) — déplacer hors de l’ANCIEN les copies identiques afin de pouvoir les restaurer",
            "Recycle", "Corbeille Windows — envoyer à la Corbeille les copies identiques de l’ANCIEN dossier",
            "OtherOptions", "Afficher d’autres options",
            "HideOptions", "Masquer les autres options",
            "RemoveEmpty", "Supprimer les dossiers devenus complètement vides dans l’ANCIEN dossier",
            "Confirm", "J’ai compris : SEUL l’ANCIEN dossier sera modifié. Le dossier ACTUEL restera inchangé.",
            "Cleanup", "RETIRER LES COPIES IDENTIQUES DE L’ANCIEN DOSSIER",
            "Restore", "Restaurer les fichiers mis de côté…",
            "ProtectedReminder", "ACTUEL reste protégé",
            "Ready", "Prêt.",
            "ChooseOldDialog", "Choisir l’ANCIEN dossier à contrôler et nettoyer",
            "ChooseCurrentDialog", "Choisir le dossier ACTUEL / PROTÉGÉ",
            "AnalyzeDone", "Contrôle terminé. Aucun fichier n’a été modifié.",
            "AnalyzeCanceled", "Contrôle annulé. Aucun fichier n’a été modifié.",
            "AnalyzeErrorTitle", "Problème pendant le contrôle",
            "AnalyzeErrorStatus", "Le contrôle s’est arrêté à cause d’un problème. Aucun nettoyage n’a été effectué.",
            "PathCheckTitle", "LegacySift — vérifier la sélection des dossiers",
            "CleanupConfirmTitle", "Confirmer le nettoyage de l’ANCIEN dossier",
            "CleanupConfirm", "Vous êtes sur le point de nettoyer UNIQUEMENT l’ANCIEN dossier :\n\n{0}\n\nLe dossier ACTUEL est protégé et ne sera pas modifié :\n\n{1}\n\nRetirées de l’ANCIEN : {2} copies identiques.\nRestent dans l’ANCIEN : {3} absents de l’ACTUEL, {4} autres versions possibles, {5} non contrôlés.\n\nMéthode : {6}\n\nContinuer ?",
            "ModeSafety", "DOSSIER DE SÉCURITÉ (restaurable)",
            "ModeRecycle", "CORBEILLE WINDOWS",
            "CleanupDoneStatus", "Terminé : {0} copies identiques ont été retirées de l’ANCIEN dossier ; {1} éléments ont été laissés en place par sécurité.",
            "CleanupDoneTitle", "LegacySift — terminé",
            "CleanupDone", "Nettoyage terminé.\n\nRetirées de l’ANCIEN dossier : {0} copies identiques\nLaissées en place par sécurité : {1}{2}\n\nLes fichiers absents du dossier ACTUEL et les autres versions possibles n’ont pas été touchés. Relancez le contrôle pour voir exactement ce qui reste.",
            "CleanupSafetyLocation", "\n\nDossier de sécurité :\n{0}\n\nNe le supprimez pas avant d’avoir vérifié les fichiers restés dans l’ancien dossier.",
            "CleanupCanceled", "Nettoyage interrompu. Les fichiers déjà déplacés restent dans le dossier de sécurité / la Corbeille ; les autres n’ont pas été touchés.",
            "CleanupErrorTitle", "Problème pendant le nettoyage",
            "CleanupErrorStatus", "Le nettoyage s’est arrêté à cause d’un problème. Vérifiez le dossier de sécurité et refaites une comparaison avant de réessayer.",
            "RestoreLast", "Restaurer le dernier dossier de sécurité créé ?\n\n{0}",
            "RestoreTitle", "Restaurer les fichiers",
            "RestoreChoose", "Choisir un dossier __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift essaiera de remettre les fichiers à leur emplacement d’origine dans l’ANCIEN dossier.\nLes fichiers déjà présents ne seront PAS écrasés.\n\nContinuer ?",
            "RestoreConfirmTitle", "Confirmer la restauration",
            "RestoreDoneStatus", "Restauration terminée : {0} fichiers restaurés ; {1} conflits n’ont pas été écrasés.",
            "RestoreDone", "Restaurés : {0}\nConflits NON écrasés : {1}\nErreurs : {2}",
            "RestoreCanceled", "Restauration interrompue.",
            "RestoreErrorTitle", "Problème pendant la restauration",
            "Summary", "CONTRÔLE TERMINÉ — aucun fichier n’a été modifié.\n{0} absents de l’ACTUEL   |   {1} autres versions possibles   |   {2} copies identiques ({3})   |   {4} non contrôlés",
            "CleanupCount", "RETIRER {0} COPIES IDENTIQUES DE L’ANCIEN DOSSIER",
            "PhaseOldScan", "Lecture de l’ANCIEN dossier",
            "PhaseCurrentScan", "Lecture du dossier ACTUEL protégé",
            "PhaseCompare", "Comparaison du contenu des fichiers",
            "PhaseSafety", "Déplacement vers le dossier de sécurité",
            "PhaseRecycle", "Déplacement vers la Corbeille",
            "PhaseRestoreRead", "Lecture du dossier de sécurité",
            "PhaseRestore", "Restauration des fichiers",
            "OldRequired", "Choisissez d’abord l’ANCIEN dossier.",
            "CurrentRequired", "Choisissez le dossier ACTUEL / PROTÉGÉ.",
            "InvalidPath", "Chemin non valide : {0}",
            "OldMissing", "L’ANCIEN dossier n’existe pas.",
            "CurrentMissing", "Le dossier ACTUEL / PROTÉGÉ n’existe pas.",
            "SameFolder", "Les deux sélections désignent le même dossier. Opération bloquée.",
            "OldRootBlocked", "Pour des raisons de sécurité, la racine entière d’un disque ne peut pas être utilisée comme ANCIEN dossier.",
            "CurrentRootBlocked", "Pour des raisons de sécurité, la racine entière d’un disque ne peut pas être utilisée comme dossier ACTUEL.",
            "NestedBlocked", "Un dossier sélectionné se trouve dans l’autre. Choisissez deux dossiers séparés.",
            "SystemFolderBlocked", "Pour des raisons de sécurité, LegacySift ne nettoie pas directement un dossier système principal de Windows.",
            "OutsideOld", "Échec du contrôle de sécurité : ce fichier n’est pas dans l’ANCIEN dossier.",
            "ReparseDir", "Dossier lié / point de réanalyse ignoré par sécurité.",
            "ReparseFile", "Fichier lié / point de réanalyse ignoré par sécurité.",
            "ExactNote", "Une copie identique existe dans le dossier ACTUEL. Cette copie de l’ANCIEN dossier peut être retirée en toute sécurité.",
            "VersionNoteOne", "Un fichier portant le même nom existe dans le dossier actuel, mais son contenu est différent. Ce fichier ne sera PAS retiré.",
            "VersionNoteMany", "{0} fichiers portant le même nom ont été trouvés, mais aucun n’est identique. Ce fichier ne sera PAS retiré.",
            "UniqueNote", "Aucune copie identique n’a été trouvée dans le dossier ACTUEL. Ce fichier reste dans l’ANCIEN dossier.",
            "LanguageRestart", "LegacySift va redémarrer pour appliquer la nouvelle langue. Les résultats du contrôle actuel seront effacés.",
            "LanguageRestartTitle", "Changer de langue",
            "SafetyParentMissing", "LegacySift ne peut pas déterminer où créer le dossier de sécurité.",
            "OldFileMissingNow", "Le fichier de l’ancien dossier n’existe plus.",
            "CurrentCopyMissingNow", "Le fichier correspondant du dossier actuel n’existe plus.",
            "ChangedSize", "La taille du fichier a changé après la comparaison. Le fichier a été laissé intact.",
            "ChangedHash", "Les deux fichiers ne sont plus identiques. L’ancien fichier a été laissé intact.",
            "SafetyDestinationExists", "Un fichier avec le même chemin existe déjà dans le dossier de sécurité.",
            "SafetyVerificationFailed", "La vérification après déplacement vers le dossier de sécurité a échoué. LegacySift a tenté de restaurer automatiquement le fichier d’origine.",
            "MovedSafety", "Déplacé vers le dossier de sécurité et vérifié.",
            "MovedRecycle", "Déplacé vers la Corbeille Windows.",
            "SafetyFolderMissing", "Dossier de sécurité introuvable.",
            "RestoreNoOverwrite", "NON écrasé : {0}",
            "SessionMissing", "LegacySift.session est absent ; la restauration automatique n’est pas possible.",
            "SessionInvalid", "La session du dossier de sécurité n’est pas valide : le chemin d’origine de l’ancien dossier est absent.",
            "TabRecoverHelp", "Aucune copie identique n’a été trouvée dans l’ACTUEL. Ces fichiers restent dans l’ANCIEN dossier.",
            "TabVersionsHelp", "Le même nom existe dans l’ACTUEL, mais le contenu est différent. Ces fichiers restent dans l’ANCIEN dossier.",
            "TabDuplicatesHelp", "Une copie identique existe déjà dans l’ACTUEL. Seuls ces fichiers de l’ANCIEN dossier peuvent être retirés par le nettoyage.",
            "TabProblemsHelp", "LegacySift n’a pas pu vérifier ces fichiers en toute sécurité. Ils restent dans l’ANCIEN dossier.",
            "CheckingNow", "Contrôle des deux dossiers en cours… aucun fichier n’est modifié.",
            "CleanupBeforeAnalysis", "Lancez d’abord le contrôle. LegacySift indiquera ensuite exactement ce qui peut être retiré de l’ANCIEN dossier et ce qui y restera.",
            "CleanupWaitForAnalysis", "Attendez la fin du contrôle. Le nettoyage est désactivé pendant que LegacySift lit les dossiers.",
            "CleanupExplanation", "Après le nettoyage, l’ANCIEN dossier conservera {0} fichiers absents de l’ACTUEL, {1} autres versions possibles et {2} fichiers non contrôlés. Seules les {3} copies identiques seront retirées de l’ANCIEN.",
            "AfterCleanupSummary", "Nettoyage terminé : {0} copies identiques retirées de l’ANCIEN ; {1} éléments laissés intacts par sécurité. Relancez le contrôle pour voir exactement ce qui reste.",
            "CleanupNeedsNewCheck", "Le nettoyage est terminé. Relancez le contrôle pour voir uniquement ce qui reste dans l’ANCIEN dossier.",
            "HelpText", "LEGACYSIFT — GUIDE RAPIDE\n\nÀ QUOI ÇA SERT\nLegacySift est conçu pour les migrations d’ordinateur, les anciens disques et les sauvegardes récupérées. Choisissez l’ANCIEN dossier et le dossier ACTUEL que vous utilisez aujourd’hui. LegacySift montre ce qui manque dans l’ACTUEL et quelles copies exactes vous possédez déjà.\n\nLE SENS NE CHANGE JAMAIS\nANCIEN DOSSIER = peut être nettoyé.\nDOSSIER ACTUEL = protégé, utilisé uniquement pour la comparaison. LegacySift ne le nettoie jamais.\n\nCOMMENT L’UTILISER\n1. Choisissez l’ANCIEN DOSSIER.\n2. Choisissez le DOSSIER ACTUEL.\n3. Cliquez sur VÉRIFIER CE QUE VOUS AVEZ DÉJÀ. Cette étape ne modifie rien.\n4. Lisez les résultats.\n5. S’ils sont corrects, retirez de l’ANCIEN uniquement les copies identiques.\n\nSIGNIFICATION DES RÉSULTATS\n• ABSENTS DU DOSSIER ACTUEL : aucune copie identique n’existe dans l’ACTUEL. Ces fichiers restent dans l’ANCIEN.\n• AUTRES VERSIONS POSSIBLES : le même nom existe, mais le contenu est différent. Ces fichiers restent dans l’ANCIEN.\n• COPIES IDENTIQUES : une copie exacte existe dans l’ACTUEL. Seuls ces fichiers peuvent être retirés de l’ANCIEN.\n• FICHIERS NON CONTRÔLÉS : LegacySift n’a pas pu les vérifier en toute sécurité. Ils restent dans l’ANCIEN.\n\nAPRÈS LE NETTOYAGE\nL’ANCIEN dossier conserve les fichiers absents de l’ACTUEL, les autres versions possibles et tout ce que LegacySift n’a pas pu vérifier en toute sécurité. Seules les copies identiques sont retirées.\n\nMÉTHODE LA PLUS SÛRE\nUtilisez le DOSSIER DE SÉCURITÉ. Les copies identiques sont déplacées dans un dossier séparé et restaurable à côté de l’ANCIEN au lieu d’être supprimées définitivement.\n\nSÉCURITÉ TECHNIQUE\nLe contenu exact est comparé avec SHA-256 et revérifié avant le nettoyage. Les liens et points de réanalyse sont ignorés. Les sélections de dossiers imbriqués sont bloquées. LegacySift ne demande pas de droits administrateur et fonctionne entièrement en local.\n\nRÈGLE SIMPLE\nEn cas de doute, arrêtez-vous après le contrôle. Rien ne change tant que vous ne lancez pas explicitement le nettoyage."
        );

        private static readonly Dictionary<string, string> Es = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — limpia una carpeta antigua de forma segura",
            "TabWork", "Comparar y limpiar",
            "TabHelp", "Guía y seguridad",
            "LanguageButton", "Idioma…",
            "Intro", "Carpeta antigua a la izquierda, carpeta actual a la derecha. LegacySift elimina de la carpeta ANTIGUA solo los archivos de los que ya existe una copia idéntica en la carpeta ACTUAL.",
            "OldTitle", "1. CARPETA ANTIGUA",
            "OldBadge", "ESTA SE PUEDE LIMPIAR",
            "OldDescription", "La carpeta recuperada del ordenador antiguo, disco o copia de seguridad. Solo este lado puede cambiar durante la limpieza.",
            "CurrentTitle", "2. CARPETA ACTUAL",
            "CurrentBadge", "PROTEGIDA • SOLO LECTURA",
            "CurrentDescription", "La carpeta que usas hoy. LegacySift solo la lee para comparar y nunca la limpia.",
            "Browse", "Examinar…",
            "Direction", "Comparación: carpeta ANTIGUA → carpeta ACTUAL protegida. La comprobación solo lee los archivos y no modifica nada.",
            "Analyze", "3. COMPRUEBA LO QUE YA TIENES — no modifica nada",
            "Cancel", "Cancelar",
            "OpenReport", "Abrir último informe",
            "NoAnalysis", "Elige la carpeta ANTIGUA y la carpeta ACTUAL protegida y después inicia la comprobación.",
            "PathsChanged", "Ha cambiado la selección de una carpeta. Vuelve a comprobar antes de limpiar nada.",
            "TabRecover", "NO ESTÁN EN LA CARPETA ACTUAL",
            "TabVersions", "POSIBLES VERSIONES DIFERENTES",
            "TabDuplicates", "COPIAS IDÉNTICAS",
            "TabProblems", "ARCHIVOS NO COMPROBADOS",
            "GridOld", "Archivo en la carpeta ANTIGUA",
            "GridSize", "Tamaño",
            "GridCurrent", "Archivo correspondiente en la carpeta ACTUAL",
            "GridNote", "Lo que encontró LegacySift",
            "CleanupGroup", "4. LIMPIAR LA CARPETA ANTIGUA",
            "Quarantine", "Carpeta de seguridad (recomendado) — mueve fuera de ANTIGUA las copias idénticas y permite restaurarlas",
            "Recycle", "Papelera de Windows — envía a la Papelera las copias idénticas de la carpeta ANTIGUA",
            "OtherOptions", "Mostrar otras opciones",
            "HideOptions", "Ocultar otras opciones",
            "RemoveEmpty", "Eliminar las carpetas que queden completamente vacías dentro de la carpeta ANTIGUA",
            "Confirm", "Entiendo: SOLO se modificará la carpeta ANTIGUA. La carpeta ACTUAL permanecerá sin cambios.",
            "Cleanup", "QUITAR COPIAS IDÉNTICAS DE LA CARPETA ANTIGUA",
            "Restore", "Restaurar archivos apartados…",
            "ProtectedReminder", "ACTUAL permanece protegida",
            "Ready", "Listo.",
            "ChooseOldDialog", "Elige la carpeta ANTIGUA que quieres comprobar y limpiar",
            "ChooseCurrentDialog", "Elige la carpeta ACTUAL / PROTEGIDA",
            "AnalyzeDone", "Comprobación terminada. No se ha modificado ningún archivo.",
            "AnalyzeCanceled", "Comprobación cancelada. No se ha modificado ningún archivo.",
            "AnalyzeErrorTitle", "Problema durante la comprobación",
            "AnalyzeErrorStatus", "La comprobación se detuvo por un problema. No se realizó ninguna limpieza.",
            "PathCheckTitle", "LegacySift — comprobar selección de carpetas",
            "CleanupConfirmTitle", "Confirmar limpieza de la carpeta ANTIGUA",
            "CleanupConfirm", "Vas a limpiar SOLO la carpeta ANTIGUA:\n\n{0}\n\nLa carpeta ACTUAL está protegida y no se modificará:\n\n{1}\n\nSe quitarán de ANTIGUA: {2} copias idénticas.\nPermanecerán en ANTIGUA: {3} no encontrados en ACTUAL, {4} posibles versiones diferentes, {5} no comprobados.\n\nMétodo: {6}\n\n¿Continuar?",
            "ModeSafety", "CARPETA DE SEGURIDAD (restaurable)",
            "ModeRecycle", "PAPELERA DE WINDOWS",
            "CleanupDoneStatus", "Hecho: se quitaron {0} copias idénticas de la carpeta ANTIGUA; {1} elementos quedaron sin tocar por seguridad.",
            "CleanupDoneTitle", "LegacySift — completado",
            "CleanupDone", "Limpieza completada.\n\nQuitadas de la carpeta ANTIGUA: {0} copias idénticas\nDejadas sin tocar por seguridad: {1}{2}\n\nLos archivos no encontrados en la carpeta ACTUAL y las posibles versiones diferentes no se tocaron. Vuelve a comprobar para ver exactamente qué queda.",
            "CleanupSafetyLocation", "\n\nCarpeta de seguridad:\n{0}\n\nNo la elimines hasta haber comprobado los archivos que quedan en la carpeta antigua.",
            "CleanupCanceled", "Limpieza detenida. Los archivos ya movidos permanecen en la carpeta de seguridad / Papelera; los demás no se tocaron.",
            "CleanupErrorTitle", "Problema durante la limpieza",
            "CleanupErrorStatus", "La limpieza se detuvo por un problema. Comprueba la carpeta de seguridad y vuelve a comparar antes de intentarlo de nuevo.",
            "RestoreLast", "¿Restaurar la última carpeta de seguridad creada?\n\n{0}",
            "RestoreTitle", "Restaurar archivos",
            "RestoreChoose", "Elige una carpeta __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift intentará devolver los archivos a sus ubicaciones originales dentro de la carpeta ANTIGUA.\nLos archivos que ya existan allí NO se sobrescribirán.\n\n¿Continuar?",
            "RestoreConfirmTitle", "Confirmar restauración",
            "RestoreDoneStatus", "Restauración completada: {0} archivos restaurados; {1} conflictos no se sobrescribieron.",
            "RestoreDone", "Restaurados: {0}\nConflictos NO sobrescritos: {1}\nErrores: {2}",
            "RestoreCanceled", "Restauración detenida.",
            "RestoreErrorTitle", "Problema durante la restauración",
            "Summary", "COMPROBACIÓN TERMINADA — no se modificó ningún archivo.\n{0} no están en ACTUAL   |   {1} posibles versiones diferentes   |   {2} copias idénticas ({3})   |   {4} no comprobados",
            "CleanupCount", "QUITAR {0} COPIAS IDÉNTICAS DE LA CARPETA ANTIGUA",
            "PhaseOldScan", "Leyendo carpeta ANTIGUA",
            "PhaseCurrentScan", "Leyendo carpeta ACTUAL protegida",
            "PhaseCompare", "Comparando el contenido de los archivos",
            "PhaseSafety", "Moviendo archivos a la carpeta de seguridad",
            "PhaseRecycle", "Moviendo archivos a la Papelera",
            "PhaseRestoreRead", "Leyendo carpeta de seguridad",
            "PhaseRestore", "Restaurando archivos",
            "OldRequired", "Elige primero la carpeta ANTIGUA.",
            "CurrentRequired", "Elige la carpeta ACTUAL / PROTEGIDA.",
            "InvalidPath", "Ruta no válida: {0}",
            "OldMissing", "La carpeta ANTIGUA no existe.",
            "CurrentMissing", "La carpeta ACTUAL / PROTEGIDA no existe.",
            "SameFolder", "Las dos selecciones apuntan a la misma carpeta. Operación bloqueada.",
            "OldRootBlocked", "Por seguridad, no se puede usar la raíz completa de una unidad como carpeta ANTIGUA.",
            "CurrentRootBlocked", "Por seguridad, no se puede usar la raíz completa de una unidad como carpeta ACTUAL.",
            "NestedBlocked", "Una carpeta seleccionada está dentro de la otra. Elige dos carpetas separadas.",
            "SystemFolderBlocked", "Por seguridad, LegacySift no limpia directamente una carpeta principal del sistema Windows.",
            "OutsideOld", "Falló la comprobación de seguridad: este archivo no está dentro de la carpeta ANTIGUA.",
            "ReparseDir", "Carpeta vinculada / punto de reanálisis omitido por seguridad.",
            "ReparseFile", "Archivo vinculado / punto de reanálisis omitido por seguridad.",
            "ExactNote", "Ya existe una copia idéntica en la carpeta ACTUAL. Esta copia de la carpeta ANTIGUA se puede quitar de forma segura.",
            "VersionNoteOne", "En la carpeta actual existe un archivo con el mismo nombre, pero su contenido es diferente. Este archivo NO se quitará.",
            "VersionNoteMany", "Se encontraron {0} archivos con el mismo nombre, pero ninguno es idéntico. Este archivo NO se quitará.",
            "UniqueNote", "No se encontró una copia idéntica en la carpeta ACTUAL. Este archivo permanece en la carpeta ANTIGUA.",
            "LanguageRestart", "LegacySift se reiniciará para aplicar el nuevo idioma. Los resultados actuales se borrarán.",
            "LanguageRestartTitle", "Cambiar idioma",
            "SafetyParentMissing", "LegacySift no puede determinar dónde crear la carpeta de seguridad.",
            "OldFileMissingNow", "El archivo de la carpeta antigua ya no existe.",
            "CurrentCopyMissingNow", "El archivo correspondiente de la carpeta actual ya no existe.",
            "ChangedSize", "El tamaño del archivo cambió después de la comparación. El archivo quedó sin tocar.",
            "ChangedHash", "Los dos archivos ya no son idénticos. El archivo antiguo quedó sin tocar.",
            "SafetyDestinationExists", "Ya existe un archivo con la misma ruta en la carpeta de seguridad.",
            "SafetyVerificationFailed", "Falló la verificación después de mover el archivo a la carpeta de seguridad. LegacySift intentó restaurar automáticamente el archivo original.",
            "MovedSafety", "Movido a la carpeta de seguridad y verificado.",
            "MovedRecycle", "Movido a la Papelera de Windows.",
            "SafetyFolderMissing", "No se encontró la carpeta de seguridad.",
            "RestoreNoOverwrite", "NO sobrescrito: {0}",
            "SessionMissing", "Falta LegacySift.session, por lo que no es posible la restauración automática.",
            "SessionInvalid", "La sesión de la carpeta de seguridad no es válida: falta la ruta original de la carpeta antigua.",
            "TabRecoverHelp", "No se encontró una copia idéntica en ACTUAL. Estos archivos permanecen en la carpeta ANTIGUA.",
            "TabVersionsHelp", "En ACTUAL existe el mismo nombre, pero el contenido es diferente. Estos archivos permanecen en la carpeta ANTIGUA.",
            "TabDuplicatesHelp", "Ya existe una copia idéntica en ACTUAL. Solo estos archivos de la carpeta ANTIGUA pueden quitarse durante la limpieza.",
            "TabProblemsHelp", "LegacySift no pudo verificar estos archivos con seguridad. Permanecen en la carpeta ANTIGUA.",
            "CheckingNow", "Comprobando las dos carpetas… no se está modificando ningún archivo.",
            "CleanupBeforeAnalysis", "Primero ejecuta la comprobación. Después LegacySift mostrará exactamente qué se puede quitar de la carpeta ANTIGUA y qué permanecerá allí.",
            "CleanupWaitForAnalysis", "Espera a que termine la comprobación. La limpieza está desactivada mientras LegacySift lee las carpetas.",
            "CleanupExplanation", "Después de la limpieza, la carpeta ANTIGUA conservará {0} archivos no encontrados en ACTUAL, {1} posibles versiones diferentes y {2} archivos no comprobados. Solo las {3} copias idénticas se quitarán de ANTIGUA.",
            "AfterCleanupSummary", "Limpieza completada: {0} copias idénticas quitadas de ANTIGUA; {1} elementos quedaron sin tocar por seguridad. Vuelve a comprobar para ver exactamente qué queda.",
            "CleanupNeedsNewCheck", "La limpieza ha terminado. Vuelve a ejecutar la comprobación para ver solo lo que queda en la carpeta ANTIGUA.",
            "HelpText", "LEGACYSIFT — GUÍA RÁPIDA\n\nPARA QUÉ SIRVE\nLegacySift está pensado para migraciones de ordenador, discos antiguos y copias de seguridad recuperadas. Elige la carpeta ANTIGUA y la carpeta ACTUAL que usas hoy. LegacySift muestra qué falta en ACTUAL y qué copias exactas ya tienes.\n\nLA DIRECCIÓN NUNCA CAMBIA\nCARPETA ANTIGUA = se puede limpiar.\nCARPETA ACTUAL = protegida, solo para comparar. LegacySift nunca la limpia.\n\nCÓMO SE USA\n1. Elige la CARPETA ANTIGUA.\n2. Elige la CARPETA ACTUAL.\n3. Pulsa COMPRUEBA LO QUE YA TIENES. Este paso no modifica nada.\n4. Lee los resultados.\n5. Si todo es correcto, quita de ANTIGUA solo las copias idénticas.\n\nQUÉ SIGNIFICAN LOS RESULTADOS\n• NO ESTÁN EN LA CARPETA ACTUAL: no existe una copia idéntica en ACTUAL. Estos archivos permanecen en ANTIGUA.\n• POSIBLES VERSIONES DIFERENTES: existe el mismo nombre, pero el contenido es distinto. Estos archivos permanecen en ANTIGUA.\n• COPIAS IDÉNTICAS: ya existe una copia exacta en ACTUAL. Solo estos archivos se pueden quitar de ANTIGUA.\n• ARCHIVOS NO COMPROBADOS: LegacySift no pudo verificarlos con seguridad. Permanecen en ANTIGUA.\n\nDESPUÉS DE LA LIMPIEZA\nLa carpeta ANTIGUA conserva los archivos no encontrados en ACTUAL, las posibles versiones diferentes y todo lo que LegacySift no pudo verificar con seguridad. Solo se quitan las copias idénticas.\n\nMÉTODO MÁS SEGURO\nUsa la CARPETA DE SEGURIDAD. Las copias idénticas se mueven a una carpeta separada y restaurable junto a ANTIGUA en lugar de borrarse definitivamente.\n\nSEGURIDAD TÉCNICA\nEl contenido exacto se compara con SHA-256 y se vuelve a comprobar antes de la limpieza. Se omiten enlaces y puntos de reanálisis. Se bloquean selecciones de carpetas anidadas. LegacySift no solicita permisos de administrador y funciona completamente en local.\n\nREGLA SIMPLE\nSi tienes dudas, detente después de la comprobación. Nada cambia hasta que inicies explícitamente la limpieza."
        );

        private static readonly Dictionary<string, string> Pt = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — limpe uma pasta antiga com segurança",
            "TabWork", "Comparar e limpar",
            "TabHelp", "Guia e segurança",
            "LanguageButton", "Idioma…",
            "Intro", "Pasta antiga à esquerda, pasta atual à direita. O LegacySift remove da pasta ANTIGA apenas os ficheiros dos quais já existe uma cópia idêntica na pasta ATUAL.",
            "OldTitle", "1. PASTA ANTIGA",
            "OldBadge", "ESTA PODE SER LIMPA",
            "OldDescription", "A pasta recuperada do computador antigo, disco ou cópia de segurança. Apenas este lado pode ser alterado pela limpeza.",
            "CurrentTitle", "2. PASTA ATUAL",
            "CurrentBadge", "PROTEGIDA • SÓ DE LEITURA",
            "CurrentDescription", "A pasta que utiliza hoje. O LegacySift apenas a lê para comparação e nunca a limpa.",
            "Browse", "Procurar…",
            "Direction", "Comparação: pasta ANTIGA → pasta ATUAL protegida. A verificação apenas lê os ficheiros e não altera nada.",
            "Analyze", "3. VERIFIQUE O QUE JÁ TEM — não altera nada",
            "Cancel", "Cancelar",
            "OpenReport", "Abrir último relatório",
            "NoAnalysis", "Escolha a pasta ANTIGA e a pasta ATUAL protegida e depois inicie a verificação.",
            "PathsChanged", "A seleção de uma pasta mudou. Execute novamente a verificação antes de limpar qualquer coisa.",
            "TabRecover", "NÃO PRESENTES NA PASTA ATUAL",
            "TabVersions", "POSSÍVEIS VERSÕES DIFERENTES",
            "TabDuplicates", "CÓPIAS IDÊNTICAS",
            "TabProblems", "FICHEIROS NÃO VERIFICADOS",
            "GridOld", "Ficheiro na pasta ANTIGA",
            "GridSize", "Tamanho",
            "GridCurrent", "Ficheiro correspondente na pasta ATUAL",
            "GridNote", "O que o LegacySift encontrou",
            "CleanupGroup", "4. LIMPAR A PASTA ANTIGA",
            "Quarantine", "Pasta de segurança (recomendado) — move para fora da ANTIGA as cópias idênticas e permite restaurá-las",
            "Recycle", "Reciclagem do Windows — envia para a Reciclagem as cópias idênticas da pasta ANTIGA",
            "OtherOptions", "Mostrar outras opções",
            "HideOptions", "Ocultar outras opções",
            "RemoveEmpty", "Remover as pastas que fiquem completamente vazias dentro da pasta ANTIGA",
            "Confirm", "Compreendo: APENAS a pasta ANTIGA será alterada. A pasta ATUAL permanecerá inalterada.",
            "Cleanup", "REMOVER CÓPIAS IDÊNTICAS DA PASTA ANTIGA",
            "Restore", "Restaurar ficheiros postos de lado…",
            "ProtectedReminder", "ATUAL permanece protegida",
            "Ready", "Pronto.",
            "ChooseOldDialog", "Escolha a pasta ANTIGA para verificar e limpar",
            "ChooseCurrentDialog", "Escolha a pasta ATUAL / PROTEGIDA",
            "AnalyzeDone", "Verificação concluída. Nenhum ficheiro foi alterado.",
            "AnalyzeCanceled", "Verificação cancelada. Nenhum ficheiro foi alterado.",
            "AnalyzeErrorTitle", "Problema durante a verificação",
            "AnalyzeErrorStatus", "A verificação parou devido a um problema. Não foi efetuada qualquer limpeza.",
            "PathCheckTitle", "LegacySift — verificar seleção de pastas",
            "CleanupConfirmTitle", "Confirmar limpeza da pasta ANTIGA",
            "CleanupConfirm", "Está prestes a limpar APENAS a pasta ANTIGA:\n\n{0}\n\nA pasta ATUAL está protegida e não será alterada:\n\n{1}\n\nRemovidas da ANTIGA: {2} cópias idênticas.\nFicam na ANTIGA: {3} não presentes na ATUAL, {4} possíveis versões diferentes, {5} não verificados.\n\nMétodo: {6}\n\nContinuar?",
            "ModeSafety", "PASTA DE SEGURANÇA (restaurável)",
            "ModeRecycle", "RECICLAGEM DO WINDOWS",
            "CleanupDoneStatus", "Concluído: {0} cópias idênticas foram removidas da pasta ANTIGA; {1} itens ficaram inalterados por segurança.",
            "CleanupDoneTitle", "LegacySift — concluído",
            "CleanupDone", "Limpeza concluída.\n\nRemovidas da pasta ANTIGA: {0} cópias idênticas\nMantidas por segurança: {1}{2}\n\nOs ficheiros não presentes na pasta ATUAL e as possíveis versões diferentes não foram tocados. Execute novamente a verificação para ver exatamente o que resta.",
            "CleanupSafetyLocation", "\n\nPasta de segurança:\n{0}\n\nNão a elimine até ter verificado os ficheiros que ficaram na pasta antiga.",
            "CleanupCanceled", "Limpeza interrompida. Os ficheiros já movidos permanecem na pasta de segurança / Reciclagem; os restantes não foram tocados.",
            "CleanupErrorTitle", "Problema durante a limpeza",
            "CleanupErrorStatus", "A limpeza parou devido a um problema. Verifique a pasta de segurança e faça uma nova comparação antes de tentar novamente.",
            "RestoreLast", "Restaurar a última pasta de segurança criada?\n\n{0}",
            "RestoreTitle", "Restaurar ficheiros",
            "RestoreChoose", "Escolha uma pasta __LegacySift_Safety_...",
            "RestoreConfirm", "O LegacySift tentará repor os ficheiros nas localizações originais dentro da pasta ANTIGA.\nOs ficheiros que já existirem NÃO serão substituídos.\n\nContinuar?",
            "RestoreConfirmTitle", "Confirmar restauro",
            "RestoreDoneStatus", "Restauro concluído: {0} ficheiros restaurados; {1} conflitos não foram substituídos.",
            "RestoreDone", "Restaurados: {0}\nConflitos NÃO substituídos: {1}\nErros: {2}",
            "RestoreCanceled", "Restauro interrompido.",
            "RestoreErrorTitle", "Problema durante o restauro",
            "Summary", "VERIFICAÇÃO CONCLUÍDA — nenhum ficheiro foi alterado.\n{0} não presentes na ATUAL   |   {1} possíveis versões diferentes   |   {2} cópias idênticas ({3})   |   {4} não verificados",
            "CleanupCount", "REMOVER {0} CÓPIAS IDÊNTICAS DA PASTA ANTIGA",
            "PhaseOldScan", "A ler pasta ANTIGA",
            "PhaseCurrentScan", "A ler pasta ATUAL protegida",
            "PhaseCompare", "A comparar conteúdo dos ficheiros",
            "PhaseSafety", "A mover ficheiros para a pasta de segurança",
            "PhaseRecycle", "A mover ficheiros para a Reciclagem",
            "PhaseRestoreRead", "A ler pasta de segurança",
            "PhaseRestore", "A restaurar ficheiros",
            "OldRequired", "Escolha primeiro a pasta ANTIGA.",
            "CurrentRequired", "Escolha a pasta ATUAL / PROTEGIDA.",
            "InvalidPath", "Caminho inválido: {0}",
            "OldMissing", "A pasta ANTIGA não existe.",
            "CurrentMissing", "A pasta ATUAL / PROTEGIDA não existe.",
            "SameFolder", "As duas seleções apontam para a mesma pasta. Operação bloqueada.",
            "OldRootBlocked", "Por segurança, a raiz inteira de uma unidade não pode ser usada como pasta ANTIGA.",
            "CurrentRootBlocked", "Por segurança, a raiz inteira de uma unidade não pode ser usada como pasta ATUAL.",
            "NestedBlocked", "Uma pasta selecionada está dentro da outra. Escolha duas pastas separadas.",
            "SystemFolderBlocked", "Por segurança, o LegacySift não limpa diretamente uma pasta principal do sistema Windows.",
            "OutsideOld", "Falha na verificação de segurança: este ficheiro não está dentro da pasta ANTIGA.",
            "ReparseDir", "Pasta ligada / ponto de reanálise ignorado por segurança.",
            "ReparseFile", "Ficheiro ligado / ponto de reanálise ignorado por segurança.",
            "ExactNote", "Existe uma cópia idêntica na pasta ATUAL. Esta cópia na pasta ANTIGA pode ser removida com segurança.",
            "VersionNoteOne", "Existe um ficheiro com o mesmo nome na pasta atual, mas o conteúdo é diferente. Este ficheiro NÃO será removido.",
            "VersionNoteMany", "Foram encontrados {0} ficheiros com o mesmo nome, mas nenhum é idêntico. Este ficheiro NÃO será removido.",
            "UniqueNote", "Não foi encontrada uma cópia idêntica na pasta ATUAL. Este ficheiro permanece na pasta ANTIGA.",
            "LanguageRestart", "O LegacySift será reiniciado para aplicar o novo idioma. Os resultados atuais serão apagados.",
            "LanguageRestartTitle", "Alterar idioma",
            "SafetyParentMissing", "O LegacySift não consegue determinar onde criar a pasta de segurança.",
            "OldFileMissingNow", "O ficheiro na pasta antiga já não existe.",
            "CurrentCopyMissingNow", "O ficheiro correspondente na pasta atual já não existe.",
            "ChangedSize", "O tamanho do ficheiro mudou após a comparação. O ficheiro ficou inalterado.",
            "ChangedHash", "Os dois ficheiros já não são idênticos. O ficheiro antigo ficou inalterado.",
            "SafetyDestinationExists", "Já existe um ficheiro com o mesmo caminho na pasta de segurança.",
            "SafetyVerificationFailed", "A verificação após a deslocação para a pasta de segurança falhou. O LegacySift tentou restaurar automaticamente o ficheiro original.",
            "MovedSafety", "Movido para a pasta de segurança e verificado.",
            "MovedRecycle", "Movido para a Reciclagem do Windows.",
            "SafetyFolderMissing", "Pasta de segurança não encontrada.",
            "RestoreNoOverwrite", "NÃO substituído: {0}",
            "SessionMissing", "Falta o ficheiro LegacySift.session; o restauro automático não é possível.",
            "SessionInvalid", "A sessão da pasta de segurança é inválida: falta o caminho original da pasta antiga.",
            "TabRecoverHelp", "Não foi encontrada uma cópia idêntica na ATUAL. Estes ficheiros permanecem na pasta ANTIGA.",
            "TabVersionsHelp", "Existe o mesmo nome na ATUAL, mas o conteúdo é diferente. Estes ficheiros permanecem na pasta ANTIGA.",
            "TabDuplicatesHelp", "Já existe uma cópia idêntica na ATUAL. Apenas estes ficheiros da pasta ANTIGA podem ser removidos pela limpeza.",
            "TabProblemsHelp", "O LegacySift não conseguiu verificar estes ficheiros com segurança. Permanecem na pasta ANTIGA.",
            "CheckingNow", "A verificar as duas pastas… nenhum ficheiro está a ser alterado.",
            "CleanupBeforeAnalysis", "Execute primeiro a verificação. Depois o LegacySift mostrará exatamente o que pode ser removido da pasta ANTIGA e o que ficará lá.",
            "CleanupWaitForAnalysis", "Aguarde o fim da verificação. A limpeza está desativada enquanto o LegacySift lê as pastas.",
            "CleanupExplanation", "Após a limpeza, a pasta ANTIGA manterá {0} ficheiros não presentes na ATUAL, {1} possíveis versões diferentes e {2} ficheiros não verificados. Apenas as {3} cópias idênticas serão removidas da ANTIGA.",
            "AfterCleanupSummary", "Limpeza concluída: {0} cópias idênticas removidas da ANTIGA; {1} itens ficaram inalterados por segurança. Execute novamente a verificação para ver exatamente o que resta.",
            "CleanupNeedsNewCheck", "A limpeza terminou. Execute novamente a verificação para ver apenas o que resta na pasta ANTIGA.",
            "HelpText", "LEGACYSIFT — GUIA RÁPIDO\n\nPARA QUE SERVE\nO LegacySift foi criado para migrações de computadores, discos antigos e cópias de segurança recuperadas. Escolha a pasta ANTIGA e a pasta ATUAL que utiliza hoje. O LegacySift mostra o que falta na ATUAL e quais cópias exatas já possui.\n\nA DIREÇÃO NUNCA MUDA\nPASTA ANTIGA = pode ser limpa.\nPASTA ATUAL = protegida, apenas para comparação. O LegacySift nunca a limpa.\n\nCOMO UTILIZAR\n1. Escolha a PASTA ANTIGA.\n2. Escolha a PASTA ATUAL.\n3. Clique em VERIFIQUE O QUE JÁ TEM. Este passo não altera nada.\n4. Leia os resultados.\n5. Se estiver tudo correto, remova da ANTIGA apenas as cópias idênticas.\n\nO QUE SIGNIFICAM OS RESULTADOS\n• NÃO PRESENTES NA PASTA ATUAL: não existe uma cópia idêntica na ATUAL. Estes ficheiros permanecem na ANTIGA.\n• POSSÍVEIS VERSÕES DIFERENTES: existe o mesmo nome, mas o conteúdo é diferente. Estes ficheiros permanecem na ANTIGA.\n• CÓPIAS IDÊNTICAS: já existe uma cópia exata na ATUAL. Apenas estes ficheiros podem ser removidos da ANTIGA.\n• FICHEIROS NÃO VERIFICADOS: o LegacySift não conseguiu verificá-los com segurança. Permanecem na ANTIGA.\n\nAPÓS A LIMPEZA\nA pasta ANTIGA mantém os ficheiros não encontrados na ATUAL, as possíveis versões diferentes e tudo o que o LegacySift não conseguiu verificar com segurança. Apenas as cópias idênticas são removidas.\n\nMÉTODO MAIS SEGURO\nUtilize a PASTA DE SEGURANÇA. As cópias idênticas são movidas para uma pasta separada e restaurável ao lado da ANTIGA em vez de serem eliminadas definitivamente.\n\nSEGURANÇA TÉCNICA\nO conteúdo exato é comparado com SHA-256 e verificado novamente antes da limpeza. Ligações e pontos de reanálise são ignorados. Seleções de pastas aninhadas são bloqueadas. O LegacySift não pede privilégios de administrador e funciona totalmente em local.\n\nREGRA SIMPLES\nSe tiver dúvidas, pare após a verificação. Nada muda até iniciar explicitamente a limpeza."
        );
    }
}
