using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Nb = Make(
            "AppTitle", "LegacySift 0.2.2-alpha – rydd trygt i en gammel mappe",
            "TabWork", "Sammenlign og rydd",
            "TabHelp", "Veiledning og sikkerhet",
            "LanguageButton", "Språk…",
            "Intro", "Gammel mappe til venstre. Gjeldende mappe til høyre. LegacySift fjerner kun filer fra den GAMLE mappen dersom de allerede er identiske i den GJELDENDE mappen.",
            "OldTitle", "1. GAMMEL MAPPE",
            "OldBadge", "HER KAN DET RYDDES",
            "OldDescription", "Mappen hentet fra den gamle datamaskinen, disken eller sikkerhetskopien. Kun denne siden kan endres ved opprydding.",
            "CurrentTitle", "2. GJELDENDE MAPPE",
            "CurrentBadge", "BESKYTTET • SKRIVBESKYTTET",
            "CurrentDescription", "Mappen du bruker i dag. LegacySift leser den kun for sammenligning og gjør aldri endringer i den.",
            "Browse", "Bla gjennom…",
            "Direction", "Sammenlign GAMMEL mappe → GJELDENDE beskyttet mappe. Kontrollen leser kun filer;ingenting endres.",
            "Analyze", "3. SJEKK HVA DU ALLEREDE HAR – endrer ingenting",
            "Cancel", "Avbryt",
            "OpenReport", "Åpne siste rapport",
            "NoAnalysis", "Velg den GAMLE mappen og den GJELDENDE beskyttede mappen, og kjør deretter kontrollen.",
            "PathsChanged", "Et mappevalg er endret. Kjør kontrollen på nytt før du utfører opprydding.",
            "TabRecover", "IKKE FUNNET I GJELDENDE",
            "TabVersions", "MULIGE ULIKE VERSJONER",
            "TabDuplicates", "IDENTISKE KOPIER",
            "TabProblems", "FILER IKKE KONTROLLERT",
            "GridOld", "Fil i GAMMEL mappe",
            "GridSize", "Størrelse",
            "GridCurrent", "Matchende fil i GJELDENDE mappe",
            "GridNote", "Hva LegacySift fant",
            "CleanupGroup", "4. RYDD I DEN GAMLE MAPPEN",
            "Quarantine", "Sikkerhetsmappe (anbefales) – flytt identiske kopier ut av GAMMEL mappe slik at de kan gjenopprettes",
            "Recycle", "Windows-papirkurv – send identiske kopier fra GAMMEL mappe til papirkurven",
            "OtherOptions", "Vis andre alternativer",
            "HideOptions", "Skjul andre alternativer",
            "RemoveEmpty", "Fjern mapper som står helt tomme inne i den GAMLE mappen",
            "Confirm", "Jeg forstår: KUN den GAMLE mappen vil bli endret. Den GJELDENDE mappen forblir uendret.",
            "Cleanup", "FJERN IDENTISKE KOPIER FRA DEN GAMLE MAPPEN",
            "Restore", "Gjenopprett filer som ble lagt til side…",
            "ProtectedReminder", "CURRENT forblir beskyttet",
            "Ready", "Klar.",
            "ChooseOldDialog", "Velg OLD-mappen som skal kontrolleres og ryddes",
            "ChooseCurrentDialog", "Velg CURRENT / PROTECTED-mappen",
            "AnalyzeDone", "Kontroll fullført. Ingen filer ble endret.",
            "AnalyzeCanceled", "Kontroll avbrutt. Ingen filer ble endret.",
            "AnalyzeErrorTitle", "Problem under kontrollen",
            "AnalyzeErrorStatus", "Kontrollen stoppet på grunn av et problem. Ingen opprydding ble utført.",
            "PathCheckTitle", "LegacySift – kontroller mappeutvalget",
            "CleanupConfirmTitle", "Bekreft opprydding av OLD-mappen",
            "CleanupConfirm", "Du er i ferd med å rydde KUN OLD-mappen:\\n\\n{0}\\n\\nCURRENT-mappen er beskyttet og vil ikke bli endret:\\n\\n{1}\\n\\nFjernet fra OLD: {2} identiske kopier.\\nIgjen i OLD: {3} ikke funnet i CURRENT, {4} mulige ulike versjoner, {5} ikke kontrollert.\\n\\nMetode: {6}\\n\\nFortsette?",
            "ModeSafety", "SIKKERHETSmappe (kan gjenopprettes)",
            "ModeRecycle", "Windows-papirkurv",
            "CleanupDoneStatus", "Ferdig: {0} identiske kopier ble fjernet fra OLD-mappen;{1} kandidater ble latt være i fred av sikkerhetshensyn.",
            "CleanupDoneTitle", "LegacySift – fullført",
            "CleanupDone", "Opprydding fullført.\\n\\nFjernet fra OLD-mappen: {0} identiske kopier\\nBeholdt av sikkerhetshensyn: {1}{2}\\n\\nFiler som ikke ble funnet i CURRENT, samt mulige ulike versjoner, ble ikke rørt. Kjør kontrollen på nytt for å se nøyaktig hva som gjenstår.",
            "CleanupSafetyLocation", "\n\nSikkerhetsmappe:\n{0}\n\nIkke slett den før du har kontrollert filene som er igjen i den gamle mappen.",
            "CleanupCanceled", "Opprydding stoppet. Filer som allerede er flyttet, ligger i sikkerhetsmappen / papirkurven;gjenværende filer ble ikke rørt.",
            "CleanupErrorTitle", "Problem under opprydding",
            "CleanupErrorStatus", "Opprydding stoppet på grunn av et problem. Kontroller sikkerhetsmappen og kjør en ny sammenligning før du prøver igjen.",
            "RestoreLast", "Gjenopprette den sist opprettede sikkerhetsmappen?\n\n{0}",
            "RestoreTitle", "Gjenopprett filer",
            "RestoreChoose", "Velg en __LegacySift_Safety_...-mappe",
            "RestoreConfirm", "LegacySift vil prøve å flytte filer tilbake til de opprinnelige plasseringene i OLD-mappen. Filer som allerede finnes der, blir IKKE overskrevet. Fortsette?",
            "RestoreConfirmTitle", "Bekreft gjenoppretting",
            "RestoreDoneStatus", "Gjenoppretting fullført: {0} filer gjenopprettet;{1} konflikter ble ikke overskrevet.",
            "RestoreDone", "Gjenopprettet: {0}  Konflikter IKKE overskrevet: {1}  Feil: {2}",
            "RestoreCanceled", "Gjenoppretting stoppet.",
            "RestoreErrorTitle", "Problem under gjenoppretting",
            "Summary", "KONTROLL FULLFØRT – ingen filer ble endret.\\n{0} ikke funnet i CURRENT   |{1} mulige ulike versjoner   |{2} identiske kopier ({3})   |{4} ikke kontrollert",
            "CleanupCount", "FJERN IDENTISKE KOPIER AV {0} FRA DEN GAMLE MAPPEN",
            "PhaseOldScan", "Leser den GAMLE mappen",
            "PhaseCurrentScan", "Leser den BESKYTTEDE mappen (CURRENT)",
            "PhaseCompare", "Sammenligner filinnhold",
            "PhaseSafety", "Flytter filer til sikkerhetsmappen",
            "PhaseRecycle", "Flytter filer til papirkurven",
            "PhaseRestoreRead", "Leser sikkerhetsmappen",
            "PhaseRestore", "Gjenoppretter filer",
            "OldRequired", "Velg den GAMLE mappen først.",
            "CurrentRequired", "Velg mappen CURRENT / BESKYTTET.",
            "InvalidPath", "Ugyldig bane: {0}",
            "OldMissing", "Den GAMLE mappen finnes ikke.",
            "CurrentMissing", "Mappen CURRENT / BESKYTTET finnes ikke.",
            "SameFolder", "De to valgene peker på samme mappe. Operasjonen er blokkert.",
            "OldRootBlocked", "Av sikkerhetshensyn kan ikke roten til en hel disk brukes som den GAMLE mappen.",
            "CurrentRootBlocked", "Av sikkerhetshensyn kan ikke roten til en hel disk brukes som mappen CURRENT.",
            "NestedBlocked", "En av de valgte mappene ligger inni den andre. Velg to separate mapper.",
            "SystemFolderBlocked", "Av sikkerhetshensyn vil ikke LegacySift rydde i en viktig systemmappe i Windows.",
            "OutsideOld", "Sikkerhetskontroll mislyktes: denne filen ligger ikke i den GAMLE mappen.",
            "ReparseDir", "Koblet mappe / reparse-punkt ble hoppet over av sikkerhetshensyn.",
            "ReparseFile", "Koblet fil / reparse-punkt ble hoppet over av sikkerhetshensyn.",
            "ExactNote", "En identisk kopi finnes i mappen CURRENT. Denne kopien fra den GAMLE mappen kan trygt fjernes.",
            "VersionNoteOne", "En fil med samme navn finnes i mappen CURRENT, men innholdet er forskjellig. Denne filen vil IKKE bli fjernet.",
            "VersionNoteMany", "Filer med samme navn ({0}) ble funnet, men ingen er identiske. Denne filen vil IKKE bli fjernet.",
            "UniqueNote", "Ingen identisk kopi ble funnet i mappen CURRENT. Denne filen blir værende i OLD-mappen.",
            "LanguageRestart", "LegacySift starter på nytt for å ta i bruk det nye språket. Eventuelle nåværende sammenligningsresultater slettes.",
            "LanguageRestartTitle", "Endre språk",
            "SafetyParentMissing", "LegacySift kan ikke avgjøre hvor sikkerhetsmappen skal opprettes.",
            "OldFileMissingNow", "Filen i den gamle mappen finnes ikke lenger.",
            "CurrentCopyMissingNow", "Den tilsvarende filen i den nåværende mappen finnes ikke lenger.",
            "ChangedSize", "Filstørrelsen endret seg etter sammenligningen. Filen ble ikke rørt.",
            "ChangedHash", "De to filene er ikke lenger identiske. Den gamle filen ble ikke rørt.",
            "SafetyDestinationExists", "En fil med samme bane finnes allerede i sikkerhetsmappen.",
            "SafetyVerificationFailed", "Verifisering av sikkerhetsmappen mislyktes etter flyttingen. LegacySift forsøkte å gjenopprette den opprinnelige filen automatisk.",
            "MovedSafety", "Flyttet til sikkerhetsmappen og verifisert.",
            "MovedRecycle", "Flyttet til papirkurven i Windows.",
            "SafetyFolderMissing", "Sikkerhetsmappen ble ikke funnet.",
            "RestoreNoOverwrite", "IKKE overskrevet: {0}",
            "SessionMissing", "LegacySift.session mangler, så automatisk gjenoppretting er ikke mulig.",
            "SessionInvalid", "Sesjonen for sikkerhetsmappen er ugyldig: banen til den opprinnelige gamle mappen mangler.",
            "TabRecoverHelp", "Ingen identisk kopi ble funnet i CURRENT. Disse filene blir værende i OLD-mappen.",
            "TabVersionsHelp", "En fil med samme navn finnes i CURRENT, men innholdet er forskjellig. Disse filene blir værende i OLD-mappen.",
            "TabDuplicatesHelp", "En identisk kopi finnes allerede i CURRENT. Bare disse filene i OLD-mappen kan fjernes ved opprydding.",
            "TabProblemsHelp", "LegacySift kunne ikke verifisere disse filene på en sikker måte. De blir værende i OLD-mappen.",
            "CheckingNow", "Kontrollerer de to mappene... ingen filer endres.",
            "CleanupBeforeAnalysis", "Kjør kontrollen først. Deretter vil LegacySift vise nøyaktig hva som kan fjernes fra OLD-mappen, og hva som blir værende der.",
            "CleanupWaitForAnalysis", "Vent til kontrollen er fullført. Opprydding er deaktivert mens LegacySift leser mappene.",
            "CleanupExplanation", "Etter opprydding vil OLD beholde {0}-filer som ikke finnes i CURRENT, {1}-filer som kan være ulike versjoner, og {2}-filer som ikke er kontrollert. Bare de identiske kopiene av typen {3} blir fjernet fra OLD.",
            "AfterCleanupSummary", "Opprydding fullført: Identiske kopier av typen {0} er fjernet fra OLD;kandidater av typen {1} er latt være i fred av sikkerhetshensyn. Kjør kontrollen på nytt for å se nøyaktig hva som gjenstår.",
            "CleanupNeedsNewCheck", "Oppryddingen er ferdig. Kjør kontrollen på nytt for å se hva som gjenstår i OLD-mappen.",
            "HelpText", "LEGACYSIFT — HURTIGVEILEDNING\\n\\nHVA PROGRAMMET GJØR\\nLegacySift er beregnet på datamaskinmigrering, gamle disker og gjenopprettede sikkerhetskopier. Velg mappen med eldre data (OLD) og mappen du bruker i dag (CURRENT). LegacySift viser hva som mangler i CURRENT, og hvilke identiske kopier du allerede har.\\n\\nRETNINGEN ER FASTLÅST\\nOLD-mappen = kan ryddes opp i.\\nCURRENT-mappen = beskyttet, kun for sammenligning. LegacySift gjør aldri endringer her.\\n\\nSLIK BRUKER DU DET\\n1. Velg OLD-mappen.\\n2. Velg CURRENT-mappen.\\n3. Klikk på «CHECK WHAT YOU ALREADY HAVE» (Sjekk hva du allerede har). Dette trinnet endrer ingenting.\\n4. Les resultatene.\\n5. Hvis resultatene gir mening, sletter du kun de identiske kopiene fra OLD-mappen.\\n\\nHVA RESULTATENE BETYR\\n• NOT FOUND IN CURRENT (Ikke funnet i CURRENT): Ingen identisk kopi finnes i CURRENT. Disse filene blir værende i OLD.\\n• POSSIBLE DIFFERENT VERSIONS (Mulige ulike versjoner): Samme filnavn finnes, men innholdet er ulikt. Disse filene blir værende i OLD.\\n• IDENTICAL COPIES ALREADY IN CURRENT (Identiske kopier finnes allerede i CURRENT): En nøyaktig kopi finnes i CURRENT. Kun disse filene fra OLD kan slettes.\\n• FILES NOT CHECKED (Filer ikke sjekket): LegacySift kunne ikke verifisere dem på en sikker måte. De blir værende i OLD.\\n\\nETTER OPPRYDDING\\nOLD-mappen sitter igjen med filene som ikke ble funnet i CURRENT, mulige ulike versjoner, og filer LegacySift ikke kunne verifisere sikkert. Kun nøyaktige kopier fjernes fra OLD-mappen.\\n\\nDEN SIKRESTE METODEN\\nBruk sikkerhetsmappen (Safety folder). Identiske kopier flyttes til en egen mappe ved siden av OLD-mappen – der de kan gjenopprettes – i stedet for å bli slettet permanent.\\n\\nTEKNISK SIKKERHET\\nDet faktiske innholdet verifiseres med SHA-256 og kontrolleres på nytt før opprydding. Koblede mapper / «reparse points» hoppes over. Valg av nøstede mapper er blokkert. LegacySift krever ikke administratorrettigheter og kjører utelukkende lokalt.\\n\\nENKEL REGEL\\nHvis du er usikker, stopp etter kontrollen. Ingenting endres før du uttrykkelig starter oppryddingen."
        );
    }
}
