using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Ko = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — 오래된 폴더를 안전하게 정리",
            "TabWork", "비교 및 정리",
            "TabHelp", "사용 안내 및 안전",
            "LanguageButton", "언어…",
            "Intro", "왼쪽은 이전 폴더, 오른쪽은 현재 폴더입니다. LegacySift는 현재 폴더에 이미 완전히 같은 복사본이 있는 파일만 이전 폴더에서 제거합니다.",
            "OldTitle", "1. 이전 폴더",
            "OldBadge", "이 폴더만 정리 가능",
            "OldDescription", "이전 컴퓨터, 디스크 또는 백업에서 복구한 폴더입니다. 정리 과정에서는 이쪽만 변경될 수 있습니다.",
            "CurrentTitle", "2. 현재 폴더",
            "CurrentBadge", "보호됨 • 읽기 전용",
            "CurrentDescription", "지금 사용하는 폴더입니다. LegacySift는 비교를 위해 읽기만 하며 절대 정리하지 않습니다.",
            "Browse", "찾아보기…",
            "Direction", "비교 방향: 이전 폴더 → 보호된 현재 폴더. 검사는 파일을 읽기만 하며 아무것도 변경하지 않습니다.",
            "Analyze", "3. 이미 있는 파일 확인 — 아무것도 변경하지 않음",
            "Cancel", "취소",
            "OpenReport", "최근 보고서 열기",
            "NoAnalysis", "이전 폴더와 보호된 현재 폴더를 선택한 뒤 검사를 시작하세요.",
            "PathsChanged", "폴더 선택이 변경되었습니다. 정리하기 전에 검사를 다시 실행하세요.",
            "TabRecover", "현재 폴더에 없음",
            "TabVersions", "다른 버전일 수 있음",
            "TabDuplicates", "완전히 같은 복사본",
            "TabProblems", "확인하지 못한 파일",
            "GridOld", "이전 폴더의 파일",
            "GridSize", "크기",
            "GridCurrent", "현재 폴더의 대응 파일",
            "GridNote", "LegacySift 확인 결과",
            "CleanupGroup", "4. 이전 폴더 정리",
            "Quarantine", "안전 폴더(권장) — 동일한 복사본을 이전 폴더 밖으로 옮겨 나중에 복원할 수 있게 함",
            "Recycle", "Windows 휴지통 — 이전 폴더의 동일한 복사본을 휴지통으로 보냄",
            "OtherOptions", "다른 옵션 보기",
            "HideOptions", "다른 옵션 숨기기",
            "RemoveEmpty", "이전 폴더 안에서 완전히 비게 된 폴더 제거",
            "Confirm", "이해했습니다. 이전 폴더만 변경되고 현재 폴더는 그대로 유지됩니다.",
            "Cleanup", "이전 폴더에서 동일한 복사본 제거",
            "Restore", "따로 보관한 파일 복원…",
            "ProtectedReminder", "현재 폴더는 계속 보호됩니다",
            "Ready", "준비됨.",
            "ChooseOldDialog", "검사하고 정리할 이전 폴더 선택",
            "ChooseCurrentDialog", "현재 / 보호된 폴더 선택",
            "AnalyzeDone", "검사가 완료되었습니다. 변경된 파일은 없습니다.",
            "AnalyzeCanceled", "검사가 취소되었습니다. 변경된 파일은 없습니다.",
            "AnalyzeErrorTitle", "검사 중 문제 발생",
            "AnalyzeErrorStatus", "문제로 인해 검사가 중단되었습니다. 정리는 수행되지 않았습니다.",
            "PathCheckTitle", "LegacySift — 폴더 선택 확인",
            "CleanupConfirmTitle", "이전 폴더 정리 확인",
            "CleanupConfirm", "이전 폴더만 정리하려고 합니다:\n\n{0}\n\n현재 폴더는 보호되며 변경되지 않습니다:\n\n{1}\n\n이전 폴더에서 제거: 동일한 복사본 {2}개.\n이전 폴더에 유지: 현재에 없는 파일 {3}개, 다른 버전일 수 있는 파일 {4}개, 확인하지 못한 파일 {5}개.\n\n방법: {6}\n\n계속할까요?",
            "ModeSafety", "안전 폴더(복원 가능)",
            "ModeRecycle", "WINDOWS 휴지통",
            "CleanupDoneStatus", "완료: 이전 폴더에서 동일한 복사본 {0}개를 제거했고, 안전을 위해 {1}개 항목은 그대로 두었습니다.",
            "CleanupDoneTitle", "LegacySift — 완료",
            "CleanupDone", "정리가 완료되었습니다.\n\n이전 폴더에서 제거: 동일한 복사본 {0}개\n안전을 위해 그대로 둠: {1}{2}\n\n현재 폴더에 없는 파일과 다른 버전일 수 있는 파일은 건드리지 않았습니다. 검사를 다시 실행하면 남은 파일을 정확히 볼 수 있습니다.",
            "CleanupSafetyLocation", "\n\n안전 폴더:\n{0}\n\n이전 폴더에 남은 파일을 확인할 때까지 이 폴더를 삭제하지 마세요.",
            "CleanupCanceled", "정리가 중단되었습니다. 이미 옮긴 파일은 안전 폴더 / 휴지통에 남아 있으며 나머지는 건드리지 않았습니다.",
            "CleanupErrorTitle", "정리 중 문제 발생",
            "CleanupErrorStatus", "문제로 인해 정리가 중단되었습니다. 다시 시도하기 전에 안전 폴더를 확인하고 새로 비교하세요.",
            "RestoreLast", "마지막으로 만든 안전 폴더를 복원할까요?\n\n{0}",
            "RestoreTitle", "파일 복원",
            "RestoreChoose", "__LegacySift_Safety_... 폴더 선택",
            "RestoreConfirm", "LegacySift가 파일을 이전 폴더의 원래 위치로 되돌립니다.\n그 위치에 이미 있는 파일은 덮어쓰지 않습니다.\n\n계속할까요?",
            "RestoreConfirmTitle", "복원 확인",
            "RestoreDoneStatus", "복원 완료: {0}개 파일 복원, {1}개 충돌은 덮어쓰지 않음.",
            "RestoreDone", "복원됨: {0}\n덮어쓰지 않은 충돌: {1}\n오류: {2}",
            "RestoreCanceled", "복원이 중단되었습니다.",
            "RestoreErrorTitle", "복원 중 문제 발생",
            "Summary", "검사 완료 — 변경된 파일 없음.\n현재에 없음 {0}개   |   다른 버전 가능 {1}개   |   동일한 복사본 {2}개({3})   |   미확인 {4}개",
            "CleanupCount", "이전 폴더에서 동일한 복사본 {0}개 제거",
            "PhaseOldScan", "이전 폴더 읽는 중",
            "PhaseCurrentScan", "보호된 현재 폴더 읽는 중",
            "PhaseCompare", "파일 내용 비교 중",
            "PhaseSafety", "안전 폴더로 파일 이동 중",
            "PhaseRecycle", "휴지통으로 파일 이동 중",
            "PhaseRestoreRead", "안전 폴더 읽는 중",
            "PhaseRestore", "파일 복원 중",
            "OldRequired", "먼저 이전 폴더를 선택하세요.",
            "CurrentRequired", "현재 / 보호된 폴더를 선택하세요.",
            "InvalidPath", "잘못된 경로: {0}",
            "OldMissing", "이전 폴더가 없습니다.",
            "CurrentMissing", "현재 / 보호된 폴더가 없습니다.",
            "SameFolder", "두 선택이 같은 폴더를 가리킵니다. 작업이 차단되었습니다.",
            "OldRootBlocked", "안전을 위해 드라이브 전체의 루트를 이전 폴더로 사용할 수 없습니다.",
            "CurrentRootBlocked", "안전을 위해 드라이브 전체의 루트를 현재 폴더로 사용할 수 없습니다.",
            "NestedBlocked", "선택한 폴더 하나가 다른 폴더 안에 있습니다. 서로 분리된 두 폴더를 선택하세요.",
            "SystemFolderBlocked", "안전을 위해 LegacySift는 Windows의 주요 시스템 폴더를 직접 정리하지 않습니다.",
            "OutsideOld", "안전 검사 실패: 이 파일은 이전 폴더 안에 없습니다.",
            "ReparseDir", "안전을 위해 연결된 폴더 / 재분석 지점을 건너뛰었습니다.",
            "ReparseFile", "안전을 위해 연결된 파일 / 재분석 지점을 건너뛰었습니다.",
            "ExactNote", "현재 폴더에 완전히 같은 복사본이 있습니다. 이전 폴더의 이 복사본은 안전하게 제거할 수 있습니다.",
            "VersionNoteOne", "현재 폴더에 이름은 같지만 내용이 다른 파일이 있습니다. 이 파일은 제거되지 않습니다.",
            "VersionNoteMany", "이름이 같은 파일 {0}개를 찾았지만 완전히 같은 파일은 없습니다. 이 파일은 제거되지 않습니다.",
            "UniqueNote", "현재 폴더에서 완전히 같은 복사본을 찾지 못했습니다. 이 파일은 이전 폴더에 남습니다.",
            "LanguageRestart", "새 언어를 적용하기 위해 LegacySift가 다시 시작됩니다. 현재 검사 결과는 지워집니다.",
            "LanguageRestartTitle", "언어 변경",
            "SafetyParentMissing", "LegacySift가 안전 폴더를 만들 위치를 정할 수 없습니다.",
            "OldFileMissingNow", "이전 폴더의 파일이 더 이상 없습니다.",
            "CurrentCopyMissingNow", "현재 폴더의 대응 파일이 더 이상 없습니다.",
            "ChangedSize", "비교 후 파일 크기가 변경되었습니다. 파일은 건드리지 않았습니다.",
            "ChangedHash", "두 파일이 더 이상 동일하지 않습니다. 이전 파일은 건드리지 않았습니다.",
            "SafetyDestinationExists", "안전 폴더의 같은 경로에 파일이 이미 있습니다.",
            "SafetyVerificationFailed", "안전 폴더로 옮긴 뒤 확인에 실패했습니다. LegacySift가 원본 파일을 자동으로 복원하려고 했습니다.",
            "MovedSafety", "안전 폴더로 이동하고 확인했습니다.",
            "MovedRecycle", "Windows 휴지통으로 이동했습니다.",
            "SafetyFolderMissing", "안전 폴더를 찾지 못했습니다.",
            "RestoreNoOverwrite", "덮어쓰지 않음: {0}",
            "SessionMissing", "LegacySift.session이 없어서 자동 복원이 불가능합니다.",
            "SessionInvalid", "안전 폴더 세션이 잘못되었습니다. 이전 폴더의 원래 경로가 없습니다.",
            "TabRecoverHelp", "현재 폴더에서 동일한 복사본을 찾지 못했습니다. 이 파일들은 이전 폴더에 남습니다.",
            "TabVersionsHelp", "현재 폴더에 같은 이름이 있지만 내용이 다릅니다. 이 파일들은 이전 폴더에 남습니다.",
            "TabDuplicatesHelp", "현재 폴더에 동일한 복사본이 이미 있습니다. 이전 폴더에서 이 파일들만 정리할 수 있습니다.",
            "TabProblemsHelp", "LegacySift가 이 파일들을 안전하게 확인하지 못했습니다. 이전 폴더에 남습니다.",
            "CheckingNow", "두 폴더를 검사하는 중… 어떤 파일도 변경하지 않습니다.",
            "CleanupBeforeAnalysis", "먼저 검사를 실행하세요. 그러면 LegacySift가 이전 폴더에서 제거할 수 있는 파일과 남을 파일을 정확히 보여 줍니다.",
            "CleanupWaitForAnalysis", "검사가 끝날 때까지 기다리세요. LegacySift가 폴더를 읽는 동안 정리는 비활성화됩니다.",
            "CleanupExplanation", "정리 후 이전 폴더에는 현재에 없는 파일 {0}개, 다른 버전일 수 있는 파일 {1}개, 확인하지 못한 파일 {2}개가 남습니다. 동일한 복사본 {3}개만 이전 폴더에서 제거됩니다.",
            "AfterCleanupSummary", "정리 완료: 이전 폴더에서 동일한 복사본 {0}개 제거, 안전을 위해 {1}개 항목 유지. 다시 검사하여 남은 파일을 정확히 확인하세요.",
            "CleanupNeedsNewCheck", "정리가 끝났습니다. 다시 검사하여 이전 폴더에 남은 파일만 확인하세요.",
            "HelpText", "LEGACYSIFT — 빠른 안내\n\n기능\nLegacySift는 컴퓨터 이전, 오래된 디스크 및 복구한 백업을 위한 도구입니다. 이전 폴더와 지금 사용하는 현재 폴더를 선택하세요. 현재 폴더에 없는 파일과 이미 가지고 있는 완전히 같은 복사본을 보여 줍니다.\n\n방향은 절대 바뀌지 않습니다\n이전 폴더 = 정리할 수 있습니다.\n현재 폴더 = 보호되며 비교에만 사용됩니다. LegacySift는 현재 폴더를 절대 정리하지 않습니다.\n\n사용 방법\n1. 이전 폴더를 선택합니다.\n2. 현재 폴더를 선택합니다.\n3. 이미 있는 파일 확인을 누릅니다. 이 단계에서는 아무것도 변경하지 않습니다.\n4. 결과를 읽습니다.\n5. 결과가 맞으면 이전 폴더에서 동일한 복사본만 제거합니다.\n\n결과의 의미\n• 현재 폴더에 없음: 동일한 복사본이 없습니다. 이전 폴더에 남습니다.\n• 다른 버전일 수 있음: 이름은 같지만 내용이 다릅니다. 이전 폴더에 남습니다.\n• 현재 폴더에 동일한 복사본 있음: 완전히 같은 복사본이 있습니다. 이전 폴더에서 이 파일들만 제거할 수 있습니다.\n• 확인하지 못한 파일: LegacySift가 안전하게 확인하지 못했습니다. 이전 폴더에 남습니다.\n\n정리 후\n현재 폴더에 없는 파일, 다른 버전일 수 있는 파일, 안전하게 확인하지 못한 모든 파일은 이전 폴더에 남습니다. 완전히 같은 복사본만 이전 폴더에서 제거됩니다.\n\n가장 안전한 방법\n안전 폴더를 사용하세요. 동일한 복사본을 영구 삭제하지 않고 이전 폴더 옆의 별도 복원 가능 폴더로 옮깁니다.\n\n기술적 안전\n파일 내용은 SHA-256으로 비교하고 정리 직전에 다시 확인합니다. 연결된 폴더와 재분석 지점은 건너뜁니다. 중첩된 폴더 선택은 차단됩니다. 관리자 권한을 요구하지 않으며 모든 작업은 이 컴퓨터에서만 수행됩니다.\n\n간단한 규칙\n확신이 없다면 검사 후 멈추세요. 정리를 직접 시작하기 전에는 아무것도 변경되지 않습니다."
        );
    }
}
