using System;
using System.Collections.Generic;
using System.Globalization;

namespace LegacySift
{
    internal enum AppLanguage
    {
        English,
        Italian
    }

    internal static class L10n
    {
        private static readonly Dictionary<string, string> En = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "AppTitle", "LegacySift 0.2.1-alpha — safely clean an old folder" },
            { "TabWork", "Compare and clean" },
            { "TabHelp", "Guide and safety" },
            { "LanguageButton", "Language…" },
            { "Intro", "Old folder on the left. Current folder on the right. LegacySift only removes from the OLD folder files that are already identical in the CURRENT folder." },
            { "OldTitle", "1. OLD FOLDER" },
            { "OldBadge", "THIS ONE MAY BE CLEANED" },
            { "OldDescription", "The recovered folder from the old computer, disk or backup. Only this side can be changed by cleanup." },
            { "CurrentTitle", "2. CURRENT FOLDER" },
            { "CurrentBadge", "PROTECTED • READ ONLY" },
            { "CurrentDescription", "The folder you use today. LegacySift reads it only for comparison and never cleans it." },
            { "Browse", "Browse…" },
            { "Direction", "Compare OLD folder → CURRENT protected folder. Checking only reads files; it changes nothing." },
            { "Analyze", "3. CHECK WHAT YOU ALREADY HAVE — changes nothing" },
            { "Cancel", "Cancel" },
            { "OpenReport", "Open last report" },
            { "NoAnalysis", "Choose the OLD folder and the CURRENT protected folder, then run the check." },
            { "PathsChanged", "A folder selection changed. Run the check again before cleaning anything." },
            { "TabRecover", "NOT FOUND IN CURRENT" },
            { "TabVersions", "POSSIBLE DIFFERENT VERSIONS" },
            { "TabDuplicates", "IDENTICAL COPIES" },
            { "TabProblems", "FILES NOT CHECKED" },
            { "GridOld", "File in OLD folder" },
            { "GridSize", "Size" },
            { "GridCurrent", "Matching file in CURRENT folder" },
            { "GridNote", "What LegacySift found" },
            { "CleanupGroup", "4. CLEAN THE OLD FOLDER" },
            { "Quarantine", "Safety folder (recommended) — move identical copies out of OLD so they can be restored" },
            { "Recycle", "Windows Recycle Bin — send identical OLD-folder copies to the Recycle Bin" },
            { "OtherOptions", "Show other options" },
            { "HideOptions", "Hide other options" },
            { "RemoveEmpty", "Remove folders left completely empty inside the OLD folder" },
            { "Confirm", "I understand: ONLY the OLD folder will be changed. The CURRENT folder will stay unchanged." },
            { "Cleanup", "REMOVE IDENTICAL COPIES FROM THE OLD FOLDER" },
            { "Restore", "Restore files put aside…" },
            { "ProtectedReminder", "CURRENT stays protected" },
            { "Ready", "Ready." },
            { "ChooseOldDialog", "Choose the OLD folder to check and clean" },
            { "ChooseCurrentDialog", "Choose the CURRENT / PROTECTED folder" },
            { "AnalyzeDone", "Check complete. No file was changed." },
            { "AnalyzeCanceled", "Check cancelled. No file was changed." },
            { "AnalyzeErrorTitle", "Problem during the check" },
            { "AnalyzeErrorStatus", "The check stopped because of a problem. No cleanup was performed." },
            { "PathCheckTitle", "LegacySift — check folder selection" },
            { "CleanupConfirmTitle", "Confirm cleaning the OLD folder" },
            { "CleanupConfirm", "You are about to clean ONLY the OLD folder:\n\n{0}\n\nThe CURRENT folder is protected and will not be changed:\n\n{1}\n\nRemoved from OLD: {2} identical copies.\nLeft in OLD: {3} not found in CURRENT, {4} possible different versions, {5} not checked.\n\nMethod: {6}\n\nContinue?" },
            { "ModeSafety", "SAFETY FOLDER (restorable)" },
            { "ModeRecycle", "WINDOWS RECYCLE BIN" },
            { "CleanupDoneStatus", "Done: {0} identical copies were removed from the OLD folder; {1} candidates were left untouched for safety." },
            { "CleanupDoneTitle", "LegacySift — completed" },
            { "CleanupDone", "Cleanup completed.\n\nRemoved from the OLD folder: {0} identical copies\nLeft in place for safety: {1}{2}\n\nFiles not found in CURRENT and possible different versions were not touched. Run the check again to see exactly what remains." },
            { "CleanupSafetyLocation", "\n\nSafety folder:\n{0}\n\nDo not delete it until you have checked the files left in the old folder." },
            { "CleanupCanceled", "Cleanup stopped. Files already moved stay in the safety folder / Recycle Bin; remaining files were not touched." },
            { "CleanupErrorTitle", "Problem during cleanup" },
            { "CleanupErrorStatus", "Cleanup stopped because of a problem. Check the safety folder and run a new comparison before trying again." },
            { "RestoreLast", "Restore the last safety folder created?\n\n{0}" },
            { "RestoreTitle", "Restore files" },
            { "RestoreChoose", "Choose a __LegacySift_Safety_... folder" },
            { "RestoreConfirm", "LegacySift will try to put files back in their original OLD-folder locations.\nFiles that already exist there will NOT be overwritten.\n\nContinue?" },
            { "RestoreConfirmTitle", "Confirm restore" },
            { "RestoreDoneStatus", "Restore complete: {0} files restored; {1} conflicts were not overwritten." },
            { "RestoreDone", "Restored: {0}\nConflicts NOT overwritten: {1}\nErrors: {2}" },
            { "RestoreCanceled", "Restore stopped." },
            { "RestoreErrorTitle", "Problem during restore" },
            { "Summary", "CHECK COMPLETE — no file was changed.\n{0} not found in CURRENT   |   {1} possible different versions   |   {2} identical copies ({3})   |   {4} not checked" },
            { "CleanupCount", "REMOVE {0} IDENTICAL COPIES FROM THE OLD FOLDER" },
            { "PhaseOldScan", "Reading OLD folder" },
            { "PhaseCurrentScan", "Reading CURRENT protected folder" },
            { "PhaseCompare", "Comparing file contents" },
            { "PhaseSafety", "Moving files to the safety folder" },
            { "PhaseRecycle", "Moving files to the Recycle Bin" },
            { "PhaseRestoreRead", "Reading safety folder" },
            { "PhaseRestore", "Restoring files" },
            { "OldRequired", "Choose the OLD folder first." },
            { "CurrentRequired", "Choose the CURRENT / PROTECTED folder." },
            { "InvalidPath", "Invalid path: {0}" },
            { "OldMissing", "The OLD folder does not exist." },
            { "CurrentMissing", "The CURRENT / PROTECTED folder does not exist." },
            { "SameFolder", "The two selections point to the same folder. Operation blocked." },
            { "OldRootBlocked", "For safety, a whole drive root cannot be used as the OLD folder." },
            { "CurrentRootBlocked", "For safety, a whole drive root cannot be used as the CURRENT folder." },
            { "NestedBlocked", "One selected folder is inside the other. Choose two separate folders." },
            { "SystemFolderBlocked", "For safety, LegacySift will not clean a main Windows system folder." },
            { "OutsideOld", "Safety check failed: this file is not inside the OLD folder." },
            { "ReparseDir", "Linked folder / reparse point skipped for safety." },
            { "ReparseFile", "Linked file / reparse point skipped for safety." },
            { "ExactNote", "An identical copy exists in the CURRENT folder. This OLD-folder copy can be removed safely." },
            { "VersionNoteOne", "A file with the same name exists in the current folder, but its contents are different. This file will NOT be removed." },
            { "VersionNoteMany", "{0} files with the same name were found, but none is identical. This file will NOT be removed." },
            { "UniqueNote", "No identical copy was found in the CURRENT folder. This file stays in the OLD folder." },
            { "LanguageRestart", "LegacySift will restart to apply the new language. Any current comparison results will be cleared." },
            { "LanguageRestartTitle", "Change language" },
            { "SafetyParentMissing", "LegacySift cannot determine where to create the safety folder." },
            { "OldFileMissingNow", "The file in the old folder no longer exists." },
            { "CurrentCopyMissingNow", "The matching file in the current folder no longer exists." },
            { "ChangedSize", "File size changed after the comparison. The file was left untouched." },
            { "ChangedHash", "The two files are no longer identical. The old file was left untouched." },
            { "SafetyDestinationExists", "A file with the same path already exists in the safety folder." },
            { "SafetyVerificationFailed", "Safety-folder verification failed after the move. LegacySift attempted to restore the original file automatically." },
            { "MovedSafety", "Moved to the safety folder and verified." },
            { "MovedRecycle", "Moved to the Windows Recycle Bin." },
            { "SafetyFolderMissing", "Safety folder not found." },
            { "RestoreNoOverwrite", "NOT overwritten: {0}" },
            { "SessionMissing", "LegacySift.session is missing, so automatic restore is not possible." },
            { "SessionInvalid", "The safety-folder session is invalid: the original old-folder path is missing." },
            { "TabRecoverHelp", "No identical copy was found in CURRENT. These files stay in the OLD folder." },
            { "TabVersionsHelp", "A file with the same name exists in CURRENT, but the contents differ. These files stay in the OLD folder." },
            { "TabDuplicatesHelp", "An identical copy already exists in CURRENT. Only these OLD-folder files can be removed by cleanup." },
            { "TabProblemsHelp", "LegacySift could not safely verify these files. They stay in the OLD folder." },
            { "CheckingNow", "Checking the two folders… no file is being changed." },
            { "CleanupBeforeAnalysis", "First run the check. Then LegacySift will show exactly what can be removed from the OLD folder and what will stay there." },
            { "CleanupWaitForAnalysis", "Wait for the check to finish. Cleanup is disabled while LegacySift is reading the folders." },
            { "CleanupExplanation", "After cleanup, OLD will keep {0} files not found in CURRENT, {1} possible different versions and {2} files not checked. Only the {3} identical copies will be removed from OLD." },
            { "AfterCleanupSummary", "Cleanup completed: {0} identical copies removed from OLD; {1} candidates left untouched for safety. Run the check again to see exactly what remains." },
            { "CleanupNeedsNewCheck", "Cleanup has finished. Run the check again to see only what remains in the OLD folder." },
            { "HelpText", "LEGACYSIFT — QUICK GUIDE\n\nWHAT IT DOES\nLegacySift is for computer migrations, old disks and recovered backups. Choose the OLD folder and the CURRENT folder you use today. LegacySift shows what is missing from CURRENT and which exact copies you already have.\n\nTHE DIRECTION NEVER CHANGES\nOLD FOLDER = may be cleaned.\nCURRENT FOLDER = protected, comparison only. LegacySift never cleans it.\n\nHOW TO USE IT\n1. Choose OLD FOLDER.\n2. Choose CURRENT FOLDER.\n3. Click CHECK WHAT YOU ALREADY HAVE. This step changes nothing.\n4. Read the results.\n5. If they make sense, remove only the identical copies from OLD.\n\nWHAT THE RESULTS MEAN\n• NOT FOUND IN CURRENT: no identical copy exists in CURRENT. These files stay in OLD.\n• POSSIBLE DIFFERENT VERSIONS: the same name exists, but the contents differ. These files stay in OLD.\n• IDENTICAL COPIES ALREADY IN CURRENT: an exact copy exists in CURRENT. Only these OLD files can be removed.\n• FILES NOT CHECKED: LegacySift could not verify them safely. They stay in OLD.\n\nAFTER CLEANUP\nThe OLD folder is left with the files that were not found in CURRENT, possible different versions, and anything LegacySift could not safely verify. Exact copies are the only files removed from OLD.\n\nSAFEST METHOD\nUse the Safety folder. Exact copies are moved to a separate, restorable folder beside OLD instead of being permanently deleted.\n\nTECHNICAL SAFETY\nExact content is checked with SHA-256 and is checked again before cleanup. Linked folders/reparse points are skipped. Nested folder selections are blocked. LegacySift does not request administrator privileges and works entirely locally.\n\nSIMPLE RULE\nIf you are unsure, stop after the check. Nothing changes until you explicitly start cleanup." },
        };

        private static readonly Dictionary<string, string> It = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "AppTitle", "LegacySift 0.2.1-alpha — ripulisci in sicurezza una vecchia cartella" },
            { "TabWork", "Confronta e ripulisci" },
            { "TabHelp", "Guida e sicurezza" },
            { "LanguageButton", "Lingua…" },
            { "Intro", "Vecchia cartella a sinistra, cartella attuale a destra. LegacySift toglie dalla VECCHIA cartella solo i file di cui esiste già una copia identica nella cartella ATTUALE." },
            { "OldTitle", "1. VECCHIA CARTELLA" },
            { "OldBadge", "QUESTA PUÒ ESSERE RIPULITA" },
            { "OldDescription", "La cartella recuperata dal vecchio computer, disco o backup. Solo questo lato può essere modificato dalla pulizia." },
            { "CurrentTitle", "2. CARTELLA ATTUALE" },
            { "CurrentBadge", "PROTETTA • SOLA LETTURA" },
            { "CurrentDescription", "La cartella che usi oggi. LegacySift la legge solo per il confronto e non la ripulisce mai." },
            { "Browse", "Sfoglia…" },
            { "Direction", "Confronto: VECCHIA cartella → cartella ATTUALE protetta. Il controllo legge soltanto i file e non modifica nulla." },
            { "Analyze", "3. CONTROLLA COSA POSSIEDI GIÀ — non modifica nulla" },
            { "Cancel", "Annulla" },
            { "OpenReport", "Apri ultimo report" },
            { "NoAnalysis", "Scegli la VECCHIA cartella e la cartella ATTUALE protetta, poi avvia il controllo." },
            { "PathsChanged", "Hai cambiato una cartella. Esegui di nuovo il controllo prima di ripulire qualsiasi file." },
            { "TabRecover", "NON PRESENTI NELLA CARTELLA ATTUALE" },
            { "TabVersions", "POSSIBILI VERSIONI DIVERSE" },
            { "TabDuplicates", "COPIE IDENTICHE" },
            { "TabProblems", "FILE NON CONTROLLATI" },
            { "GridOld", "File nella VECCHIA cartella" },
            { "GridSize", "Dimensione" },
            { "GridCurrent", "File corrispondente nella cartella ATTUALE" },
            { "GridNote", "Cosa ha trovato LegacySift" },
            { "CleanupGroup", "4. RIPULISCI LA VECCHIA CARTELLA" },
            { "Quarantine", "Cartella di sicurezza (consigliata) — sposta fuori dalla VECCHIA le copie identiche e permette di ripristinarle" },
            { "Recycle", "Cestino di Windows — invia al Cestino le copie identiche della VECCHIA cartella" },
            { "OtherOptions", "Mostra altre opzioni" },
            { "HideOptions", "Nascondi altre opzioni" },
            { "RemoveEmpty", "Rimuovi le cartelle rimaste completamente vuote dentro la VECCHIA cartella" },
            { "Confirm", "Ho capito: verrà modificata SOLO la VECCHIA cartella. La cartella ATTUALE resterà invariata." },
            { "Cleanup", "TOGLI LE COPIE IDENTICHE DALLA VECCHIA CARTELLA" },
            { "Restore", "Ripristina file messi da parte…" },
            { "ProtectedReminder", "ATTUALE sempre protetta" },
            { "Ready", "Pronto." },
            { "ChooseOldDialog", "Seleziona la VECCHIA cartella da controllare e ripulire" },
            { "ChooseCurrentDialog", "Seleziona la cartella ATTUALE / PROTETTA" },
            { "AnalyzeDone", "Controllo completato. Nessun file è stato modificato." },
            { "AnalyzeCanceled", "Controllo annullato. Nessun file è stato modificato." },
            { "AnalyzeErrorTitle", "Problema durante il controllo" },
            { "AnalyzeErrorStatus", "Il controllo si è fermato per un problema. Non è stata eseguita nessuna pulizia." },
            { "PathCheckTitle", "LegacySift — controllo delle cartelle" },
            { "CleanupConfirmTitle", "Conferma pulizia della VECCHIA cartella" },
            { "CleanupConfirm", "Stai per ripulire SOLO la VECCHIA cartella:\n\n{0}\n\nLa cartella ATTUALE è protetta e non verrà modificata:\n\n{1}\n\nVerranno tolte dalla VECCHIA: {2} copie identiche.\nResteranno nella VECCHIA: {3} non presenti nell’ATTUALE, {4} possibili versioni diverse, {5} non controllati.\n\nMetodo: {6}\n\nContinuare?" },
            { "ModeSafety", "CARTELLA DI SICUREZZA (ripristinabile)" },
            { "ModeRecycle", "CESTINO DI WINDOWS" },
            { "CleanupDoneStatus", "Fatto: {0} copie identiche sono state tolte dalla VECCHIA cartella; {1} candidate sono rimaste al loro posto per sicurezza." },
            { "CleanupDoneTitle", "LegacySift — operazione completata" },
            { "CleanupDone", "Pulizia completata.\n\nTolte dalla VECCHIA cartella: {0} copie identiche\nLasciate al loro posto per sicurezza: {1}{2}\n\nI file non presenti nella cartella ATTUALE e le possibili versioni diverse non sono stati toccati. Esegui di nuovo il controllo per vedere esattamente cosa resta." },
            { "CleanupSafetyLocation", "\n\nCartella di sicurezza:\n{0}\n\nNon eliminarla finché non hai controllato i file rimasti nella vecchia cartella." },
            { "CleanupCanceled", "Pulizia interrotta. I file già spostati restano nella cartella di sicurezza / Cestino; gli altri non sono stati toccati." },
            { "CleanupErrorTitle", "Problema durante la pulizia" },
            { "CleanupErrorStatus", "La pulizia si è fermata per un problema. Controlla la cartella di sicurezza e rifai il confronto prima di riprovare." },
            { "RestoreLast", "Ripristinare l'ultima cartella di sicurezza creata?\n\n{0}" },
            { "RestoreTitle", "Ripristina file" },
            { "RestoreChoose", "Seleziona una cartella __LegacySift_Safety_..." },
            { "RestoreConfirm", "LegacySift proverà a rimettere i file nei percorsi originali della VECCHIA cartella.\nI file già presenti non verranno MAI sovrascritti.\n\nContinuare?" },
            { "RestoreConfirmTitle", "Conferma ripristino" },
            { "RestoreDoneStatus", "Ripristino completato: {0} file ripristinati; {1} conflitti non sovrascritti." },
            { "RestoreDone", "Ripristinati: {0}\nConflitti NON sovrascritti: {1}\nErrori: {2}" },
            { "RestoreCanceled", "Ripristino interrotto." },
            { "RestoreErrorTitle", "Problema durante il ripristino" },
            { "Summary", "CONTROLLO COMPLETATO — nessun file è stato modificato.\n{0} non presenti nell’ATTUALE   |   {1} possibili versioni diverse   |   {2} copie identiche ({3})   |   {4} non controllati" },
            { "CleanupCount", "TOGLI {0} COPIE IDENTICHE DALLA VECCHIA CARTELLA" },
            { "PhaseOldScan", "Lettura VECCHIA cartella" },
            { "PhaseCurrentScan", "Lettura cartella ATTUALE protetta" },
            { "PhaseCompare", "Confronto del contenuto dei file" },
            { "PhaseSafety", "Spostamento nella cartella di sicurezza" },
            { "PhaseRecycle", "Spostamento nel Cestino" },
            { "PhaseRestoreRead", "Lettura cartella di sicurezza" },
            { "PhaseRestore", "Ripristino dei file" },
            { "OldRequired", "Seleziona prima la VECCHIA cartella." },
            { "CurrentRequired", "Seleziona la cartella ATTUALE / PROTETTA." },
            { "InvalidPath", "Percorso non valido: {0}" },
            { "OldMissing", "La VECCHIA cartella non esiste." },
            { "CurrentMissing", "La cartella ATTUALE / PROTETTA non esiste." },
            { "SameFolder", "Le due selezioni indicano la stessa cartella. Operazione bloccata." },
            { "OldRootBlocked", "Per sicurezza non puoi usare l'intera radice di un disco come VECCHIA cartella." },
            { "CurrentRootBlocked", "Per sicurezza non puoi usare l'intera radice di un disco come cartella ATTUALE." },
            { "NestedBlocked", "Una cartella selezionata si trova dentro l'altra. Scegli due cartelle separate." },
            { "SystemFolderBlocked", "Per sicurezza LegacySift non ripulisce direttamente una delle principali cartelle di sistema di Windows." },
            { "OutsideOld", "Controllo di sicurezza fallito: questo file non appartiene alla VECCHIA cartella." },
            { "ReparseDir", "Cartella collegata / reparse point ignorata per sicurezza." },
            { "ReparseFile", "File collegato / reparse point ignorato per sicurezza." },
            { "ExactNote", "Nella cartella ATTUALE esiste una copia identica. Questa copia nella VECCHIA cartella può essere tolta in sicurezza." },
            { "VersionNoteOne", "Nella cartella attuale esiste un file con lo stesso nome, ma il contenuto è diverso. Questo file NON verrà rimosso." },
            { "VersionNoteMany", "Sono stati trovati {0} file con lo stesso nome, ma nessuno è identico. Questo file NON verrà rimosso." },
            { "UniqueNote", "Nella cartella ATTUALE non è stata trovata una copia identica. Questo file resta nella VECCHIA cartella." },
            { "LanguageRestart", "LegacySift verrà riavviato per applicare la nuova lingua. Gli eventuali risultati del controllo corrente verranno azzerati." },
            { "LanguageRestartTitle", "Cambia lingua" },
            { "SafetyParentMissing", "LegacySift non riesce a determinare dove creare la cartella di sicurezza." },
            { "OldFileMissingNow", "Il file nella vecchia cartella non esiste più." },
            { "CurrentCopyMissingNow", "Il file corrispondente nella cartella attuale non esiste più." },
            { "ChangedSize", "La dimensione del file è cambiata dopo il confronto. Il file è rimasto invariato." },
            { "ChangedHash", "I due file non sono più identici. Il file vecchio è rimasto invariato." },
            { "SafetyDestinationExists", "Nella cartella di sicurezza esiste già un file con lo stesso percorso." },
            { "SafetyVerificationFailed", "La verifica dopo lo spostamento nella cartella di sicurezza è fallita. LegacySift ha tentato di ripristinare automaticamente il file originale." },
            { "MovedSafety", "Spostato nella cartella di sicurezza e verificato." },
            { "MovedRecycle", "Spostato nel Cestino di Windows." },
            { "SafetyFolderMissing", "Cartella di sicurezza non trovata." },
            { "RestoreNoOverwrite", "NON sovrascritto: {0}" },
            { "SessionMissing", "Manca LegacySift.session: il ripristino automatico non è possibile." },
            { "SessionInvalid", "La sessione della cartella di sicurezza non è valida: manca il percorso originale della vecchia cartella." },
            { "TabRecoverHelp", "Nella cartella ATTUALE non è stata trovata una copia identica. Questi file resteranno nella VECCHIA cartella." },
            { "TabVersionsHelp", "Nella cartella ATTUALE esiste lo stesso nome, ma il contenuto è diverso. Questi file resteranno nella VECCHIA cartella." },
            { "TabDuplicatesHelp", "Nella cartella ATTUALE esiste già una copia identica. Solo questi file della VECCHIA cartella possono essere tolti dalla pulizia." },
            { "TabProblemsHelp", "LegacySift non è riuscito a verificare questi file in sicurezza. Resteranno nella VECCHIA cartella." },
            { "CheckingNow", "Controllo delle due cartelle in corso… nessun file viene modificato." },
            { "CleanupBeforeAnalysis", "Prima esegui il controllo. Poi LegacySift ti mostrerà esattamente cosa può essere tolto dalla VECCHIA cartella e cosa resterà lì." },
            { "CleanupWaitForAnalysis", "Attendi la fine del controllo. La pulizia è disattivata mentre LegacySift legge le cartelle." },
            { "CleanupExplanation", "Dopo la pulizia, nella VECCHIA cartella resteranno {0} file non presenti nell’ATTUALE, {1} possibili versioni diverse e {2} file non controllati. Solo le {3} copie identiche verranno tolte dalla VECCHIA cartella." },
            { "AfterCleanupSummary", "Pulizia completata: {0} copie identiche tolte dalla VECCHIA cartella; {1} candidate lasciate al loro posto per sicurezza. Esegui di nuovo il controllo per vedere esattamente cosa resta." },
            { "CleanupNeedsNewCheck", "La pulizia è terminata. Esegui di nuovo il controllo per vedere soltanto ciò che è rimasto nella VECCHIA cartella." },
            { "HelpText", "LEGACYSIFT — GUIDA RAPIDA\n\nA COSA SERVE\nLegacySift è pensato per migrazioni di computer, vecchi dischi e backup recuperati. Scegli la VECCHIA cartella e la cartella ATTUALE che usi oggi. LegacySift ti mostra cosa manca nella cartella ATTUALE e quali copie identiche possiedi già.\n\nIL VERSO NON CAMBIA MAI\nVECCHIA CARTELLA = può essere ripulita.\nCARTELLA ATTUALE = protetta, serve solo per il confronto. LegacySift non la ripulisce mai.\n\nCOME SI USA\n1. Scegli la VECCHIA CARTELLA.\n2. Scegli la CARTELLA ATTUALE.\n3. Premi CONTROLLA COSA POSSIEDI GIÀ. Questa fase non modifica nulla.\n4. Leggi i risultati.\n5. Se sono corretti, togli dalla VECCHIA cartella soltanto le copie identiche.\n\nCOSA SIGNIFICANO I RISULTATI\n• NON PRESENTI NELLA CARTELLA ATTUALE: non esiste una copia identica nell’ATTUALE. Questi file restano nella VECCHIA.\n• POSSIBILI VERSIONI DIVERSE: esiste lo stesso nome, ma il contenuto è diverso. Questi file restano nella VECCHIA.\n• COPIE IDENTICHE GIÀ NELLA CARTELLA ATTUALE: nell’ATTUALE esiste una copia esatta. Solo questi file possono essere tolti dalla VECCHIA.\n• FILE NON CONTROLLATI: LegacySift non è riuscito a verificarli in sicurezza. Restano nella VECCHIA.\n\nDOPO LA PULIZIA\nNella VECCHIA cartella restano i file non trovati nella cartella ATTUALE, le possibili versioni diverse e tutto ciò che LegacySift non ha potuto verificare in sicurezza. Le copie identiche sono gli unici file che vengono tolti dalla VECCHIA.\n\nMETODO PIÙ SICURO\nUsa la CARTELLA DI SICUREZZA. Le copie identiche vengono spostate in una cartella separata e ripristinabile accanto alla VECCHIA, invece di essere eliminate definitivamente.\n\nSICUREZZA TECNICA\nIl contenuto esatto viene confrontato con SHA-256 e ricontrollato prima della pulizia. Collegamenti e reparse point vengono ignorati. Le cartelle annidate vengono bloccate. LegacySift non richiede privilegi amministrativi e lavora completamente in locale.\n\nREGOLA SEMPLICE\nSe hai un dubbio, fermati dopo il controllo. Non cambia nulla finché non avvii esplicitamente la pulizia." },
        };

        public static AppLanguage CurrentLanguage { get; private set; } = DetectDefaultLanguage();

        public static void SetLanguage(AppLanguage language)
        {
            CurrentLanguage = language;
        }

        public static string T(string key, params object[] args)
        {
            string value;
            var dict = CurrentLanguage == AppLanguage.Italian ? It : En;
            if (!dict.TryGetValue(key, out value))
            {
                if (!En.TryGetValue(key, out value)) value = key;
            }
            return args != null && args.Length > 0 ? string.Format(CultureInfo.CurrentCulture, value, args) : value;
        }

        public static AppLanguage DetectDefaultLanguage()
        {
            return string.Equals(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName, "it", StringComparison.OrdinalIgnoreCase)
                ? AppLanguage.Italian
                : AppLanguage.English;
        }
    }
}
