using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Fi = Make(
            "AppTitle", "LegacySift 0.2.3-alpha – puhdista vanha kansio turvallisesti",
            "TabWork", "Vertaa ja puhdista",
            "TabHelp", "Ohje ja turvallisuus",
            "LanguageButton", "Kieli…",
            "Intro", "Vanha kansio vasemmalla. Nykyinen kansio oikealla. LegacySift poistaa VANHASTA kansiosta vain ne tiedostot, jotka ovat jo identtisiä NYKYISESSÄ kansiossa.",
            "OldTitle", "1. VANHA KANSIO",
            "OldBadge", "TÄMÄ VOIDAAN PUHDISTAA",
            "OldDescription", "Vanhasta tietokoneesta, levyltä tai varmuuskopiosta palautettu kansio. Vain tätä puolta voidaan muuttaa puhdistuksen yhteydessä.",
            "CurrentTitle", "2. NYKYINEN KANSIO",
            "CurrentBadge", "SUOJATTU • VAIN LUKUOIKEUS",
            "CurrentDescription", "Kansio, jota käytät nykyään. LegacySift lukee sitä vain vertailua varten eikä koskaan puhdista sitä.",
            "Browse", "Selaa…",
            "Direction", "Vertaa VANHAA kansiota → NYKYISTÄ suojattua kansiota. Tarkistus vain lukee tiedostoja;se ei muuta mitään.",
            "Analyze", "3. TARKISTA MITÄ SINULLA JO ON – ei muuta mitään",
            "Cancel", "Peruuta",
            "OpenReport", "Avaa viimeisin raportti",
            "NoAnalysis", "Valitse VANHA kansio ja NYKYINEN suojattu kansio ja suorita sitten tarkistus.",
            "PathsChanged", "Kansiovalinta muuttui. Suorita tarkistus uudelleen ennen puhdistamista.",
            "TabRecover", "EI LÖYDY NYKYISESTÄ",
            "TabVersions", "MAHDOLLISIA ERI VERSIOITA",
            "TabDuplicates", "IDENTTISIÄ KOPIOITA",
            "TabProblems", "TARKISTAMATTOMIA TIEDOSTOJA",
            "GridOld", "Tiedosto VANHASSA kansiossa",
            "GridSize", "Koko",
            "GridCurrent", "Vastaava tiedosto NYKYISESSÄ kansiossa",
            "GridNote", "Mitä LegacySift löysi",
            "CleanupGroup", "4. PUHDISTA VANHA KANSIO",
            "Quarantine", "Turvakansio (suositus) – siirrä identtiset kopiot pois VANHASTA kansiosta, jotta ne voidaan palauttaa",
            "Recycle", "Windowsin roskakori – lähetä VANHAN kansion identtiset kopiot roskakoriin",
            "OtherOptions", "Näytä muut vaihtoehdot",
            "HideOptions", "Piilota muut vaihtoehdot",
            "RemoveEmpty", "Poista VANHAN kansion sisällä täysin tyhjiksi jääneet kansiot",
            "Confirm", "Ymmärrän: VAIN VANHA kansio muuttuu. NYKYINEN kansio pysyy muuttumattomana.",
            "Cleanup", "POISTA IDENTTISET KOPIOT VANHASTA KANSIOSTA",
            "Restore", "Palauta sivuun siirretyt tiedostot…",
            "ProtectedReminder", "CURRENT-kansio pysyy suojattuna",
            "Ready", "Valmis.",
            "ChooseOldDialog", "Valitse OLD-kansio tarkistusta ja puhdistusta varten",
            "ChooseCurrentDialog", "Valitse CURRENT- / suojattu kansio",
            "AnalyzeDone", "Tarkistus valmis. Yhtäkään tiedostoa ei muutettu.",
            "AnalyzeCanceled", "Tarkistus peruutettu. Yhtäkään tiedostoa ei muutettu.",
            "AnalyzeErrorTitle", "Ongelma tarkistuksen aikana",
            "AnalyzeErrorStatus", "Tarkistus pysähtyi ongelman vuoksi. Puhdistusta ei suoritettu.",
            "PathCheckTitle", "LegacySift – kansion valinta",
            "CleanupConfirmTitle", "Vahvista OLD-kansion puhdistus",
            "CleanupConfirm", "Olet puhdistamassa VAIN OLD-kansion:\\n\\n{0}\\n\\nCURRENT-kansio on suojattu, eikä siihen tehdä muutoksia:\\n\\n{1}\\n\\nPoistettu OLD-kansiosta: {2} identtistä kopiota.\\nJätetty OLD-kansioon: {3} ei löytynyt CURRENT-kansiosta, {4} mahdollisesti eri versioita, {5} ei tarkistettu.\\n\\nMenetelmä: {6}\\n\\nJatka?",
            "ModeSafety", "TURVAKANSIO (palautettavissa)",
            "ModeRecycle", "Windowsin roskakori",
            "CleanupDoneStatus", "Valmis: {0} identtistä kopiota poistettiin OLD-kansiosta;{1} kohdetta jätettiin koskemattomiksi turvallisuussyistä.",
            "CleanupDoneTitle", "LegacySift – valmis",
            "CleanupDone", "Puhdistus valmis.\\n\\nPoistettu OLD-kansiosta: {0} identtistä kopiota\\nJätetty paikoilleen turvallisuussyistä: {1}{2}\\n\\nTiedostoihin, joita ei löytynyt CURRENT-kansiosta, sekä mahdollisiin eri versioihin ei koskettu. Suorita tarkistus uudelleen nähdäksesi tarkalleen, mitä on jäljellä.",
            "CleanupSafetyLocation", "\n\nTurvakansio:\n{0}\n\nÄlä poista sitä, ennen kuin olet tarkistanut vanhaan kansioon jääneet tiedostot.",
            "CleanupCanceled", "Puhdistus pysäytetty. Jo siirretyt tiedostot jäävät varmuuskopiokansioon / roskakoriin;jäljellä oleviin tiedostoihin ei koskettu.",
            "CleanupErrorTitle", "Ongelma puhdistuksen aikana",
            "CleanupErrorStatus", "Puhdistus pysäytettiin ongelman vuoksi. Tarkista varmuuskopiokansio ja suorita uusi vertailu ennen kuin yrität uudelleen.",
            "RestoreLast", "Palautetaanko viimeksi luotu turvakansio?\n\n{0}",
            "RestoreTitle", "Palauta tiedostot",
            "RestoreChoose", "Valitse __LegacySift_Safety_... -kansio",
            "RestoreConfirm", "LegacySift yrittää palauttaa tiedostot niiden alkuperäisiin sijainteihin vanhassa kansiossa. Siellä jo olevia tiedostoja ei ylikirjoiteta. Jatketaanko?",
            "RestoreConfirmTitle", "Vahvista palautus",
            "RestoreDoneStatus", "Palautus valmis: {0} tiedostoa palautettu;{1} ristiriitaa ei ylikirjoitettu.",
            "RestoreDone", "Palautettu: {0}  Ristiriitoja ei ylikirjoitettu: {1}  Virheitä: {2}",
            "RestoreCanceled", "Palautus pysäytetty.",
            "RestoreErrorTitle", "Ongelma palautuksen aikana",
            "Summary", "TARKISTUS VALMIS – yhtäkään tiedostoa ei muutettu.\\n{0} ei löytynyt CURRENT-kansiosta   |{1} mahdollisesti eri versioita   |{2} identtisiä kopioita ({3})   |{4} ei tarkistettu",
            "CleanupCount", "POISTA {0}-IDENTTISET KOPIOT VANHASTA KANSIOSTA",
            "PhaseOldScan", "Luetaan VANHAA kansiota",
            "PhaseCurrentScan", "Luetaan CURRENT-suojattua kansiota",
            "PhaseCompare", "Verrataan tiedostojen sisältöjä",
            "PhaseSafety", "Siirretään tiedostoja turvakansioon",
            "PhaseRecycle", "Siirretään tiedostoja roskakoriin",
            "PhaseRestoreRead", "Luetaan turvakansiota",
            "PhaseRestore", "Palautetaan tiedostoja",
            "OldRequired", "Valitse ensin VANHA kansio.",
            "CurrentRequired", "Valitse CURRENT / SUOJATTU kansio.",
            "InvalidPath", "Virheellinen polku: {0}",
            "OldMissing", "VANHAA kansiota ei ole olemassa.",
            "CurrentMissing", "CURRENT / SUOJATTUA kansiota ei ole olemassa.",
            "SameFolder", "Valinnat osoittavat samaan kansioon. Toiminto estetty.",
            "OldRootBlocked", "Turvallisuussyistä aseman juurikansiota ei voi käyttää VANHANA kansiona.",
            "CurrentRootBlocked", "Turvallisuussyistä aseman juurikansiota ei voi käyttää CURRENT-kansiona.",
            "NestedBlocked", "Toinen valituista kansioista on toisen sisällä. Valitse kaksi erillistä kansiota.",
            "SystemFolderBlocked", "Turvallisuussyistä LegacySift ei puhdista Windowsin pääjärjestelmäkansiota.",
            "OutsideOld", "Turvallisuustarkistus epäonnistui: tämä tiedosto ei ole VANHAN kansion sisällä.",
            "ReparseDir", "Linkitetty kansio / uudelleenjäsennyspiste ohitettu turvallisuussyistä.",
            "ReparseFile", "Linkitetty tiedosto / uudelleenjäsennyspiste ohitettu turvallisuussyistä.",
            "ExactNote", "CURRENT-kansiossa on identtinen kopio. Tämä VANHAN kansion kopio voidaan poistaa turvallisesti.",
            "VersionNoteOne", "CURRENT-kansiossa on samanniminen tiedosto, mutta sen sisältö on erilainen. Tätä tiedostoa EI poisteta.",
            "VersionNoteMany", "Löytyi samannimisiä {0}-tiedostoja, mutta yksikään ei ole identtinen. Tätä tiedostoa EI poisteta.",
            "UniqueNote", "CURRENT-kansiosta ei löytynyt identtistä kopiota. Tämä tiedosto jää OLD-kansioon.",
            "LanguageRestart", "LegacySift käynnistyy uudelleen uuden kielen ottamiseksi käyttöön. Nykyiset vertailutulokset tyhjennetään.",
            "LanguageRestartTitle", "Vaihda kieli",
            "SafetyParentMissing", "LegacySift ei pysty määrittämään, mihin varmuuskansio tulisi luoda.",
            "OldFileMissingNow", "Tiedostoa ei enää ole OLD-kansiossa.",
            "CurrentCopyMissingNow", "Vastaavaa tiedostoa ei enää ole CURRENT-kansiossa.",
            "ChangedSize", "Tiedostokoko muuttui vertailun jälkeen. Tiedosto jätettiin ennalleen.",
            "ChangedHash", "Tiedostot eivät ole enää identtisiä. Vanha tiedosto jätettiin ennalleen.",
            "SafetyDestinationExists", "Varmuuskansiossa on jo tiedosto, jolla on sama polku.",
            "SafetyVerificationFailed", "Varmuuskansion tarkistus epäonnistui siirron jälkeen. LegacySift yritti palauttaa alkuperäisen tiedoston automaattisesti.",
            "MovedSafety", "Siirretty varmuuskansioon ja tarkistettu.",
            "MovedRecycle", "Siirretty Windowsin roskakoriin.",
            "SafetyFolderMissing", "Varmuuskansiota ei löytynyt.",
            "RestoreNoOverwrite", "EI korvattu: {0}",
            "SessionMissing", "LegacySift.session-tiedosto puuttuu, joten automaattinen palautus ei ole mahdollista.",
            "SessionInvalid", "Varmuuskansion istunto on virheellinen: alkuperäinen OLD-kansion polku puuttuu.",
            "TabRecoverHelp", "CURRENT-kansiosta ei löytynyt identtistä kopiota. Nämä tiedostot jäävät OLD-kansioon.",
            "TabVersionsHelp", "CURRENT-kansiossa on samanniminen tiedosto, mutta sisältö poikkeaa. Nämä tiedostot jäävät OLD-kansioon.",
            "TabDuplicatesHelp", "CURRENT-kansiossa on jo identtinen kopio. Vain nämä OLD-kansion tiedostot voidaan poistaa siivouksen yhteydessä.",
            "TabProblemsHelp", "LegacySift ei voinut tarkistaa näitä tiedostoja luotettavasti. Ne jäävät OLD-kansioon.",
            "CheckingNow", "Tarkistetaan kansioita... yhtäkään tiedostoa ei muuteta.",
            "CleanupBeforeAnalysis", "Suorita ensin tarkistus. Sen jälkeen LegacySift näyttää tarkalleen, mitä OLD-kansiosta voidaan poistaa ja mikä sinne jää.",
            "CleanupWaitForAnalysis", "Odota tarkistuksen valmistumista. Siivoustoiminto on poissa käytöstä, kun LegacySift lukee kansioita.",
            "CleanupExplanation", "Siivouksen jälkeen OLD-kansioon jäävät tiedostot {0} (ei löydy CURRENT-kansiosta), {1} (mahdolliset eri versiot) ja {2} (tarkistamattomat tiedostot). Vain identtiset {3}-kopiot poistetaan OLD-kansiosta.",
            "AfterCleanupSummary", "Siivous valmis: identtiset {0}-kopiot poistettu OLD-kansiosta;{1}-ehdokkaat jätetty ennalleen turvallisuussyistä. Suorita tarkistus uudelleen nähdäksesi tarkalleen, mitä on jäljellä.",
            "CleanupNeedsNewCheck", "Siivous on päättynyt. Suorita tarkistus uudelleen nähdäksesi, mitä OLD-kansioon on jäänyt jäljelle.",
            "HelpText", "LEGACYSIFT — PIKAOPAS\\n\\nMITÄ OHJELMA TEKEE\\nLegacySift on tarkoitettu tietokoneiden välisiin siirtoihin, vanhoille levyille ja palautetuille varmuuskopioille. Valitse OLD-kansio (vanha aineisto) ja CURRENT-kansio (nykyinen käytössä oleva aineisto). LegacySift näyttää, mitä CURRENT-kansiosta puuttuu ja mitkä tiedostot ovat jo olemassa täsmälleen samoina kopioina.\\n\\nSUUNTA EI KOSKAAN MUUTU\\nOLD-KANSIO = voidaan siivota.\\nCURRENT-KANSIO = suojattu, vain vertailua varten. LegacySift ei koskaan muokkaa sitä.\\n\\nKÄYTTÖOHJE\\n1. Valitse OLD-KANSIO.\\n2. Valitse CURRENT-KANSIO.\\n3. Napsauta CHECK WHAT YOU ALREADY HAVE (Tarkista jo olemassa olevat). Tämä vaihe ei muuta mitään.\\n4. Lue tulokset.\\n5. Jos tulokset vaikuttavat oikeilta, poista OLD-kansiosta vain identtiset kopiot.\\n\\nTULOSTEN MERKITYS\\n• NOT FOUND IN CURRENT (Ei löydy CURRENT-kansiosta): identtistä kopiota ei ole CURRENT-kansiossa. Nämä tiedostot säilyvät OLD-kansiossa.\\n• POSSIBLE DIFFERENT VERSIONS (Mahdollisesti eri versioita): tiedostonimi on sama, mutta sisältö eroaa. Nämä tiedostot säilyvät OLD-kansiossa.\\n• IDENTICAL COPIES ALREADY IN CURRENT (Identtiset kopiot jo CURRENT-kansiossa): täsmällinen kopio on olemassa CURRENT-kansiossa. Vain nämä OLD-kansion tiedostot voidaan poistaa.\\n• FILES NOT CHECKED (Tiedostoja ei tarkistettu): LegacySift ei voinut varmistaa niitä turvallisesti. Ne säilyvät OLD-kansiossa.\\n\\nSIIVOUKSEN JÄLKEEN\\nOLD-kansioon jäävät tiedostot, joita ei löytynyt CURRENT-kansiosta, mahdolliset eri versiot sekä tiedostot, joita LegacySift ei voinut varmistaa turvallisesti. Vain täsmälliset kopiot poistetaan OLD-kansiosta.\\n\\nTURVALLISIN MENETELMÄ\\nKäytä Safety-kansiota. Täsmälliset kopiot siirretään erilliseen, palautettavissa olevaan kansioon OLD-kansion viereen sen sijaan, että ne poistettaisiin pysyvästi.\\n\\nTEKNINEN TURVALLISUUS\\nSisällön oikeellisuus varmistetaan SHA-256-tarkistussummalla, ja tarkistus toistetaan ennen puhdistusta. Linkitettyjä kansioita ja uudelleenjäsennyspisteitä (reparse points) ei käsitellä. Sisäkkäisten kansioiden valitseminen on estetty. LegacySift ei vaadi järjestelmänvalvojan oikeuksia ja toimii täysin paikallisesti.\\n\\nYKSINKERTAINEN SÄÄNTÖ\\nJos olet epävarma, lopeta tarkistuksen jälkeen. Mitään ei muuteta, ennen kuin käynnistät puhdistuksen erikseen."
        );
    }
}
