using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Da = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — ryd sikkert op i en gammel mappe",
            "TabWork", "Sammenlign og ryd op",
            "TabHelp", "Vejledning og sikkerhed",
            "LanguageButton", "Sprog…",
            "Intro", "Gammel mappe til venstre. Nuværende mappe til højre. LegacySift fjerner kun filer fra den GAMLE mappe, når der allerede findes en identisk kopi i den NUVÆRENDE mappe.",
            "OldTitle", "1. GAMMEL MAPPE",
            "OldBadge", "DENNE MÅ RYDDES OP",
            "OldDescription", "Mappen fra den gamle computer, disk eller sikkerhedskopi. Kun denne side kan ændres ved oprydning.",
            "CurrentTitle", "2. NUVÆRENDE MAPPE",
            "CurrentBadge", "BESKYTTET • SKRIVEBESKYTTET",
            "CurrentDescription", "Mappen, du bruger i dag. LegacySift læser den kun til sammenligning og rydder aldrig op i den.",
            "Browse", "Gennemse…",
            "Direction", "Sammenlign GAMMEL mappe → beskyttet NUVÆRENDE mappe. Kontrollen læser kun filer og ændrer intet.",
            "Analyze", "3. KONTROLLÉR HVAD DU ALLEREDE HAR — ændrer intet",
            "Cancel", "Annuller",
            "OpenReport", "Åbn seneste rapport",
            "NoAnalysis", "Vælg den GAMLE mappe og den beskyttede NUVÆRENDE mappe, og start derefter kontrollen.",
            "PathsChanged", "Et mappevalg er ændret. Kør kontrollen igen, før du rydder noget op.",
            "TabRecover", "IKKE FUNDET I NUVÆRENDE",
            "TabVersions", "MULIGE ANDRE VERSIONER",
            "TabDuplicates", "IDENTISKE KOPIER",
            "TabProblems", "FILER IKKE KONTROLLERET",
            "GridOld", "Fil i GAMMEL mappe",
            "GridSize", "Størrelse",
            "GridCurrent", "Tilsvarende fil i NUVÆRENDE mappe",
            "GridNote", "Det fandt LegacySift",
            "CleanupGroup", "4. RYD OP I DEN GAMLE MAPPE",
            "Quarantine", "Sikkerhedsmappe (anbefalet) — flyt identiske kopier ud af GAMMEL, så de kan gendannes",
            "Recycle", "Windows Papirkurv — send identiske kopier fra GAMMEL til Papirkurven",
            "OtherOptions", "Vis andre indstillinger",
            "HideOptions", "Skjul andre indstillinger",
            "RemoveEmpty", "Fjern mapper, der er helt tomme i den GAMLE mappe",
            "Confirm", "Jeg forstår: KUN den GAMLE mappe ændres. Den NUVÆRENDE mappe forbliver uændret.",
            "Cleanup", "FJERN IDENTISKE KOPIER FRA DEN GAMLE MAPPE",
            "Restore", "Gendan filer, der er lagt til side…",
            "ProtectedReminder", "NUVÆRENDE forbliver beskyttet",
            "Ready", "Klar.",
            "ChooseOldDialog", "Vælg den GAMLE mappe, der skal kontrolleres og ryddes op",
            "ChooseCurrentDialog", "Vælg den NUVÆRENDE / BESKYTTEDE mappe",
            "AnalyzeDone", "Kontrol fuldført. Ingen filer blev ændret.",
            "AnalyzeCanceled", "Kontrol annulleret. Ingen filer blev ændret.",
            "AnalyzeErrorTitle", "Problem under kontrollen",
            "AnalyzeErrorStatus", "Kontrollen stoppede på grund af et problem. Der blev ikke ryddet op.",
            "PathCheckTitle", "LegacySift — kontrollér mappevalg",
            "CleanupConfirmTitle", "Bekræft oprydning i den GAMLE mappe",
            "CleanupConfirm", "Du er ved at rydde op KUN i den GAMLE mappe:\n\n{0}\n\nDen NUVÆRENDE mappe er beskyttet og ændres ikke:\n\n{1}\n\nFjernes fra GAMMEL: {2} identiske kopier.\nBliver i GAMMEL: {3} ikke fundet i NUVÆRENDE, {4} mulige andre versioner, {5} ikke kontrolleret.\n\nMetode: {6}\n\nFortsæt?",
            "ModeSafety", "SIKKERHEDSMAPPE (kan gendannes)",
            "ModeRecycle", "WINDOWS PAPIRKURV",
            "CleanupDoneStatus", "Færdig: {0} identiske kopier blev fjernet fra den GAMLE mappe; {1} kandidater blev ikke ændret af hensyn til sikkerheden.",
            "CleanupDoneTitle", "LegacySift — fuldført",
            "CleanupDone", "Oprydning fuldført.\n\nFjernet fra den GAMLE mappe: {0} identiske kopier\nIkke ændret af hensyn til sikkerheden: {1}{2}\n\nFiler, der ikke blev fundet i NUVÆRENDE, og mulige andre versioner blev ikke rørt. Kør kontrollen igen for at se præcist, hvad der er tilbage.",
            "CleanupSafetyLocation", "\n\nSikkerhedsmappe:\n{0}\n\nSlet den ikke, før du har kontrolleret filerne, der er tilbage i den gamle mappe.",
            "CleanupCanceled", "Oprydning stoppet. Filer, der allerede er flyttet, bliver i sikkerhedsmappen/Papirkurven; de resterende filer blev ikke rørt.",
            "CleanupErrorTitle", "Problem under oprydning",
            "CleanupErrorStatus", "Oprydningen stoppede på grund af et problem. Kontrollér sikkerhedsmappen, og kør en ny sammenligning, før du prøver igen.",
            "RestoreLast", "Gendan den senest oprettede sikkerhedsmappe?\n\n{0}",
            "RestoreTitle", "Gendan filer",
            "RestoreChoose", "Vælg en __LegacySift_Safety_...-mappe",
            "RestoreConfirm", "LegacySift forsøger at lægge filerne tilbage på deres oprindelige placeringer i den GAMLE mappe.\nFiler, der allerede findes der, bliver IKKE overskrevet.\n\nFortsæt?",
            "RestoreConfirmTitle", "Bekræft gendannelse",
            "RestoreDoneStatus", "Gendannelse fuldført: {0} filer gendannet; {1} konflikter blev ikke overskrevet.",
            "RestoreDone", "Gendannet: {0}\nKonflikter IKKE overskrevet: {1}\nFejl: {2}",
            "RestoreCanceled", "Gendannelse stoppet.",
            "RestoreErrorTitle", "Problem under gendannelse",
            "Summary", "KONTROL FULDFØRT — ingen filer blev ændret.\n{0} ikke fundet i NUVÆRENDE   |   {1} mulige andre versioner   |   {2} identiske kopier ({3})   |   {4} ikke kontrolleret",
            "CleanupCount", "FJERN {0} IDENTISKE KOPIER FRA DEN GAMLE MAPPE",
            "PhaseOldScan", "Læser GAMMEL mappe",
            "PhaseCurrentScan", "Læser beskyttet NUVÆRENDE mappe",
            "PhaseCompare", "Sammenligner filindhold",
            "PhaseSafety", "Flytter filer til sikkerhedsmappen",
            "PhaseRecycle", "Flytter filer til Papirkurven",
            "PhaseRestoreRead", "Læser sikkerhedsmappe",
            "PhaseRestore", "Gendanner filer",
            "OldRequired", "Vælg først den GAMLE mappe.",
            "CurrentRequired", "Vælg den NUVÆRENDE / BESKYTTEDE mappe.",
            "InvalidPath", "Ugyldig sti: {0}",
            "OldMissing", "Den GAMLE mappe findes ikke.",
            "CurrentMissing", "Den NUVÆRENDE / BESKYTTEDE mappe findes ikke.",
            "SameFolder", "De to valg peger på den samme mappe. Handlingen er blokeret.",
            "OldRootBlocked", "Af sikkerhedshensyn kan roden af et helt drev ikke bruges som GAMMEL mappe.",
            "CurrentRootBlocked", "Af sikkerhedshensyn kan roden af et helt drev ikke bruges som NUVÆRENDE mappe.",
            "NestedBlocked", "Den ene valgte mappe ligger i den anden. Vælg to separate mapper.",
            "SystemFolderBlocked", "Af sikkerhedshensyn rydder LegacySift ikke op i en vigtig Windows-systemmappe.",
            "OutsideOld", "Sikkerhedskontrol mislykkedes: denne fil ligger ikke i den GAMLE mappe.",
            "ReparseDir", "Tilknyttet mappe/reparse point blev sprunget over af hensyn til sikkerheden.",
            "ReparseFile", "Tilknyttet fil/reparse point blev sprunget over af hensyn til sikkerheden.",
            "ExactNote", "Der findes en identisk kopi i den NUVÆRENDE mappe. Denne kopi i den GAMLE mappe kan fjernes sikkert.",
            "VersionNoteOne", "Der findes en fil med samme navn i den nuværende mappe, men indholdet er anderledes. Denne fil bliver IKKE fjernet.",
            "VersionNoteMany", "Der blev fundet {0} filer med samme navn, men ingen er identiske. Denne fil bliver IKKE fjernet.",
            "UniqueNote", "Der blev ikke fundet en identisk kopi i den NUVÆRENDE mappe. Denne fil bliver i den GAMLE mappe.",
            "LanguageRestart", "LegacySift genstarter for at anvende det nye sprog. Aktuelle sammenligningsresultater ryddes.",
            "LanguageRestartTitle", "Skift sprog",
            "SafetyParentMissing", "LegacySift kan ikke afgøre, hvor sikkerhedsmappen skal oprettes.",
            "OldFileMissingNow", "Filen i den gamle mappe findes ikke længere.",
            "CurrentCopyMissingNow", "Den tilsvarende fil i den nuværende mappe findes ikke længere.",
            "ChangedSize", "Filstørrelsen blev ændret efter sammenligningen. Filen blev ikke rørt.",
            "ChangedHash", "De to filer er ikke længere identiske. Den gamle fil blev ikke rørt.",
            "SafetyDestinationExists", "Der findes allerede en fil med samme sti i sikkerhedsmappen.",
            "SafetyVerificationFailed", "Kontrol af sikkerhedsmappen mislykkedes efter flytningen. LegacySift forsøgte automatisk at gendanne originalfilen.",
            "MovedSafety", "Flyttet til sikkerhedsmappen og kontrolleret.",
            "MovedRecycle", "Flyttet til Windows Papirkurv.",
            "SafetyFolderMissing", "Sikkerhedsmappen blev ikke fundet.",
            "RestoreNoOverwrite", "IKKE overskrevet: {0}",
            "SessionMissing", "LegacySift.session mangler, så automatisk gendannelse er ikke mulig.",
            "SessionInvalid", "Sikkerhedsmappens session er ugyldig: den oprindelige sti til den gamle mappe mangler.",
            "TabRecoverHelp", "Der blev ikke fundet en identisk kopi i NUVÆRENDE. Disse filer bliver i den GAMLE mappe.",
            "TabVersionsHelp", "Der findes en fil med samme navn i NUVÆRENDE, men indholdet er anderledes. Disse filer bliver i den GAMLE mappe.",
            "TabDuplicatesHelp", "Der findes allerede en identisk kopi i NUVÆRENDE. Kun disse filer i den GAMLE mappe kan fjernes ved oprydning.",
            "TabProblemsHelp", "LegacySift kunne ikke kontrollere disse filer sikkert. De bliver i den GAMLE mappe.",
            "CheckingNow", "Kontrollerer de to mapper… ingen filer ændres.",
            "CleanupBeforeAnalysis", "Kør først kontrollen. Derefter viser LegacySift præcist, hvad der kan fjernes fra den GAMLE mappe, og hvad der bliver der.",
            "CleanupWaitForAnalysis", "Vent på, at kontrollen bliver færdig. Oprydning er deaktiveret, mens LegacySift læser mapperne.",
            "CleanupExplanation", "Efter oprydning beholder GAMMEL {0} filer, der ikke findes i NUVÆRENDE, {1} mulige andre versioner og {2} filer, der ikke er kontrolleret. Kun de {3} identiske kopier fjernes fra GAMMEL.",
            "AfterCleanupSummary", "Oprydning fuldført: {0} identiske kopier fjernet fra GAMMEL; {1} kandidater blev ikke ændret af hensyn til sikkerheden. Kør kontrollen igen for at se præcist, hvad der er tilbage.",
            "CleanupNeedsNewCheck", "Oprydningen er afsluttet. Kør kontrollen igen for kun at se det, der er tilbage i den GAMLE mappe.",
            "HelpText", "LEGACYSIFT — HURTIG VEJLEDNING\n\nHVAD PROGRAMMET GØR\nLegacySift er beregnet til computerflytninger, gamle diske og gendannede sikkerhedskopier. Vælg den GAMLE mappe og den NUVÆRENDE mappe, du bruger i dag. LegacySift viser, hvad der mangler i NUVÆRENDE, og hvilke nøjagtige kopier du allerede har.\n\nRETNINGEN ÆNDRES ALDRIG\nGAMMEL MAPPE = må ryddes op.\nNUVÆRENDE MAPPE = beskyttet, kun til sammenligning. LegacySift rydder aldrig op i den.\n\nSÅDAN GØR DU\n1. Vælg GAMMEL MAPPE.\n2. Vælg NUVÆRENDE MAPPE.\n3. Klik på KONTROLLÉR HVAD DU ALLEREDE HAR. Dette trin ændrer intet.\n4. Læs resultaterne.\n5. Hvis de giver mening, skal du kun fjerne de identiske kopier fra GAMMEL.\n\nDET BETYDER RESULTATERNE\n• IKKE FUNDET I NUVÆRENDE: Der findes ingen identisk kopi i NUVÆRENDE. Disse filer bliver i GAMMEL.\n• MULIGE ANDRE VERSIONER: Det samme navn findes, men indholdet er anderledes. Disse filer bliver i GAMMEL.\n• IDENTISKE KOPIER ALLEREDE I NUVÆRENDE: Der findes en nøjagtig kopi i NUVÆRENDE. Kun disse GAMLE filer kan fjernes.\n• FILER IKKE KONTROLLERET: LegacySift kunne ikke kontrollere dem sikkert. De bliver i GAMMEL.\n\nEFTER OPRYDNING\nDen GAMLE mappe beholder filer, der ikke blev fundet i NUVÆRENDE, mulige andre versioner og alt, som LegacySift ikke kunne kontrollere sikkert. Nøjagtige kopier er de eneste filer, der fjernes fra GAMMEL.\n\nSIKRESTE METODE\nBrug sikkerhedsmappen. Nøjagtige kopier flyttes til en separat mappe ved siden af GAMMEL, hvorfra de kan gendannes, i stedet for at blive slettet permanent.\n\nTEKNISK SIKKERHED\nNøjagtigt indhold kontrolleres med SHA-256 og kontrolleres igen før oprydning. Tilknyttede mapper/reparse points springes over. Indlejrede mappevalg blokeres. LegacySift kræver ikke administratorrettigheder og arbejder helt lokalt.\n\nENKEL REGEL\nHvis du er i tvivl, skal du stoppe efter kontrollen. Intet ændres, før du udtrykkeligt starter oprydningen."
        );
    }
}
