using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Sv = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — rensa en gammal mapp säkert",
            "TabWork", "Jämför och rensa",
            "TabHelp", "Guide och säkerhet",
            "LanguageButton", "Språk…",
            "Intro", "Den GAMLA mappen är till vänster och den AKTUELLA till höger. LegacySift tar bara bort filer från den GAMLA mappen när en identisk kopia redan finns i den AKTUELLA.",
            "OldTitle", "1. GAMMAL MAPP",
            "OldBadge", "DEN HÄR FÅR RENSAS",
            "OldDescription", "Mappen som återställts från den gamla datorn, disken eller säkerhetskopian. Bara den här sidan kan ändras av rensningen.",
            "CurrentTitle", "2. AKTUELL MAPP",
            "CurrentBadge", "SKYDDAD • ENDAST LÄSNING",
            "CurrentDescription", "Mappen du använder i dag. LegacySift läser den bara för jämförelse och rensar den aldrig.",
            "Browse", "Bläddra…",
            "Direction", "Jämförelse: GAMMAL mapp → skyddad AKTUELL mapp. Kontrollen läser bara filer och ändrar ingenting.",
            "Analyze", "3. KONTROLLERA VAD DU REDAN HAR — ändrar ingenting",
            "Cancel", "Avbryt",
            "OpenReport", "Öppna senaste rapporten",
            "NoAnalysis", "Välj den GAMLA mappen och den skyddade AKTUELLA mappen och starta sedan kontrollen.",
            "PathsChanged", "Ett mappval ändrades. Kör kontrollen igen innan du rensar något.",
            "TabRecover", "SAKNAS I AKTUELL MAPP",
            "TabVersions", "MÖJLIGA ANDRA VERSIONER",
            "TabDuplicates", "IDENTISKA KOPIOR",
            "TabProblems", "FILER SOM INTE KONTROLLERATS",
            "GridOld", "Fil i den GAMLA mappen",
            "GridSize", "Storlek",
            "GridCurrent", "Motsvarande fil i den AKTUELLA mappen",
            "GridNote", "Vad LegacySift hittade",
            "CleanupGroup", "4. RENSA DEN GAMLA MAPPEN",
            "Quarantine", "Säkerhetsmapp (rekommenderas) — flytta identiska kopior ur GAMMAL så att de kan återställas",
            "Recycle", "Windows Papperskorg — skicka identiska kopior från den GAMLA mappen till Papperskorgen",
            "OtherOptions", "Visa fler alternativ",
            "HideOptions", "Dölj fler alternativ",
            "RemoveEmpty", "Ta bort mappar som blivit helt tomma i den GAMLA mappen",
            "Confirm", "Jag förstår: ENDAST den GAMLA mappen ändras. Den AKTUELLA mappen förblir oförändrad.",
            "Cleanup", "TA BORT IDENTISKA KOPIOR FRÅN DEN GAMLA MAPPEN",
            "Restore", "Återställ undanlagda filer…",
            "ProtectedReminder", "Den AKTUELLA mappen förblir skyddad",
            "Ready", "Klar.",
            "ChooseOldDialog", "Välj den GAMLA mappen som ska kontrolleras och rensas",
            "ChooseCurrentDialog", "Välj den AKTUELLA / SKYDDADE mappen",
            "AnalyzeDone", "Kontrollen är klar. Ingen fil ändrades.",
            "AnalyzeCanceled", "Kontrollen avbröts. Ingen fil ändrades.",
            "AnalyzeErrorTitle", "Problem under kontrollen",
            "AnalyzeErrorStatus", "Kontrollen stoppades av ett problem. Ingen rensning utfördes.",
            "PathCheckTitle", "LegacySift — kontrollera mappval",
            "CleanupConfirmTitle", "Bekräfta rensning av den GAMLA mappen",
            "CleanupConfirm", "Du är på väg att rensa ENDAST den GAMLA mappen:\n\n{0}\n\nDen AKTUELLA mappen är skyddad och ändras inte:\n\n{1}\n\nTas bort från GAMMAL: {2} identiska kopior.\nBlir kvar i GAMMAL: {3} som saknas i AKTUELL, {4} möjliga andra versioner, {5} ej kontrollerade.\n\nMetod: {6}\n\nFortsätta?",
            "ModeSafety", "SÄKERHETSMAPP (kan återställas)",
            "ModeRecycle", "WINDOWS PAPPERSKORG",
            "CleanupDoneStatus", "Klart: {0} identiska kopior togs bort från den GAMLA mappen; {1} objekt lämnades orörda för säkerhets skull.",
            "CleanupDoneTitle", "LegacySift — klart",
            "CleanupDone", "Rensningen är klar.\n\nBorttaget från den GAMLA mappen: {0} identiska kopior\nLämnat kvar för säkerhets skull: {1}{2}\n\nFiler som saknas i AKTUELL och möjliga andra versioner rördes inte. Kör kontrollen igen för att se exakt vad som finns kvar.",
            "CleanupSafetyLocation", "\n\nSäkerhetsmapp:\n{0}\n\nTa inte bort den förrän du har kontrollerat filerna som finns kvar i den gamla mappen.",
            "CleanupCanceled", "Rensningen stoppades. Filer som redan flyttats ligger kvar i säkerhetsmappen / Papperskorgen; övriga filer rördes inte.",
            "CleanupErrorTitle", "Problem under rensningen",
            "CleanupErrorStatus", "Rensningen stoppades av ett problem. Kontrollera säkerhetsmappen och gör en ny jämförelse innan du försöker igen.",
            "RestoreLast", "Återställa den senast skapade säkerhetsmappen?\n\n{0}",
            "RestoreTitle", "Återställ filer",
            "RestoreChoose", "Välj en __LegacySift_Safety_...-mapp",
            "RestoreConfirm", "LegacySift försöker lägga tillbaka filerna på deras ursprungliga platser i den GAMLA mappen.\nFiler som redan finns där skrivs INTE över.\n\nFortsätta?",
            "RestoreConfirmTitle", "Bekräfta återställning",
            "RestoreDoneStatus", "Återställningen är klar: {0} filer återställdes; {1} konflikter skrevs inte över.",
            "RestoreDone", "Återställda: {0}\nKonflikter som INTE skrevs över: {1}\nFel: {2}",
            "RestoreCanceled", "Återställningen stoppades.",
            "RestoreErrorTitle", "Problem under återställningen",
            "Summary", "KONTROLLEN ÄR KLAR — ingen fil ändrades.\n{0} saknas i AKTUELL   |   {1} möjliga andra versioner   |   {2} identiska kopior ({3})   |   {4} ej kontrollerade",
            "CleanupCount", "TA BORT {0} IDENTISKA KOPIOR FRÅN DEN GAMLA MAPPEN",
            "PhaseOldScan", "Läser den GAMLA mappen",
            "PhaseCurrentScan", "Läser den skyddade AKTUELLA mappen",
            "PhaseCompare", "Jämför filinnehåll",
            "PhaseSafety", "Flyttar filer till säkerhetsmappen",
            "PhaseRecycle", "Flyttar filer till Papperskorgen",
            "PhaseRestoreRead", "Läser säkerhetsmappen",
            "PhaseRestore", "Återställer filer",
            "OldRequired", "Välj den GAMLA mappen först.",
            "CurrentRequired", "Välj den AKTUELLA / SKYDDADE mappen.",
            "InvalidPath", "Ogiltig sökväg: {0}",
            "OldMissing", "Den GAMLA mappen finns inte.",
            "CurrentMissing", "Den AKTUELLA / SKYDDADE mappen finns inte.",
            "SameFolder", "De två valen pekar på samma mapp. Åtgärden blockerades.",
            "OldRootBlocked", "Av säkerhetsskäl kan roten på en hel enhet inte användas som GAMMAL mapp.",
            "CurrentRootBlocked", "Av säkerhetsskäl kan roten på en hel enhet inte användas som AKTUELL mapp.",
            "NestedBlocked", "Den ena valda mappen ligger inuti den andra. Välj två separata mappar.",
            "SystemFolderBlocked", "Av säkerhetsskäl rensar LegacySift inte en viktig systemmapp i Windows direkt.",
            "OutsideOld", "Säkerhetskontrollen misslyckades: filen ligger inte i den GAMLA mappen.",
            "ReparseDir", "Länkad mapp / reparse point hoppades över av säkerhetsskäl.",
            "ReparseFile", "Länkad fil / reparse point hoppades över av säkerhetsskäl.",
            "ExactNote", "En identisk kopia finns i den AKTUELLA mappen. Den här kopian i GAMMAL kan tas bort säkert.",
            "VersionNoteOne", "En fil med samma namn finns i den aktuella mappen, men innehållet skiljer sig. Filen tas INTE bort.",
            "VersionNoteMany", "{0} filer med samma namn hittades, men ingen är identisk. Filen tas INTE bort.",
            "UniqueNote", "Ingen identisk kopia hittades i den AKTUELLA mappen. Filen stannar i den GAMLA mappen.",
            "LanguageRestart", "LegacySift startas om för att använda det nya språket. Nuvarande kontrollresultat rensas.",
            "LanguageRestartTitle", "Byt språk",
            "SafetyParentMissing", "LegacySift kan inte avgöra var säkerhetsmappen ska skapas.",
            "OldFileMissingNow", "Filen i den gamla mappen finns inte längre.",
            "CurrentCopyMissingNow", "Den motsvarande filen i den aktuella mappen finns inte längre.",
            "ChangedSize", "Filstorleken ändrades efter jämförelsen. Filen lämnades orörd.",
            "ChangedHash", "Filerna är inte längre identiska. Den gamla filen lämnades orörd.",
            "SafetyDestinationExists", "En fil med samma sökväg finns redan i säkerhetsmappen.",
            "SafetyVerificationFailed", "Kontrollen efter flytten till säkerhetsmappen misslyckades. LegacySift försökte återställa originalfilen automatiskt.",
            "MovedSafety", "Flyttad till säkerhetsmappen och verifierad.",
            "MovedRecycle", "Flyttad till Windows Papperskorg.",
            "SafetyFolderMissing", "Säkerhetsmappen hittades inte.",
            "RestoreNoOverwrite", "INTE överskriven: {0}",
            "SessionMissing", "LegacySift.session saknas, så automatisk återställning är inte möjlig.",
            "SessionInvalid", "Säkerhetsmappens session är ogiltig: den gamla mappens ursprungliga sökväg saknas.",
            "TabRecoverHelp", "Ingen identisk kopia hittades i AKTUELL. Filerna stannar i den GAMLA mappen.",
            "TabVersionsHelp", "Samma namn finns i AKTUELL, men innehållet skiljer sig. Filerna stannar i den GAMLA mappen.",
            "TabDuplicatesHelp", "En identisk kopia finns redan i AKTUELL. Bara dessa filer i den GAMLA mappen kan tas bort.",
            "TabProblemsHelp", "LegacySift kunde inte verifiera filerna säkert. De stannar i den GAMLA mappen.",
            "CheckingNow", "De två mapparna kontrolleras… ingen fil ändras.",
            "CleanupBeforeAnalysis", "Kör kontrollen först. Sedan visar LegacySift exakt vad som kan tas bort från GAMMAL och vad som blir kvar.",
            "CleanupWaitForAnalysis", "Vänta tills kontrollen är klar. Rensning är avstängd medan LegacySift läser mapparna.",
            "CleanupExplanation", "Efter rensningen behåller GAMMAL {0} filer som saknas i AKTUELL, {1} möjliga andra versioner och {2} ej kontrollerade filer. Bara de {3} identiska kopiorna tas bort från GAMMAL.",
            "AfterCleanupSummary", "Rensningen är klar: {0} identiska kopior togs bort från GAMMAL; {1} objekt lämnades orörda för säkerhets skull. Kör kontrollen igen för att se exakt vad som finns kvar.",
            "CleanupNeedsNewCheck", "Rensningen är klar. Kör kontrollen igen för att bara se det som finns kvar i den GAMLA mappen.",
            "HelpText", "LEGACYSIFT — SNABBGUIDE\n\nVAD DET GÖR\nLegacySift är avsett för datorflyttar, gamla diskar och återställda säkerhetskopior. Välj den GAMLA mappen och den AKTUELLA mappen du använder i dag. LegacySift visar vad som saknas i AKTUELL och vilka exakta kopior du redan har.\n\nRIKTNINGEN ÄNDRAS ALDRIG\nGAMMAL MAPP = får rensas.\nAKTUELL MAPP = skyddad, endast för jämförelse. LegacySift rensar den aldrig.\n\nSÅ HÄR GÖR DU\n1. Välj GAMMAL MAPP.\n2. Välj AKTUELL MAPP.\n3. Klicka på KONTROLLERA VAD DU REDAN HAR. Detta ändrar ingenting.\n4. Läs resultaten.\n5. Om de stämmer, ta bara bort identiska kopior från GAMMAL.\n\nVAD RESULTATEN BETYDER\n• SAKNAS I AKTUELL: ingen identisk kopia finns i AKTUELL. Filerna stannar i GAMMAL.\n• MÖJLIGA ANDRA VERSIONER: samma namn finns, men innehållet skiljer sig. Filerna stannar i GAMMAL.\n• IDENTISKA KOPIOR I AKTUELL: en exakt kopia finns i AKTUELL. Bara dessa filer kan tas bort från GAMMAL.\n• FILER SOM INTE KONTROLLERATS: LegacySift kunde inte verifiera dem säkert. De stannar i GAMMAL.\n\nEFTER RENSNING\nI den GAMLA mappen finns filer som saknas i AKTUELL, möjliga andra versioner och allt som inte kunde verifieras säkert kvar. Endast exakta kopior tas bort från GAMMAL.\n\nSÄKRASTE METODEN\nAnvänd säkerhetsmappen. Exakta kopior flyttas till en separat mapp bredvid GAMMAL som kan återställas, i stället för att raderas permanent.\n\nTEKNISK SÄKERHET\nExakt innehåll jämförs med SHA-256 och kontrolleras igen före rensning. Länkade mappar och reparse points hoppas över. Kapslade mappval blockeras. LegacySift begär inte administratörsrättigheter och arbetar helt lokalt.\n\nENKEL REGEL\nOm du är osäker, stanna efter kontrollen. Ingenting ändras förrän du uttryckligen startar rensningen."
        );
    }
}
