using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Cs = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — bezpečně vyčistěte starou složku",
            "TabWork", "Porovnat a vyčistit",
            "TabHelp", "Návod a bezpečnost",
            "LanguageButton", "Jazyk…",
            "Intro", "STARÁ složka je vlevo, AKTUÁLNÍ složka vpravo. LegacySift odstraní ze STARÉ složky pouze soubory, jejichž totožná kopie už je v AKTUÁLNÍ složce.",
            "OldTitle", "1. STARÁ SLOŽKA",
            "OldBadge", "TUTO LZE VYČISTIT",
            "OldDescription", "Složka obnovená ze starého počítače, disku nebo zálohy. Pouze tuto stranu může čištění změnit.",
            "CurrentTitle", "2. AKTUÁLNÍ SLOŽKA",
            "CurrentBadge", "CHRÁNĚNÁ • JEN PRO ČTENÍ",
            "CurrentDescription", "Složka, kterou používáte dnes. LegacySift ji pouze čte pro porovnání a nikdy ji nečistí.",
            "Browse", "Procházet…",
            "Direction", "Porovnání: STARÁ složka → chráněná AKTUÁLNÍ složka. Kontrola soubory jen čte; nic nemění.",
            "Analyze", "3. ZKONTROLOVAT, CO UŽ MÁTE — nic nemění",
            "Cancel", "Zrušit",
            "OpenReport", "Otevřít poslední zprávu",
            "NoAnalysis", "Vyberte STAROU složku a chráněnou AKTUÁLNÍ složku a spusťte kontrolu.",
            "PathsChanged", "Výběr složky se změnil. Před čištěním spusťte kontrolu znovu.",
            "TabRecover", "NENALEZENO V AKTUÁLNÍ",
            "TabVersions", "MOŽNÉ JINÉ VERZE",
            "TabDuplicates", "TOTOŽNÉ KOPIE",
            "TabProblems", "NEZKONTROLOVANÉ SOUBORY",
            "GridOld", "Soubor ve STARÉ složce",
            "GridSize", "Velikost",
            "GridCurrent", "Odpovídající soubor v AKTUÁLNÍ složce",
            "GridNote", "Co LegacySift zjistil",
            "CleanupGroup", "4. VYČISTIT STAROU SLOŽKU",
            "Quarantine", "Bezpečnostní složka (doporučeno) — přesune totožné kopie ze STARÉ a umožní je obnovit",
            "Recycle", "Koš systému Windows — odešle totožné kopie ze STARÉ složky do Koše",
            "OtherOptions", "Zobrazit další možnosti",
            "HideOptions", "Skrýt další možnosti",
            "RemoveEmpty", "Odstranit složky, které zůstaly ve STARÉ složce zcela prázdné",
            "Confirm", "Rozumím: změněna bude POUZE STARÁ složka. AKTUÁLNÍ složka zůstane beze změny.",
            "Cleanup", "ODSTRANIT TOTOŽNÉ KOPIE ZE STARÉ SLOŽKY",
            "Restore", "Obnovit odložené soubory…",
            "ProtectedReminder", "AKTUÁLNÍ složka zůstává chráněná",
            "Ready", "Připraveno.",
            "ChooseOldDialog", "Vyberte STAROU složku ke kontrole a vyčištění",
            "ChooseCurrentDialog", "Vyberte AKTUÁLNÍ / CHRÁNĚNOU složku",
            "AnalyzeDone", "Kontrola dokončena. Žádný soubor nebyl změněn.",
            "AnalyzeCanceled", "Kontrola zrušena. Žádný soubor nebyl změněn.",
            "AnalyzeErrorTitle", "Problém během kontroly",
            "AnalyzeErrorStatus", "Kontrola se zastavila kvůli problému. Čištění neproběhlo.",
            "PathCheckTitle", "LegacySift — kontrola výběru složek",
            "CleanupConfirmTitle", "Potvrdit vyčištění STARÉ složky",
            "CleanupConfirm", "Chystáte se vyčistit POUZE STAROU složku:\n\n{0}\n\nAKTUÁLNÍ složka je chráněná a nebude změněna:\n\n{1}\n\nZe STARÉ bude odstraněno: {2} totožných kopií.\nVe STARÉ zůstane: {3} nenalezených v AKTUÁLNÍ, {4} možných jiných verzí, {5} nezkontrolovaných.\n\nMetoda: {6}\n\nPokračovat?",
            "ModeSafety", "BEZPEČNOSTNÍ SLOŽKA (lze obnovit)",
            "ModeRecycle", "KOŠ SYSTÉMU WINDOWS",
            "CleanupDoneStatus", "Hotovo: ze STARÉ složky bylo odstraněno {0} totožných kopií; {1} položek zůstalo z bezpečnostních důvodů beze změny.",
            "CleanupDoneTitle", "LegacySift — dokončeno",
            "CleanupDone", "Čištění dokončeno.\n\nZe STARÉ složky odstraněno: {0} totožných kopií\nZ bezpečnostních důvodů ponecháno: {1}{2}\n\nSoubory nenalezené v AKTUÁLNÍ a možné jiné verze nebyly změněny. Spusťte kontrolu znovu a uvidíte, co přesně zůstalo.",
            "CleanupSafetyLocation", "\n\nBezpečnostní složka:\n{0}\n\nNeodstraňujte ji, dokud nezkontrolujete soubory zbylé ve staré složce.",
            "CleanupCanceled", "Čištění zastaveno. Již přesunuté soubory zůstávají v bezpečnostní složce / Koši; ostatní nebyly změněny.",
            "CleanupErrorTitle", "Problém během čištění",
            "CleanupErrorStatus", "Čištění se zastavilo kvůli problému. Před dalším pokusem zkontrolujte bezpečnostní složku a proveďte nové porovnání.",
            "RestoreLast", "Obnovit poslední vytvořenou bezpečnostní složku?\n\n{0}",
            "RestoreTitle", "Obnovit soubory",
            "RestoreChoose", "Vyberte složku __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift se pokusí vrátit soubory na původní místa ve STARÉ složce.\nSoubory, které tam již existují, NEBUDOU přepsány.\n\nPokračovat?",
            "RestoreConfirmTitle", "Potvrdit obnovení",
            "RestoreDoneStatus", "Obnovení dokončeno: {0} souborů obnoveno; {1} konfliktů nebylo přepsáno.",
            "RestoreDone", "Obnoveno: {0}\nKonflikty NEPŘEPSÁNY: {1}\nChyby: {2}",
            "RestoreCanceled", "Obnovení zastaveno.",
            "RestoreErrorTitle", "Problém během obnovení",
            "Summary", "KONTROLA DOKONČENA — žádný soubor nebyl změněn.\n{0} nenalezených v AKTUÁLNÍ   |   {1} možných jiných verzí   |   {2} totožných kopií ({3})   |   {4} nezkontrolovaných",
            "CleanupCount", "ODSTRANIT {0} TOTOŽNÝCH KOPIÍ ZE STARÉ SLOŽKY",
            "PhaseOldScan", "Čtení STARÉ složky",
            "PhaseCurrentScan", "Čtení chráněné AKTUÁLNÍ složky",
            "PhaseCompare", "Porovnávání obsahu souborů",
            "PhaseSafety", "Přesouvání souborů do bezpečnostní složky",
            "PhaseRecycle", "Přesouvání souborů do Koše",
            "PhaseRestoreRead", "Čtení bezpečnostní složky",
            "PhaseRestore", "Obnovování souborů",
            "OldRequired", "Nejprve vyberte STAROU složku.",
            "CurrentRequired", "Vyberte AKTUÁLNÍ / CHRÁNĚNOU složku.",
            "InvalidPath", "Neplatná cesta: {0}",
            "OldMissing", "STARÁ složka neexistuje.",
            "CurrentMissing", "AKTUÁLNÍ / CHRÁNĚNÁ složka neexistuje.",
            "SameFolder", "Oba výběry ukazují na stejnou složku. Operace byla zablokována.",
            "OldRootBlocked", "Z bezpečnostních důvodů nelze jako STAROU složku použít kořen celého disku.",
            "CurrentRootBlocked", "Z bezpečnostních důvodů nelze jako AKTUÁLNÍ složku použít kořen celého disku.",
            "NestedBlocked", "Jedna vybraná složka je uvnitř druhé. Vyberte dvě oddělené složky.",
            "SystemFolderBlocked", "Z bezpečnostních důvodů LegacySift přímo nečistí hlavní systémovou složku Windows.",
            "OutsideOld", "Bezpečnostní kontrola selhala: tento soubor není ve STARÉ složce.",
            "ReparseDir", "Propojená složka / bod změny zpracování byl z bezpečnostních důvodů přeskočen.",
            "ReparseFile", "Propojený soubor / bod změny zpracování byl z bezpečnostních důvodů přeskočen.",
            "ExactNote", "V AKTUÁLNÍ složce je totožná kopie. Tuto kopii ve STARÉ složce lze bezpečně odstranit.",
            "VersionNoteOne", "V aktuální složce existuje soubor se stejným názvem, ale jiným obsahem. Tento soubor NEBUDE odstraněn.",
            "VersionNoteMany", "Bylo nalezeno {0} souborů se stejným názvem, ale žádný není totožný. Tento soubor NEBUDE odstraněn.",
            "UniqueNote", "V AKTUÁLNÍ složce nebyla nalezena totožná kopie. Tento soubor zůstane ve STARÉ složce.",
            "LanguageRestart", "LegacySift se restartuje, aby použil nový jazyk. Aktuální výsledky kontroly budou vymazány.",
            "LanguageRestartTitle", "Změnit jazyk",
            "SafetyParentMissing", "LegacySift nemůže určit, kde vytvořit bezpečnostní složku.",
            "OldFileMissingNow", "Soubor ve staré složce již neexistuje.",
            "CurrentCopyMissingNow", "Odpovídající soubor v aktuální složce již neexistuje.",
            "ChangedSize", "Velikost souboru se po porovnání změnila. Soubor zůstal beze změny.",
            "ChangedHash", "Soubory již nejsou totožné. Starý soubor zůstal beze změny.",
            "SafetyDestinationExists", "V bezpečnostní složce již existuje soubor se stejnou cestou.",
            "SafetyVerificationFailed", "Ověření po přesunu do bezpečnostní složky selhalo. LegacySift se pokusil původní soubor automaticky obnovit.",
            "MovedSafety", "Přesunuto do bezpečnostní složky a ověřeno.",
            "MovedRecycle", "Přesunuto do Koše systému Windows.",
            "SafetyFolderMissing", "Bezpečnostní složka nebyla nalezena.",
            "RestoreNoOverwrite", "NEPŘEPSÁNO: {0}",
            "SessionMissing", "Soubor LegacySift.session chybí, automatické obnovení proto není možné.",
            "SessionInvalid", "Relace bezpečnostní složky není platná: chybí původní cesta staré složky.",
            "TabRecoverHelp", "V AKTUÁLNÍ nebyla nalezena totožná kopie. Tyto soubory zůstávají ve STARÉ složce.",
            "TabVersionsHelp", "V AKTUÁLNÍ je stejný název, ale obsah se liší. Tyto soubory zůstávají ve STARÉ složce.",
            "TabDuplicatesHelp", "V AKTUÁLNÍ již existuje totožná kopie. Čištěním lze odstranit pouze tyto soubory ze STARÉ složky.",
            "TabProblemsHelp", "LegacySift nemohl tyto soubory bezpečně ověřit. Zůstávají ve STARÉ složce.",
            "CheckingNow", "Kontrolují se obě složky… žádný soubor se nemění.",
            "CleanupBeforeAnalysis", "Nejprve spusťte kontrolu. LegacySift pak přesně ukáže, co lze ze STARÉ odstranit a co tam zůstane.",
            "CleanupWaitForAnalysis", "Počkejte na dokončení kontroly. Dokud LegacySift čte složky, čištění je vypnuté.",
            "CleanupExplanation", "Po čištění zůstane ve STARÉ složce {0} souborů nenalezených v AKTUÁLNÍ, {1} možných jiných verzí a {2} nezkontrolovaných souborů. Ze STARÉ bude odstraněno pouze {3} totožných kopií.",
            "AfterCleanupSummary", "Čištění dokončeno: ze STARÉ bylo odstraněno {0} totožných kopií; {1} položek zůstalo z bezpečnostních důvodů beze změny. Spusťte kontrolu znovu a uvidíte, co přesně zůstalo.",
            "CleanupNeedsNewCheck", "Čištění skončilo. Spusťte kontrolu znovu, abyste viděli jen to, co zůstalo ve STARÉ složce.",
            "HelpText", "LEGACYSIFT — RYCHLÝ NÁVOD\n\nK ČEMU SLOUŽÍ\nLegacySift je určen pro přesuny počítačů, staré disky a obnovené zálohy. Vyberte STAROU složku a AKTUÁLNÍ složku, kterou dnes používáte. LegacySift ukáže, co v AKTUÁLNÍ chybí a které přesné kopie již máte.\n\nSMĚR SE NIKDY NEMĚNÍ\nSTARÁ SLOŽKA = lze ji vyčistit.\nAKTUÁLNÍ SLOŽKA = chráněná, jen pro porovnání. LegacySift ji nikdy nečistí.\n\nJAK SE POUŽÍVÁ\n1. Vyberte STAROU SLOŽKU.\n2. Vyberte AKTUÁLNÍ SLOŽKU.\n3. Klikněte na ZKONTROLOVAT, CO UŽ MÁTE. Tento krok nic nemění.\n4. Přečtěte si výsledky.\n5. Pokud dávají smysl, odstraňte ze STARÉ pouze totožné kopie.\n\nCO ZNAMENAJÍ VÝSLEDKY\n• NENALEZENO V AKTUÁLNÍ: v AKTUÁLNÍ není totožná kopie. Soubory zůstávají ve STARÉ.\n• MOŽNÉ JINÉ VERZE: existuje stejný název, ale obsah se liší. Soubory zůstávají ve STARÉ.\n• TOTOŽNÉ KOPIE JIŽ V AKTUÁLNÍ: v AKTUÁLNÍ existuje přesná kopie. Pouze tyto soubory lze ze STARÉ odstranit.\n• NEZKONTROLOVANÉ SOUBORY: LegacySift je nemohl bezpečně ověřit. Zůstávají ve STARÉ.\n\nPO VYČIŠTĚNÍ\nVe STARÉ složce zůstanou soubory nenalezené v AKTUÁLNÍ, možné jiné verze a vše, co LegacySift nemohl bezpečně ověřit. Ze STARÉ se odstraní pouze přesné kopie.\n\nNEJBEZPEČNĚJŠÍ METODA\nPoužijte bezpečnostní složku. Přesné kopie se místo trvalého odstranění přesunou do samostatné obnovitelné složky vedle STARÉ.\n\nTECHNICKÁ BEZPEČNOST\nPřesný obsah se porovnává pomocí SHA-256 a před čištěním se znovu ověří. Propojené složky a body změny zpracování se přeskakují. Vnořené výběry složek jsou blokovány. LegacySift nevyžaduje práva správce a pracuje zcela místně.\n\nJEDNODUCHÉ PRAVIDLO\nPokud si nejste jistí, skončete po kontrole. Nic se nezmění, dokud výslovně nespustíte čištění."
        );
    }
}
