using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Fil = Make(
            "AppTitle", "LegacySift 0.2.2-alpha — ligtas na linisin ang isang lumang folder",
            "TabWork", "Paghambingin at linisin",
            "TabHelp", "Gabay at kaligtasan",
            "LanguageButton", "Wika…",
            "Intro", "Lumang folder sa kaliwa. Kasalukuyang folder sa kanan. Tinatanggal lamang ng LegacySift mula sa LUMANG folder ang mga file na magkapareho na sa KASALUKUYANG folder.",
            "OldTitle", "1. LUMANG FOLDER",
            "OldBadge", "MAAARING LINISIN ITO",
            "OldDescription", "Ang nabawing folder mula sa lumang computer, disk o backup. Tanging ang bahaging ito ang maaaring baguhin sa pamamagitan ng paglilinis.",
            "CurrentTitle", "2. KASALUKUYANG FOLDER",
            "CurrentBadge", "PROTEKTADO • NABABASA LAMANG",
            "CurrentDescription", "Ang folder na ginagamit mo ngayon. Binabasa lamang ito ng LegacySift para sa paghahambing at hindi kailanman nililinis ito.",
            "Browse", "Mag-browse…",
            "Direction", "Paghambingin ang LUMANG folder → KASALUKUYANG protektadong folder. Binabasa lamang ng pagsusuri ang mga file;wala itong binabago.",
            "Analyze", "3. SURIIN ANG MERON KA NA — walang binabago",
            "Cancel", "Kanselahin",
            "OpenReport", "Buksan ang huling ulat",
            "NoAnalysis", "Piliin ang LUMANG folder at ang KASALUKUYANG protektadong folder, pagkatapos ay patakbuhin ang pagsusuri.",
            "PathsChanged", "Binago ang napiling folder. Patakbuhin muli ang pagsusuri bago linisin ang anuman.",
            "TabRecover", "HINDI Natagpuan sa KASALUKUYAN",
            "TabVersions", "MGA POSIBLENG IBA'T IBANG BERSYON",
            "TabDuplicates", "MGA MAGKAKATULAD NA KOPYA",
            "TabProblems", "MGA FILE NA HINDI NASURI",
            "GridOld", "File sa LUMANG folder",
            "GridSize", "Sukat",
            "GridCurrent", "Katugmang file sa KASALUKUYANG folder",
            "GridNote", "Ang natagpuan ng LegacySift",
            "CleanupGroup", "4. LINISIN ANG LUMANG FOLDER",
            "Quarantine", "Safety folder (inirerekomenda) — ilipat ang magkaparehong kopya mula sa LUMANG upang maibalik ang mga ito",
            "Recycle", "Windows Recycle Bin — ipadala ang magkaparehong kopya ng LUMANG folder sa Recycle Bin",
            "OtherOptions", "Ipakita ang iba pang mga opsyon",
            "HideOptions", "Itago ang iba pang mga opsyon",
            "RemoveEmpty", "Alisin ang mga folder na naiwang walang laman sa loob ng LUMANG folder",
            "Confirm", "Nauunawaan ko: TANGING ang LUMANG folder ang babaguhin. Ang KASALUKUYANG folder ay mananatiling hindi nagbabago.",
            "Cleanup", "ALISIN ANG MGA MAGKAKATULAD NA KOPYA MULA SA LUMANG FOLDER",
            "Restore", "Ibalik ang mga file, isantabi…",
            "ProtectedReminder", "Ang KASALUKUYANG ay mananatiling protektado",
            "Ready", "Handa na.",
            "ChooseOldDialog", "Piliin ang LUMANG folder na susuriin at lilinisin",
            "ChooseCurrentDialog", "Piliin ang KASALUKUYANG / PROTEKTADONG folder",
            "AnalyzeDone", "Kumpleto na ang pagsusuri. Walang binagong file.",
            "AnalyzeCanceled", "Kinansela ang pagsusuri. Walang binagong file.",
            "AnalyzeErrorTitle", "Problema habang sinusuri",
            "AnalyzeErrorStatus", "Tumigil ang pagsusuri dahil sa isang problema. Walang isinagawang paglilinis.",
            "PathCheckTitle", "LegacySift — suriin ang pagpili ng folder",
            "CleanupConfirmTitle", "Kumpirmahin ang paglilinis ng LUMANG folder",
            "CleanupConfirm", "Lilinisin mo LAMANG ang LUMANG folder:\\n\\n{0}\\n\\nAng KASALUKUYANG folder ay protektado at hindi babaguhin:\\n\\n{1}\\n\\nInalis mula sa LUMANG: {2} magkaparehong kopya.\\nNaiwan sa LUMANG: {3} hindi natagpuan sa KASALUKUYAN, {4} posibleng iba't ibang bersyon, {5} hindi nasuri.\\n\\nParaan: {6}\\n\\nMagpatuloy?",
            "ModeSafety", "SAFETY FOLDER (maaaring ibalik)",
            "ModeRecycle", "WINDOWS RECYCLE BIN",
            "CleanupDoneStatus", "Tapos na: Ang mga magkaparehong kopya ng {0} ay tinanggal mula sa LUMANG folder;ang mga kandidato ng {1} ay hindi ginalaw para sa kaligtasan.",
            "CleanupDoneTitle", "LegacySift — natapos",
            "CleanupDone", "Nakumpleto ang paglilinis.\\n\\nTinanggal mula sa LUMANG folder: {0} mga magkaparehong kopya\\nIniwan sa lugar para sa kaligtasan: {1}{2}\\n\\nHindi natagpuan ang mga file sa KASALUKUYAN at posibleng hindi ginalaw ang iba't ibang bersyon. Patakbuhin muli ang pagsusuri upang makita kung ano mismo ang natitira.",
            "CleanupSafetyLocation", "\\n\\nFolder ng kaligtasan:\\n{0}\\n\\nHuwag itong burahin hangga't hindi mo nasusuri ang mga file na natitira sa lumang folder.",
            "CleanupCanceled", "Natigil ang paglilinis. Ang mga file na nailipat na ay nananatili sa safety folder / Recycle Bin;ang mga natitirang file ay hindi nahawakan.",
            "CleanupErrorTitle", "Problema habang nililinis",
            "CleanupErrorStatus", "Natigil ang paglilinis dahil sa isang problema. Suriin ang safety folder at magpatakbo ng bagong paghahambing bago subukang muli.",
            "RestoreLast", "Ibalik ang huling safety folder na nilikha?\\n\\n{0}",
            "RestoreTitle", "Ibalik ang mga file",
            "RestoreChoose", "Pumili ng __LegacySift_Safety_... folder",
            "RestoreConfirm", "Susubukan ng LegacySift na ibalik ang mga file sa kanilang orihinal na lokasyon ng LUMANG folder.\\nAng mga file na umiiral na doon ay HINDI mapapatungan.\\n\\nMagpatuloy?",
            "RestoreConfirmTitle", "Kumpirmahin ang pagbabalik",
            "RestoreDoneStatus", "Kumpleto na ang pagbabalik: Naibalik ang mga file na {0}; Hindi napapatungan ang mga conflict ng {1}.",
            "RestoreDone", "Naibalik: {0}\\nHindi na-overwrite ang mga conflict: {1}\\nMga Error: {2}",
            "RestoreCanceled", "Itinigil ang pagbabalik.",
            "RestoreErrorTitle", "Problema habang nagre-restore",
            "Summary", "SURIIN KUMPLETO — walang file na binago.\\n{0} hindi natagpuan sa KASALUKUYAN |{1} posibleng iba't ibang bersyon |{2} magkaparehong kopya ({3}) |{4} hindi nasuri",
            "CleanupCount", "TANGGALIN ANG {0} MGA MAGKAKATAWANG KOPYA MULA SA LUMANG FOLDER",
            "PhaseOldScan", "Binabasa ang LUMANG folder",
            "PhaseCurrentScan", "Binabasa ang KASALUKUYANG protektadong folder",
            "PhaseCompare", "Paghahambing ng mga nilalaman ng file",
            "PhaseSafety", "Paglilipat ng mga file sa safety folder",
            "PhaseRecycle", "Paglilipat ng mga file sa Recycle Bin",
            "PhaseRestoreRead", "Binabasa ang safety folder",
            "PhaseRestore", "Pagpapanumbalik ng mga file",
            "OldRequired", "Piliin muna ang LUMANG folder.",
            "CurrentRequired", "Piliin ang KASALUKUYAN / PROTEKTADONG folder.",
            "InvalidPath", "Hindi wastong path: {0}",
            "OldMissing", "Wala ang OLD folder.",
            "CurrentMissing", "Wala ang CURRENT / PROTECTED folder.",
            "SameFolder", "Ang dalawang seleksyon ay nakaturo sa iisang folder. Na-block ang operasyon.",
            "OldRootBlocked", "Para sa kaligtasan, hindi maaaring gamitin ang isang buong drive root bilang OLD folder.",
            "CurrentRootBlocked", "Para sa kaligtasan, hindi maaaring gamitin ang isang buong drive root bilang CURRENT folder.",
            "NestedBlocked", "Ang isang napiling folder ay nasa loob ng isa pa. Pumili ng dalawang magkahiwalay na folder.",
            "SystemFolderBlocked", "Para sa kaligtasan, hindi lilinisin ng LegacySift ang isang pangunahing folder ng Windows system.",
            "OutsideOld", "Nabigo ang pagsusuri sa kaligtasan: ang file na ito ay wala sa loob ng OLD folder.",
            "ReparseDir", "Nilaktawan ang naka-link na folder / reparse point para sa kaligtasan.",
            "ReparseFile", "Nilaktawan ang naka-link na file / reparse point para sa kaligtasan.",
            "ExactNote", "May magkaparehong kopya sa CURRENT folder. Ang kopya ng OLD-folder na ito ay maaaring ligtas na matanggal.",
            "VersionNoteOne", "May umiiral na file na may parehong pangalan sa kasalukuyang folder, ngunit iba ang mga nilalaman nito. HINDI aalisin ang file na ito.",
            "VersionNoteMany", "May natagpuang {0} na mga file na may parehong pangalan, ngunit walang magkapareho. HINDI aalisin ang file na ito.",
            "UniqueNote", "Walang natagpuang magkaparehong kopya sa KASALUKUYANG folder. Nanatili ang file na ito sa LUMANG folder.",
            "LanguageRestart", "Magsisimula muli ang LegacySift upang ilapat ang bagong wika. Anumang kasalukuyang resulta ng paghahambing ay buburahin.",
            "LanguageRestartTitle", "Baguhin ang wika",
            "SafetyParentMissing", "Hindi matukoy ng LegacySift kung saan gagawin ang safety folder.",
            "OldFileMissingNow", "Wala na ang file sa lumang folder.",
            "CurrentCopyMissingNow", "Wala na ang tumutugmang file sa kasalukuyang folder.",
            "ChangedSize", "Nagbago ang laki ng file pagkatapos ng paghahambing. Hindi ginalaw ang file.",
            "ChangedHash", "Hindi na magkapareho ang dalawang file. Hindi ginalaw ang lumang file.",
            "SafetyDestinationExists", "Mayroon nang file na may parehong path sa safety folder.",
            "SafetyVerificationFailed", "Nabigo ang pag-verify ng safety-folder pagkatapos ng paglipat. Sinubukan ng LegacySift na awtomatikong ibalik ang orihinal na file.",
            "MovedSafety", "Inilipat sa safety folder at na-verify.",
            "MovedRecycle", "Inilipat sa Windows Recycle Bin.",
            "SafetyFolderMissing", "Hindi natagpuan ang safety folder.",
            "RestoreNoOverwrite", "HINDI na-overwrite: {0}",
            "SessionMissing", "Nawawala ang LegacySift.session, kaya hindi posible ang awtomatikong pag-restore.",
            "SessionInvalid", "Hindi wasto ang session ng safety-folder: nawawala ang orihinal na path ng old-folder.",
            "TabRecoverHelp", "Walang natagpuang magkaparehong kopya sa CURRENT. Nananatili ang mga file na ito sa OLD folder.",
            "TabVersionsHelp", "May umiiral na file na may parehong pangalan sa CURRENT, ngunit magkaiba ang mga nilalaman. Nananatili ang mga file na ito sa OLD folder.",
            "TabDuplicatesHelp", "May umiiral nang magkaparehong kopya sa CURRENT. Tanging ang mga OLD-folder file na ito ang maaaring alisin sa pamamagitan ng paglilinis.",
            "TabProblemsHelp", "Hindi ligtas na ma-verify ng LegacySift ang mga file na ito. Nanatili ang mga ito sa OLD folder.",
            "CheckingNow", "Sinusuri ang dalawang folder… walang file na binabago.",
            "CleanupBeforeAnalysis", "Una, patakbuhin ang pagsusuri. Pagkatapos, ipapakita ng LegacySift kung ano mismo ang maaaring alisin mula sa OLD folder at kung ano ang mananatili roon.",
            "CleanupWaitForAnalysis", "Hintaying matapos ang pagsusuri. Hindi pinagana ang paglilinis habang binabasa ng LegacySift ang mga folder.",
            "CleanupExplanation", "Pagkatapos ng paglilinis, pananatilihin ng OLD ang mga {0} file na hindi matatagpuan sa CURRENT, posibleng iba't ibang bersyon ng {1} at mga {2} file na hindi nasuri. Tanging ang magkaparehong kopya ng {3} ang aalisin mula sa OLD.",
            "AfterCleanupSummary", "Nakumpleto na ang paglilinis: Tinanggal ang magkaparehong kopya ng {0} mula sa OLD; Hindi ginalaw ang mga kandidato ng {1} para sa kaligtasan. Patakbuhin muli ang pagsusuri upang makita kung ano mismo ang natitira.",
            "CleanupNeedsNewCheck", "Natapos na ang paglilinis. Patakbuhin muli ang pagsusuri upang makita lamang kung ano ang natitira sa OLD folder.",
            "HelpText", "LEGACYSIFT — MABILISANG GABAY\\n\\nANG GINAGAWA NITO\\nAng LegacySift ay para sa mga paglilipat ng computer, mga lumang disk at mga na-recover na backup. Piliin ang OLD folder at ang CURRENT folder na ginagamit mo ngayon. Ipinapakita ng LegacySift kung ano ang nawawala mula sa CURRENT at kung aling mga eksaktong kopya ang mayroon ka na.\\n\\nANG DIREKSYON AY HINDI NAGBABAGO\\nOLD FOLDER = maaaring linisin.\\nCURRENT FOLDER = protektado, paghahambing lamang. Hindi ito nililinis ng LegacySift.\\n\\nPAANO GAMITIN ITO\\n1. Piliin ang OLD FOLDER.\\n2. Piliin ang CURRENT FOLDER.\\n3. I-click ang CHECK WHAT ALTERNET YOU. Walang binabago ang hakbang na ito.\\n4. Basahin ang mga resulta.\\n5. Kung may katuturan ang mga ito, alisin lamang ang magkaparehong kopya mula sa OLD.\\n\\nANG IBIG SABIHIN NG MGA RESULTA\\n• HINDI MATATAGPUAN SA KASALUKUYAN: walang magkaparehong kopya ang umiiral sa KASALUKUYAN. Ang mga file na ito ay nananatili sa OLD.\\n• MGA POSIBLENG IBA'T IBANG BERSYON: umiiral ang parehong pangalan, ngunit magkaiba ang mga nilalaman. Ang mga file na ito ay nananatili sa OLD.\\n• MGA MAGKAKATAWANG KOPYA NA NASA KASALUKUYAN NA: mayroong eksaktong kopya sa KASALUKUYAN. Tanging ang mga OLD file na ito ang maaaring alisin.\\n• MGA FILE NA HINDI NASURI: Hindi ligtas na ma-verify ng LegacySift ang mga ito. Nanatili ang mga ito sa OLD.\\n\\nPAGKATAPOS NG PAGLILINIS\\nAng OLD folder ay naiiwan kasama ang mga file na hindi natagpuan sa CURRENT, posibleng iba't ibang bersyon, at anumang hindi ligtas na ma-verify ng LegacySift. Ang mga eksaktong kopya lamang ang mga file na inalis mula sa OLD.\\n\\nPINAKALIGTAS NA PARAAN\\nGamitin ang Safety folder. Ang mga eksaktong kopya ay inililipat sa isang hiwalay at maaaring ibalik na folder sa tabi ng OLD sa halip na permanenteng tanggalin.\\n\\nTEKNIKAL NA KALIGTASAN\\nSinusuri ang eksaktong nilalaman gamit ang SHA-256 at sinusuri muli bago ang paglilinis. Nilalaktawan ang mga naka-link na folder/reparse point. Hinaharangan ang mga napiling nested folder. Hindi humihingi ng mga pribilehiyo ng administrator ang LegacySift at gumagana nang lokal.\\n\\nSIMPLE RULE\\nKung hindi ka sigurado, itigil pagkatapos ng pagsusuri. Walang magbabago hangga't hindi mo sinisimulan ang paglilinis."
        );
    }
}
