using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Vi = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — dọn thư mục cũ một cách an toàn",
            "TabWork", "So sánh và dọn dẹp",
            "TabHelp", "Hướng dẫn và an toàn",
            "LanguageButton", "Ngôn ngữ…",
            "Intro", "Thư mục CŨ ở bên trái, thư mục HIỆN TẠI ở bên phải. LegacySift chỉ xóa khỏi thư mục CŨ những tệp đã có bản sao giống hệt trong thư mục HIỆN TẠI.",
            "OldTitle", "1. THƯ MỤC CŨ",
            "OldBadge", "CÓ THỂ DỌN THƯ MỤC NÀY",
            "OldDescription", "Thư mục được khôi phục từ máy tính, ổ đĩa hoặc bản sao lưu cũ. Chỉ phía này có thể bị thay đổi khi dọn dẹp.",
            "CurrentTitle", "2. THƯ MỤC HIỆN TẠI",
            "CurrentBadge", "ĐƯỢC BẢO VỆ • CHỈ ĐỌC",
            "CurrentDescription", "Thư mục bạn đang dùng. LegacySift chỉ đọc để so sánh và không bao giờ dọn thư mục này.",
            "Browse", "Duyệt…",
            "Direction", "So sánh: thư mục CŨ → thư mục HIỆN TẠI được bảo vệ. Việc kiểm tra chỉ đọc tệp và không thay đổi gì.",
            "Analyze", "3. KIỂM TRA NHỮNG GÌ BẠN ĐÃ CÓ — không thay đổi gì",
            "Cancel", "Hủy",
            "OpenReport", "Mở báo cáo gần nhất",
            "NoAnalysis", "Chọn thư mục CŨ và thư mục HIỆN TẠI được bảo vệ, rồi bắt đầu kiểm tra.",
            "PathsChanged", "Lựa chọn thư mục đã thay đổi. Hãy kiểm tra lại trước khi dọn bất kỳ thứ gì.",
            "TabRecover", "KHÔNG CÓ TRONG THƯ MỤC HIỆN TẠI",
            "TabVersions", "CÓ THỂ LÀ PHIÊN BẢN KHÁC",
            "TabDuplicates", "BẢN SAO GIỐNG HỆT",
            "TabProblems", "TỆP CHƯA KIỂM TRA",
            "GridOld", "Tệp trong thư mục CŨ",
            "GridSize", "Kích thước",
            "GridCurrent", "Tệp tương ứng trong thư mục HIỆN TẠI",
            "GridNote", "Kết quả của LegacySift",
            "CleanupGroup", "4. DỌN THƯ MỤC CŨ",
            "Quarantine", "Thư mục an toàn (khuyên dùng) — chuyển bản sao giống hệt ra khỏi CŨ để có thể khôi phục",
            "Recycle", "Thùng rác Windows — đưa các bản sao giống hệt trong thư mục CŨ vào Thùng rác",
            "OtherOptions", "Hiện tùy chọn khác",
            "HideOptions", "Ẩn tùy chọn khác",
            "RemoveEmpty", "Xóa các thư mục đã hoàn toàn trống bên trong thư mục CŨ",
            "Confirm", "Tôi hiểu: CHỈ thư mục CŨ bị thay đổi. Thư mục HIỆN TẠI vẫn giữ nguyên.",
            "Cleanup", "XÓA BẢN SAO GIỐNG HỆT KHỎI THƯ MỤC CŨ",
            "Restore", "Khôi phục các tệp đã cất riêng…",
            "ProtectedReminder", "Thư mục HIỆN TẠI luôn được bảo vệ",
            "Ready", "Sẵn sàng.",
            "ChooseOldDialog", "Chọn thư mục CŨ để kiểm tra và dọn dẹp",
            "ChooseCurrentDialog", "Chọn thư mục HIỆN TẠI / ĐƯỢC BẢO VỆ",
            "AnalyzeDone", "Kiểm tra hoàn tất. Không tệp nào bị thay đổi.",
            "AnalyzeCanceled", "Đã hủy kiểm tra. Không tệp nào bị thay đổi.",
            "AnalyzeErrorTitle", "Sự cố khi kiểm tra",
            "AnalyzeErrorStatus", "Kiểm tra dừng do sự cố. Chưa thực hiện dọn dẹp.",
            "PathCheckTitle", "LegacySift — kiểm tra lựa chọn thư mục",
            "CleanupConfirmTitle", "Xác nhận dọn thư mục CŨ",
            "CleanupConfirm", "Bạn sắp dọn CHỈ thư mục CŨ:\n\n{0}\n\nThư mục HIỆN TẠI được bảo vệ và sẽ không thay đổi:\n\n{1}\n\nXóa khỏi CŨ: {2} bản sao giống hệt.\nGiữ trong CŨ: {3} tệp không có trong HIỆN TẠI, {4} phiên bản có thể khác, {5} tệp chưa kiểm tra.\n\nPhương thức: {6}\n\nTiếp tục?",
            "ModeSafety", "THƯ MỤC AN TOÀN (có thể khôi phục)",
            "ModeRecycle", "THÙNG RÁC WINDOWS",
            "CleanupDoneStatus", "Xong: đã xóa {0} bản sao giống hệt khỏi thư mục CŨ; {1} mục được giữ nguyên để bảo đảm an toàn.",
            "CleanupDoneTitle", "LegacySift — hoàn tất",
            "CleanupDone", "Dọn dẹp hoàn tất.\n\nĐã xóa khỏi thư mục CŨ: {0} bản sao giống hệt\nGiữ nguyên để an toàn: {1}{2}\n\nCác tệp không có trong HIỆN TẠI và những phiên bản có thể khác không bị đụng đến. Hãy kiểm tra lại để biết chính xác những gì còn lại.",
            "CleanupSafetyLocation", "\n\nThư mục an toàn:\n{0}\n\nĐừng xóa thư mục này cho đến khi bạn đã kiểm tra các tệp còn lại trong thư mục cũ.",
            "CleanupCanceled", "Dọn dẹp đã dừng. Tệp đã chuyển vẫn nằm trong thư mục an toàn / Thùng rác; các tệp còn lại không bị đụng đến.",
            "CleanupErrorTitle", "Sự cố khi dọn dẹp",
            "CleanupErrorStatus", "Dọn dẹp dừng do sự cố. Hãy kiểm tra thư mục an toàn và so sánh lại trước khi thử tiếp.",
            "RestoreLast", "Khôi phục thư mục an toàn được tạo gần nhất?\n\n{0}",
            "RestoreTitle", "Khôi phục tệp",
            "RestoreChoose", "Chọn thư mục __LegacySift_Safety_...",
            "RestoreConfirm", "LegacySift sẽ cố đưa tệp về vị trí ban đầu trong thư mục CŨ.\nTệp đã tồn tại ở đó sẽ KHÔNG bị ghi đè.\n\nTiếp tục?",
            "RestoreConfirmTitle", "Xác nhận khôi phục",
            "RestoreDoneStatus", "Khôi phục hoàn tất: đã khôi phục {0} tệp; {1} xung đột không bị ghi đè.",
            "RestoreDone", "Đã khôi phục: {0}\nXung đột KHÔNG bị ghi đè: {1}\nLỗi: {2}",
            "RestoreCanceled", "Khôi phục đã dừng.",
            "RestoreErrorTitle", "Sự cố khi khôi phục",
            "Summary", "KIỂM TRA HOÀN TẤT — không tệp nào bị thay đổi.\n{0} không có trong HIỆN TẠI   |   {1} phiên bản có thể khác   |   {2} bản sao giống hệt ({3})   |   {4} chưa kiểm tra",
            "CleanupCount", "XÓA {0} BẢN SAO GIỐNG HỆT KHỎI THƯ MỤC CŨ",
            "PhaseOldScan", "Đang đọc thư mục CŨ",
            "PhaseCurrentScan", "Đang đọc thư mục HIỆN TẠI được bảo vệ",
            "PhaseCompare", "Đang so sánh nội dung tệp",
            "PhaseSafety", "Đang chuyển tệp vào thư mục an toàn",
            "PhaseRecycle", "Đang chuyển tệp vào Thùng rác",
            "PhaseRestoreRead", "Đang đọc thư mục an toàn",
            "PhaseRestore", "Đang khôi phục tệp",
            "OldRequired", "Hãy chọn thư mục CŨ trước.",
            "CurrentRequired", "Hãy chọn thư mục HIỆN TẠI / ĐƯỢC BẢO VỆ.",
            "InvalidPath", "Đường dẫn không hợp lệ: {0}",
            "OldMissing", "Thư mục CŨ không tồn tại.",
            "CurrentMissing", "Thư mục HIỆN TẠI / ĐƯỢC BẢO VỆ không tồn tại.",
            "SameFolder", "Hai lựa chọn trỏ đến cùng một thư mục. Thao tác đã bị chặn.",
            "OldRootBlocked", "Để an toàn, không thể dùng toàn bộ thư mục gốc của ổ đĩa làm thư mục CŨ.",
            "CurrentRootBlocked", "Để an toàn, không thể dùng toàn bộ thư mục gốc của ổ đĩa làm thư mục HIỆN TẠI.",
            "NestedBlocked", "Một thư mục đã chọn nằm trong thư mục kia. Hãy chọn hai thư mục tách biệt.",
            "SystemFolderBlocked", "Để an toàn, LegacySift không trực tiếp dọn một thư mục hệ thống chính của Windows.",
            "OutsideOld", "Kiểm tra an toàn thất bại: tệp này không nằm trong thư mục CŨ.",
            "ReparseDir", "Đã bỏ qua thư mục liên kết / reparse point để bảo đảm an toàn.",
            "ReparseFile", "Đã bỏ qua tệp liên kết / reparse point để bảo đảm an toàn.",
            "ExactNote", "Có bản sao giống hệt trong thư mục HIỆN TẠI. Có thể xóa an toàn bản sao này khỏi thư mục CŨ.",
            "VersionNoteOne", "Có tệp cùng tên trong thư mục hiện tại nhưng nội dung khác. Tệp này sẽ KHÔNG bị xóa.",
            "VersionNoteMany", "Đã tìm thấy {0} tệp cùng tên nhưng không tệp nào giống hệt. Tệp này sẽ KHÔNG bị xóa.",
            "UniqueNote", "Không tìm thấy bản sao giống hệt trong thư mục HIỆN TẠI. Tệp này vẫn ở thư mục CŨ.",
            "LanguageRestart", "LegacySift sẽ khởi động lại để áp dụng ngôn ngữ mới. Kết quả kiểm tra hiện tại sẽ bị xóa.",
            "LanguageRestartTitle", "Đổi ngôn ngữ",
            "SafetyParentMissing", "LegacySift không thể xác định nơi tạo thư mục an toàn.",
            "OldFileMissingNow", "Tệp trong thư mục cũ không còn tồn tại.",
            "CurrentCopyMissingNow", "Tệp tương ứng trong thư mục hiện tại không còn tồn tại.",
            "ChangedSize", "Kích thước tệp đã thay đổi sau khi so sánh. Tệp được giữ nguyên.",
            "ChangedHash", "Hai tệp không còn giống hệt. Tệp cũ được giữ nguyên.",
            "SafetyDestinationExists", "Một tệp có cùng đường dẫn đã tồn tại trong thư mục an toàn.",
            "SafetyVerificationFailed", "Xác minh sau khi chuyển vào thư mục an toàn thất bại. LegacySift đã thử tự động khôi phục tệp gốc.",
            "MovedSafety", "Đã chuyển vào thư mục an toàn và xác minh.",
            "MovedRecycle", "Đã chuyển vào Thùng rác Windows.",
            "SafetyFolderMissing", "Không tìm thấy thư mục an toàn.",
            "RestoreNoOverwrite", "KHÔNG ghi đè: {0}",
            "SessionMissing", "Thiếu LegacySift.session nên không thể tự động khôi phục.",
            "SessionInvalid", "Phiên của thư mục an toàn không hợp lệ: thiếu đường dẫn ban đầu của thư mục cũ.",
            "TabRecoverHelp", "Không tìm thấy bản sao giống hệt trong HIỆN TẠI. Các tệp này vẫn ở thư mục CŨ.",
            "TabVersionsHelp", "Trong HIỆN TẠI có cùng tên nhưng nội dung khác. Các tệp này vẫn ở thư mục CŨ.",
            "TabDuplicatesHelp", "Trong HIỆN TẠI đã có bản sao giống hệt. Chỉ các tệp này trong thư mục CŨ mới có thể bị xóa.",
            "TabProblemsHelp", "LegacySift không thể xác minh an toàn các tệp này. Chúng vẫn ở thư mục CŨ.",
            "CheckingNow", "Đang kiểm tra hai thư mục… không tệp nào bị thay đổi.",
            "CleanupBeforeAnalysis", "Trước tiên hãy chạy kiểm tra. Sau đó LegacySift sẽ cho biết chính xác những gì có thể xóa khỏi CŨ và những gì sẽ ở lại.",
            "CleanupWaitForAnalysis", "Hãy đợi kiểm tra hoàn tất. Dọn dẹp bị tắt trong khi LegacySift đang đọc thư mục.",
            "CleanupExplanation", "Sau khi dọn, CŨ sẽ giữ {0} tệp không có trong HIỆN TẠI, {1} phiên bản có thể khác và {2} tệp chưa kiểm tra. Chỉ {3} bản sao giống hệt bị xóa khỏi CŨ.",
            "AfterCleanupSummary", "Dọn dẹp hoàn tất: đã xóa {0} bản sao giống hệt khỏi CŨ; {1} mục được giữ nguyên để an toàn. Hãy kiểm tra lại để biết chính xác những gì còn lại.",
            "CleanupNeedsNewCheck", "Dọn dẹp đã xong. Hãy kiểm tra lại để chỉ xem những gì còn trong thư mục CŨ.",
            "HelpText", "LEGACYSIFT — HƯỚNG DẪN NHANH\n\nCÔNG DỤNG\nLegacySift dành cho việc chuyển máy tính, ổ đĩa cũ và bản sao lưu đã khôi phục. Chọn thư mục CŨ và thư mục HIỆN TẠI bạn đang dùng. LegacySift cho biết những gì còn thiếu trong HIỆN TẠI và các bản sao chính xác bạn đã có.\n\nHƯỚNG KHÔNG BAO GIỜ THAY ĐỔI\nTHƯ MỤC CŨ = có thể dọn.\nTHƯ MỤC HIỆN TẠI = được bảo vệ, chỉ dùng để so sánh. LegacySift không bao giờ dọn thư mục này.\n\nCÁCH SỬ DỤNG\n1. Chọn THƯ MỤC CŨ.\n2. Chọn THƯ MỤC HIỆN TẠI.\n3. Bấm KIỂM TRA NHỮNG GÌ BẠN ĐÃ CÓ. Bước này không thay đổi gì.\n4. Đọc kết quả.\n5. Nếu kết quả hợp lý, chỉ xóa các bản sao giống hệt khỏi CŨ.\n\nÝ NGHĨA KẾT QUẢ\n• KHÔNG CÓ TRONG HIỆN TẠI: không có bản sao giống hệt. Các tệp vẫn ở CŨ.\n• CÓ THỂ LÀ PHIÊN BẢN KHÁC: có cùng tên nhưng nội dung khác. Các tệp vẫn ở CŨ.\n• BẢN SAO GIỐNG HỆT ĐÃ CÓ TRONG HIỆN TẠI: đã có bản sao chính xác. Chỉ các tệp này có thể bị xóa khỏi CŨ.\n• TỆP CHƯA KIỂM TRA: LegacySift không thể xác minh an toàn. Các tệp vẫn ở CŨ.\n\nSAU KHI DỌN\nThư mục CŨ vẫn chứa các tệp không có trong HIỆN TẠI, những phiên bản có thể khác và mọi thứ LegacySift không thể xác minh an toàn. Chỉ bản sao chính xác bị xóa khỏi CŨ.\n\nPHƯƠNG PHÁP AN TOÀN NHẤT\nDùng thư mục an toàn. Bản sao chính xác được chuyển vào một thư mục riêng có thể khôi phục bên cạnh CŨ thay vì bị xóa vĩnh viễn.\n\nAN TOÀN KỸ THUẬT\nNội dung chính xác được so sánh bằng SHA-256 và kiểm tra lại trước khi dọn. Thư mục liên kết và reparse point bị bỏ qua. Lựa chọn thư mục lồng nhau bị chặn. LegacySift không yêu cầu quyền quản trị và hoạt động hoàn toàn trên máy này.\n\nQUY TẮC ĐƠN GIẢN\nNếu không chắc chắn, hãy dừng sau khi kiểm tra. Không có gì thay đổi cho đến khi bạn chủ động bắt đầu dọn dẹp."
        );
    }
}
