using System.Collections.Generic;

namespace LegacySift
{
    internal static partial class L10n
    {
        private static readonly Dictionary<string, string> Et = Make(
            "AppTitle", "LegacySift 0.2.3-alpha — vana kausta ohutu puhastamine",
            "TabWork", "Võrdlemine ja puhastamine",
            "TabHelp", "Juhend ja ohutus",
            "LanguageButton", "Keel…",
            "Intro", "Vasakul vana kaust. Paremal praegune kaust. LegacySift eemaldab VANAST kaustast ainult need failid, mis on PRAEGUSES kaustas juba identsed.",
            "OldTitle", "1. VANA KAUST",
            "OldBadge", "SEDA VÕIB PUHASTADA",
            "OldDescription", "Vanast arvutist, kettast või varukoopiast taastatud kaust. Puhastamise käigus saab muuta ainult seda poolt.",
            "CurrentTitle", "2. PRAEGUNE KAUST",
            "CurrentBadge", "KAITSTUD • AINULT LUGEMISEKS",
            "CurrentDescription", "Kaust, mida praegu kasutate. LegacySift loeb seda vaid võrdlemise eesmärgil ega puhasta seda kunagi.",
            "Browse", "Sirvi…",
            "Direction", "Võrdle: VANA kaust → PRAEGUNE kaitstud kaust. Kontrollimine ainult loeb faile;see ei muuda midagi.",
            "Analyze", "3. KONTROLLI OLEMASOLEVAID FAILE — ei muuda midagi",
            "Cancel", "Loobu",
            "OpenReport", "Ava viimane aruanne",
            "NoAnalysis", "Vali VANA kaust ja PRAEGUNE kaitstud kaust, seejärel käivita kontroll.",
            "PathsChanged", "Kaustavalik muutus. Käivita kontroll uuesti enne puhastamist.",
            "TabRecover", "EI LEIDUNUD PRAEGUSES KAUSTAS",
            "TabVersions", "VÕIMALIKUD ERINEVAD VERSIOONID",
            "TabDuplicates", "IDENTSED KOopiad",
            "TabProblems", "KONTROLLIMATA FAILID",
            "GridOld", "Fail VANAS kaustas",
            "GridSize", "Suurus",
            "GridCurrent", "Vastav fail PRAEGUSES kaustas",
            "GridNote", "LegacySifti tulemused",
            "CleanupGroup", "4. PUHASTA VANA KAUST",
            "Quarantine", "Ohutuskaust (soovitatav) — teisalda identsed koopiad VANAST kaustast välja, et neid saaks taastada",
            "Recycle", "Windowsi prügikast — saada identsed VANA kausta koopiad prügikasti",
            "OtherOptions", "Kuva muud valikud",
            "HideOptions", "Peida muud valikud",
            "RemoveEmpty", "Eemalda VANAS kaustas täiesti tühjaks jäänud alamkaustad",
            "Confirm", "Mõistan: muudetakse AINULT VANA kausta. PRAEGUNE kaust jääb muutmata.",
            "Cleanup", "EEMALDA IDENTSED KOopiad VANAST KAUSTAST",
            "Restore", "Taasta kõrvale pandud failid…",
            "ProtectedReminder", "CURRENT (praegune) jääb kaitstuks",
            "Ready", "Valmis.",
            "ChooseOldDialog", "Vali OLD (vana) kaust kontrollimiseks ja puhastamiseks",
            "ChooseCurrentDialog", "Vali CURRENT (praegune) / PROTECTED (kaitstud) kaust",
            "AnalyzeDone", "Kontrollimine lõpetatud. Ühtegi faili ei muudetud.",
            "AnalyzeCanceled", "Kontrollimine tühistatud. Ühtegi faili ei muudetud.",
            "AnalyzeErrorTitle", "Probleem kontrollimise ajal",
            "AnalyzeErrorStatus", "Kontrollimine peatati probleemi tõttu. Puhastamist ei toimunud.",
            "PathCheckTitle", "LegacySift – kaustade valik",
            "CleanupConfirmTitle", "Kinnita OLD (vana) kausta puhastamine",
            "CleanupConfirm", "Puhastad AINULT OLD (vana) kausta:\\n\\n{0}\\n\\nCURRENT (praegune) kaust on kaitstud ja seda ei muudeta:\\n\\n{1}\\n\\nEemaldatud OLD (vanast) kaustast: {2} identset koopiat.\\nJäetud OLD (vanasse) kausta: {3} mida ei leitud CURRENT (praegusest) kaustast, {4} võimalikud erinevad versioonid, {5} kontrollimata.\\n\\nMeetod: {6}\\n\\nJätkata?",
            "ModeSafety", "TURVAKAUST (taastatav)",
            "ModeRecycle", "WINDOWSI PRÜGIKAST",
            "CleanupDoneStatus", "Valmis: OLD (vanast) kaustast eemaldati {0} identset koopiat;{1} kandidaati jäeti ohutuse huvides puutumata.",
            "CleanupDoneTitle", "LegacySift – lõpetatud",
            "CleanupDone", "Puhastamine lõpetatud.\\n\\nEemaldatud OLD (vanast) kaustast: {0} identset koopiat\\nOhutuse huvides alles jäetud: {1}{2}\\n\\nFaile, mida ei leitud CURRENT (praegusest) kaustast, ja võimalikke erinevaid versioone ei puudutatud. Käivita kontroll uuesti, et näha täpselt, mis alles jäi.",
            "CleanupSafetyLocation", "\n\nTurvakaust:\n{0}\n\nÄrge kustutage seda enne, kui olete vanasse kausta jäänud failid üle kontrollinud.",
            "CleanupCanceled", "Puhastamine peatati. Juba teisaldatud failid jäävad turvakausta / prügikasti;ülejäänud faile ei puudutatud.",
            "CleanupErrorTitle", "Probleem puhastamise ajal",
            "CleanupErrorStatus", "Puhastamine peatati probleemi tõttu. Kontrollige turvakausta ja käivitage uus võrdlus enne uuesti proovimist.",
            "RestoreLast", "Kas taastada viimati loodud turvakaust?\n\n{0}",
            "RestoreTitle", "Taasta failid",
            "RestoreChoose", "Valige __LegacySift_Safety_... kaust",
            "RestoreConfirm", "LegacySift püüab failid tagasi nende algsetesse asukohtadesse (OLD-kausta) paigutada. Seal juba olemasolevaid faile EI kirjutata üle. Kas jätkata?",
            "RestoreConfirmTitle", "Kinnita taastamine",
            "RestoreDoneStatus", "Taastamine lõpetatud: taastati {0} faili;{1} konflikti ei kirjutatud üle.",
            "RestoreDone", "Taastatud: {0};konflikte EI kirjutatud üle: {1}; vigu: {2}",
            "RestoreCanceled", "Taastamine peatati.",
            "RestoreErrorTitle", "Probleem taastamisel",
            "Summary", "Kontrollimine lõpetatud – ühtegi faili ei muudetud.\\n{0} ei leitud kaustast CURRENT   |{1} võimalikud erinevad versioonid   |{2} identsed koopiad ({3})   |{4} kontrollimata",
            "CleanupCount", "Eemalda {0} identsed koopiad vanast kaustast",
            "PhaseOldScan", "Loetakse vana kausta",
            "PhaseCurrentScan", "Loetakse praegust kaitstud kausta",
            "PhaseCompare", "Võrreldakse failide sisu",
            "PhaseSafety", "Teisaldatakse failid turvakausta",
            "PhaseRecycle", "Teisaldatakse failid prügikasti",
            "PhaseRestoreRead", "Loetakse turvakausta",
            "PhaseRestore", "Taastatakse faile",
            "OldRequired", "Vali esmalt vana kaust.",
            "CurrentRequired", "Vali praegune / kaitstud kaust.",
            "InvalidPath", "Vigane tee: {0}",
            "OldMissing", "Vana kausta ei eksisteeri.",
            "CurrentMissing", "Praegust / kaitstud kausta ei eksisteeri.",
            "SameFolder", "Mõlemad valikud viitavad samale kaustale. Toiming peatatud.",
            "OldRootBlocked", "Ohutuse huvides ei saa vana kaustana kasutada ketta juurkataloogi.",
            "CurrentRootBlocked", "Ohutuse huvides ei saa praeguse kaustana kasutada ketta juurkataloogi.",
            "NestedBlocked", "Üks valitud kaust asub teise sees. Vali kaks eraldi kausta.",
            "SystemFolderBlocked", "Ohutuse huvides ei puhasta LegacySift Windowsi peamist süsteemikausta.",
            "OutsideOld", "Ohutuskontroll ebaõnnestus: see fail ei asu vanas kaustas.",
            "ReparseDir", "Lingitud kaust / ümbersuunamispunkt jäeti ohutuse huvides vahele.",
            "ReparseFile", "Lingitud fail / ümbersuunamispunkt jäeti ohutuse huvides vahele.",
            "ExactNote", "Praeguses kaustas leidub identne koopia. Selle vana kausta koopia võib ohutult eemaldada.",
            "VersionNoteOne", "Praeguses kaustas leidub sama nimega fail, kuid selle sisu on erinev. Seda faili EI eemaldata.",
            "VersionNoteMany", "Leiti sama nimega {0}-faile, kuid ükski neist pole identne. Seda faili EI eemaldata.",
            "UniqueNote", "Praegusest kaustast ei leitud identset koopiat. See fail jääb kausta OLD.",
            "LanguageRestart", "LegacySift taaskäivitub uue keele rakendamiseks. Kõik praegused võrdlustulemused kustutatakse.",
            "LanguageRestartTitle", "Muuda keelt",
            "SafetyParentMissing", "LegacySift ei suuda tuvastada, kuhu turvakaust luua.",
            "OldFileMissingNow", "Faili kaustas OLD enam ei eksisteeri.",
            "CurrentCopyMissingNow", "Vastavat faili praeguses kaustas enam ei eksisteeri.",
            "ChangedSize", "Faili suurus muutus pärast võrdlust. Fail jäeti muutmata.",
            "ChangedHash", "Need kaks faili ei ole enam identsed. Vana fail jäeti muutmata.",
            "SafetyDestinationExists", "Sama teega fail on turvakaustas juba olemas.",
            "SafetyVerificationFailed", "Turvakausta kontrollimine pärast teisaldamist ebaõnnestus. LegacySift üritas algset faili automaatselt taastada.",
            "MovedSafety", "Teisaldatud turvakausta ja kontrollitud.",
            "MovedRecycle", "Teisaldatud Windowsi prügikasti.",
            "SafetyFolderMissing", "Turvakausta ei leitud.",
            "RestoreNoOverwrite", "EI kirjutatud üle: {0}",
            "SessionMissing", "Fail LegacySift.session puudub, seega pole automaatne taastamine võimalik.",
            "SessionInvalid", "Turvakausta seanss on vigane: algne kausta OLD tee puudub.",
            "TabRecoverHelp", "Kaustast CURRENT ei leitud identset koopiat. Need failid jäävad kausta OLD.",
            "TabVersionsHelp", "Kaustas CURRENT on sama nimega fail olemas, kuid sisu erineb. Need failid jäävad kausta OLD.",
            "TabDuplicatesHelp", "Kaustas CURRENT on identne koopia juba olemas. Puhastamise käigus saab eemaldada ainult neid kausta OLD faile.",
            "TabProblemsHelp", "LegacySift ei saanud neid faile turvaliselt kontrollida. Need jäävad kausta OLD.",
            "CheckingNow", "Kontrollitakse kahte kausta... ühtegi faili ei muudeta.",
            "CleanupBeforeAnalysis", "Kõigepealt käivita kontroll. Seejärel näitab LegacySift täpselt, mida saab kaustast OLD eemaldada ja mis sinna alles jääb.",
            "CleanupWaitForAnalysis", "Oota kontrolli lõppemist. Puhastamine on keelatud seni, kuni LegacySift loeb kaustade sisu.",
            "CleanupExplanation", "Pärast puhastamist jäävad kausta OLD alles failid {0} (mida ei leitud kaustast CURRENT), võimalikud erinevad versioonid {1} ja kontrollimata failid {2}. Kaustast OLD eemaldatakse ainult identsed koopiad {3}.",
            "AfterCleanupSummary", "Puhastamine lõpetatud: identsed koopiad {0} eemaldati kaustast OLD;kandidaadid {1} jäeti ohutuse huvides puutumata. Käivita kontroll uuesti, et näha, mis täpselt alles jäi.",
            "CleanupNeedsNewCheck", "Puhastamine on lõppenud. Käivita kontroll uuesti, et näha, mis jäi alles kausta OLD.",
            "HelpText", "LEGACYSIFT — LÜHIJUHEND\\n\\nMIDA SEE TEEB\\nLegacySift on mõeldud arvutite vaheliseks andmete üleviimiseks, vanade ketaste ja taastatud varukoopiate haldamiseks. Valige vana kaust (OLD) ja praegune kaust (CURRENT), mida igapäevaselt kasutate. LegacySift näitab, mis on praegusest kaustast puudu ja millised täpsed koopiad teil juba olemas on.\\n\\nSUUND EI MUUTU KUNAGI\\nVANA KAUST (OLD) = võib puhastada.\\nPRAEGUNE KAUST (CURRENT) = kaitstud, toimub vaid võrdlus. LegacySift ei muuda seda kunagi.\\n\\nKUIDAS KASUTADA\\n1. Valige vana kaust (OLD).\\n2. Valige praegune kaust (CURRENT).\\n3. Klõpsake nupul „Kontrolli olemasolevaid faile” (CHECK WHAT YOU ALREADY HAVE). See samm ei muuda midagi.\\n4. Tutvuge tulemustega.\\n5. Kui tulemused tunduvad õiged, eemaldage vanast kaustast (OLD) ainult identsed koopiad.\\n\\nTULEMUSTE TÄHENDUS\\n• EI LEIDUNUD PRAEGUSES KAUSTAS (NOT FOUND IN CURRENT): praeguses kaustas (CURRENT) pole identset koopiat. Need failid jäävad vanasse kausta (OLD).\\n• VÕIMALIKUD ERINEVAD VERSIOONID (POSSIBLE DIFFERENT VERSIONS): failinimi on sama, kuid sisu erineb. Need failid jäävad vanasse kausta (OLD).\\n• IDENTSED KOOPIAD JUBA PRAEGUSES KAUSTAS (IDENTICAL COPIES ALREADY IN CURRENT): praeguses kaustas (CURRENT) on täpne koopia olemas. Ainult neid vanas kaustas (OLD) olevaid faile saab eemaldada.\\n• KONTROLLIMATA FAILID (FILES NOT CHECKED): LegacySift ei saanud neid ohutult kontrollida. Need jäävad vanasse kausta (OLD).\\n\\nPÄRAST PUHASTAMIST\\nVanasse kausta (OLD) jäävad failid, mida ei leitud praegusest kaustast (CURRENT), võimalikud erinevad versioonid ja kõik, mida LegacySift ei saanud ohutult kontrollida. Vanast kaustast (OLD) eemaldatakse vaid täpsed koopiad.\\n\\nOHUTUIM MEETOD\\nKasutage turvakausta (Safety folder). Täpsed koopiad teisaldatakse vanast kaustast (OLD) eraldi taastatavasse kausta, selle asemel et neid jäädavalt kustutada.\\n\\nTEHNILINE OHUTUS\\nTäpset sisu kontrollitakse SHA-256 abil ja kontrollitakse uuesti enne puhastamist. Lingitud kaustu ja uuesti sõelutavaid punkte (reparse points) eiratakse. Pesastatud kaustade valimine on blokeeritud. LegacySift ei küsi administraatoriõigusi ja töötab täielikult lokaalselt.\\n\\nLIHTNE REEGEL\\nKui olete ebakindel, peatuge pärast kontrollimist. Midagi ei muutu, kuni käivitate sõnaselgelt puhastamise."
        );
    }
}
