using System;
using System.Collections.Generic;
using System.Globalization;

namespace LegacySift
{
    internal enum AppLanguage { English, Italian }

    internal static class L10n
    {
        private static readonly Dictionary<string, string> En = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            {"AppTitle","LegacySift 0.2.0-alpha — recover what is missing from an old folder"},
            {"TabWork","Compare and recover"},{"TabHelp","Guide and safety"},{"LanguageButton","Language…"},
            {"Intro","Recovered files from an old computer or backup? LegacySift shows what you already have and what may still be worth keeping. Your CURRENT folder is protected and is never cleaned."},
            {"OldTitle","1. CHOOSE THE OLD FOLDER"},{"OldBadge","CAN BE CHANGED"},{"OldDescription","Choose the folder recovered from the old computer or backup. Only this folder can be cleaned."},
            {"CurrentTitle","2. CHOOSE THE CURRENT FOLDER"},{"CurrentBadge","PROTECTED • READ ONLY"},{"CurrentDescription","Choose the folder you use today. LegacySift only reads it for comparison. It never deletes, moves or renames files here."},
            {"Browse","Browse…"},{"Direction","LegacySift looks inside the OLD folder for files that already exist in the CURRENT folder. The check itself changes nothing."},
            {"Analyze","3. CHECK THE TWO FOLDERS — changes nothing"},{"Cancel","Cancel"},{"OpenReport","Open last report"},
            {"NoAnalysis","Nothing has been checked yet. Choose the two folders, then run the check."},{"PathsChanged","Folder paths changed. Run the check again before putting files aside."},
            {"TabRecover","FILES TO KEEP"},{"TabVersions","VERSIONS TO CHECK"},{"TabDuplicates","ALREADY PRESENT"},{"TabProblems","PROBLEMS / WARNINGS"},
            {"GridOld","File in OLD folder"},{"GridSize","Size"},{"GridCurrent","Matching file in CURRENT folder"},{"GridNote","What LegacySift found"},
            {"CleanupGroup","4. PUT ASIDE FILES THAT ARE ALREADY PRESENT"},{"Quarantine","Safety folder (recommended) — move matching files to a separate folder that can be restored"},
            {"Recycle","Windows Recycle Bin — send matching OLD-folder files to the Recycle Bin"},{"OtherOptions","Show other options"},{"HideOptions","Hide other options"},
            {"RemoveEmpty","Remove folders left completely empty inside the OLD folder"},{"Confirm","I checked the paths above. I want LegacySift to change only the OLD folder."},
            {"Cleanup","PUT ASIDE FILES ALREADY PRESENT"},{"Restore","Restore files put aside…"},{"ProtectedReminder","The CURRENT folder is comparison-only. Cleanup can act only inside the OLD folder."},{"Ready","Ready."},
            {"ChooseOldDialog","Choose the OLD folder to check and clean"},{"ChooseCurrentDialog","Choose the CURRENT / PROTECTED folder"},
            {"AnalyzeDone","Check complete. No file was changed."},{"AnalyzeCanceled","Check cancelled. No file was changed."},{"AnalyzeErrorTitle","Problem during the check"},{"AnalyzeErrorStatus","The check stopped because of a problem. No cleanup was performed."},
            {"PathCheckTitle","LegacySift — check folder selection"},{"CleanupConfirmTitle","Confirm changes to the OLD folder"},
            {"CleanupConfirm","LegacySift is about to change ONLY the OLD folder:\n\n{0}\n\nThe CURRENT folder stays protected and unchanged:\n\n{1}\n\nFiles already present that can be put aside: {2}\nMethod: {3}\n\nContinue?"},
            {"ModeSafety","SAFETY FOLDER (restorable)"},{"ModeRecycle","WINDOWS RECYCLE BIN"},{"CleanupDoneStatus","Done: {0} files were removed from the old folder; {1} were left untouched for safety."},
            {"CleanupDoneTitle","LegacySift — completed"},{"CleanupDone","Completed.\n\nPut aside from the OLD folder: {0}\nSkipped / not changed: {1}{2}"},
            {"CleanupSafetyLocation","\n\nSafety folder:\n{0}\n\nDo not delete it until you have checked the files left in the old folder."},
            {"CleanupCanceled","Cleanup stopped. Files already moved stay where they were put aside; remaining files were not touched."},{"CleanupErrorTitle","Problem during cleanup"},{"CleanupErrorStatus","Cleanup stopped because of a problem. Check the safety folder and run a new comparison before trying again."},
            {"RestoreLast","Restore the last safety folder created?\n\n{0}"},{"RestoreTitle","Restore files"},{"RestoreChoose","Choose a __LegacySift_Safety_... folder"},
            {"RestoreConfirm","LegacySift will try to put files back in their original OLD-folder locations.\nFiles already there will NOT be overwritten.\n\nContinue?"},{"RestoreConfirmTitle","Confirm restore"},
            {"RestoreDoneStatus","Restore complete: {0} files restored; {1} conflicts were not overwritten."},{"RestoreDone","Restored: {0}\nConflicts NOT overwritten: {1}\nErrors: {2}"},{"RestoreCanceled","Restore stopped."},{"RestoreErrorTitle","Problem during restore"},
            {"Summary","OLD folder: {0} files   |   CURRENT protected folder: {1} files\nAlready present: {2} ({3})   |   Files to keep: {4}   |   Versions to check: {5}   |   Problems/warnings: {6}\nCHECK COMPLETE: NO FILE WAS CHANGED."},
            {"CleanupCount","PUT ASIDE {0} FILES ALREADY PRESENT"},{"PhaseOldScan","Reading OLD folder"},{"PhaseCurrentScan","Reading CURRENT protected folder"},{"PhaseCompare","Comparing file contents"},{"PhaseSafety","Moving files to the safety folder"},{"PhaseRecycle","Moving files to the Recycle Bin"},{"PhaseRestoreRead","Reading safety folder"},{"PhaseRestore","Restoring files"},
            {"OldRequired","Choose the OLD folder first."},{"CurrentRequired","Choose the CURRENT / PROTECTED folder."},{"InvalidPath","Invalid path: {0}"},{"OldMissing","The OLD folder does not exist."},{"CurrentMissing","The CURRENT / PROTECTED folder does not exist."},{"SameFolder","The two selections point to the same folder. Operation blocked."},{"OldRootBlocked","For safety, a whole drive root cannot be used as the OLD folder."},{"CurrentRootBlocked","For safety, a whole drive root cannot be used as the CURRENT folder."},{"NestedBlocked","One selected folder is inside the other. Choose two separate folders."},{"SystemFolderBlocked","For safety, LegacySift will not clean a main Windows system folder."},{"OutsideOld","Safety check failed: this file is not inside the OLD folder."},
            {"ReparseDir","Linked folder / reparse point skipped for safety."},{"ReparseFile","Linked file / reparse point skipped for safety."},{"ExactNote","An identical file already exists in the current folder."},{"VersionNoteOne","A file with the same name exists in the current folder, but its contents are different. This file will NOT be removed."},{"VersionNoteMany","{0} files with the same name were found, but none is identical. This file will NOT be removed."},{"UniqueNote","No identical file was found in the current folder. This file stays in the old folder."},
            {"LanguageRestart","LegacySift will restart to apply the new language. Current results will be cleared."},{"LanguageRestartTitle","Change language"},{"SafetyParentMissing","LegacySift cannot determine where to create the safety folder."},{"OldFileMissingNow","The file in the old folder no longer exists."},{"CurrentCopyMissingNow","The matching file in the current folder no longer exists."},{"ChangedSize","File size changed after the comparison. The file was left untouched."},{"ChangedHash","The two files are no longer identical. The old file was left untouched."},{"SafetyDestinationExists","A file with the same path already exists in the safety folder."},{"SafetyVerificationFailed","Verification failed after the move. LegacySift attempted to restore the original file automatically."},{"MovedSafety","Moved to the safety folder and verified."},{"MovedRecycle","Moved to the Windows Recycle Bin."},{"SafetyFolderMissing","Safety folder not found."},{"RestoreNoOverwrite","NOT overwritten: {0}"},{"SessionMissing","LegacySift.session is missing, so automatic restore is not possible."},{"SessionInvalid","The safety-folder session is invalid: the original old-folder path is missing."},
            {"HelpText","LEGACYSIFT — QUICK GUIDE\n\nWHAT IT DOES\nChoose an OLD folder recovered from another computer or backup, then choose the CURRENT folder you use today. LegacySift shows which old files already exist and which may still be worth recovering.\n\nTHE DIRECTION NEVER CHANGES\nOLD FOLDER = may be changed if you explicitly start cleanup.\nCURRENT FOLDER = protected and read only for comparison.\n\nSAFE WORKFLOW\n1. Choose OLD folder.\n2. Choose CURRENT folder.\n3. Run the check. Nothing is changed.\n4. Review FILES TO KEEP and VERSIONS TO CHECK.\n5. If the results make sense, put aside only files already present.\n\nRECOMMENDED\nUse the Safety folder. It is reversible. If in doubt, stop after the check."}
        };

        private static readonly Dictionary<string, string> It = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            {"AppTitle","LegacySift 0.2.0-alpha — recupera ciò che manca da una vecchia cartella"},
            {"TabWork","Confronta e recupera"},{"TabHelp","Guida e sicurezza"},{"LanguageButton","Lingua…"},
            {"Intro","Hai recuperato file da un vecchio computer o backup? LegacySift mostra ciò che possiedi già e ciò che potrebbe ancora valere la pena conservare. La cartella ATTUALE è protetta e non viene mai ripulita."},
            {"OldTitle","1. SCEGLI LA VECCHIA CARTELLA"},{"OldBadge","PUÒ ESSERE MODIFICATA"},{"OldDescription","Scegli la cartella recuperata dal vecchio computer o backup. Solo questa cartella può essere ripulita."},
            {"CurrentTitle","2. SCEGLI LA CARTELLA ATTUALE"},{"CurrentBadge","PROTETTA • SOLA LETTURA"},{"CurrentDescription","Scegli la cartella che usi oggi. LegacySift la legge solo per confrontare i file. Qui non cancella, sposta o rinomina nulla."},
            {"Browse","Sfoglia…"},{"Direction","LegacySift cerca nella VECCHIA cartella i file che esistono già nella cartella ATTUALE. Il controllo non modifica nulla."},
            {"Analyze","3. CONTROLLA LE DUE CARTELLE — non modifica nulla"},{"Cancel","Annulla"},{"OpenReport","Apri ultimo report"},
            {"NoAnalysis","Nessun controllo eseguito. Scegli le due cartelle e avvia il controllo."},{"PathsChanged","Hai cambiato una cartella. Esegui di nuovo il controllo prima di mettere da parte file."},
            {"TabRecover","FILE DA CONSERVARE"},{"TabVersions","VERSIONI DA CONTROLLARE"},{"TabDuplicates","GIÀ PRESENTI"},{"TabProblems","PROBLEMI / AVVISI"},
            {"GridOld","File nella VECCHIA cartella"},{"GridSize","Dimensione"},{"GridCurrent","File corrispondente nella cartella ATTUALE"},{"GridNote","Cosa ha trovato LegacySift"},
            {"CleanupGroup","4. METTI DA PARTE I FILE GIÀ PRESENTI"},{"Quarantine","Cartella di sicurezza (consigliata) — sposta i file identici in una cartella separata e ripristinabile"},
            {"Recycle","Cestino di Windows — invia al Cestino solo i file identici della VECCHIA cartella"},{"OtherOptions","Mostra altre opzioni"},{"HideOptions","Nascondi altre opzioni"},
            {"RemoveEmpty","Rimuovi le cartelle rimaste completamente vuote dentro la VECCHIA cartella"},{"Confirm","Ho controllato i percorsi. Voglio che LegacySift modifichi soltanto la VECCHIA cartella."},
            {"Cleanup","METTI DA PARTE I FILE GIÀ PRESENTI"},{"Restore","Ripristina file messi da parte…"},{"ProtectedReminder","La cartella ATTUALE serve solo per il confronto. La pulizia può agire soltanto dentro la VECCHIA cartella."},{"Ready","Pronto."},
            {"ChooseOldDialog","Scegli la VECCHIA cartella da controllare e ripulire"},{"ChooseCurrentDialog","Scegli la cartella ATTUALE / PROTETTA"},
            {"AnalyzeDone","Controllo completato. Nessun file è stato modificato."},{"AnalyzeCanceled","Controllo annullato. Nessun file è stato modificato."},{"AnalyzeErrorTitle","Problema durante il controllo"},{"AnalyzeErrorStatus","Il controllo si è fermato per un problema. Non è stata eseguita alcuna pulizia."},
            {"PathCheckTitle","LegacySift — controllo delle cartelle"},{"CleanupConfirmTitle","Conferma modifiche alla VECCHIA cartella"},
            {"CleanupConfirm","LegacySift sta per modificare SOLO la VECCHIA cartella:\n\n{0}\n\nLa cartella ATTUALE resterà protetta e invariata:\n\n{1}\n\nFile già presenti da mettere da parte: {2}\nMetodo: {3}\n\nContinuare?"},
            {"ModeSafety","CARTELLA DI SICUREZZA (ripristinabile)"},{"ModeRecycle","CESTINO DI WINDOWS"},{"CleanupDoneStatus","Fatto: {0} file rimossi dalla vecchia cartella; {1} lasciati invariati per sicurezza."},{"CleanupDoneTitle","LegacySift — operazione completata"},{"CleanupDone","Operazione completata.\n\nMessi da parte dalla VECCHIA cartella: {0}\nSaltati / non modificati: {1}{2}"},{"CleanupSafetyLocation","\n\nCartella di sicurezza:\n{0}\n\nNon eliminarla finché non hai controllato ciò che è rimasto nella vecchia cartella."},{"CleanupCanceled","Pulizia interrotta. I file già spostati restano dove sono stati messi da parte; gli altri non sono stati toccati."},{"CleanupErrorTitle","Problema durante la pulizia"},{"CleanupErrorStatus","La pulizia si è fermata per un problema. Controlla la cartella di sicurezza e rifai il confronto prima di riprovare."},
            {"RestoreLast","Ripristinare l'ultima cartella di sicurezza creata?\n\n{0}"},{"RestoreTitle","Ripristina file"},{"RestoreChoose","Scegli una cartella __LegacySift_Safety_..."},{"RestoreConfirm","LegacySift proverà a rimettere i file nei percorsi originali della VECCHIA cartella.\nI file già presenti NON verranno sovrascritti.\n\nContinuare?"},{"RestoreConfirmTitle","Conferma ripristino"},{"RestoreDoneStatus","Ripristino completato: {0} file ripristinati; {1} conflitti non sovrascritti."},{"RestoreDone","Ripristinati: {0}\nConflitti NON sovrascritti: {1}\nErrori: {2}"},{"RestoreCanceled","Ripristino interrotto."},{"RestoreErrorTitle","Problema durante il ripristino"},
            {"Summary","VECCHIA cartella: {0} file   |   Cartella ATTUALE protetta: {1} file\nGià presenti: {2} ({3})   |   File da conservare: {4}   |   Versioni da controllare: {5}   |   Problemi/avvisi: {6}\nCONTROLLO COMPLETATO: NESSUN FILE È STATO MODIFICATO."},{"CleanupCount","METTI DA PARTE {0} FILE GIÀ PRESENTI"},
            {"PhaseOldScan","Lettura VECCHIA cartella"},{"PhaseCurrentScan","Lettura cartella ATTUALE protetta"},{"PhaseCompare","Confronto del contenuto dei file"},{"PhaseSafety","Spostamento nella cartella di sicurezza"},{"PhaseRecycle","Spostamento nel Cestino"},{"PhaseRestoreRead","Lettura cartella di sicurezza"},{"PhaseRestore","Ripristino dei file"},
            {"OldRequired","Scegli prima la VECCHIA cartella."},{"CurrentRequired","Scegli la cartella ATTUALE / PROTETTA."},{"InvalidPath","Percorso non valido: {0}"},{"OldMissing","La VECCHIA cartella non esiste."},{"CurrentMissing","La cartella ATTUALE / PROTETTA non esiste."},{"SameFolder","Hai scelto la stessa cartella due volte. Operazione bloccata."},{"OldRootBlocked","Per sicurezza non puoi usare l'intera radice di un disco come VECCHIA cartella."},{"CurrentRootBlocked","Per sicurezza non puoi usare l'intera radice di un disco come cartella ATTUALE."},{"NestedBlocked","Una cartella si trova dentro l'altra. Scegli due cartelle separate."},{"SystemFolderBlocked","Per sicurezza LegacySift non ripulisce direttamente una cartella principale di Windows."},{"OutsideOld","Controllo di sicurezza fallito: il file non appartiene alla VECCHIA cartella."},
            {"ReparseDir","Cartella collegata ignorata per sicurezza."},{"ReparseFile","File collegato ignorato per sicurezza."},{"ExactNote","Un file identico esiste già nella cartella attuale."},{"VersionNoteOne","Nella cartella attuale esiste un file con lo stesso nome, ma contenuto diverso. Questo file NON verrà rimosso."},{"VersionNoteMany","Trovati {0} file con lo stesso nome, ma nessuno identico. Questo file NON verrà rimosso."},{"UniqueNote","Nella cartella attuale non è stato trovato nessun file identico. Questo file resta nella vecchia cartella."},
            {"LanguageRestart","LegacySift verrà riavviato per applicare la lingua. I risultati correnti verranno azzerati."},{"LanguageRestartTitle","Cambia lingua"},{"SafetyParentMissing","LegacySift non riesce a determinare dove creare la cartella di sicurezza."},{"OldFileMissingNow","Il file nella vecchia cartella non esiste più."},{"CurrentCopyMissingNow","Il file corrispondente nella cartella attuale non esiste più."},{"ChangedSize","La dimensione del file è cambiata dopo il confronto. Il file è rimasto invariato."},{"ChangedHash","I due file non sono più identici. Il file vecchio è rimasto invariato."},{"SafetyDestinationExists","Nella cartella di sicurezza esiste già un file con lo stesso percorso."},{"SafetyVerificationFailed","La verifica dopo lo spostamento è fallita. LegacySift ha tentato di ripristinare automaticamente il file originale."},{"MovedSafety","Spostato nella cartella di sicurezza e verificato."},{"MovedRecycle","Spostato nel Cestino di Windows."},{"SafetyFolderMissing","Cartella di sicurezza non trovata."},{"RestoreNoOverwrite","NON sovrascritto: {0}"},{"SessionMissing","Manca LegacySift.session: il ripristino automatico non è possibile."},{"SessionInvalid","La sessione della cartella di sicurezza non è valida: manca il percorso originale della vecchia cartella."},
            {"HelpText","LEGACYSIFT — GUIDA RAPIDA\n\nA COSA SERVE\nScegli una VECCHIA cartella recuperata da un altro computer o backup, poi la cartella ATTUALE che usi oggi. LegacySift mostra quali file vecchi possiedi già e quali potrebbero essere ancora da recuperare.\n\nIL VERSO NON CAMBIA MAI\nVECCHIA CARTELLA = può essere modificata solo se avvii esplicitamente la pulizia.\nCARTELLA ATTUALE = protetta e usata in sola lettura per il confronto.\n\nPROCEDURA SICURA\n1. Scegli la VECCHIA cartella.\n2. Scegli la cartella ATTUALE.\n3. Avvia il controllo: non modifica nulla.\n4. Controlla FILE DA CONSERVARE e VERSIONI DA CONTROLLARE.\n5. Se i risultati hanno senso, metti da parte soltanto i file già presenti.\n\nCONSIGLIATO\nUsa la Cartella di sicurezza: è ripristinabile. Se hai un dubbio, fermati dopo il controllo."}
        };

        public static AppLanguage CurrentLanguage { get; private set; } = DetectDefaultLanguage();
        public static void SetLanguage(AppLanguage language) { CurrentLanguage = language; }
        public static string T(string key, params object[] args)
        {
            string value;
            var dict = CurrentLanguage == AppLanguage.Italian ? It : En;
            if (!dict.TryGetValue(key, out value) && !En.TryGetValue(key, out value)) value = key;
            return args != null && args.Length > 0 ? string.Format(CultureInfo.CurrentCulture, value, args) : value;
        }
        public static AppLanguage DetectDefaultLanguage()
        {
            return string.Equals(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName, "it", StringComparison.OrdinalIgnoreCase) ? AppLanguage.Italian : AppLanguage.English;
        }
    }
}
